### ISSUE TITLE
Tool inclusion in Parrot Security

### ISSUE THREAD

**Issue by PalinuroSec** [rizinorg/rizin#1006]
Hello, i am a Parrot Security developer and we are at work to include rizin and rizin-cutter by default as part of our security oriented distribution.

The first packages are already installable via APT and will come pre-installed in the next minor version. We would like hear your opinion on how our packaging was done and whether you have any tips for us.

**Comment by karliss** [comment]
Do you have any links to the repository with package build scripts you used?

**Comment by PalinuroSec** [comment]
this is where we maintain the packages
https://nest.parrotsec.org/packages/tools/rizin
https://nest.parrotsec.org/packages/tools/rizin-cutter
https://nest.parrotsec.org/packages/tools/rizin-ghidra-plugin

and this is where you can find the binary artifacts
https://deb.parrot.sh/parrot/pool/main/r/rizin/
https://deb.parrot.sh/parrot/pool/main/r/rizin-cutter/
https://deb.parrot.sh/parrot/pool/main/r/rizin-ghidra-plugin/


CC @dmknght

**Comment by karliss** [comment]
@PalinuroSec Why are you manually copying each file from source or build folder during install step for Cutter instead of using provided install step with minor adjustments if necessary?

**Comment by dmknght** [comment]
> @PalinuroSec Why are you manually copying each file from source or build folder during install step for Cutter instead of using provided install step with minor adjustments if necessary?

Because the `Make install` installs files to system directly and the Debian packaging need to write files into `debian/<package_name>` to create packages so some files could be missing.

**Comment by karliss** [comment]
> Because the Make install installs files to system directly

Make install places files where you ask it to place them. Any sane packaging system should be able to deal with it and I assume that Debian tooling isn't an exception. Even if it doesn't do it automatically there should be a way to pass extra argument to configure and install calls to do the required folder adjustments.

**Comment by ret2libc** [comment]
Thank you for this! Right now I'm not that familiar with debian packaging... I need however to look at it a bit so I will review this in the next couple of weeks.

**Comment by ret2libc** [comment]
How are things going here? Is there anything we can/shall do?

**Comment by dmknght** [comment]
> How are things going here? Is there anything we can/shall do?

I believe everything is completed. Rizin, rizin-cutter and rizin-ghidra works by install from repo with `apt` command. I'm thinking about do more plugins for rizin like frida or retdec

**Comment by karliss** [comment]
> I believe everything is completed. 

What was the point of asking for feedback if you are ignoring the suggestions. The install process of for cutter is still completely wrong.

**Comment by ret2libc** [comment]
Closing this for now. I think there's nothing else to do from our side. Thanks for opening this!
