### ISSUE TITLE
Create system plugin path for rizin for more friendly Debian packaging

### ISSUE THREAD

**Issue by dmknght** [rizinorg/rizin#1013]
**Is your feature request related to a problem? Please describe.**

Current path of rizin's system plugins is not very friendly with Debian packaging. When i create new package (let say that ghidra plugin), there are some cons:
- Save time for users by installing pre-compiled package to system
- Easier to search and install by using `apt` or `software-center` like Gnome just in case some new users are not familiar with `rz-pm`
However it is having some problems:
- as Debian package so the package will install compiled data only, Debian packaging standard can't make package install to `$HOME`. So a system PATH is needed
- For now (rizin version 0.2.0), the path of rizin's global plugins is at `RZ_LIBR_PLUGINS=/usr/lib/x86_64-linux-gnu/rizin/0.2.0` so each release of rizin needs to create new path for compile rule
- When i define the `PREFIX_PATH` flag for Cmake of plugins, files are generated to `$PREFIX_PATH/share/rizin/plugins/`

**Describe the solution you'd like**
Rizin loads plugins from `$PREFIX_PATH/share/rizin/plugins/` as well as other old path, like this old issue 
https://github.com/radareorg/cutter/issues/1783

**Describe alternatives you've considered**
For now i am having a solution that when a plugin is installed by `apt` package manager, it will create a symlink to current rizin's plugin folder
```
#!/bin/sh

rizin_version=$(rizin -H | grep RZ_VERSION | cut -d = -f 2)
# Parse the version of rizin on user's system as name of symlink. It will be like 0.2.0 from RZ_VERSION=0.2.0
dest="/usr/lib/x86_64-linux-gnu/rizin/$rizin_version"
# Dest path is like RZ_LIBR_PLUGINS=/usr/lib/x86_64-linux-gnu/rizin/0.2.0 which should be changed when rizin has new release
if [ ! -L $dest ]; then
  ln -s /usr/share/rizin/plugins/ $dest
fi
```

**Additional context**
A similar issue was closed before on radare2's git issue
https://github.com/radareorg/radare2/issues/15620

**Comment by dmknght** [comment]
More info: the path is hardcoded and likely can't be changed by cmake flags
https://github.com/rizinorg/rz-ghidra/blob/dev/CMakeLists.txt#L6

**Comment by karliss** [comment]
That's more of rz-ghidra issue. The path can be changed using CMAKE flags, that's exactly what official Cutter packaging scripts do and is opposite of hardcoding. You are supposed to set them since folder varies based on operating system and how you built rizin.

**Comment by ret2libc** [comment]
As said by @karliss I think it should be possible to force the plugins to compile libs in the proper directory.

That said, the fact that home plugins are in one directory, while system plugins are split by version puzzles me a bit. cc @thestr4ng3r . I think it might make sense to have plugins split by version, because as we are doing things right now and in the foreseeable future we won't guarantee plugins built for 1.5.0 would work exactly the same in 1.5.1, right? So they need anyway to be rebuilt for each version. WDYT?

**Comment by dmknght** [comment]
> I think it might make sense to have plugins split by version, because as we are doing things right now and in the foreseeable future we won't guarantee plugins built for 1.5.0 would work exactly the same in 1.5.1, right? So they need anyway to be rebuilt for each version. WDYT?

I agree about rebuild plugins. But when Rizin is upgraded, all plugins must be upgraded or rebuild on maintainer's side before arrives repository and can be installed at user's system -> Everything is latest so i see no point of keeping an other version of plugin for older version of rizin. Eventually system will upgrade all plugins and remove older versions unless maintainers does something wrong and some plugins can't be rebuilt. At this point, I see it works as same as install from `rz-pm` for plugin path.
P/s: I tried reading the `CMakelist.txt` but i couldn't find any flags that could change either `RZ_LIBR_PLUGINS` nor plugin location of `rz-ghidra`.
P/s2: Since home plugin is at `.local/share/rizin/plugins` so i think path of system plugin is at `$INSTALL_PREFIX/share/rizin/plugins` makes sense?

**Comment by ret2libc** [comment]
> P/s2: Since home plugin is at .local/share/rizin/plugins so i think path of system plugin is at $INSTALL_PREFIX/share/rizin/plugins makes sense?

I think it does make sense, yes.

**Comment by dmknght** [comment]
@ret2libc and imo, about the plugin compatible when rizin release newer version: maybe plugins should contains version of rizin at compile time so plugins can show warning message about compatible version?

**Comment by ret2libc** [comment]
> @ret2libc and imo, about the plugin compatible when rizin release newer version: maybe plugins should contains version of rizin at compile time so plugins can show warning message about compatible version?

I believe there is already a check for that. https://github.com/rizinorg/rizin/blob/db04bed5031f1a46be7628040b37948c67af5c62/librz/util/lib.c#L314

**Comment by dmknght** [comment]
> I believe there is already a check for that. 

Thank you! good to know because i didn't test plugins when rizin is upgraded :D

**Comment by ret2libc** [comment]
@dmknght just to wrap up and be clear: this issue is about changing `RZ_LIBR_PLUGINS=/usr/lib64/rizin/0.2.0` to `RZ_LIBR_PLUGINS=/usr/share/rizin/plugins`, right?

**Comment by dmknght** [comment]
> @dmknght just to wrap up and be clear: this issue is about changing `RZ_LIBR_PLUGINS=/usr/lib64/rizin/0.2.0` to `RZ_LIBR_PLUGINS=/usr/share/rizin/plugins`, right?

Yes it is just like that. i think maybe if rizin team wants to keep original PATH as well so maybe having 2 paths of global plugin location is possible. Ofc it creates problems like what if 2 folders are having same plugin and further problems but i think it is possible todo. Cutter added multiple paths before.

**Comment by ret2libc** [comment]
I think it is alright to have just one system plugin directory.

**Comment by XVilka** [comment]
By the way, I found out, that if we use the following API:
```c
rz_core_loadlibs(core, RZ_CORE_LOADLIBS_HOME | RZ_CORE_LOADLIBS_SYSTEM, NULL);
```
 which is supposed to search in these "system" paths, it doesn't load plugin, while `rizin` binary itself does. The symlink into `$HOME` helps:
```
ln -s /usr/local/lib/rizin/0.3.0-git/core_ghidra.so ~/.local/share/rizin/plugins/core_ghidra.so
```
But that `core_ghidra.so` plugin was installed with `rz-pm`. There is obvious inconsistency that we should solve.

**Comment by dmknght** [comment]
> By the way, I found out, that if we use the following API:
> 
> ```c
> rz_core_loadlibs(core, RZ_CORE_LOADLIBS_HOME | RZ_CORE_LOADLIBS_SYSTEM, NULL);
> ```
> 
> which is supposed to search in these "system" paths, it doesn't load plugin, while `rizin` binary itself does. The symlink into `$HOME` helps:
> 
> ```
> ln -s /usr/local/lib/rizin/0.3.0-git/core_ghidra.so ~/.local/share/rizin/plugins/core_ghidra.so
> ```
> 
> But that `core_ghidra.so` plugin was installed with `rz-pm`. There is obvious inconsistency that we should solve.

Is there any method to make `rizin` loads plugin from path that has no version? like `$PREFIX/lib/rizin/plugins/` or something like that? Because we always triggers rebuild the `ghidra` plugin (and could be other plugins` after rizin and cutter is updated). For now i'm using the symlink generation method (as i mentioned above) but i think a folder without symlink could be better.

**Comment by ret2libc** [comment]
I'm going to add this for 0.4.0. I will probably work on rz-pm and libs/plugins in general, so it would be a nice opportunity to improve this as well.

**Comment by ret2libc** [comment]
I think this was fixed in https://github.com/rizinorg/rizin/pull/1997 and other following PRs.

Could you test on dev if it works for you?
You should see with `rizin -H` both RZ_LIBR_PLUGINS and RZ_USER_PLUGINS that makes sense.

**Comment by XVilka** [comment]
@dmknght could you please test it and write here if it was fixed?

**Comment by dmknght** [comment]
Hello team! Sorry for late reply and testing. I completely forgot about this. I confirm this issue is completed on my side.
![image](https://user-images.githubusercontent.com/29118926/154298147-f3d5d010-4aa4-45f6-ac90-914ddd5241bc.png)
