### ISSUE TITLE
API for the `i` (file information) commands

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1027]
In particular the most important are:
- [x] `i` - file basic info `RzBinInfo *rz_bin_get_info(RzBin *bin);`
- [x] `iSS` - file segments
- [ ] `iS` - file sections
- [ ] `is` - file symbols
- [ ] `ii` - file imports
- [ ] `iE` - file exports
- [ ] `ie` - file entrypoint
- [ ] `iz`, `izz`, `izzz` - file strings

There should be also unit tests in `librz/unit/` for those.

Also related: https://github.com/rizinorg/rizin/issues/786 and required for Cutter: https://github.com/rizinorg/cutter/pull/2637

**Comment by ret2libc** [comment]
See also https://github.com/rizinorg/cutter/issues/2666

**Comment by ret2libc** [comment]
Commands without nice API:
- `it`
- `iV`
- `iC`

**Comment by ret2libc** [comment]
I would like to close this together with https://github.com/rizinorg/rizin/pull/1238  . I think API might not be perfect yet, but I'd prefer proper issues if problems are found while using them. Also, there are no unit tests for all those things, yet.
