### ISSUE TITLE
Provide SVD handling out of the box.

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#103]
There is some script already but maybe can be redone from scratch:
- https://github.com/radareorg/radare2-extras/tree/master/r2svd
- https://github.com/leveldown-security/SVD-Loader-Ghidra
- https://github.com/rust-embedded/svd
- https://github.com/posborne/cmsis-svd

**Comment by ret2libc** [comment]
Is this related to rz-svd done by @officialcjunior ?

**Comment by XVilka** [comment]
Solved by https://github.com/rizinorg/rizin-extras/tree/master/rz-svd
