### ISSUE TITLE
Wrong use of `sz = wcstombs(NULL, buf, len);` in `librz/util/str.c`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1032]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33 x86_64 
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/41192158ecf168eb18e831d225cdfb02829a40b9

### Expected behavior

No warnings

### Actual behavior

```
../librz/util/str.c: In function ‘rz_str_wc_to_mb_l’:
../librz/util/str.c:3519:7: warning: argument 1 is null but the corresponding size argument 3 range is [1, 2147483647] [-Wnonnull]
 3519 |  sz = wcstombs(NULL, buf, len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../librz/include/rz_types.h:250,
                 from ../librz/util/str.c:4:
/usr/include/stdlib.h:937:15: note: in a call to function ‘wcstombs’ declared with attribute ‘write_only (1, 3)’
  937 | extern size_t wcstombs (char *__restrict __s,
      |               ^~~~~~~~
```

This call was introduced in https://github.com/rizinorg/rizin/commit/527ff71d4184a07d724f9a7c3a464a3b228ea408

**Comment by ret2libc** [comment]
What about putting this for 0.2.1? I don't like having such warnings when building :D
