### ISSUE TITLE
Add support for UTF-16 BE, UTF-32 BE strings detection

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1052]
Currently Rizin supports UTF-16 LE and UTF-32 LE strings detection but not the big-endian versions of these.
The support should be added with corresponding tests.

The detection is implemented in `static int string_scan_range()` and `static void get_strings_range()` in [`librz/bin/bfile.c`](https://github.com/rizinorg/rizin/blob/dev/librz/bin/bfile.c)

Since most of the function operates on the `RzBuf`, I recommend to extract it from the `librz/bin/` and put the searching logic into `librz/util/` instead, probably a separate file, like `librz/util/str_search.c` or something similar.

**Comment by Youssef-Beltagy** [comment]
This is my first issue, so I am not sure how it will go. But I'm working on this issue.
