### ISSUE TITLE
Migrate from `wcstombs()` function since is not thread-safe

### ISSUE THREAD

**Issue by wargio** [rizinorg/rizin#1058]
`wcstombs` is not thread safe and should be fixed.

This issue is linked to this PR: https://github.com/rizinorg/rizin/pull/1045

![image](https://user-images.githubusercontent.com/561184/115545748-7408c480-a2a4-11eb-899a-91dc892f7fbf.png)

**Comment by XVilka** [comment]
Isn't this just a 2 line fix to use this function instead?
- https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/wcsrtombs?view=msvc-160
- https://www.cplusplus.com/reference/cwchar/wcsrtombs/

**Comment by karliss** [comment]
Now that this is a separate issue. Wouldn't hurt checking other functions with similar problem. Here are a few links listing some of them:
* http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1371.htm
* https://www.keil.com/support/man/docs/armlib/armlib_chr1359122864707.htm
* https://sourceforge.net/p/opensaf/wiki/Unsafe%20and%20Obsolete%20Functions/

**Comment by kholis1** [comment]
So the issue here is that one thread can call `setlocale() ` but at the same time another thread could call `wcstombs()` ?

**Comment by wargio** [comment]
potentially, but the issue itself is linked to the concurrent access to a global variable, and needs to be replaced with the thread safe one.

**Comment by iiiuwioajdks** [comment]
Hello, I saw the thread-safety and multithreading project on gsoc and was very interested. I myself have recently participated in the work of c/c++ concurrency in the internship of ByteDance. I would like to ask if there is still a chance to apply for this project? @wargio

**Comment by wargio** [comment]
Yes, sure! join our mattermost: https://im.rizin.re
Specifically please join  https://im.rizin.re/rizinorg/channels/gsoc-2023-applicants
