### ISSUE TITLE
Integration Test test_open_analyse_save_load_project only works a single time

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#1093]
After running it once, the `.tmp` folder already exists and it fails:
![Bildschirmfoto 2021-04-30 um 09 21 48](https://user-images.githubusercontent.com/1460997/116662056-9631cf00-a995-11eb-8286-200f8412d8a6.png)

**Comment by XVilka** [comment]
Fixed in https://github.com/rizinorg/rizin/commit/28faeff9ef261ff68922daea1e8b8b2ac33c0293
