### ISSUE TITLE
Proposal: write meson command line flags to build rizin for each linux distro

### ISSUE THREAD

**Issue by wargio** [rizinorg/rizin#1094]
**Is your feature request related to a problem? Please describe.**

Users are finding issues due wrong installation paths when building from sources. 

**Describe the solution you'd like**
My proposal is to add an markdown file with a list of configurations per distro (or even better per OS).

**Comment by ret2libc** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Users are finding issues due wrong installation paths when building from sources. 
> 

What kind of issues?

**Comment by wargio** [comment]
Like wrong install dir, like /usr/local instead of /usr

**Comment by ret2libc** [comment]
What is wrong in installing in /usr/local? I think these kind of things are already explained in BUILDING.md

**Comment by wargio** [comment]
sometimes libs doesn't work because of the wrong installation path. so for example you the bin doesn't find the right locatioin

**Comment by ret2libc** [comment]
As said, it's already explained in the building instructions. Packagers in particular should be very well aware that by default most build systems use /usr/linux . What else do you want to add?

**Comment by wargio** [comment]
that most people don't go past `meson build/`

**Comment by ret2libc** [comment]
Ok, what do you want to do exactly? I mean, you can't force people to read and adding yet another markdown file to read won't change or solve anything. If you have practical changes to improve building.md I'd suggest to just do them there and close this issue.

**Comment by wargio** [comment]
hmm you are right.. i'm closing this
