### ISSUE TITLE
rz-asm show a detailed description for a single opcode

### ISSUE THREAD

**Issue by eadmaster** [rizinorg/rizin#1100]
**Is your feature request related to a problem? Please describe.**
Is it possible to get a short text description associated to every instruction decoded?

**Describe the solution you'd like**
e.g.
````
$ rz-asm -t -a x86  nop
90
No Operation
Performs no operation. This instruction is a one-byte instruction that takes up space in the instruction stream but does not affect the machine context, except the EIP register.
````

A json output would be nice as well:
````
$ rz-asm -json -a x86  nop
{
"opcode": 90,
"size": 1,
"name": "No Operation",
"description": "Performs no operation. This instruction is a one-byte instruction that takes up space in the instruction stream but does not affect the machine context, except the EIP register."
}
````

**Describe alternatives you've considered**

- Consult online docs (not always available, slower to search).
- Looked for a downloadable db in some common plaintext format (json, csv, xml, etc.), but still found none. If you know some alternative please post here.

**Additional context**

**Comment by ret2libc** [comment]
It is possible to get something like that with `rizin` (e.g. use `asm.describe=true`) but I think there's no way right now to get that same behaviour just within `rz-asm`.

**Comment by eadmaster** [comment]
> It is possible to get something like that with rizin (e.g. use asm.describe=true) 

can this be done via a script invoked from the shell? (e.g. `$ opcodefind x86 nop`)

As alternative i've found the files in `/usr/share/rizin/0.2.1/opcodes/*.sdb` holds the infos i am looking for, and [this tool](https://github.com/rizinorg/sdb) should be able to parse them.
But i am not sure how to use it to query those dbs, can you help me with that?

**Comment by eadmaster** [comment]
btw [static binaries should not be linked with glibc in order to avoid this issue](https://stackoverflow.com/questions/26304531/compiling-with-static-libgcc-static-libstdc-still-results-in-dynamic-depende)...

**Comment by ret2libc** [comment]
Ok there is the flag also in `rz-asm`.

`rz-asm -w -a x86 -b 32 mov`

That accepts just the mnemonic though, not the full instruction, but it returns the same results that you would get from the full instruction actually (because the descriptions are based just on that).

If you want to get the output from rizin instead you can either do:
* `aoda` to get the full dump of all descriptions
* `aod xor` to get the description of just one mnemonic
* `ao` to get additional data about current opcode, description included.

**Comment by eadmaster** [comment]
> `rz-asm -w -a x86 -b 32 mov`

when i  run that with the [static build](https://github.com/rizinorg/rizin/releases/download/v0.2.1/rizin-v0.2.1-static-x86_64.tar.xz) i get no output...
is it a limitation of the static build?

EDIT: indeed with a reguar radare2 install works:
```
$ rasm2 -w -a x86 -b 32 mov

moves data from src to dst
```

**Comment by ret2libc** [comment]
> > `rz-asm -w -a x86 -b 32 mov`
> 
> when i run that with the [static build](https://github.com/rizinorg/rizin/releases/download/v0.2.1/rizin-v0.2.1-static-x86_64.tar.xz) i get no output...
> is it a limitation of the static build?
> 
> EDIT: indeed with a reguar radare2 install works:
> 
> ```
> $ rasm2 -w -a x86 -b 32 mov
> 
> moves data from src to dst
> ```

Please be aware that this is rizin, not radare2. So the right command is `rz-asm`. And it should work in rizin indeed.

Where are you trying those binaries?

```
podman run -it fedora:33 bash
[root@75476dfb4904 /]#                                                                          
[root@75476dfb4904 /]# dnf install -y wget xz
[root@75476dfb4904 /]# wget https://github.com/rizinorg/rizin/releases/download/v0.2.1/rizin-v0.2.1-static-x86_64.tar.xz
[root@75476dfb4904 /]# tar xvf rizin-v0.2.1-static-x86_64.tar.xz
[root@75476dfb4904 /]# ./bin/rz-asm -w -a x86 -b 32 mov
moves data from src to dst
```

**Comment by eadmaster** [comment]
> Where are you trying those binaries?

nevermind, i've found this was a problem with my setup missing the shared files...

**Comment by eadmaster** [comment]
is it possible to get more infos for each instruction, like the size in byes?

**Comment by ret2libc** [comment]
> > Where are you trying those binaries?
> 
> nevermind, i've found this was a problem with my setup missing the shared files...

Our static binaries don't have shared libraries... Otherwise they wouldn't be *static*.

 Please confirm that it works on static rizin release.

> is it possible to get more infos for each instruction, like the size in byes?

`ao` in rizin gives you a lot of info. You can use `rz-pipe` right now if you want to use those information easily in python or other supported languages. Otherwise for bash or quick stuff you can still do:
```
$ rizin -qc'aoj@main;q' /bin/ls 2>/dev/null  | jq '.'
[
  {
    "opcode": "endbr64",
    "disasm": "endbr64",
    "pseudo": "endbr64 ",
    "mnemonic": "endbr64",
    "mask": "ffffffff",
    "sign": false,
    "prefix": 0,
    "id": 1500,
    "opex": {
      "operands": []
    },
    "addr": 19840,
    "bytes": "f30f1efa",
    "size": 4,
    "type": "null",
    "esilcost": 0,
    "scale": 0,
    "refptr": 0,
    "cycles": 1,
    "failcycles": 0,
    "delay": 0,
    "stackptr": 0,
    "family": "cpu"
  }
]
```

**Comment by eadmaster** [comment]
> Our static binaries don't have shared libraries... Otherwise they wouldn't be static.

I meant the shared files in `/usr/share/rizin/0.2.1/opcodes`

> $ rizin -qc'aoj@main;q' /bin/ls 2>/dev/null  | jq '.'

Thanks alot, exactly what i was looking for!

**Comment by ret2libc** [comment]
> > Our static binaries don't have shared libraries... Otherwise they wouldn't be static.
> 
> I meant the shared files in `/usr/share/rizin/0.2.1/opcodes`

What do you mean? Those files should come together with the static release and the static rizin binary should be able to correctly find those files, relative to the directory where the static rizin is placed.

> Thanks alot, exactly what i was looking for!

:+1:

**Comment by eadmaster** [comment]
> What do you mean? Those files should come together with the static release and the static rizin binary should be able to correctly find those files, relative to the directory where the static rizin is placed.

Yep, but i didn't extract those :-P

Btw, is it possible to invoke `rizin` without passing a binary to it? (pass only an opcode like `rz-asm`)

**Comment by eadmaster** [comment]
> What do you mean? Those files should come together with the static release and the static rizin binary should be able to correctly find those files, relative to the directory where the static rizin is placed.

Yep, but i didn't extract those :-P

Btw, is it possible to invoke `rizin` without passing a binary to it? (pass only an opcode like `rz-asm`)

I've tried with: `rizin -a x86 -qc'aoj nop;q' -`, but it prints the description of the `add` instruction instead...

**Comment by ret2libc** [comment]
> I've tried with: `rizin -a x86 -qc'aoj nop;q' -`, but it prints the description of the `add` instruction instead...

So, this is changing in `dev` and it will change in next release. We have chosen to become more "unix-like", meaning that we will try to follow usual things done by unix tool. That means that `rizin` will open rizin without any file opened. `rizin =` will open a `malloc://512`, that is `0000...` (this is what `rizin -`/ was doing up to latest release). `rizin -` will take the input binary from the stdin, like any other unix tool.

You are seeing an `add` because `rizin -`, as said, in last release means `rizin malloc://512`, which essentially opens a file of only 0. 00000... in x86 means `add byte [rax], al`. That's why you see `add`.

Anyway, you can try with:
```
aoj @x:`pa mov eax, edx`
```
`@x` essentially replace the "input" with some hexadecimal values, `pa` assemble an instruction and prints the hex.

**Comment by eadmaster** [comment]
ok, so, in the current release there is no way to pass a binary from stdin?

> aoj @x:`pa mov eax, edx`

this works but requires a complete instruction with its args  to be passed , while i'd like to query for an instruction/opcode without knowing the args required.

**Comment by ret2libc** [comment]
> ok, so, in the current release there is no way to pass a binary from stdin?
> 

Yes for current release just use riZin = 


> > aoj @x:`pa mov eax, edx`
> 
> this works but requires a complete instruction with its args  to be passed , while i'd like to query for an instruction/opcode without knowing the args required.

See previous comments. aod, etc.

**Comment by eadmaster** [comment]
EDIT: i still do not see how to print a full instruction description without passing the operands:
````
rz-asm -B -q -a x86 sub | rizin -q -a x86 -c"ao sub;q" = 
`````
(the 1st command fails depending on the instruction)

Will it work this way with the next release?
````
rizin -q -a x86 -c"ao sub;q"
````

**Comment by eadmaster** [comment]
As alternative, can you link me the original dataset from which the files in `share/rizin/0.2.1/opcodes/` are built, so i can convert them into something i can query directly with `jq`?

**Comment by ret2libc** [comment]
> rz-asm -B -q -a x86 sub | rizin -q -a x86 -c"ao sub;q" = 

Where did you take this command? What are you trying to achieve?

```
$ rz-asm -w -a x86 -b 32 sub
substract src and dst, stores result on dst
```
or
```
$ rizin -q -a x86 -c"aod sub;q" - 2>/dev/null 
substract src and dst, stores result on dst
$ rizin -v
rizin 0.2.0 @ linux-x86-64, package: 0.2.0-2.fc33 (Fedora)
```
or
```
$ ~/.local/bin/rizin -q -a x86 -c"aod sub;q" = 2>/dev/null 
substract src and dst, stores result on dst
$ ~/.local/bin/rizin -v
rizin 0.3.0-git @ linux-x86-64
commit: 1348c247df151d5fdf8a6dd2b90222da14f7f6cb, build: 2021-05-19__10:47:49
```

> As alternative, can you link me the original dataset from which the files in share/rizin/0.2.1/opcodes/ are built, so i can convert them into something i can query directly with jq?

Those files are generated from `librz/asm/d/*.sdb.txt` files. I think they were manually created.

**Comment by eadmaster** [comment]
my aim was to get this output without having to type a full instruction:
````
[
  {
    "opcode": "endbr64",
    "disasm": "endbr64",
    "pseudo": "endbr64 ",
    "mnemonic": "endbr64",
    "mask": "ffffffff",
    "sign": false,
    "prefix": 0,
    "id": 1500,
    "opex": {
      "operands": []
    },
    "addr": 19840,
    "bytes": "f30f1efa",
    "size": 4,
    "type": "null",
    "esilcost": 0,
    "scale": 0,
    "refptr": 0,
    "cycles": 1,
    "failcycles": 0,
    "delay": 0,
    "stackptr": 0,
    "family": "cpu"
  }
]
````

After digging a bit in the source code, i've found the numeric fields are stored inside [these `ops` arrays](https://github.com/rizinorg/rizin/blob/dev/librz/asm/arch/6502/6502dis.c#L16). If there is no other way i'll try exporting these arrays into json via a script.

**Comment by ret2libc** [comment]
I think you can't get those data by just providing a mnemonic. A mov instruction in x86, for example, could be 2, 4 or more bytes based on the operands. So I'm not sure what kind of data you really expect to find by just giving the mnemonic

**Comment by eadmaster** [comment]
I didn't know some archs could have variable instruction sizes, i've only hacked very old archs like the z80 and 6502...

Btw in these cases having a list of values instead of a single one would work out for me. e.g.:
````
"size": [4, 8],
"cycles": [1, 2],
````

What do you think could be the easiest solution for this i could try?
Maybe via a core plugin?

Since this is meant only for quick reference usage i don't mind if some archs won't be supported.

**Comment by ret2libc** [comment]
Right not this request seems quite specific to your use case, so I think it won't be included/implemented within Rizin. As I said, most data won't make sense without having a full instruction. I'm not sure you can really extract all the right data from the current API (e.g. there is no way AFAIK to get the max size of an instruction just by giving the mnemonic).

**Comment by eadmaster** [comment]
I understand, thank you for your help anyway, i'll keep looking for alternative solutions for this.

If you have any tip just post here, i have subscribed the issue.

**Comment by ret2libc** [comment]
Sure, thanks for your patience! I was absent from Rizin for a while...
