### ISSUE TITLE
Support JSON Path in `librz/util/json_parser.c`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1108]
To ease the access of corresponding key and array number if available, something like `[0].methods[2].flags[0]` where first `[0]` will take first element of the JSON array, then key `"methods"`, which contains an array in turn, then take third element from that array, search for `"flags"` key, which has an array as a value, and take a first element of that array.

Files to change:
- `librz/util/json_parser.c`
- `librz/include/rz_util/rz_json.h`

**Comment by herrgahr** [comment]
Would you want to go full-on JSON path and support things like `[0].methods[*].flags[0]` or is it enough to limit the functionality to getting single elements?
