### ISSUE TITLE
Make sure to use the x64 Command Prompt for Visual studio

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#112]
The GitHub CI that builds windows uses the x32 command prompt and it generates 32bit binaries. This issue is to make sure we use the x64 environment and we generate 64 bit binaries.

**Comment by kazarmy** [comment]
> The GitHub CI that builds windows uses the x32 command prompt ...

Just nitpicking here but it should be x86 ... x32 is a slightly different arch

**Comment by ret2libc** [comment]
ehehe yeah :D it was just a mistake in the issue description.
