### ISSUE TITLE
Suggestion to move `ib` command

### ISSUE THREAD

**Issue by haystack-ia** [rizinorg/rizin#1120]
**Is your feature request related to a problem? Please describe.**

I recently had cause to use the `ib` command to reload a file using the ELF loader after extracting an ELF into a `malloc://` buffer from something else. Despite being a somewhat experienced user, it took me quite a while (and some googling) to figure out what command to use.

I was struck by the weird placement of the `ib` command; most all of the other `i` commands are for querying information, so it makes no sense (to me) that a command for reloading a file would be there.

**Describe the solution you'd like**
I think it should be under `o`, since that's where all the other commands for manipulating files and maps are.

**Describe alternatives you've considered**
I've poked around and I don't see any other places that would make sense.

**Comment by XVilka** [comment]
Good idea, `ob` is already taken though, we should think about the good alternative. cc @ret2libc @thestr4ng3r

**Comment by wargio** [comment]
agree. i saw that being used in the java tests before.

**Comment by thestr4ng3r** [comment]
It does reloading of the bin so it belongs under `ob`, yes.
