### ISSUE TITLE
Update currently broken core_plugin_example.c to Newshell API

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#1134]
The example core plugin at https://github.com/rizinorg/rizin/blob/bdface85a24a52d1c4a8cf2daa00dc6099e5db51/librz/core/p/core_plugin_example.c still uses a `.call = rz_cmd_example_call` callback for injecting commands, which does not exist anymore.

For reference, here are some plugins that have been updated:
https://git.sr.ht/~thestr4ng3r/rz-commodore/tree/master/item/src/core_commodore.c
https://github.com/rizinorg/rz-ghidra/blob/dev/src/core_ghidra.cpp
https://github.com/rizinorg/jsdec/blob/master/p/core_pdd.c

It might also be nice to somehow embed this in our build system and add to the test suite in some way.

**Comment by pparmin** [comment]
Hey everyone :) 

I am new to the project (for more information about me, check my post on [Mattermost](https://im.rizin.re/rizinorg/pl/3j4j1adkui8odfe8jj186trfqe) ) and I would love to tackle this! I have looked at the update files you have linked and saw that for the update files the ``.call`` part has mostly been removed. Would the updated  core_plugin_example.c require a mere removal of the ``.call`` section, or will it require additional functionality to be added to make it work again?

**Comment by ret2libc** [comment]
@pparmin It's not just about removing `.call` but it is about making it a "newshell" example (see https://github.com/rizinorg/rizin/blob/dev/doc/newshell.md).

Moreover, in the linked files you can see how those commands are implemented. For example, https://github.com/rizinorg/rz-ghidra/blob/dev/src/core_ghidra.cpp#L668 .
