### ISSUE TITLE
Expand the testsuite

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#114]
Current rizin testsuite is not extensive in regard to different compilers, optimization options, formats and programming languages. We need to expand it to cover more cases, platforms, ABIs, operating systems. Here are a few example where we can import some tests from:
- https://github.com/BinaryAnalysisPlatform/bap-testsuite
- https://github.com/LL-MM/approxis-groundtruth
- https://github.com/junxzm1990/x86-sok/tree/master/testsuite ([explanation paper](https://arxiv.org/ftp/arxiv/papers/2007/2007.14266.pdf))
- https://github.com/cmu-sei/pharos/tree/master/tests
- https://github.com/radareorg/radeco-regressions

**Comment by fangxlmr** [comment]
@Heersin This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by Heersin** [comment]
Thanks， I will do my best
