### ISSUE TITLE
`Ll~!^c` should print all lines that *aren't* started from `c` but it doesn't

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1140]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 34 x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64
commit: 07b937e235de1a0e0a416bf6c3af08c202bd5a7e, build: 2021-05-17__13:43:45

### Expected behavior

`Ll~!^c` should print all lines that *aren't* started from `c`:
```
[0x00006b10]> Ll~!^c
vala: Vala language extension (LGPL)
rust: Rust language extension (MIT)
zig: Zig language extension (MIT)
spp: SPP template programs (MIT)
```
### Actual behavior

```
[0x00006b10]> Ll~!^c
c: C language extension (LGPL)
cpipe: rzpipe scripting in C (LGPL)
vala: Vala language extension (LGPL)
rust: Rust language extension (MIT)
zig: Zig language extension (MIT)
spp: SPP template programs (MIT)
[0x00006b10]> Ll~"!^c"
[0x00006b10]> Ll~^c
c: C language extension (LGPL)
cpipe: rzpipe scripting in C (LGPL)
[0x00006b10]> Ll~^!c
c: C language extension (LGPL)
cpipe: rzpipe scripting in C (LGPL)
vala: Vala language extension (LGPL)
rust: Rust language extension (MIT)
zig: Zig language extension (MIT)
spp: SPP template programs (MIT)
```

**Comment by theopechli** [comment]
This doesn't work for any `L` cmd. I will look into it when I have time.

**Comment by theopechli** [comment]
Actually this doesn't work for many cmds.

```shell
[0x00005b20]> pI 20
endbr64
xor ebp, ebp
mov r9, rdx
pop rsi
mov rdx, rsp
and rsp, 0xfffffffffffffff0
push rax
push rsp
invalid
[0x00005b20]> pI 20~^mov
mov r9, rdx
mov rdx, rsp
[0x00005b20]> pI 20~!^mov
endbr64
xor ebp, ebp
mov r9, rdx
pop rsi
mov rdx, rsp
and rsp, 0xfffffffffffffff0
push rax
push rsp
invalid
```
So it's a problem with `!`. Dunno if I will work on it.
