### ISSUE TITLE
Write over (wo) commands don't respect block size override

### ISSUE THREAD

**Issue by TrungNguyen1909** [rizinorg/rizin#1165]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64
| File format of the file you reverse (mandatory)      | All
| Architecture/bits of the file (mandatory)            | All
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0 @ darwin-x86-64 commit: 6c7d508c9e8257c7e6f3f1fa78299eaf64114dbc, build: 2021-05-24__23:01:1

### Expected behavior

`wox 0x37 @0x0!0x30` should only xor 0x30 bytes

### Actual behavior

It xors 0x100 bytes (set block size)

### Steps to reproduce the behavior

Here is the [asciinema record](https://asciinema.org/a/Y80MjmMJnTfHiI26HwA72C2Cs)

**Comment by ret2libc** [comment]
This is valid bug indeed. Existing help still suggests to use `| <cmd> @ <addr>!<blocksize> # Temporary seek to <addr> and set blocksize to <blocksize>` as a way to temporarily set blocksize while also changing address, however I think we should kill this line of help and just use `@ <addr> @!<blocksize>`. You can indeed chain `@`statements as you prefer and I don't see particular reasons to support another syntax when `@!` is just as effective.

@XVilka @wargio @TrungNguyen1909 what do you think?

**Comment by wargio** [comment]
agree, but the help should be `| <cmd> @ <addr> @!<blocksize> # Temporary seek to <addr> and set blocksize to <blocksize>`

**Comment by ret2libc** [comment]
> agree, but the help should be `| <cmd> @ <addr> @!<blocksize> # Temporary seek to <addr> and set blocksize to <blocksize>`

We don't really need that line of help, we can remove it completely, because you can chain various statements as you like.
