### ISSUE TITLE
Jemalloc heap commands cause segfault

### ISSUE THREAD

**Issue by MalhotraPulak** [rizinorg/rizin#1167]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64, package: 0.2.0.1 (ret2libc) commit: c875be9afde5a6eed037249854b8a8759517263c, build: 2021-01-26__18:17:13

### Expected behavior
When using Jemalloc heap commands Rizin should not segfault.

### Actual behavior
After using Jemalloc heap commands Rizin segfaults. This behavior does not happen 100% but quite frequently. 

### Steps to reproduce the behavior
1. Load the libjemalloc shared object. I am using version 4.5
```bash
export LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"
```
2. Compile a simple binary. Here is the binary that I am using.
```C
#include <stdio.h>
#include <stdlib.h>

void stopper(){
    printf("hello");
}

int main(){
    char* first = malloc(64);
    stopper();
}
```
3. Run binary in Rizin in debug mode. Rizin log:
```
[0x7f1eb7709100]> db sym.stopper
[0x7f1eb7709100]> dc
hit breakpoint at: 0x5615d35e4169
[0x5615d35e4169]> e dbg.malloc=jemalloc
[0x5615d35e4169]> dmha
narenas : 16
arenas[16] @ 0x7f1eb7203c00 {
  arenas[0]: @ 0x7f1eb7203c00
  arenas[1]: (empty)
  arenas[2]: (empty)
  arenas[3]: (empty)
  arenas[4]: (empty)
  arenas[5]: (empty)
  arenas[6]: (empty)
  arenas[7]: (empty)
  arenas[8]: (empty)
  arenas[9]: (empty)
  arenas[10]: (empty)
  arenas[11]: (empty)
  arenas[12]: (empty)
  arenas[13]: (empty)
  arenas[14]: (empty)
  arenas[15]: (empty)
}
[0x5615d35e4169]> hello./compile_and_run.sh: line 4: 516482 Segmentation fault      (core dumped) ./rizin-linux/build/binrz/rizin/rizin -d simp
```
Note: Jemalloc commands have now changed to `dmx` from `dmh` so using commands like `dmxc` is causing crash in newer builds of Rizin

**Comment by ret2libc** [comment]
@PulakIIIT is this still happening? Could you confirm?

**Comment by MalhotraPulak** [comment]
@ret2libc Yes I am still able to replicate this issue

**Comment by XVilka** [comment]
@PulakIIIT is there any way to avoid the crash and at least print some error meanwhile? Such a quick fix if the proper fix will take time, would be a perfect fit to include in the upcoming 0.3.0

**Comment by MalhotraPulak** [comment]
I am not certain of the cause of this seg fault at the moment. I will look more into and see if it is possible to print some error in the meanwhile.
