### ISSUE TITLE
Rizin-0.2.1 compilation on Gentoo error: ‘TSLanguage’ has no member named ‘production_id_count’

### ISSUE THREAD

**Issue by Petross404** [rizinorg/rizin#1194]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                   | Gentoo  x64
| Compiler                                             | GCC 11.1

### Expected behavior
Building rizin should finish

### Actual behavior
Build fails with error:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: total time in link: 0.044487
[162/1186] x86_64-pc-linux-gnu-gcc -Ishlr/rizin-shell-parser/libshell_parser.a.p -Ishlr/rizin-shell-parser -I../rizin-v0.2.1/shlr/rizin-shell-parser -I. -I../rizin-v0.2.1 -I../rizin-v0.2.1/librz/include -I../rizin-v0.2.1/shlr/rizin-shell-parser/src/tree_sitter -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch --std=gnu99 -D_GNU_SOURCE -Werror=sizeof-pointer-memaccess -fvisibility=hidden -march=native -mprefer-avx128 -mvzeroupper -frecord-gcc-switches -mindirect-branch=thunk -mfunction-return=thunk -mindirect-branch-register -flto -flto-report -fuse-linker-plugin -O2 -fno-lto -fno-use-linker-plugin -fPIC -MD -MQ shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o -MF shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o.d -o shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o -c ../rizin-v0.2.1/shlr/rizin-shell-parser/src/parser.c
FAILED: shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o 
x86_64-pc-linux-gnu-gcc -Ishlr/rizin-shell-parser/libshell_parser.a.p -Ishlr/rizin-shell-parser -I../rizin-v0.2.1/shlr/rizin-shell-parser -I. -I../rizin-v0.2.1 -I../rizin-v0.2.1/librz/include -I../rizin-v0.2.1/shlr/rizin-shell-parser/src/tree_sitter -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch --std=gnu99 -D_GNU_SOURCE -Werror=sizeof-pointer-memaccess -fvisibility=hidden -march=native -mprefer-avx128 -mvzeroupper -frecord-gcc-switches -mindirect-branch=thunk -mfunction-return=thunk -mindirect-branch-register -flto -flto-report -fuse-linker-plugin -O2 -fno-lto -fno-use-linker-plugin -fPIC -MD -MQ shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o -MF shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o.d -o shlr/rizin-shell-parser/libshell_parser.a.p/src_parser.c.o -c ../rizin-v0.2.1/shlr/rizin-shell-parser/src/parser.c
../rizin-v0.2.1/shlr/rizin-shell-parser/src/parser.c: In function ‘tree_sitter_rzcmd’:
../rizin-v0.2.1/shlr/rizin-shell-parser/src/parser.c:29425:6: error: ‘TSLanguage’ has no member named ‘production_id_count’
29425 |     .production_id_count = PRODUCTION_ID_COUNT,
      |      ^~~~~~~~~~~~~~~~~~~
```
### Steps to reproduce the behavior
emerge -1 rizin

### Additional Logs, screenshots, source code,  configuration dump, ...
[dev-util:rizin-0.2.1:20210606-091509.log](https://github.com/rizinorg/rizin/files/6603944/dev-util.rizin-0.2.1.20210606-091509.log)

**Comment by ret2libc** [comment]
Hi @Petross404 !

Looking at the logs you provided I saw:
```
Run-time dependency tree-sitter found: YES 0.6.3
```

I would expect to see at least 0.19.x. Could you double check you have an updated version of tree-sitter on your system? I also tried to build locally against the very latest 0.19.5 release of tree-sitter and it seems to work. My guess is that your version of tree-sitter is older than what we expect.

If you want to build with system tree-sitter lib, I think you should update it.
Otherwise, you can use `use_sys_tree_sitter=disabled` to force the usage of embedded tree-sitter version.

Let us know if this works!

**Comment by XVilka** [comment]
I think the ebuild of `dev-util/rizin` should be updated to restrict the acceptable tree-sitter version:
https://github.com/gentoo/gentoo/blob/master/dev-util/rizin/rizin-0.2.1.ebuild#L32
```
RDEPEND="
	sys-apps/file
	app-arch/lz4:0=
	dev-libs/capstone:0=
	dev-libs/libuv:0=
	dev-libs/libzip:0=
	dev-libs/openssl:0=
	dev-libs/tree-sitter
	dev-libs/xxhash
	sys-libs/zlib:0=
"
```
cc @trofi

**Comment by trofi** [comment]
Gentoo has 2 tree-sitter libraries:
- C library: https://packages.gentoo.org/packages/dev-libs/tree-sitter
- Python library: https://packages.gentoo.org/packages/dev-python/tree-sitter

`0.6.3` looks very misleading. It comes from `0.19.5`'s `/usr/lib64/pkgconfig/tree-sitter.pc` file and happens on my machine as well. I'll investigate locally. Probably a `dev-libs/tree-sitter` packaging bug.

**Comment by trofi** [comment]
@Petross404 if you stil have this build issue can you post your `emerge --info dev-libs/tree-sitter` output to see what version you actually have installed?

**Comment by trofi** [comment]
`production_id_count` was added in `0.19.0`: https://github.com/tree-sitter/tree-sitter/commit/c1639cc456b0fafb73d91108617ffa1206d6e9f9

**Comment by Petross404** [comment]
Oh dear, I missed the whole conversation. I will sync my portage tree and let you know!

**Comment by Petross404** [comment]
Updating dev-libs/tree-sitter to 0.19 fixed the build issue for Rizin.

Thank you for your time!
