### ISSUE TITLE
Migrate function checks from headers to Meson

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1261]
Currently we have code like
```c
#ifndef HAVE_EPRINTF
#define eprintf(...) fprintf(stderr, __VA_ARGS__)
#define HAVE_EPRINTF 1
#endif
```
in `librz/include/rz_types.h`.
It should be migrated to the `meson.build` checks like it's done for some functions already:
```meson
foreach item : [
    ['arc4random_uniform', '#include <stdlib.h>', []],
    ['explicit_bzero', '#include <string.h>', []],
    ['explicit_memset', '#include <string.h>', []],
    ['clock_nanosleep', '#include <time.h>', []],
    ['clock_gettime', '#include <time.h>', [lrt]],
    ['sigaction', '#include <signal.h>', []],
    ['pipe', '#include <unistd.h>', []],
    ['execv', '#include <unistd.h>', []],
    ['execve', '#include <unistd.h>', []],
    ['execvp', '#include <unistd.h>', []],
    ['execl', '#include <unistd.h>', []],
    ['system', '#include <stdlib.h>', []],
    ['fork', '#include <unistd.h>', []],
    ['pipe2', '#define _GNU_SOURCE\n#include <fcntl.h>\n#include <unistd.h>', []]
  ]
  func = item[0]
  ok = cc.has_function(func, prefix: item[1], dependencies: item[2])
  userconf.set10('HAVE_@0@'.format(func.to_upper()), ok)
endforeach
```

**Comment by XVilka** [comment]
There is one more thing, these are defined but not used. Probably should be safe to remove:
```c
/* release >= 5.9 */
#if __OpenBSD__ && OpenBSD >= 201605
#define LIBC_HAVE_PLEDGE 1
#else
#define LIBC_HAVE_PLEDGE 0
#endif

#if __sun
#define LIBC_HAVE_PRIV_SET 1
#else
#define LIBC_HAVE_PRIV_SET 0
#endif
```

It was used in `librz/util/sandbox.c` which was removed:
- https://github.com/rizinorg/rizin/commit/40a29cba29ebb58a15ca372a765be56e5d19d5ac#diff-d12676f3646474c2ad227b96dc3bb5edf0990fb356b099bfd2b91c194e240ee9L131
- https://github.com/rizinorg/rizin/commit/40a29cba29ebb58a15ca372a765be56e5d19d5ac#diff-d12676f3646474c2ad227b96dc3bb5edf0990fb356b099bfd2b91c194e240ee9L14

**Comment by ret2libc** [comment]
I will split this into a list of defines that we need to have, but I think there's no need for this to block any release. We did already major meson stuff in the last release and the upcoming one, this is just a nice plus but IMO not a blocker. Postponing for 0.4.0. I will focus a bit more on these kind of things in the future.

**Comment by XVilka** [comment]
I think all function detection is already converted to Meson by now.

**Comment by ret2libc** [comment]
More or less.. there's probably much more room for improvements, but let's close this. Things will be fixed as they are noticed!
