### ISSUE TITLE
Missing method references in DEX

### ISSUE THREAD

**Issue by haeter525** [rizinorg/rizin#1276]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04.2 LTS x64
| File format of the file you reverse (mandatory)      | APK
| Architecture/bits of the file (mandatory)            | Dalvik
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64 commit: ad5dd4831782b771a41547602c2cd0ac9657b162, build: 2021-07-06__19:45:082021-01-26__18:17:13

### Expected behavior
List all the function references of a given method.

### Actual behavior
Rizin missed some function references of the given method.

---

For instance, find the references of the following method.
```
Lahmyth/mine/king/ahmyth/ConnectionManager; sendReq ()V
```

When using `axff~CALL` command, Rizin gives the output. 
```
CALL 0x000411ce 0x00041934 method.static.public.Lahmyth_mine_king_ahmyth_IOSocket.Lahmyth_mine_king_ahmyth_IOSocket.method.getInstance__Lahmyth_mine_king_ahmyth_IOSocket
CALL 0x000411d6 0x0004194c method.public.Lahmyth_mine_king_ahmyth_IOSocket.Lahmyth_mine_king_ahmyth_IOSocket.method.getIoSocket__Lio_socket_client_Socket
CALL 0x000411ee 0x00040e40 method.constructor.Lahmyth_mine_king_ahmyth_ConnectionManager_1.Lahmyth_mine_king_ahmyth_ConnectionManager_1.method._init___V
CALL 0x00041206 0x00040e84 method.constructor.Lahmyth_mine_king_ahmyth_ConnectionManager_2.Lahmyth_mine_king_ahmyth_ConnectionManager_2.method._init___V
CALL 0x00041216 0x00044ce8 method.public.Lio_socket_client_Socket.Lio_socket_client_Socket.method.connect__Lio_socket_client_Socket
```

However, if using [Jadx](https://github.com/skylot/jadx) to view the bytecode, you would see some methods are not listed above.

One of these methods is as follows.
```
Lio/socket/client/Socket; on (Ljava/lang/String; Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter;
```

It is called in line 117, with a yellow background.

![](https://i.imgur.com/fZ9IhCK.png)

### Steps to reproduce the behavior
1. Download the [APK](https://github.com/rizinorg/rizin/files/6770399/Ahmyth.zip)
2. Unzip it and open it with Rizin
3. Type in the following commands
```
aaa
s `is~Lahmyth/mine/king/ahmyth/ConnectionManager.method.sendReq[1]`
axff~CALL
```

**Comment by haeter525** [comment]
Hi, we (@18z, @krnick, @pulorsok, and me) plan to use Rizin as a new core library of our Android malware scoring system, [Quark-Engine](https://github.com/quark-engine/quark-engine).

Solving the issue will help us a lot. If there is anything we can do, please feel free to let us know. :)

**Comment by ret2libc** [comment]
```
[0x000411c4]> pdf
            ;-- Lahmyth/mine/king/ahmyth/ConnectionManager.method.sendReq()V:
┌ method.static.public.Lahmyth_mine_king_ahmyth_ConnectionManager.Lahmyth_mine_king_ahmyth_ConnectionManager.method.sendReq__V ();
│           0x000411c4      sget-object v1, Lahmyth/mine/king/ahmyth/ConnectionManager;->ioSocket Lio/socket/client/Socket; ; ConnectionManager.java:53
│       ┌─< 0x000411c8      if-eqz v1, 0x000411ce                      ; ConnectionManager.java:125
│       │   0x000411cc      return-void
│       └─> 0x000411ce      invoke-static {}, Lahmyth/mine/king/ahmyth/IOSocket.getInstance()Lahmyth/mine/king/ahmyth/IOSocket; ; 0x23
│           0x000411d4      move-result-object v1
│           0x000411d6      invoke-virtual {v1}, Lahmyth/mine/king/ahmyth/IOSocket.getIoSocket()Lio/socket/client/Socket; ; 0x24
│           0x000411dc      move-result-object v1
│           0x000411de      sput-object v1, Lahmyth/mine/king/ahmyth/ConnectionManager;->ioSocket Lio/socket/client/Socket;
│           0x000411e2      sget-object v1, Lahmyth/mine/king/ahmyth/ConnectionManager;->ioSocket Lio/socket/client/Socket;
│           0x000411e6      const-string v2, 0x28f85
│           0x000411ea      new-instance v3, Lahmyth/mine/king/ahmyth/ConnectionManager$1;
│           0x000411ee      invoke-direct {v3}, Lahmyth/mine/king/ahmyth/ConnectionManager$1.<init>()V ; 0xc
│           0x000411f4      invoke-virtual {v1, v2, v3}, Lio/socket/client/Socket.on(Ljava/lang/String;Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter; ; 0x141
│           0x000411fa      sget-object v1, Lahmyth/mine/king/ahmyth/ConnectionManager;->ioSocket Lio/socket/client/Socket;
│           0x000411fe      const-string v2, 0x28a0a
│           0x00041202      new-instance v3, Lahmyth/mine/king/ahmyth/ConnectionManager$2;
│           0x00041206      invoke-direct {v3}, Lahmyth/mine/king/ahmyth/ConnectionManager$2.<init>()V ; 0xe
│           0x0004120c      invoke-virtual {v1, v2, v3}, Lio/socket/client/Socket.on(Ljava/lang/String;Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter; ; 0x141
│           0x00041212      sget-object v1, Lahmyth/mine/king/ahmyth/ConnectionManager;->ioSocket Lio/socket/client/Socket;
│           0x00041216      invoke-virtual {v1}, Lio/socket/client/Socket.connect()Lio/socket/client/Socket; ; 0x138
│           0x0004121c      goto  0x000411cc
```

It seems that somehow `axff` is missing `0x000411f4      invoke-virtual {v1, v2, v3}, Lio/socket/client/Socket.on(Ljava/lang/String;Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter; ; 0x141` and `0x0004120c      invoke-virtual {v1, v2, v3}, Lio/socket/client/Socket.on(Ljava/lang/String;Lio/socket/emitter/Emitter$Listener;)Lio/socket/emitter/Emitter; ; 0x141`

**Comment by wargio** [comment]
looks like an issue related to the xrefs and how dex is parsed.
I will fix this, but it will require a huge refactoring of DEX.

**Comment by wargio** [comment]
Fix submitted, by resolving virtual methods
