### ISSUE TITLE
Wrong analysis results of Busybox PowerPC

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1282]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PPC 32bit
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/0e11486f36aa784b471d8d4ecf291a8d962b4c47

### Expected behavior

Auto-detection of the function boundaries and function arguments.

### Actual behavior

```
rizin tests/bins/elf/busybox-powerpc
aaa
s 0x10002d70
Vp
```

![image](https://user-images.githubusercontent.com/203261/124909594-369f1200-e01d-11eb-896f-bda96416484b.png)

Also note the invalid detection of the function arguments.

### Additional Logs, screenshots, source code,  configuration dump, ...

See also https://github.com/rizinorg/rizin/pull/1281#issuecomment-876327317

**Comment by wargio** [comment]
This issue seems to be already fixed (see screenshot below)
![image](https://user-images.githubusercontent.com/561184/147795914-9760d03f-b89a-47c1-b8b8-784fcffe86c5.png)
