### ISSUE TITLE
Adapt release pipeline to include submodules code in the src tarball

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#13]
SDB is now a submodule and it is not automatically included in the github-generated tarball.

**Comment by XVilka** [comment]
Please also update the tree-sitter to the latest release before the 0.1.0: https://github.com/tree-sitter/tree-sitter/releases

To date it will be 0.18.0 likely: https://github.com/tree-sitter/tree-sitter/releases/tag/0.18.0

**Comment by XVilka** [comment]
Just checked with
```
meson dist --include-subprojects --no-tests
``` 
It works like a charm. Should be enough.
