### ISSUE TITLE
Visual `p==` mode

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#130]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/203261/77060963-700cd200-6a14-11ea-9ec4-f16d6acd49f9.png)
It would be awesome to provide the similar looking visual mode, but with the hotkeys for each columns.

For example on the screenshot you see the **7th column** with high entropy, which might be of our interest. But there is no indication how to get there. So in the visual alternative to `p==` command there are will be hotkeys to go for the each section, like we have the hotkeys in the visual disasm or graph modes.

What I meant is to have the whole-file overview of the `p==` mode, withe the ability to jump quickly to the corresponding place, and showing where we are on it, with some kind of cursor. Like a map of the file in Cutter, but with entropy. For visual mode it might be:
- At the top of the view is the `p==` output for the whole file with cursor and navigation
- At the left/right part of the view is the `p=` output for the current block (or on-screen content?)
- And the hexdump or whatever you want in the main part of the screen.

See also:
- [Add visual `p=` scrolling mode](https://github.com/rizinorg/rizin/issues/128) (similar problem, just more detailed - vertical mode, while this issue is for horizontal mode)
- [Add a ruler to horizontal histogram output (e.g. `p==`)](https://github.com/rizinorg/rizin/issues/129)
- librz/cons/histogram.c
- librz/cons/bar.c

**Comment by XVilka** [comment]
@parthbansaliitr since you worked on entropy mode, maybe this one (or other related issues) could be interesting for you.

**Comment by banparth** [comment]
@XVilka, I would love to work on this issue. Can you please elaborate on what kind of hotkeys you wanted?

**Comment by XVilka** [comment]
@parthbansaliitr you can assign every peak (over certain threshold) with a number, just like we have ones for calls in visual disasm `[0]`, `[1]`, etc.

**Comment by XVilka** [comment]
Nevermind, this approach will not be scalable for files with many peaks and falls. We probably should offer "zoom" and "left"-"right" hotkeys instead.

**Comment by banparth** [comment]
Okay, thanks. Is there any existing visual mode for some features? Please tell me. It will help me to know about some existing functions.

**Comment by banparth** [comment]
@XVilka, can you please tell me how to start on this issue?

**Comment by XVilka** [comment]
@parthbansaliitr see `librz/core/agraph.c` as an example, and current implementation is in `librz/cons/histogram.c`

**Comment by banparth** [comment]
@XVilka I have implemented a simple interactive histogram that currently moves "left-right" according to the current block (keeping current block in the center and highlighting the current block) and information about the current block at the bottom. Please tell me what else I need to add to this or changes in the contemporary design. https://github.com/parthbansaliitr/rizin/tree/visual_p%3D%3D_mode.130

**Comment by banparth** [comment]
@XVilka, Can you please check the progress and tell me the further requirements?
