### ISSUE TITLE
Compress all resoures (SDB files, etc) into binary for static builds

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1301]
Currently statically-built `rizin` still has a bunch of SDB files that should be located at the prefix. We could just concatenate them together and put directly into the binary.

**Comment by ret2libc** [comment]
We have portable builds where you can move your static bin wherever you want as long as you move the whole riZin directory. Is it worth the effort?

**Comment by ret2libc** [comment]
I propose to close this. As said, there is already portable builds which solve the issue.
