### ISSUE TITLE
PowerPC QPX not supported

### ISSUE THREAD

**Issue by Phosphorus15** [rizinorg/rizin#1306]
Rizin has no support for PowerPC QPX instructions for now, and from some of the source files it was commented out for some reason

https://github.com/rizinorg/rizin/blob/cad4e0ae0f967f325bfb2da25d18f1d3ddff2966/librz/parse/p/parse_ppc_pseudo.c

**Comment by wargio** [comment]
[Qpx.pdf](https://github.com/rizinorg/rizin/files/6816022/Qpx.pdf)

**Comment by Rot127** [comment]
Capstone supports them since 4.0 (since ~2019: https://www.capstone-engine.org/Version-4.0-changelog). If someone has a binary we should test it actually does not work.

**Comment by wargio** [comment]
i guess you can build an example with something like this:
```c
// g++ qpx.c -lquadmath
#include <stdio.h>
#include <quadmath.h>

int main(){
  __float128 x = expq(282.49q);
  char buffer[128];
  quadmath_snprintf(buffer, sizeof buffer, "%.36Qg\n", x);
  puts(buffer)
}
```

**Comment by XVilka** [comment]
Will probably be addressed by https://github.com/rizinorg/rizin/pull/3648 but maybe worth adding an actual test, maybe even in the same PR if it works already @Rot127

**Comment by Rot127** [comment]
Sure. Would copy some asm tests from LLVM.
