### ISSUE TITLE
zfs creates multiple functions with the same name, breaking project opening

### ISSUE THREAD

**Issue by ctlayon** [rizinorg/rizin#1314]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MAC OS Big Sur x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0 @ darwin-x86-64 commit: 432e4ba85fbd992f6e926012b5bf29d97ecbc092, build: 2021-07-16__10:46:57

### Expected behavior
When I open a sufficiently large windows binary and apply a flirt signature file (I'm using vc64ucrt.sig from hexrays) and the same pattern matches twice I expect:

1. A flirt flag to be created 
2. If the flirt name is not already a defined function and the matched function is not already named, the flirt flag to be used as the function name
3. If the flirt name is already a defined function a duplicate function name should not be created but something like:
```
First Match: flirt.acrt_uninitialize_locks
Second Match: flirt.acrt_uninitialize_locks_02

```
At a minimum there should be a check if the function name already exists. And if it does do not duplicate it when saving.

### Actual behavior

When I do a Ps project_name, the project saves an invalid .rzdb file as the function is duplicated resulting in the following error when loading via Po:
```
[0x140002e14]> Po dump.rzdb
Invalid function name 'flirt.acrt_uninitialize_ptd' at 0x140006b48
Failed to load project: invalid content encountered
  functions parsing failed
```
Looking at the DB file you see the duplicated name:
```
▶ cat dump.rzdb | egrep -i "acrt_uninitialize_ptd"
0x140004214={"name":"flirt.__acrt_uninitialize_ptd","bits":64,"type":1,"cc":"ms","stack":80,"maxstack":80,"ninstr":9,"bp_frame":true,"diff":{},"bbs":[5368726036,5368726051,5368726063]}
0x140006b48={"name":"flirt.__acrt_uninitialize_ptd","bits":64,"type":1,"cc":"ms","stack":80,"maxstack":80,"ninstr":9,"bp_frame":true,"diff":{},"bbs":[5368736584,5368736599,5368736611]}
flirt.__acrt_uninitialize_ptd={"realname":"flirt.__acrt_uninitialize_ptd","demangled":false,"offset":5368736584,"size":34,"space":"flirt"}

```

### Steps to reproduce the behavior
Using calc.exe (MD5: afaf2cdf9981342c494b28630608f74a) from a windows 10 x86_64, attached as a zip
[calc.zip](https://github.com/rizinorg/rizin/files/6827710/calc.zip)
:

1. rizin -a x86 -b 64 calc.exe
2. [0x1400017e0]> aaa
```
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
```
3. [0x1400017e0]> zfs ./sigs/vc64rtf.sig # where vc64rtf is from hexrays, but any sig pattern that matches twice would work
```
Found flirt.__security_check_cookie
Found flirt._guard_dispatch_icall
Found flirt._guard_dispatch_icall
Found flirt._IsNonwritableInCurrentImage
Found flirt._ValidateImageBase
Found flirt._guard_dispatch_icall
```
4. [0x1400017e0]> Ps calc
5. [0x1400017e0]> q
6. rizin -a x86 -b 64 calc.exe
7. [0x1400017e0]> Po calc
```
Invalid function name 'flirt._guard_dispatch_icall' at 0x1400018f9
Failed to load project: invalid content encountered
  functions parsing failed
```

### Additional Logs, screenshots, source code,  configuration dump, ...
```
▶ cat calc | egrep "flirt._guard_dispatch_icall"
0x140001858={"name":"flirt._guard_dispatch_icall","bits":64,"type":1,"cc":"ms","stack":40,"maxstack":40,"ninstr":1,"bp_frame":true,"diff":{},"bbs":[5368715352]}
0x1400018f9={"name":"flirt._guard_dispatch_icall","bits":64,"type":1,"cc":"ms","stack":40,"maxstack":40,"ninstr":1,"bp_frame":true,"diff":{},"bbs":[5368715513]}
flirt._guard_dispatch_icall={"realname":"flirt._guard_dispatch_icall","demangled":false,"offset":5368715352,"size":6,"space":"flirt"}
```

Again the solution for me was to rename the second match by appending _02:
```
▶ cat calc | egrep "flirt._guard_dispatch_icall"
0x140001858={"name":"flirt._guard_dispatch_icall","bits":64,"type":1,"cc":"ms","stack":40,"maxstack":40,"ninstr":1,"bp_frame":true,"diff":{},"bbs":[5368715352]}
0x1400018f9={"name":"flirt._guard_dispatch_icall_02","bits":64,"type":1,"cc":"ms","stack":40,"maxstack":40,"ninstr":1,"bp_frame":true,"diff":{},"bbs":[5368715513]}
flirt._guard_dispatch_icall={"realname":"flirt._guard_dispatch_icall","demangled":false,"offset":5368715352,"size":6,"space":"flirt"}

▶ rizin -a x86 -b 64 calc.exe
[0x1400017e0]> Po calc
[0x1400017e0]> afl~+icall
0x140001858    1 6            flirt._guard_dispatch_icall
0x1400018f9    1 6            flirt._guard_dispatch_icall_02
```

Ideally there should be a check when first saving the .rzdb file to ensure this error does not occur.

**Comment by ctlayon** [comment]
Rudimentary script to clean this up for anyone else experiencing this in the meantime:
```python
import json
import sys

in_path = sys.argv[1]
out_path = f'{in_path}_clean.rzdb'

if in_path[-5:] == '.rzdb':
    out_path = f'{in_path[:-5]}_clean.rzdb'

data = open(in_path, 'r').readlines()
out = ''

seen = {}

for line in data:
    to_add = line
    if '0x' != line[0:2]:
        out += to_add
        continue

    if '{\"name\":\"flirt.' not in line[:100]:
        out += to_add
        continue

    address, raw_json_data = line.split('=', 1)
    json_data = json.loads(raw_json_data)
    name = json_data['name']
    if name in seen:
        seen[name] += 1
        json_data['name'] = f'{name}_{seen[name]:02d}'
    elif name not in seen:
        seen[name] = 0
        json_data['name'] = f'{name}'

    out += f'{address}={json.dumps(json_data)}\n'

open(out_path, 'w').write(out)
```

**Comment by ret2libc** [comment]
Moving to 0.4.0, so it can be done together with #973 and #272 . Thanks for the precise report btw!
