### ISSUE TITLE
Improve Windows `rz-test` performance

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1320]
Currently, the Windows `rz-test` performance is significantly slower than any other platform. It is beneficial to figure out possible bottleneck and improve testing times.

See
- `binrz/rz-test/rz-test.c`
- `binrz/rz-test/run.c`
- `librz/util/subprocess.c`

**Comment by mdonoughe** [comment]
PerfView sampling on my system says about 60% of samples are in `CreateProcessWStub` so it looks like process creation is the problem. I tried explicitly specifying the handles to inherit using `PROC_THREAD_ATTRIBUTE_HANDLE_LIST`, but there was no meaningful improvement. If this is the performance limit for process creation on Windows there's not much that can be done about it short of redesigning rz-test.

**Comment by XVilka** [comment]
Thank you, @mdonoughe!
I think we can close this then.
