### ISSUE TITLE
Fix PE: corkami 65535sects.exe - section list, entrypoint, open and analyze with ASAN build

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1341]
It is unnecessary slow. Could be and should be optimized. It fails on our CI
```
[XX] db/formats/pe/65535sects PE: corkami 65535sects.exe - section list, entrypoint, open and analyze
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aa
om~?
s
pi 1
q!
' bins/pe/65535sects.exe
-- stdout
--- expected
+++ actual
@@ -1,3 +1,0 @@
-65536
-0x291120
-mov edi, 0x7027aff9

-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

-- exit status: -1
```

**Comment by p371jah** [comment]
I guess it's just killed by timeout.

**Comment by wargio** [comment]
this behaviour changed with the new code for the Type Analysis.

**Comment by ret2libc** [comment]
Not sure of the status of this... Seems it worked in some cases recently. Let's see.

**Comment by wargio** [comment]
if you check the phy size and ignore any 0 sizes when allocating the PE data structure, you will notice that the test will be super fast.
now the issue is that we should rule out any invalid data structure that is not a known used PE section.

**Comment by wargio** [comment]
is this fixed? dev is green

**Comment by ret2libc** [comment]
It seems so, but let's wait few days and then we can close this and probably also another one.

**Comment by ret2libc** [comment]
Seems green lately!
