### ISSUE TITLE
Default page of this project now says "anal" many times, as well as git history.

### ISSUE THREAD

**Issue by giantpune** [rizinorg/rizin#136]
There were a couple commits trying to PC up the potty language in r2.  As a result, now a dozen or so files on the default page for this repo show "anal".

![image](https://user-images.githubusercontent.com/543833/101530321-c1bd0a00-395f-11eb-8717-dcd67af6c8ac.png)

**Comment by ITAYC0HEN** [comment]
Hi giantpune, thank you for opening the issue.
It is unfortunate but that is the consequence of the renaming we did. With time, commits will be added and different commits messages will be shown.

Thank you once again!
