### ISSUE TITLE
Add API for C string representation of types

### ISSUE THREAD

**Issue by MalhotraPulak** [rizinorg/rizin#1399]
**Is your feature request related to a problem? Please describe.**
Cutter relies on parsing the cmd output of `tXc` commands to get the C string representation of struct/enum etc but this functionality is not working with the new RzTypes commands for some reason. A better solution is to just use an RZ_API for getting the c string representation of the type.

**Describe alternatives you've considered**
- Fix `cmd_raw` so that it works with the new rztypes commands. I am not sure how `cmd_raw` works so this is hard for me to fix.

**Comment by MalhotraPulak** [comment]
Ill give this issue a try!

**Comment by XVilka** [comment]
See also https://github.com/rizinorg/rizin/issues/727

**Comment by XVilka** [comment]
In general it should be enough to use `rz_type_as_string()` and `rz_type_declaration_as_string()` and `rz_type_indentifier_declaration_as_string()` depending on the use case.

**Comment by MalhotraPulak** [comment]
Since `rz_type_as_string()` mostly does the job I am closing this issue
