### ISSUE TITLE
Save project in compressed format, to save disk space.

### ISSUE THREAD

**Issue by xrkk** [rizinorg/rizin#1417]
Since default gzip will compress 8.1M rzdb to 1.1M, it will save a lot of disk space.

Rizin has `rz_inflate_*()` functions for decompression of the Zlib data. It might be useful to add the `rz_deflate_*()` functions and use them in the compressing the projects.

See:
- `librz/include/rz_util/rz_file.h`
- `librz/util/file.c`
- `librz/core/project.h`

**Comment by Himanxu1** [comment]
I want to contribute to this project!

**Comment by ret2libc** [comment]
cc @thestr4ng3r
