### ISSUE TITLE
Backport "Sort flags by [sections,formats][other][regs]"

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1429]
radareorg/radare2@4ade590

I haven't tested the radare2 code, but I think we don't need all that to reach the purpose We can use rz_flag_get_by_spaces (or rz_core_flag_get_by_spaces if that's fine) which allows you get to get the flags at a given address sorted by FlagSpaces. We already use rz_core_flag_get_by_spaces in many other places, so maybe that's the right function to use here as well, for consistency in the order used.

**Comment by ret2libc** [comment]
I'm going to remove this from 0.3.0 because this is not going to be a simple backport. In particular, we should first add a rz_flag_get_list_by_spaces API, add unit tests for it and use that in disasm.c to get a list of flagitems sorted by the specified spaces.

**Comment by XVilka** [comment]
I think it's better to coincide this change with porting of the `f` commands to the newshell and proper API. It will help to understand better API design.

**Comment by ret2libc** [comment]
@wargio wasn't this done already by you? Or do i remember wrong?

**Comment by ret2libc** [comment]
> @wargio wasn't this done already by you? Or do i remember wrong?

@wargio ping?

**Comment by wargio** [comment]
no i do not remember doing this.

**Comment by ret2libc** [comment]
I'm going to close this because TBH I do not see any special improvements to the output... If we notice, we are going to fix it.
