### ISSUE TITLE
Convert analysis `a` (cmd_analysis.c) commands to rzshell

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1442]
Some of the commands are already converted, we should finish the complete migration. Moreover, some analysis logic is inside the `librz/core/cmd_analysis.c`. We should move as much as possible inside either `librz/analysis/*` or `librz/core/canalysis.c` from `librz/core/cmd_analysis.c`.

The task implies also possible API changes and some refactorings, see https://github.com/rizinorg/rizin/issues/1223, https://github.com/rizinorg/rizin/issues/1117, https://github.com/rizinorg/rizin/issues/992, and https://github.com/rizinorg/rizin/issues/489

- [x] `ar` https://github.com/rizinorg/rizin/pull/2006
- [x] `af` https://github.com/rizinorg/rizin/pull/2040, https://github.com/rizinorg/rizin/pull/2586
- [x] `aa` https://github.com/rizinorg/rizin/pull/2594
- [x] `a8` https://github.com/rizinorg/rizin/pull/2396
- [x] `ab` https://github.com/rizinorg/rizin/pull/2395
- [x] `ac` https://github.com/rizinorg/rizin/pull/2160
- [x] `aC` https://github.com/rizinorg/rizin/pull/2793
- [x] `ad`
- [ ] `ae`  https://github.com/rizinorg/rizin/issues/1533
- [x] `aF`
- [x] `ag` https://github.com/rizinorg/rizin/pull/2916
- [x] `ah` https://github.com/rizinorg/rizin/pull/2130
- [x] `ai`
- [x] `aL`
- [x] `an` https://github.com/rizinorg/rizin/pull/2447
- [x] `ao` https://github.com/rizinorg/rizin/pull/2396
- [x] `aO` https://github.com/rizinorg/rizin/pull/2396
- [x] `ap` (removed)
- [x] `as` https://github.com/rizinorg/rizin/pull/2323
- [x] `av`
- [x] `ax`

See these files:
- `librz/core/cmd_analysis.c`
- `librz/core/cmd_descs/cmd_analysis.yaml`

The task is important for further porting of different architectures to the global variables, new IL.

**Comment by p371jah** [comment]
`ax` commands have already been ported
