### ISSUE TITLE
Excessive use of builds.sr.ht

### ISSUE THREAD

**Issue by ddevault** [rizinorg/rizin#1449]
Hello! I am an administrator for sourcehut and I've noticed that your builds are consuming an excessive amount of resources. Over the past month, Rizin has run over 121,000 build minutes on builds.sr.ht, which if priced similarly to, say, CircleCI, would have run you a bill over $750.

You need to reduce your usage: it is disruptive to other users. Please disable your pull request hook on https://dispatch.sr.ht and please move your feature branches to each developer's personal forks, so that only commits to master are built rather than every commit to each pull request being built twice. You can also check GITHUB_REF in the build manifest and terminate the build early (using the "complete-build" command) if you're building something other than the master branch.

**Comment by XVilka** [comment]
Disabled the PR hook.

**Comment by XVilka** [comment]
Sorry about that. We will add the github ref checks into the build configuration to build only `dev`, `stable`, `dist`, and dedicated `bsd` branch later today.

**Comment by ddevault** [comment]
Thanks!

**Comment by ddevault** [comment]
Any updates? In the last month you have used over 1500 build hours, which is about a quarter of all builds.sr.ht usage.

**Comment by XVilka** [comment]
@ddevault I checked the documentation and found nothing about how to limit the trigger only to the particular branch. Is there anything something like GitHub's CI:
```
on:
  push:
    branches:
    - 'dev'
    - 'stable'
    - 'bsd-*'
```
Sorry for the trouble. I grepped also SourceHut sources but found nothing useful either. Thank you!

**Comment by ddevault** [comment]
No - but you can terminate the build early (via the "complete-build" command) if you're not on the right branch.

https://man.sr.ht/dispatch.sr.ht/github.md#environment-variables

GITHUB_REF will be set to e.g. refs/heads/dev.

**Comment by thestr4ng3r** [comment]
Thanks, that seems even better than built into the yml.

**Comment by thestr4ng3r** [comment]
Looks like that pr has the wrong builds associated with it (commit id matches, but branch does not).
Still it seems to work: https://builds.sr.ht/~xvilka/job/587135 vs https://builds.sr.ht/~xvilka/job/587138
It is still installing packages always though. Do you think this is ok @ddevault or should we move the installing to a shell script after the skipping?

**Comment by ddevault** [comment]
This is an improvement, if nothing else - can keep improving if it doesn't sufficiently address the problem. Thanks!

**Comment by thestr4ng3r** [comment]
Ok, let's see how it goes with this. Sorry for the long delay and thank you!
