### ISSUE TITLE
Move all printing functions from `librz/core/*.c` into one file `librz/core/print.c`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1458]
Currently, there are functions that print something all over the place of `librz/core/*.c`, e.g. `rz_core_analysis_bbs_info_print()` or `rz_core_analysis_bb_info_print()`  from `librz/core/canalysis.c` or `rz_core_asm_plugin_print()` from `librz/core/casm.c`.

I suggest to separate "logic" and non-printing API from the printing one, they all should have a `_print()` suffix and located in the same file. Conversely, some of these functions called `rz_something_list()` while they don't return `RzList` or anything similar, they just print the list of some things. These functions should be renamed from `rz_something_list()` to `rz_something_print()` instead.

Also related: https://github.com/rizinorg/rizin/issues/1392

**Comment by ret2libc** [comment]
I do agree with the `_list` and `_print` suffixes, however I don't like having all _print functions in one place. I think the _print should be close to the related file. So having fcn_var_print in canalysis.c is ok for me.

**Comment by XVilka** [comment]
@wargio @thestr4ng3r @kazarmy any opinion on this?

**Comment by kazarmy** [comment]
> I do agree with the `_list` and `_print` suffixes, however I don't like having all _print functions in one place. I think the _print should be close to the related file.

I agree with @ret2libc. This is the OOP philosophy of organizing methods based on state, which seems to work well imo.
