### ISSUE TITLE
Document how to update or remove the installation of Rizin

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#146]
**Is your feature request related to a problem? Please describe.**
Updating Rizin, and removing the installation, are two processes that are missing from README, BUILDING.md and rizin book.

**Describe the solution you'd like**
- Document how to update Rizin 
- Document how to uninstall Rizin

It will be good to have in README.md, BUILDING.md and rizin book.

For example, to update radare2 one had to use `./sys/install.sh`.

**Comment by officialcjunior** [comment]
What's the recommended way to do both?
I saw that `ninja uninstall` was one way to uninstall it.

**Comment by XVilka** [comment]
I think we should mention `ninja uninstall` as the preferred removal method, but also maybe to explain how to troubleshoot if the rizin was installed differently - e.g. with `make` or from the distribution package.

**Comment by officialcjunior** [comment]
And for updating?

**Comment by ITAYC0HEN** [comment]
For updating one need to return on the two last commands

```
$ ninja -C build # or `meson compile -C build`
$ ninja -C build install # or `meson install -C build` 
```

Calling @ret2libc for verifying

**Comment by ret2libc** [comment]
To re-build after you have updated your source code (e.g. by doing `git pull` or by doing manual changes to the rizin code base) just do what @ITAYC0HEN suggested (`ninja -C build` + `ninja -C build install`). Maybe it's also worth mentioning that to while developing, it is not strictly necessary to run the `install` step, but one could instead use `rizin` directly from `./build/binrz/rizin/rizin`.

To uninstall, you have to run `ninja -C uninstall` from the same build dir you used to run the `install` step.

Please let me know if something is not clear.

**Comment by officialcjunior** [comment]
So far so good, I hope.
Where are we going add this? BUILDING.md or README.md?

**Comment by Maijin** [comment]
@officialcjunior - I would add it in README.md, BUIDLING.md and the rizin book.

**Comment by ret2libc** [comment]
Yeah. Maybe just a small mention of it in the README.md
```
$ meson build
$ ninja -C build # or `meson compile -C build`
$ ninja -C build install # or `meson install -C build`
$ rizin
Usage: rizin [-ACdfLMnNqStuvwzX] [-P patch] [-p prj] [-a arch] [-b bits] [-i file]
             [-s addr] [-B baddr] [-m maddr] [-c cmd] [-e k=v] file|pid|-|--|=
# Run "ninja -C build uninstall" without quotes to uninstall it
```
And then a more detailed explanation in BUILDING.md
