### ISSUE TITLE
avg <non-existing-var> does not return an error

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1493]
Filing so i remember:

`avg asdsadsadas` where `asdadsadsa` does not exist just returns nothing. It should give a user-visible error so I know something is wrong.

Reference: https://github.com/rizinorg/rizin/issues/333

**Comment by XVilka** [comment]
@Basstorm could you please take a look at this after PDB? Should be quick to do and is important.

**Comment by Basstorm** [comment]
> @Basstorm could you please take a look at this after PDB? Should be quick to do and is important.

Sure

**Comment by XVilka** [comment]
Please also add a small test
