### ISSUE TITLE
Global variables should be valid addresses 

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1494]
**Is your feature request related to a problem? Please describe.**
If I define a global variable then I can't use it to seek somewhere else.

**Describe the solution you'd like**
When I define a global variable with `avga` at a particular address, then I want to be able to use that same global variable name to e.g. seek to that address.

**Describe alternatives you've considered**
.

**Additional context**
Maybe we can just create a flag when we create a global variable.

Reference: https://github.com/rizinorg/rizin/issues/333

**Comment by DMaroo** [comment]
I would like to work on this. Shall I go ahead?

**Comment by ret2libc** [comment]
> I would like to work on this. Shall I go ahead?

Cool! Thanks!

@XVilka @wargio @kazarmy do you think adding a flag at the variable address is an ok solution? Do you have alternative ideas? Better to think about them now so @DMaroo can start working on this with a clear goal and path.

**Comment by XVilka** [comment]
Yes, lets just add a flag.

**Comment by wargio** [comment]
agree. just add the flag

**Comment by kazarmy** [comment]
Since the flag is expected just like function flags are expected, I agree to add a flag. Just don't forget to delete/change the flag when the global variable is deleted/changed.
