### ISSUE TITLE
Global variables should be replaced in disassembly

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1495]
**Is your feature request related to a problem? Please describe.**
Even if I have defined a global variable with `avg`, this does not improve the readability of the disassembly.

**Describe the solution you'd like**
- [ ] global variable name used when the address is used in the disassembly
- [ ] if the variable is a struct or a complex type, show also accesses to inner fields

**Describe alternatives you've considered**
.

**Additional context**
.

Reference: https://github.com/rizinorg/rizin/issues/333

Depends on https://github.com/rizinorg/rizin/issues/1437

**Comment by DMaroo** [comment]
The first point will be taken care of by #1536. Addresses in disassembly will now have a comment next to them (containing the global variable name) in case they refer to a global variable (this is because of the flag corresponding to the global variable being recognized by rizin while showing disassembly).

**Comment by ret2libc** [comment]
I didn't see any work on this during this time, so I doubt it will be done for 0.4.0.
I'm removing the 0.4.0 milestone for now until someone starts to actively looking at this.

cc @XVilka

**Comment by ret2libc** [comment]
Does the PR also show this `if the variable is a struct or a complex type, show also accesses to inner fields`? @XVilka

**Comment by XVilka** [comment]
Yes. Before typelinks did that, but now it's from globals. It's not perfect and requires running `aat` beforehand but missing cases should be handled separately, open an issue with concrete test if you think it doesn't work in particular case.
