### ISSUE TITLE
avgt should specify var_name as VAR_TYPE, not STRING

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1496]
https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/cmd_analysis.yaml#L444

Just so i don't forget.

**Comment by DMaroo** [comment]
This will be fixed in #1577. It uses `RZ_CMD_ARG_TYPE_GLOBAL_VAR` for specifying the name of the global. This takes care of the associated auto-completion as well.
