### ISSUE TITLE
def-use analysis capabilities

### ISSUE THREAD

**Issue by xrkk** [rizinorg/rizin#1511]
I searched doc, but didn't find any information about `def-use` analysis.

**Comment by ret2libc** [comment]
AFAIK there isn't any kind of def-use/use-def analysis, sorry.

You can find variables in a function and where they are read/written (with `afvR`/`afvW`), but likely that isn't exactly what you are looking for.

**Comment by XVilka** [comment]
This kind of analysis is best defined in terms of the new IL, which is not yet finished and major architectures are not ported. Before that point it really doesn't make sense to work on that.

You can keep an eye on https://github.com/rizinorg/rizin/issues/277 and https://github.com/rizinorg/rizin/pull/1451
