### ISSUE TITLE
`izzz` reports wrong addresses

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1514]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33
| File format of the file you reverse (mandatory)      | Macho
| Architecture/bits of the file (mandatory)            | 64
| `rizin -v` full output, **not truncated** (mandatory)  | 3b0d11eebb3af4634741c7a22f70b6c8d4e174f5,

### Expected behavior
```
093 0x00002f3c 0x100002f3c  47  48 () ascii ,http://www.apple.com/appleca/codesigning.crl0\r
```

### Actual behavior
```
093 0x00002f3c 0x00002f3c  47  48 () ascii ,http://www.apple.com/appleca/codesigning.crl0\r
```

### Steps to reproduce the behavior
```
$ ./build-dev/binrz/rizin/rizin ./test/bins/mach0/fatmach0-3true
> [0x100000ef8]> izzz~http~codesigning
```

### Additional info
The address currently reported is wrong because there's nothing at that address, see:
```
[0x100000ef8]> pd 1 @ 0x2f3c
            0x00002f3c      add   byte [rax], al
[0x100000ef8]> px 30 @ 0x2f3c
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00002f3c  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00002f4c  0000 0000 0000 0000 0000 0000 0000       ..............
[0x100000ef8]> 
```

**Comment by ret2libc** [comment]
After looking at the code that searches for strings... I'm not sure we can fix it in short time. The whole "string search" code is a quite convoluted that would likely require a big refactoring + unit tests to properly fix the problem and be sure things would still work.

**Comment by XVilka** [comment]
Agree. It will also benefit from this work: https://github.com/rizinorg/rizin/pull/1535

**Comment by XVilka** [comment]
I know the reason - it's actually quite trivial. The string search is ran using the physical address of the buf, for example in https://github.com/rizinorg/rizin/pull/1752 I did this code to search in the current address space:
```c
ut64 paddr = rz_io_v2p(core->io, addr);
int count = rz_scan_strings(bf->buf, str_list, &scan_opt, paddr, paddr + limit, encoding);
if (count <= 0) {
	rz_list_free(str_list);
	free(*name);
	return false;
}
```
Thus, to show the right addresses, you have to convert them, probably worth to print both vaddr and paddr in the `iz` output, with `rz_io_p2v()` calls.
