### ISSUE TITLE
Migrate `ae` commands to the rzshell

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1533]
To make ESIL API more consistent and ease the migration from ESIL to RZIL.

See:
- `librz/core/cmd_analysis.c`
- `librz/core/cmd_descs/cmd_analysis.yaml`

### Todo

**Remove**

- [ ] `ae*` - https://github.com/rizinorg/rizin/pull/4730

**To RzShell, but remove with ESIL**
- [ ] `aepc`
- [ ] `ae `
- [ ] `aex`

**To RzShell, but port to RzIL**

- [ ] `aeb`
- [ ] `aef`
- [ ] `aefa`
- [ ] `aeA`
- [ ] `aea`
- [ ] `aeab`
- [ ] `aeafj`
- [ ] `aeafj`
- [ ] `aeab`
- [ ] `aeabj`

**To RzShell, but reimplement**
- [ ] `aek`
- [ ] `aek`
- [ ] `aek `
- [ ] `aek-`
- [ ] `aeli`
- [ ] `aeli`
- [ ] `aelir`

**Comment by ret2libc** [comment]
I didn't see any work on this during this time, so I doubt it will be done for 0.4.0.
I'm removing the 0.4.0 milestone for now until someone starts to actively looking at this.

cc @XVilka

**Comment by XVilka** [comment]
At this point, it probably makes sense to wait until ESIL is completely removed: https://github.com/rizinorg/rizin/issues/2080
