### ISSUE TITLE
Update shellforge (for rz-gg/rzegg)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#154]
See https://github.com/whatsbcn/shellforge4 for more architectures/platforms and various bugfixes

See `librz/include/sflib` and `librz/egg` on where it should be updated/improved.

**Comment by temp1337temp1337** [comment]
Currently working on the issue as part of the GSoC 2021.

Thank you!

**Comment by temp1337temp1337** [comment]
Initial work for this issue has been conducted, for platform `freebsd-i386`. The PR should be ready within the next week. 

Thank you.

**Comment by XVilka** [comment]
Fixed by https://github.com/rizinorg/rizin/commit/782fcd5257f6f16f924162675c2f0f6189f864a4
