### ISSUE TITLE
Script to detect unused RZ_API functions

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1580]
**Is your feature request related to a problem? Please describe.**
Due to RZ_API being exported functions, compiler does not warn you about unused functions. This can be useful to notice old APIs that are not used anymore and can be finally removed after being deprecated.

**Describe the solution you'd like**
A script to print the list of unused functions.

**Describe alternatives you've considered**
Maybe compile in static mode shows the same info? Need to check...

**Comment by XVilka** [comment]
We could make a simple Python script that would detect those functions, also extend it to detect the presence of the Doxygen comments.

**Comment by ret2libc** [comment]
@wingdeans you did something in this regard, didn't you?

**Comment by wingdeans** [comment]
I dumped the binary symbols using readelf and checked that every function in the rizin headers was in the dump using libclang's Python bindings. #2719
We could also try using rizin to get the symbols.

As for doxygen, I remember libclang does have `getBriefComment` to get the doc comment for a declaration, but I'll have to test.
