### ISSUE TITLE
Port `m` to rzshell

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1588]
Rizin's `m` commands are currently implemented in the old-shell way. This issue tracks porting those commands under`m` to rz-shell.

Currently, the `m` commands are at [line 827](https://github.com/rizinorg/rizin/blob/f29272cc0eb81bc0bee8d33c5eb4fe28a4eaf8de/librz/core/cmd.c#L872) at `librz/core/cmd.c`. This method or the code must be moved to their respective rz-shell command handlers. The handlers can be generated by writing down the definitions for `m` in a .yml file inside `librz/core/cmd_descs` and a new file named `cmd_move.yml` can be introduced for the purpose. 

For more information about rz-shell, see [doc/rzshell.md](https://github.com/rizinorg/rizin/blob/dev/doc/rzshell.md).
Previous commits that ports commands to rzshell and can be used as reference: https://github.com/rizinorg/rizin/commit/8a09fdcbd5d075d1fe78a878bc31814f016c8953 , https://github.com/rizinorg/rizin/commit/0abb2c8bfce69260ba11273073605146afcb1d71

**Comment by DMaroo** [comment]
This issue has already been fixed by #1875.
