### ISSUE TITLE
Automatically use RPATH when not installing in /usr prefix

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#162]
**Is your feature request related to a problem? Please describe.**
People seems to have problems with the installation of the tool, because by default /usr/local prefix is used on most systems and that is not always included in the LD_LIBRARY_PATH nor in /etc/ld.so.conf. Moreover, libraries are installed in slightly different path based on the system (e.g. ubuntu uses /usr/local/lib/x86-64-linux-gnu, while fedora and others just use /usr/local/lib).

**Describe the solution you'd like**
Detect when rizin is installed in prefixes that are not in LD_LIBRARY_PATH nor in /etc/ld.so.conf(.d) and automatically enable the `-Dlocal` option, so that RPATHs are used and the binary is linked to the installed libraries.

**Describe alternatives you've considered**
There is already the alternative, which is explaining things in the documentation, but it is probably better to provide a default install that works for people, to make it easier for everyone.

**Additional context**
See https://github.com/libvirt/libvirt/blob/master/meson.build#L148

**Comment by kazarmy** [comment]
Closed by #164.
