### ISSUE TITLE
Provide `rz_type_as_string_pretty` API for Cutter and others to pretty-print a type

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1624]
**Is your feature request related to a problem? Please describe.**
Existing API like `rz_type_db_base_type_as_string` just print the type in one line, even though i'd like a nice representation similar to what's done in `tc <type>`.

**Describe the solution you'd like**
Provide a new API that allows you to specify whether you want multiline and maybe other kind of pretty-printing stuff.

**Describe alternatives you've considered**
Just use `tc <type>`, but that's not great.

**Additional context**
I'm trying to convert the TypesWidget in Cutter to use types API and found this part is missing in terms of API.

**Comment by DMaroo** [comment]
What do you mean by other kind of pretty-printing stuff? What kind of options should the API function provide?

**Comment by XVilka** [comment]
It should allow:
- Have the option to enable/disable multiline output
- Have the option to enable/disable nested types unfolding:
```c
struct bla {
   struct foo {
       int a;
       char *b[5];
   } sf;
}
```
vs 
```c
struct bla {
   struct foo sf;
}
```
Or the anonymous structures:
```c
struct bla {
   struct {
       int a;
       char *b[5];
   } sf;
}
```
vs 
```c
struct bla {
   struct anonymous 1 sf;
}
```
