### ISSUE TITLE
`pf` prints error messages like `Cannot find format "3xi foo bar"`

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1640]
```
[0x00006b60]> pf 3xi foo bar
Cannot find format "3xi foo bar"
Cannot find format "3xi foo bar"
Cannot find format "xi foo bar"
Cannot find format "i foo bar"
Cannot find format "xi foo bar"
Cannot find format "i foo bar"
Cannot find format "xi foo bar"
Cannot find format "i foo bar"
0x00006b60 [0] {
   foo : 0x00006b60 = 0xfa1e0ff3
   bar : 0x00006b64 = -1991643855
}
0x00006b68 [1] {
   foo : 0x00006b68 = 0x89485ed1
   bar : 0x00006b6c = -461158174
}
0x00006b70 [2] {
   foo : 0x00006b70 = 0x4c5450f0
   bar : 0x00006b74 = 65406349
}
```

I do not expect those strange errors when executing `pf`.

**Comment by XVilka** [comment]
It is strange, since I don't see them. This warning is commented out a month ago...

https://github.com/rizinorg/rizin/blob/dev/librz/type/format.c#L1893

**Comment by ret2libc** [comment]
> It is strange, since I don't see them. This warning is commented out a month ago...
> 
> https://github.com/rizinorg/rizin/blob/dev/librz/type/format.c#L1893

Oops, I was probably using the wrong version sorry!
