### ISSUE TITLE
Support types with multiple declarators

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1666]
```c
struct bla {
    int foo, bar;
    void *b;
};
union foo {
    float a, b;
    int c, d;
};
typedef struct {
    char *a;
    void *b;
} ts, *pts;
```

See `librz/type/parser/type_parser.c`

The problem that such AST nodes have multiple nodes with the same identifier "declarator". And there seems no the API to get the next named field.
```
struct bla { int foo, bar; };

translation_unit [0, 0] - [1, 0]
  struct_specifier [0, 0] - [0, 28]
    name: type_identifier [0, 7] - [0, 10]
    body: field_declaration_list [0, 11] - [0, 28]
      field_declaration [0, 13] - [0, 26]
        type: primitive_type [0, 13] - [0, 16]
        declarator: field_identifier [0, 17] - [0, 20]
        declarator: field_identifier [0, 22] - [0, 25]
```

Asked the help of the Tree-Sitter community in https://github.com/tree-sitter/tree-sitter/discussions/1382

**Comment by ret2libc** [comment]
Did you try ts_node_next_sibling / ts_node_next_sibling ?

**Comment by XVilka** [comment]
@ret2libc no, they will not work in general case. The answer to the question was to use `ts_tree_cursor_current_field_name()` function, but this change would be more than a few lines. Will not make it for the 0.3.0, will do after.

**Comment by ret2libc** [comment]
> @ret2libc no, they will not work in general case. The answer to the question was to use `ts_tree_cursor_current_field_name()` function, but this change would be more than a few lines. Will not make it for the 0.3.0, will do after.

That's the cursor API, which is a completely different thing... I'm quite positive you can do that with one of the sibling functions, either ts_node_next_sibling or ts_node_next_named_sibling.
