### ISSUE TITLE
Add -Wimplicit-fallthrough to meson.build

### ISSUE THREAD

**Issue by wargio** [rizinorg/rizin#1674]
There are many `fall-through` in the codebase, which needs to be checked via `-Wimplicit-fallthrough`.

**Comment by ret2libc** [comment]
Is it really better? I think it's quite common to have comments like FALLTHRU or similar. Golang even has a fallthru instruction AFAIK. I think something that would be nice to do is instead to enable the fallthrough warning in gcc, so that we notice where fallthrough happens.

**Comment by wargio** [comment]
fully agree

**Comment by ret2libc** [comment]
So, do we agree on keeping `/* fall-thru */` comments and just add the gcc option to ensure those comments are present? If so, let's update the issue title/description.

**Comment by wargio** [comment]
ok
