### ISSUE TITLE
Convert `ec` commands to the newshell and proper API

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1676]
In `librz/core/cmd_eval.c` there is a function called `rz_eval_color()` that still represents the "oldshell-style parsing". It should be:
- Migrated to the corresponding separate rzshell commands: `ec`, `eco`, `ecr`, etc
- Use `RzOutputMode` enum and output state for JSON
- Refactor the APIs like `rz_cons_pal_list()` to return the `RzList` instead, and introduce a separate function to print this `RzList` depending on the separate modes using `RzOutputMode` enum as well.
- Refactor the `rz_core_theme_nextpal()` to use `rz_core_list_themes()` and proper output modes. Moreover, 'n' and 'p' modes probably should be extracted in separate function[s]. In function `rz_eval_color()` for the JSON mode it's better to use the better name like `rz_core_themes_print()` and use also `rz_core_list_themes()` API and `RzOutputMode` enum

See files:
- `librz/core/cmd_eval.c`
- `librz/core/cmd_descs/cmd_eval.yaml`
- `librz/cons/pal.c`

**Comment by ret2libc** [comment]
This is not perfect, yet, but I think we can close this for now. The API for `ec` could be better though...
