### ISSUE TITLE
Analysis of binary with `aaa` resulting in segfault.

### ISSUE THREAD

**Issue by TristanCrawford** [rizinorg/rizin#1696]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Void Linux x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64 commit: bbcd57d771ba08fecc2b422d8b4216a93f0eaaec, build: 2021-09-14__20:27:55

### Expected behavior

Binary is analyzed successfully so further inspection can be done.

### Actual behavior

Rizin reaches the step `Check for classes` and segfaults.

GDB Output:
```
[0x1047861b]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[ ] Check for classes
Program received signal SIGSEGV, Segmentation fault.
__strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
57      ../sysdeps/x86_64/multiarch/strchr-avx2.S: No such file or directory.
```

### Steps to reproduce the behavior

1. Open the binary ( `rizin client.dll` )
2. Run `aaa`

### Binary
[client.zip](https://github.com/rizinorg/rizin/files/7171879/client.zip)

**Comment by XVilka** [comment]
> Solves this problem by doubling the SDB key length. This is the key string of this query: `attr.CFunctor7_void____cdecl____class_Vector_const____float__int__int__class_Color__class_IMaterial____bool___class_Vector__float__int__int__class_Color__class_IMaterial____bool__class_CRefCounted1_class_CFunctor__class_CRefCountServiceBase_1__class_CRef.`
> The key got cut by the `#define KL 256` as @wargio  said.

by @Basstorm 

See `sdb/fmt.c#24`
