### ISSUE TITLE
 Consistency of coding styles

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#171]
**Is your feature request related to a problem? Please describe.**
Currently, Rizin has a coding style and a clang format file. But the project is not formatted correctly.

```
find -name "*.c" -o -name "*.h" | xargs clang-format -i
git diff
```

And the IC does not check the coding style.

**Describe the solution you'd like**
```
find -name "*.c" -o -name "*.h" | xargs clang-format -i
```
and **add a CI check**

**Describe alternatives you've considered**
Change the clang format file to match the current coding style

We need a consistent style and the only solution is automation, because manual review is unreliable.

**Additional context**
...

**Comment by XVilka** [comment]
See https://github.com/rizinorg/rizin/issues/36 and https://github.com/rizinorg/rizin/pull/159

**Comment by ghost** [comment]
Okay thanks, i didn't check sorry
