### ISSUE TITLE
[question] how to drop `-git` from `rizin_libversion`

### ISSUE THREAD

**Issue by bartoszek** [rizinorg/rizin#174]
Quick question from `meson` newbie: how to remove `-git` suffix form `rizin_libversion` (need for packaging to AUR)
Currently have:
```
...
rizin-git usr/lib/librz_parse.so
rizin-git usr/lib/librz_parse.so.4.6.0-git
rizin-git usr/lib/librz_reg.so
rizin-git usr/lib/librz_reg.so.4.6.0-git
rizin-git usr/lib/librz_search.so
rizin-git usr/lib/librz_search.so.4.6.0-git
rizin-git usr/lib/librz_socket.so
rizin-git usr/lib/librz_socket.so.4.6.0-git
rizin-git usr/lib/librz_syscall.so
rizin-git usr/lib/librz_syscall.so.4.6.0-git
rizin-git usr/lib/librz_util.so
rizin-git usr/lib/librz_util.so.4.6.0-git
```

btw. consider enabling `github/discussions` to handle similar non-issues 🤔

**Comment by bartoszek** [comment]
Ok, I've figured this out https://github.com/bartoszek/rizin/commit/d643b72669f6802b50edee3b7c3769961b86a010
Perhaps we could add `"linux"` aside with `"darwin"` in this exclusion:
https://github.com/rizinorg/rizin/blob/6377a1cfa70bf715bb6961a263482ee05a5fb95c/meson.build#L25-L27
Or format `rizin_verison` from `reizen_version_{major,minor,patch}` ?

**Comment by ret2libc** [comment]
In general, that's because you should wait for an upstream release. So when a release is going to be done, you will automatically see libraries without the `-git` suffix.

In any case, if you want to do it now, you can remove `-git` from `configure.acr`, in the second line there is `VERSION 4.6.0-git`. We still need to finalize the details, but the `dev` branch will likely always have the `-git` suffix at the end of the version.

**Comment by bartoszek** [comment]
Well, seems like I'll just have to live with this ¯\\\_(ツ)\_/¯ thanks for the quick response.

**Comment by p371jah** [comment]
> 
> 
> In general, that's because you should wait for an upstream release. So when a release is going to be done, you will automatically see libraries without the `-git` suffix.
> 
> In any case, if you want to do it now, you can remove `-git` from `configure.acr`, in the second line there is `VERSION 4.6.0-git`. We still need to finalize the details, but the `dev` branch will likely always have the `-git` suffix at the end of the version.

@ret2libc It would be better to replace this version string in `configure.acr` and regenerate `configure` file to avoid unnecessary confusion.

**Comment by ret2libc** [comment]
> > In general, that's because you should wait for an upstream release. So when a release is going to be done, you will automatically see libraries without the `-git` suffix.
> > In any case, if you want to do it now, you can remove `-git` from `configure.acr`, in the second line there is `VERSION 4.6.0-git`. We still need to finalize the details, but the `dev` branch will likely always have the `-git` suffix at the end of the version.
> 
> @ret2libc It would be better to replace this version string in `configure.acr` and regenerate `configure` file to avoid unnecessary confusion.

Yes, sure. I didn't say that, but for info... `configure` is automatically generated from `configure.acr` by `acr` (see radare/acr). So whatever change is done in `configure.acr`, it should be reflected in `configure` through a re-generation. Thanks for pointing it out!
