### ISSUE TITLE
rz-diff -H view is wrong when one file is much shorter than the other

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1770]
Version:
```
$ rz-diff -v
rz-diff 0.3.0 @ linux-x86-64, package: 0.3.0-1.fc33 (Fedora)
```

```
$ python3 -c 'print("A"*0x1000)' > /tmp/a
$ python3 -c 'print("B"*0x100)' > /tmp/b
$ rz-diff -H /tmp/a /tmp/b
```

scroll down until the end of the /tmp/b file. things at some point the /tmp/b file will stop scrolling but the /tmp/a one keeps going. Then if you scroll up the /tmp/b file starts scrolling up immediately.

![image](https://user-images.githubusercontent.com/562321/136755035-217d5d03-9b3e-4b4e-9697-5feda5384825.png)
![image](https://user-images.githubusercontent.com/562321/136755089-567f159c-3a58-4d4f-a526-df31ea89680b.png)

notice the offsets: in the first image, it is 0x3b0 on /tmp/a and still 0x100 on /tmp/b; in the second immage i have scrolled up a bit and now it is 0x0 on /tmp/b, while being just 0x5b0 on /tmp/a.

I would expect the two offsets to always be in sync.

**Comment by XVilka** [comment]
@ret2libc please write how to reproduce.
