### ISSUE TITLE
`Vv` mode left/right arrows should scroll the function name, not switch to the variables

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1779]
```
rizin /bin/ls
[0x0006b10]> aaa
[0x0006b10]> afn
entry0
[0x0006b10]> afn aaaaaaaaaaaabbbbbbbbbbbcccccccccccccdddddddddddddddeeeeeeeeeeeeeeeeeeffffffffffffff
[0x0006b10]> Vv
```
Now, the function name is obviously too long to fit into the right "functions" column. Therefore, I expect left and right arrows to scroll the contents of the left pane to show different parts of the name.
Instead, pressing the right arrow enables "variables" mode, pressing left arrow returns back to the functions mode.

Variables mode already available with `v` hotkey, thus I think arrows here are redundant and should scroll instead.

**Comment by DMaroo** [comment]
Loosely related issue: rizinorg/cutter#2734 (also reproducible in rizin in `vv` mode)

It would be nice to have both of these fixed.
