### ISSUE TITLE
Project loading does not reopen all previously opened files.

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#1782]
Opening a project (`rizin -p <project_file>`) which had several files opened before it was saved (via `o <file> <offset> <permissions>`), will only reopen the most recent one.

**Example:**

```bash
$ > rizin firmware-1.bin

[0x00000000] > o firmware-2.bin 0x5500000 rx
[0x00000000] > Ps firmware.rzdb
[0x00000000] > o
3 - r-x 0x00030000  firmware-1.bin
4 * r-x 0x00020000  firmware-2.bin
[0x00000000] > q

$ > rizin -p firmware.rzdb

[0x00000000] > o

3 * r-x 0x000020000 firmware-2.bin

# firmware-1.bin is missing.
``` 

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 x86 64
| File format of the file you reverse (mandatory)      | None
| Architecture/bits of the file (mandatory)            | raw binary file for Hexagon architecture
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64 commit: a1eb41af2a99ebcbd7c019c6c25185d1d6cd4e86, build: 2021-10-01

### Expected behavior

It should load all files just as they were loaded when the project was saved.

### Actual behavior

It loads only the most recently opened one.

### Steps to reproduce the behavior

As in the example.

### Additional Logs, screenshots, source code,  configuration dump, ...

It does not matter what kind of files it were. I created some with `cat /dev/urandom > firmware-1.bin`

**Comment by thestr4ng3r** [comment]
At the moment, this is the expected behavior. See https://rizin.re/posts/introducing-projects/#re-loading-of-underlying-binaries

**Comment by Rot127** [comment]
Just in case someone stumbles over this.
The current way to load a project with multiple files is to open all files in rizin separately and load the project on top of them with
```
Poo <file.rzdb>
```
