### ISSUE TITLE
Allow loading DWARF information from the separate files

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1805]
Many Linux distributions now ship the DWARF debugging information separately from the binaries itself in a packages with `-debuginfo` or similar prefixes.

See:
- https://wiki.gentoo.org/wiki/Debugging
- https://wiki.debian.org/DebugPackage
- https://docs.fedoraproject.org/en-US/packaging-guidelines/Debuginfo/
- https://fedoraproject.org/wiki/Releases/36/ChangeSet#MinGW_debug_symbols_location_change
- https://fedoraproject.org/wiki/Changes/F36MingwDebugLocation

Curiously, the heap parsing code in `librz/core/linux_heap.c` already supports those splitdebug symbols for GLIBC symbols parsing.

**Comment by XVilka** [comment]
See also https://discourse.llvm.org/t/rfc-support-split-dwarf-for-windows-coff/71276

**Comment by ret2libc** [comment]
@XVilka Same thing, postponing to 0.7.0
