### ISSUE TITLE
`i` commands return strings with a lot of trailing space

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1831]
See, for example `test/db/cmd/cmd_i`. It might be related to the RzTable API. It's better to avoid printing unnecessary whitespace if possible.

**Comment by ret2libc** [comment]
is it really a problem? I can see some complications in the rztable api just to do this, because when printing a column you'd have to look at the next one and if it's empty or not... (maybe even based on the type of columns, because for example X should handle -1 in different ways).

**Comment by ret2libc** [comment]
I'm closing this. Table is a specific output format, if we want no spaces we can use json format or others.
