### ISSUE TITLE
`vw?` results in a black screen

### ISSUE THREAD

**Issue by DMaroo** [rizinorg/rizin#1845]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Garuda Linux (Arch-based), x86_64
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0 @ linux-x86-64 (official release, but bug also reprodcible on current [`dev`](https://github.com/rizinorg/rizin/tree/cb46249098f0f238a840f49d1f2a479601f4b03d))

### Expected behavior

It should do nothing, or show the help for the closest parent command.

### Actual behavior

Rizin shows a black screen and sending `SIGINT` won't close Rizin (neither <kbd>Ctrl</kbd>+<kbd>C</kbd>, nor <kbd>Ctrl</kbd>+<kbd>D</kbd> works). The process has to be killed externally by sending a `SIGKILL`. Even after the kill, the shell TTY is left in a dirty state, and the block cursor is no longer visible.

Upon further checking, it seems that one can exit using `q` (as it is used to exit the visual mode), which leads to the visual mode, and then everything seems to work fine (no block cursor problem, no forceful killing).

### Steps to reproduce the behavior

Open any binary (or just run Rizin without any binary). Type `vw?` and press <kbd>Enter</kbd>.

Asciinema video: https://asciinema.org/a/tNChldGZYwiFcOMAfiFreC2bh

### Additional Logs, screenshots, source code,  configuration dump, ...

None.

**Comment by DMaroo** [comment]
`cmd.c` is missing an else statement while processing the `v` sub-commands. Relevant lines: https://github.com/rizinorg/rizin/blob/cb46249098f0f238a840f49d1f2a479601f4b03d/librz/core/cmd.c#L1179-L1181

I would invite any new contributors to try this issue. This is an easy issue and will help you start your contributions to Rizin :)

**Comment by chinggg** [comment]
It is a weird behavior because I think `v` and `Regex(v[^=i? ].*)` should have the same output as they all call `rz_core_visual_panels_root(core, core->panels_root);` at the end.
`cmd_panels` has not been ported to newshell yet, but it can be modified now. Maybe using `switch...case` is better.
