### ISSUE TITLE
Static analysis or linting tools for the project (and CI)

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#187]
**Is your feature request related to a problem? Please describe.**
For now, the only code analysis tool that analyzes this repository is codeQL (Where can I see the report?). But there are many alternatives such as the clang static analyzer, clang-tidy(it's a linter but it could be interesting).

**Describe the solution you'd like**
Add the clang static analyzer in the CI

```
meson build
scan-build meson compile -C build
scan-now <report>
```

**Describe alternatives you've considered**
Use other alternatives such as clang-tidy (there is a way to only lint changed file)

https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py

```
meson build
meson compile -C build
cd build && run-clang-tidy.py -header-filter ".*"
```
[log.zip](https://github.com/rizinorg/rizin/files/5691755/log.zip)
(if std=c11)

**Additional context**
I think that the more measures there are, the better we can assess the state of the project.

We need more than one tool.

**Comment by XVilka** [comment]
I wonder if it's possible to upload the Clan scan-build as SARIF results for the GitHub Web interface:
- https://blogs.grammatech.com/integrating-clang-static-analyzer-with-codesonar-using-sarif
- https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning
- https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github

For the `clang-tidy` there is a couple of ready GitHub Actions:
- https://github.com/marketplace/actions/clang-tidy-check
- https://github.com/marketplace/actions/c-code-linter-clang-tidy-and-cppcheck

**Comment by ghost** [comment]
Clang sanitizer can produce sarif output

I will try on a personnal repo (tonight) and if it work i will open a PR to test.

**Comment by ghost** [comment]
Example project: https://github.com/08A/RizinCiTest

I use Archlinux because Ubuntu has a lot of out dated packages.

I prefer Alpine Os but i have a bug with "ccc-analyzer" path.

If you agree with the github config, i can create a PR

**Comment by ret2libc** [comment]
> Example project: https://github.com/08A/RizinCiTest
> 
> I use Archlinux because Ubuntu has a lot of out dated packages.

Use `ubuntu-20.04` instead of `ubuntu-latest`. In github CI `ubuntu-latest` still points to `ubuntu-18.04`, but they are going to switch to 20.04 soon anyway.

**Comment by ret2libc** [comment]
With regards to `meson` and `ninja` you can install them through `pip` as we do in our own CI.yml. If possible, I'd prefer to stick with an ubuntu LTS version, so we are quite sure it won't change too much over time.

**Comment by XVilka** [comment]
Ubuntu always has very old Clang, which is more of a problem for using static analysis tools. But for Ubuntu it's possible to use official packages from the LLVM project instead: https://apt.llvm.org/

**Comment by ghost** [comment]
Okay i updated the test ci with ubuntu-20.04, and  it work, i will open a PR

**Comment by ghost** [comment]
I just check the security tab and we have a problem. I don't know why there is 0 issue detected by the new CI (clang).

![2021-01-04-200506_213x43_scrot](https://user-images.githubusercontent.com/32521367/103569681-06d54d00-4ec8-11eb-8ab9-fc44f52c2287.png)

local machine:
![2021-01-04-200525_405x27_scrot](https://user-images.githubusercontent.com/32521367/103569724-18b6f000-4ec8-11eb-972e-1190af30f355.png)

Example (Dead initialization):
```
Dead store | Dead initialization | binrz/rizin/rizin.c  | rz_cmd | 15
```
![2021-01-04-200740_521x479_scrot](https://user-images.githubusercontent.com/32521367/103569904-6d5a6b00-4ec8-11eb-8819-7397df53d3b7.png)
![2021-01-04-200753_481x501_scrot](https://user-images.githubusercontent.com/32521367/103569909-6fbcc500-4ec8-11eb-9387-fa8cd9286e83.png)

Are we reopening this issue or creating a new one?

**Comment by ghost** [comment]
And on lgtm:
![2021-01-04-201835_914x136_scrot](https://user-images.githubusercontent.com/32521367/103570777-fe7e1180-4ec9-11eb-9ba2-9b154f5840a9.png)

**Comment by ret2libc** [comment]
@08A I have re-opened this bug. Are you going to work on this?

**Comment by ghost** [comment]
> @08A I have re-opened this bug. Are you going to work on this?

yes

**Comment by ghost** [comment]
I tested on another repository and got the same result (5 problems detected).

there are three possibilities:
- Github doesn't like SARIF file related to external code (sdb, capstone, ...) 
- Invalid relative path (move steps) (wait new release https://github.com/github/codeql-action/pull/352) unlikely
- the exported file is broken (invalid sarif format) unlikely

**Comment by karliss** [comment]
From what I saw it only showed results from single file. And since the sarif file names are generated randomly file from which the errors are shown also changed. Maybe Github doesn't properly handle multiple uploaded sarif files and either takes first one or they overwrite each other.  This theory could be tested by merging them into single sarif file before upload using something like https://github.com/microsoft/sarif-sdk/blob/main/docs/multitool-usage.md

**Comment by 08A** [comment]
![Uploading IMG_20210107_130123.jpg…]()

**Comment by ghost** [comment]
![IMG_20210107_130123](https://user-images.githubusercontent.com/32521367/103890612-a709bc80-50e8-11eb-9322-fdacba061624.jpg)
