### ISSUE TITLE
Allow to specify the option for Meson/Ninja build to use wget/curl instead of git

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#188]
On some weak and unstable connections `git clone` is too brittle and often finishes with an error even due to the slightest network interruption. Both `wget` and `curl` are more resilient to this from my experience with `CS_COMMIT_ARCHIVE=1` option in the configure/make build.

It would be awesome to be able to do the same in meson.build as well.
See [`shlr/Makefile`](https://github.com/rizinorg/rizin/blob/dev/shlr/Makefile) for more details:
```make
ifeq ($(CS_COMMIT_ARCHIVE),1)
CS_ARCHIVE_URL=$(CS_ARCHIVE)/$(CS_TIP).zip
else
CS_ARCHIVE_URL=
endif

capstone-sync:
ifeq ($(WITHOUT_PULL),1)
	@echo "Nothing to sync because of --without-pull"
else
	"$(SHELL)" capstone.sh "${CS_URL}" "${CS_BRA}" "${CS_TIP}" "${CS_REV}" "${CS_ARCHIVE_URL}"
endif
```
See also [`shlr/capstone.sh`](https://github.com/rizinorg/rizin/blob/dev/shlr/capstone.sh):
```bash
download_archive() {
	echo '[capstone] Downloading capstone snapshot...' >&2
	wget --help > /dev/null 2>&1
	if [ $? = 0 ]; then
		DLBIN="wget -O"
	else
		DLBIN="curl -o"
	fi
	${DLBIN} .cs_tmp.zip "$CS_ARCHIVE" || fatal_msg 'Cannot download archived capstone'
	unzip .cs_tmp.zip || exit 1
	mv "capstone-$CS_TIP" capstone
}


if [ -z "${CS_ARCHIVE}" ]; then
	git_assert check
	if [ $? != 0 ]; then
		export CS_ARCHIVE="https://github.com/aquynh/capstone/archive/$3.zip"
	fi
fi

if [ -n "${CS_ARCHIVE}" ]; then
	download_archive
else
	git_assert
	get_capstone
	# if [ ! -d capstone/.git ]; then update_capstone_git fi
fi
```

**Comment by ret2libc** [comment]
In https://github.com/rizinorg/rizin/pull/191 I have proposed a solution that, I think, is better than relying on wget/tar/curl, which may not be available in some platforms. By using meson subprojects/wraps we can just delegate the download+extract to meson, which does so in a portable way (or it should, at least).

**Comment by ret2libc** [comment]
This can be closed as we switched to meson wraps
