### ISSUE TITLE
Make it mandatory to document modified or newly created functions/structs in PRs

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#1919]
### Is your feature request related to a problem? Please describe.

As a newbie with rizin and as not so experienced programmer it was/is relatively hard to understand the code base.

E.g. when I try to fix a bug, quite a lot of time goes into understanding the path of execution in order to pinpoint the function which _could_ be the problem.
 
Mostly because quite a lot of functions have no short description what they are doing.
This is valid even more so for some single letter variables, parameters and struct members.

### Describe the solution you'd like

It is way to much work to document everything at once. Hence:

Add another checkbox in the PR template which asks specifically for function/struct documentation. Something like:
 _"I have documented or updated the documentation of every function and struct this PR changes."_

This request to document also includes existing functions. If they were touched the PR owner has likely understood them and can therefore document them.

### Additional context

I can't assess yet how much of this problem is because of my inexperience reading code and/or laziness to invest time understanding it.
Also I guess there are also disadvantages documenting each and every function/struct? Too much information for too little gain etc.?
What do you think?

**Comment by officialcjunior** [comment]
> Add another checkbox in the PR template which asks specifically for function/struct documentation. Something like:
> "I have documented or updated the documentation of every function and struct this PR changes."

This is a pretty good idea, IMHO. I am positive that this will remind us to add docs if we missed it. I think we can try having this as a checkbox.

I think, most of the APIs that we introduced after the fork has pretty good Doxygen `\brief` docs to it, it's the others that mostly doesn't. So, your idea, which is:

>This request to document also includes existing functions. If they were touched the PR owner has likely understood them and can therefore document them.
>
will probably drive us in the right direction :)

**Comment by ret2libc** [comment]
I'm +1 for the checkbox!! Good idea. We try to have documentation for new APIs and new public structures.

**Comment by ret2libc** [comment]
Can you send a PR to edit  the `PULL_REQUEST_TEMPLATE.md` file?
