### ISSUE TITLE
iR <hashalgo>

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#1952]
**Is your feature request related to a problem? Please describe.**
To be able to hash resource the same way we can hash Section like `iS md5` -> `iR md5`.
Just like for iS it should show the hash for non-virtual

`iRj` algo should also work

**Describe the solution you'd like**
`iR algo`
`iRj algo` should also work

**Comment by ret2libc** [comment]
It should be quite easy to do. If anyone wants to have a look, you can "borrow" some code from `rz_core_bin_sections_print` and add it to `rz_core_bin_resources_print`
