### ISSUE TITLE
Provide rz_msg_digest API to compute digests from RzBuffer

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#1956]
**Is your feature request related to a problem? Please describe.**
Current API always require you to have all the data in memory. Although this is not a problem for small binaries, it is a huge issue for binaries that are hundreds or thousands of MB. Moreover, the binary data is already allocated and requiring users of the rz_msg_digest API to allocate a new buffer and rz_read the data in there is a waste of time and memory.

**Describe the solution you'd like**
Provide API that accepts `RzBuffer` as input. A RzBuffer can come in various forms and it can just be a slice of an already existing RzBuffer. Moreover, most algorithms (all?) can compute the digest piece by piece, without the need to have everything in memory in one shot.

**Describe alternatives you've considered**
None

**Additional context**
See https://github.com/rizinorg/rizin/pull/1955#issuecomment-964923656

**Comment by ret2libc** [comment]
@wargio why do you disagree with providing such an API?

**Comment by wargio** [comment]
the current C APIs allows to init, update and finalize, maybe i should change them to use directly the RzBuffer

**Comment by ret2libc** [comment]
That would be one way. Otherwise you could also just replace the small_block callback with one that uses RzBuffer. The new API will have anyway to read small chunks of data from the buffer and init/update/update/update/..../fini .

**Comment by wargio** [comment]
the current apis already supports this, just not with RzBuffer. there are 2 apis, small blocks and big blocks (via init/update/fini)

**Comment by ret2libc** [comment]
As said, I'm proposing to replace small_block callback to accept RzBuffer instead.

**Comment by XVilka** [comment]
@ret2libc since you are working on RzHash renaming in https://github.com/rizinorg/rizin/pull/2745, I wonder if it makes sense to make in one go.

**Comment by ret2libc** [comment]
After all, for now I agree with @wargio this might not be needed.
