### ISSUE TITLE
`Failed to load project: invalid content encountered` when file is moved

### ISSUE THREAD

**Issue by xrkk** [rizinorg/rizin#1957]
When open previous saved .rzdb file:
```
$rizin -p 0f673.rzdb
Failed to load project: invalid content encountered
  project migrated from version 5 to 6.
  failed to re-locate file referenced by project
 -- Analyze socket connections with the socket plugin: 'rizin socket://www.foo.com:80'. Use 'w' to send data
```
May I know what features are affected?

**Comment by ret2libc** [comment]
can you share the .rzdb file? How did you create it?

**Comment by wargio** [comment]
have you moved the binary file which you have used for the project ?

this is what is throwing the error.
```c
	file = sdb_const_get(db, "raw", 0);
	if (file) {
		r = try_load_file(core, file, res);
	}
	if (r != FILE_DOES_NOT_EXIST) {
		return r == FILE_SUCCESS;
	}

	RZ_SERIALIZE_ERR(res, "failed to re-locate file referenced by project");
	return false;
```

**Comment by xrkk** [comment]
> have you moved the binary file which you have used for the project ?
> 
> this is what is throwing the error.
> 
> ```c
> 	file = sdb_const_get(db, "raw", 0);
> 	if (file) {
> 		r = try_load_file(core, file, res);
> 	}
> 	if (r != FILE_DOES_NOT_EXIST) {
> 		return r == FILE_SUCCESS;
> 	}
> 
> 	RZ_SERIALIZE_ERR(res, "failed to re-locate file referenced by project");
> 	return false;
> ```

Yes, the binary file is moved.
Does it matter to do futher analysis with this rzdb?

**Comment by wargio** [comment]
yes, the issue is because that file has been moved. @thestr4ng3r is there a way to override this?

**Comment by thestr4ng3r** [comment]
Two ways to override this:
* Change either the absolute or relative (to the rzdb file) path in the rzdb file with a text editor:
    ```
    florian-macbook:megabeets florian$ grep -A 3 '/core/file' megabeets.rzdb
    /core/file
    absolute=/Users/florian/re/megabeets/megabeets_0x1
    raw=megabeets_0x1
    relative=megabeets_0x1
    ```
* Open the binary manually with `rz <binary>`, then load the project on top with `Poo 0f673.rzdb`

**Comment by xrkk** [comment]
> Two ways to override this:
> 
> * Change either the absolute or relative (to the rzdb file) path in the rzdb file with a text editor:
>   ```
>   florian-macbook:megabeets florian$ grep -A 3 '/core/file' megabeets.rzdb
>   /core/file
>   absolute=/Users/florian/re/megabeets/megabeets_0x1
>   raw=megabeets_0x1
>   relative=megabeets_0x1
>   ```
> * Open the binary manually with `rz <binary>`, then load the project on top with `Poo 0f673.rzdb`

OK. I understand. Thank you!

**Comment by ret2libc** [comment]
Can we close this?

**Comment by xrkk** [comment]
> Can we close this?

Yes. Thank you for your time!
