### ISSUE TITLE
Provide an `e` option for the default visual view.

### ISSUE THREAD

**Issue by vext01** [rizinorg/rizin#1963]
**Is your feature request related to a problem? Please describe.**

I mostly use visual disassembly mode. It would be nice if there was the option to select the default visual view to save keystrokes.

**Describe the solution you'd like**

Something that I can put in my config file that could make visual mode start in disassembly mode.

e.g.
```
e scr.default_visual = dis
```

**Describe alternatives you've considered**

Just pressing `p` every time :P

**Comment by thestr4ng3r** [comment]
`echo "e scr.visual.mode=1" >> ~/.rizinrc`
