### ISSUE TITLE
Build Improvements for Packaging

### ISSUE THREAD

**Issue by carlocab** [rizinorg/rizin#2013]
**Is your feature request related to a problem? Please describe.**
@ebmmy was kind enough to work on packaging Rizin for Homebrew. See Homebrew/homebrew-core#89709.

While trying to get the build to pass in Homebrew CI, we encountered issues in `meson` being able to find Homebrew `xxhash` and `libmagic`.

`libmagic` is found via Meson's `find_library`. Unfortunately, `find_library` doesn't seem to know how to find Homebrew-installed libraries by default, so we worked around this by adding a `dirs` argument to the `find_library` call.

`xxhash` is found using Meson's `dependency`, which uses `pkg-config`. Unfortunately, `pkg-config` looks for an `xxhash.pc`, but a default `xxhash` build installs only `libxxhash.pc`. We worked around this by creating a symlink, but it would be nice if this were not needed.

**Describe the solution you'd like**
For `libmagic`, it might help if there were additional options in `meson_options.txt` that allow passing the path to the directory containing `libmagic`, which is then passed to the `dirs` argument of `find_library`. This would allow us to pass this as a flag to `meson` rather than modifying your build script (which can be a bit fragile).

I'm not sure if a similar fix would work for `xxhash`, but since `meson.build` seems to fall back to `find_library` when `dependency` doesn't work, this might too.

**Describe alternatives you've considered**
We could keep carrying around our workarounds, but it would be nice if we didn't have to. Finding fixes here would also ensure that your users who encounter the same problems we did (outside of Homebrew) wouldn't have to discover our workarounds for themselves.

**Additional context**
As mentioned above, this is related to Homebrew/homebrew-core#89709.

**Comment by ret2libc** [comment]
> @ebmmy was kind enough to work on packaging Rizin for Homebrew. See Homebrew/homebrew-core#89709.

Amazing!! <3 Thanks a lot for this, it's much appreciated.

I will work through the rest of your report to find the best solution.

**Comment by ret2libc** [comment]
> xxhash is found using Meson's dependency, which uses pkg-config. Unfortunately, pkg-config looks for an xxhash.pc, but a default xxhash build installs only libxxhash.pc. We worked around this by creating a symlink, but it would be nice if this were not needed.

Nice catch, I think indeed I should replace `dependency('xxhash'..)` with `dependency('libxxhash')` because also on Ubuntu, Fedora and Arch linux the file is called libxxhash.pc. I guess this was a mistake on my side and with this change the find_library fallback should not be needed.

**Comment by carlocab** [comment]
That makes sense. Maybe a `dependency('libmagic'...)` would work for our `libmagic` issue too? We have a `libmagic.pc`. Is there any reason `libmagic` doesn't use the `dependency`-with-fallback-to-`find_library` pattern for the other dependencies?

**Comment by ret2libc** [comment]
> libmagic is found via Meson's find_library. Unfortunately, find_library doesn't seem to know how to find Homebrew-installed libraries by default, so we worked around this by adding a dirs argument to the find_library call.

Same for this. We should probably just use `dependency('libmagic'...`).

**Comment by ret2libc** [comment]
>  Is there any reason libmagic doesn't use the dependency-with-fallback-to-find_library pattern for the other dependencies?

From the top of my head I *think* I did it that way because I couldn't find the .pc files, but I could be wrong as well and I could have just missed those files. The safest approach is probably to use the dependency + find_library fallback approach for both libs.

**Comment by carlocab** [comment]
> I couldn't find the .pc files

`libmagic`'s `.pc` file is also called `libmagic.pc`, so that might also be why `dependency('magic'...)` doesn't work.

**Comment by ret2libc** [comment]
@carlocab is it ok if we reference homebrew in our INSTALL section as a way to install Rizin on Mac after the formula will be mergd?

**Comment by carlocab** [comment]
Of course; that's more than okay. :)

**Comment by ret2libc** [comment]
@carlocab https://github.com/rizinorg/rizin/pull/2023

**Comment by carlocab** [comment]
Thanks!

**Comment by XVilka** [comment]
@carlocab the fix is now included in the 0.3.3 release: https://github.com/rizinorg/rizin/releases/tag/v0.3.3

**Comment by carlocab** [comment]
Yep, I noticed. Thanks for the update!
