### ISSUE TITLE
Trailing nibble causes any disasm to fail

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/rizin#2014]
*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| Architecture/bits of the file (mandatory)            | x86_64
| `rizin -v`  | rizin 0.1.0-git 25359 @ linux-x86-64 git.0.1.0-git commit: 8d81d392c76aea394019fd2993f5d32f3c1f94a2 build: 2021-01-03__19:10:40

### Expected behavior
`rz-asm -a x86 -b64 -d 0x55f`
```
push rbp
invalid
```

### Actual behavior
`rz-asm -a x86 -b64 -d 0x55f`
```
invalid
```
### Note
This is only the shortest failing demo. The same bug applies to any valid assembly byte sequence that has an additional trailing nibble.

**Comment by Semnodime** [comment]
In case this currently is expected behavior, I propose to allow for trailing nibbles to simply be parsed as invalid instructions.

**Comment by ret2libc** [comment]
Please update your rizin. I see it is still 0.1.0-git, we are at version 0.3.1 now (though as you can see below this was fixed already at least in 0.3.0).

```
$ rz-asm -v
rz-asm 0.3.0 @ linux-x86-64, package: 0.3.0-1.fc34 (Fedora)
$ rz-asm -a x86 -b64 -d 0x55ff
push rbp
invalid
```

**Comment by Semnodime** [comment]
@ret2libc Your demo is invalid (I accidentally posted the working code that I used to print the expected behavior in the 'expected behavior' section.) Please use the code from the 'actual behavior' section.

I will update my version though to verify my assumption that behavior didn't change since my version of rizin.

**Comment by ret2libc** [comment]
Ah ok no problem then! I reopened the issue. Could you edit the description to correctly provide the expected behavior please?

**Comment by ret2libc** [comment]
Also, what does `55f` mean? `55f0`? Or `055f`? `55` in x86-64 is `push rbp`, and `f0` is likely an invalid byte sequence alone, so that's why you get `push rbp; invalid`.

**Comment by Semnodime** [comment]
> Ah ok no problem then! I reopened the issue. Could you edit the description to correctly provide the expected behavior please?

already done



> Also, what does `55f` mean? `55f0`? Or `055f`? `55` in x86-64 is `push rbp`, and `f0` is likely an invalid byte sequence alone, so that's why you get `push rbp; invalid`.

`55f` should be interpreted as `55f0` and result in 
```
push rbp
invalid
```
It just returns `invalid` and it does so on `stderr`, as I figured out now.

------------

`555555555555555555555555555555555555555555555555555555555555555555ff` will be disassebled into
```
push rbz
push rbz
push rbz
push rbz
push rbz
push rbz
....
push rbz
invalid
```
on stdout.

whereas `555555555555555555555555555555555555555555555555555555555555555555f` will be disassembled into just `invalid` on stderr.

**Comment by ret2libc** [comment]
I'm closing this as I don't think there's any point in having half-bytes handling. We can definitely improve on the error-message side, but as things are anyway read byte by byte a user should provide the full byte.
