### ISSUE TITLE
Wrong resolution of R_ARM_RELATIVE relocations

### ISSUE THREAD

**Issue by borzacchiello** [rizinorg/rizin#2052]
It seems that the `R_ARM_RELATIVE` relocation is not resolved correctly by rizin (the issue seems to affect also the latest version of rizin, and radare2).

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARMv7
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0 @ linux-x86-64

### Expected behavior

All the `R_ARM_RELATIVE` relocations should be resolved to the right addresses. For example, the relocation at offset `0x3004` should be resolved to the address `0x196b`.

### Actual behavior

rizin seems to resolve all the `R_ARM_RELATIVE` relocations to the wrong addresses. For example, it resolves the relocation at address `0x3004` to the address `0x304e`

### Steps to reproduce the behavior

Tested binary (zipped) [lib.zip](https://github.com/rizinorg/rizin/files/7627484/lib.zip)

Relocation type:
```
$ readelf -r ./lib.so| grep 3004
00003004  00000017 R_ARM_RELATIVE
```

In rizin:
```
[0x00000754]> pd 1 @ 0x3004
            0x00003004      .dword 0x0000304e                          ; RELOC 32 
```

The same address in BinaryNinja:
![image](https://user-images.githubusercontent.com/22977771/144096204-2262e82f-1012-41ea-8db7-955535789fc2.png)

### Other Info

I hope that I'm not messing something up.
Oc I can help in solving the issue! If you give me some pointers in rizin's code, I can debug it a little deeper.

**Comment by XVilka** [comment]
@borzacchiello see https://github.com/rizinorg/rizin/pull/1699 as an example. Since it's work-in-progress, you could extract ARMv7-relevant parts, improve them and send a new PR.
