### ISSUE TITLE
Wrong message / Command 'P' does not exist.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/rizin#2059]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint x86_64
| rizin 0.4.0-git @ linux-x86-64 commit: 98e4816b036214e1c3514aaa2e0e38c85f329e1d

### Expected behavior
prints `Usage: P<so?>   # Project management...`

### Actual behavior
prints `Command 'P' does not exist.`

### Steps to reproduce the behavior
- run rizin 
- run `P`

**Comment by ret2libc** [comment]
```
[0x00000000]> P?
Usage: P<so?>   # Project management
| Ps [<project.rzdb>] # Save a project
| Po <project.rzdb>   # Open a project
| Poo <project.rzdb>  # Open a project on top of currently loaded binaries
```

As you can see, `P` command does not exist.

This is expressed with the `<...>` that mean a letter is required after `P`. If `P` was a command, you would have seen `P[so?]` instead of `P<so?>`.

**Comment by ret2libc** [comment]
Let me reopen to ask: was this specifically created because you don't like the message when the command does not exist?

What if I execute `Po11111`? Would you print `Usage: Poo <project.rzdb>   # Open a project on top of currently loaded binaries`? I'm not sure about this, I think it's better to just say "Command does not exist".

**Comment by DMaroo** [comment]
I personally think that it would be consistent to print the help for `P` commands when `P` is entered. In general, for groups of commands which are longer than one letter (in this case `P` commands, `Ps`, `Po[o]`), entering any prefix string should print the help, i.e. `P` should print the help. Just to make it clear, if there is a group of commands like `nice`, `nile` and `night`, then entering both `n` and `ni` should print the help for these group of commands. Does this sound good? @ret2libc @XVilka thoughts?

**Comment by thestr4ng3r** [comment]
Sounds like a reasonable behavior to me, if it can be implemented without jumping through too many hoops regarding the newshell structure.
I think what should be printed is both "Command does not exist" and the help after it, so it's not an explicit feature to show the help, but just adding the help as an additional hint to the error.

**Comment by Semnodime** [comment]
As @DMaroo mentioned, 
I considered `P` to be a command by itself.
Sure, you could say, I should have paid attention to `P<so>` over `P[so]`.
But that'd be slightly missing the point:

----

Speaking of my intuition as a user, rizin has single-lettered commands that build on top of each other.
Specifying a wrong or incomplete command defaults to the usage guide helping me out (while matching the longest valid prefix of my command).

----

I further internalized to expect this behavior from the otherwise unrelated command line utility `nmcli`:

`nmcli` also has hierarchically structured commands as can be seen here:
`$ nmcli `<kbd>tab</kbd>
![image](https://user-images.githubusercontent.com/19511852/146635804-794c7b6d-e6dd-4a29-81d8-7f69b017b78f.png)

When an command is not fully "traversed" down to its "leaf command", `nmcli` just behaves as if the best/most used/optimal sub command had been issued. In case some parameters are missing, a usefull help message is shown instead.

![image](https://user-images.githubusercontent.com/19511852/146635880-2db01e69-5a83-408a-a0c4-57c23b897cd5.png)

----

I don't say, `rizin` has to behave exactly the same, I just want to get across the opportunity for intuitive and thus efficient user experience. :)

**Comment by ret2libc** [comment]
Please see if https://github.com/rizinorg/rizin/pull/2365 makes sense when you can :)
