### ISSUE TITLE
Incompatible (L)GPL licenses

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#2084]
As of https://github.com/rizinorg/rizin/commit/1d3f029d0775ab39cfbc14f322a328e820694ea5 , this is the list of licenses we have in our codebase:

Apache-2.0, BSD-2-Clause, BSD-3-Clause, CC-BY-SA-4.0, CC0-1.0, GPL-1.0-or-later, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-or-later, LGPL-2.0-or-later, LGPL-2.1-only, LGPL-2.1-or-later, LGPL-3.0-only, MIT, MS-PL, NCSA, RSA-MD

Apache, BSD, CC, GPL, LGPL, MIT, NCSA should be compatible with GPL AFAIK.

However, MS-PL and RSA-MD seem to not be compatible.
* RSA-MD is used in `librz/hash/algorithms/md5/`
* MS-PL is used in `librz/crypto/p/crypto_aes_algo.c`

**Comment by wargio** [comment]
```
When you distribute software (or its portion) under the Ms-PL, you’re not required to distribute its source code. You may do so if you want to, but you’re not obliged. However, you’re required to:

    Retain all copyright, patent, trademark, and attribution notices that are originally present in the software.

    Additionally, if you distribute any portion of the software in its source code form, you may do so only under the Ms-PL by including a complete copy of this license with your distribution. If you distribute any portion of the software in its compiled or object code form, you may only do so under any other license that complies with the Ms-PL.

It is important to note that the Ms-PL terms and conditions document is very short, concise and written in a very coherent language. Microsoft wanted to be very clear and direct with the open source community, which also helps adoption rate (as we know from the BSD license).
```
