### ISSUE TITLE
Enumerate all third-party code and libraries used in Rizin

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#209]
Currently some of the libraries we use are imported during the fetching process as a submodules (using system-wide version or download as an archive). But a lot of external dependencies are in fact just copied inside the sources. Some are quite diverged from the original, e.g. `shlr/tcc`, while others just outdated. We should enumerate all such occurences and list them in a separate documentation file, with instructions where it came from and how to update. Or additional scripts on automating it. Also we should note what licenses every such piece of code uses.

### Managed as subprojects

- `subprojects/yxml`, **YXML**, version in `subprojects/yxml/meson.build`. Can be updated from https://g.blicky.net/yxml.git/
- `subprojects/xxhash`, xxhash, version in `subprojects/xxhash/meson.build`

###  Copied files

- `shlr/heap/include/rz_jemalloc` - copied files from **jemalloc** library. **NOTE!**: We should not blindly update this jemalloc since we should be able to parse both old (pre-5.x) heap versions and new ones. So it might be needed to reworked completely, see also https://github.com/rizinorg/rizin/issues/157 and https://github.com/rizinorg/rizin/issues/158
- `shlr/mpc` - MPC, **BSD** license, taken from https://github.com/orangeduck/mpc Will be closed by  https://github.com/rizinorg/rizin/issues/631
- `librz/magic` - **BSD**, taken from OpenBSD, somewhat outdated, has custom modifications (**v 1.29 2009/11/11**?) #721

### Managed as subprojects

- `shlr/capstone` - almost clean **capstone** 4.0.2, but there are 4 patches applied. Most of them can either be dropped or upstreamed, only the x86-16 one is a bit tricky

###  Copied files

- pieces from **binutils-gdb** were used in many different places (opcodes library/libopcodes, libiberty, BFD library):
    1. `librz/asm/arch/arc/gnu/`
    2. `librz/asm/arch/arm/aarch64/`
    4. `librz/asm/arch/cris/gnu/`
    5. `librz/asm/arch/hppa/gnu/`
    6. `librz/asm/arch/lanai/gnu/`
    7. `librz/asm/arch/mips/gnu/`
    8. `librz/asm/arch/nios/gnu/`
    9. `librz/asm/arch/xtensa/gnu/`
    10. `librz/asm/arch/tricore/gnu/`
    11. `librz/asm/arch/sparc/gnu/`
    13. `librz/asm/arch/vax/`
    14. `librz/asm/arch/riscv/`
    16. `librz/asm/arch/sh/gnu/` 

- `librz/asm/arch/i8080/` - copied from **[rk86-tools](https://github.com/begoon/rk86-tools)** (permissive license)
- `librz/asm/arch/z80/` - copied from **[z80asm](http://git.savannah.nongnu.org/cgit/z80asm.git)** (**GPL**)

See also https://github.com/rizinorg/rizin/issues/70

**Comment by ret2libc** [comment]
Consider that if we switch to meson subprojects, it is going to be quite clear what are the third-party parts and where they come from.

**Comment by XVilka** [comment]
@ret2libc this issue is more like a prerequisite for that migration - since you need to know first what to migrate.
Also we should enumerate our own modifications that can't and shouldn't be updated.

**Comment by Maijin** [comment]
magic in libr

**Comment by p371jah** [comment]
GNU libopcodes: https://github.com/rizinorg/rizin/search?q=%22This+file+is+part+of+the+GNU+opcodes+library.%22

**Comment by karliss** [comment]
rizin/librz/asm/arch/arm/winedbg/ and possibly other winedbg files

**Comment by wargio** [comment]
maybe we need to find some software like blackduck to understand how big is this number.

**Comment by Maijin** [comment]
Found this free tool that does enumeration: https://github.com/scanoss/scanner.py

![image](https://user-images.githubusercontent.com/1408600/103362138-aefaa880-4ab9-11eb-85c2-620abe21203f.png)

They also have a github app that looks free https://github.com/marketplace/scanoss-app but that github app is limited to 5 files a day for free version so forget it.

**Comment by Maijin** [comment]
They also have a github app that looks free https://github.com/marketplace/scanoss-app

**Comment by p371jah** [comment]
> 
> 
> GNU libopcodes: https://github.com/rizinorg/rizin/search?q=%22This+file+is+part+of+the+GNU+opcodes+library.%22

This query gives more results https://github.com/rizinorg/rizin/search?q=%22This+file+is+part+of%22
Found code in `librz` from these projects:
1. `binutils-gdb` (opcodes library/libopcodes, libiberty, BFD library):
    
    1. `librz/asm/arch/arc/gnu/`
    2. `librz/asm/arch/arm/aarch64/`
    3. `librz/asm/arch/arm/gnu/`
    4. `librz/asm/arch/cris/gnu/`
    5. `librz/asm/arch/hppa/gnu/`
    6. `librz/asm/arch/lanai/gnu/`
    7. `librz/asm/arch/mips/gnu/`
    8. `librz/asm/arch/nios/gnu/`
    9. `librz/asm/arch/xtensa/gnu/`
    10. `librz/asm/arch/tricore/gnu/`
    11. `librz/asm/arch/sparc/gnu/`
    12. `librz/asm/arch/ppc/gnu/`
    10. `librz/asm/arch/vax/`
    11. `librz/asm/arch/riscv/`
    9. `librz/bin/mangling/cxx/`

1. `rk86-tools` (https://github.com/begoon/rk86-tools)
    1. `librz/asm/arch/i8080/`

1. `z80asm` (http://git.savannah.nongnu.org/cgit/z80asm.git)
    1. `librz/asm/arch/z80/`

**Comment by p371jah** [comment]
> 
> 
> Found this free tool that does enumeration: https://github.com/scanoss/scanner.py

Most of 3rd party code was modified in r2 and the tool refers to r2.

**Comment by XVilka** [comment]
Is there any automated tool to scan multiple versions of the file and find the version with the minimal difference? It might be needed for finding the exact version for the file that was copied and exact changes that were done on top of it.

**Comment by p371jah** [comment]
`librz/asm/arch/avr/` - copied from [vAVRdisasm](https://github.com/vsergeev/vAVRdisasm) (**GPL**)
`librz/asm/arch/sh/gnu/` from `binutils-gdb` too

**Comment by XVilka** [comment]
@ret2libc updated the issue, we maybe also want to document these dependencies better in the book/documentation.
Could you please check if `shlr/mpc` could be converted to the subprojects too?

**Comment by ret2libc** [comment]
@XVilka what are the actionable items to be done for this issue? It's in 0.2.0 but I'm not sure what needs to be done, *exactly*.

**Comment by XVilka** [comment]
@ret2libc it's a rolling issue, not a blocking one. Regarding actionable item, see e.g. https://github.com/rizinorg/rizin/issues/721
In general, unless there is a custom modification, everything under `Copied files` headers should be linked as a subproject or a dynamic dependency.

**Comment by XVilka** [comment]
Regarding libopcodes, here is the example on how to use it as a dependency: http://efedel.github.io/tg-community/content/opdis/index.html

**Comment by ret2libc** [comment]
It would be ideal to have this split even more so that we can assign one exact and specific task to the next releases and ensure to move it forward.

**Comment by ret2libc** [comment]
Nothing particular to do with this issue. We have already another issue about updating binutils. Apart from that I think most code has been confined in subprojects, so that's already good enough.

Can we close this @XVilka ?
