### ISSUE TITLE
Fortunes install directory

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#210]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| rizin -v full output, **not truncated** (mandatory)  | rizin 0.1.0-git 26141 @ linux-x86-64 git.4.4.0-1159-g3a94841da commit: 3a94841da363a635a1dd9fefc9409f060baec612 build: 2020-12-16__21:26:45

We provide `rizin_libdir`, `rizin_fortunes`, etc. options in meson, but they are considered only for Windows. Why? They can be useful for linux as well. For example, see https://github.com/rizinorg/rizin/issues/179#issuecomment-745476174 where gentoo requires a different doc path.

However, I question whether `/usr/share/doc/rizin/` is really the right place for fortunes, because they are not documentation files. Maybe they should be `/usr/share/rizin/fortunes/*`?

**Comment by XVilka** [comment]
fortunes.tips are documentation though

**Comment by ret2libc** [comment]
Not really "documentation". I wouldn't go to fortunes to get any real information on how to use the tool.
