### ISSUE TITLE
Windows paths are using unix slash

### ISSUE THREAD

**Issue by wargio** [rizinorg/rizin#2124]
When building on windows, the paths are set to use a mix of `/` and `\` 

This can be easily noticed when calling `rizin.exe -H`
```
C:\Users\giova\github\rizin>build\binrz\rizin\rizin.exe -H
RZ_VERSION=0.4.0-git
RZ_PREFIX=c:/
RZ_MAGICPATH=c:/\share/\magic
RZ_INCDIR=c:/\include/librz
RZ_LIBDIR=c:/\lib
RZ_LIBEXT=dll
RZ_RCONFIGHOME=C:\Users\giova\.config\rizin
RZ_RDATAHOME=C:\Users\giova\.local\share/
RZ_RCACHEHOME=C:\Users\giova\.cache\rizin
RZ_LIBR_PLUGINS=c:/\lib/plugins
RZ_USER_PLUGINS=C:\Users\giova\.local\lib/plugins
RZ_USER_ZIGNS=C:\Users\giova\.local\share/zigns
RZ_IS_PORTABLE=0

C:\Users\giova\github\rizin>
```
![nightmare](https://user-images.githubusercontent.com/561184/146920564-12cea1b7-fbc1-484a-9e77-624d00509d80.png)

**Comment by chinggg** [comment]
So which one should we pick? Windows slash `\` or UNIX slash `/`?

**Comment by ret2libc** [comment]
@wargio : please post the output you get on windows to make the description of the issue clearer. What's the expected output and what's the actual output. IOW follow the template :D

**Comment by wargio** [comment]
@ret2libc updated

**Comment by ret2libc** [comment]
> So which one should we pick? Windows slash `\` or UNIX slash `/`?

I think the expected output should be:
```
C:\Users\giova\github\rizin>build\binrz\rizin\rizin.exe -H
RZ_VERSION=0.4.0-git
RZ_PREFIX=C:\
RZ_MAGICPATH=C:\share\magic
RZ_INCDIR=C:\include\librz
RZ_LIBDIR=C:\lib
RZ_LIBEXT=dll
RZ_RCONFIGHOME=C:\Users\giova\.config\rizin
RZ_RDATAHOME=C:\Users\giova\.local\share\
RZ_RCACHEHOME=C:\Users\giova\.cache\rizin
RZ_LIBR_PLUGINS=c:\lib\plugins
RZ_USER_PLUGINS=C:\Users\giova\.local\lib\plugins
RZ_USER_ZIGNS=C:\Users\giova\.local\share\zigns
RZ_IS_PORTABLE=0

```

**Comment by ret2libc** [comment]
So, I think that this is not actually a functional issue, because everything should work fine even with this mix of slashes, however... It is not cool. I think part of the reason is that meson uses unix-slashes even for windows (because they do work AFAIR), however stuff like `rz_path` creates paths by using the platform-specific directory separator. Thus the mix.

**Comment by wargio** [comment]
yes, that is the correct output

**Comment by wargio** [comment]
> So, I think that this is not actually a functional issue, because everything should work fine even with this mix of slashes, however... It is not cool. I think part of the reason is that meson uses unix-slashes even for windows (because they do work AFAIR), however stuff like `rz_path` creates paths by using the platform-specific directory separator. Thus the mix.

that is not true, many file functions expects the windows trailer and will fail if there is a mix (for example `rz_file_basename`).
