### ISSUE TITLE
Wrong calculation of the string length in Visual Graphs

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2125]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 35 x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64, package: 0.2.0.1 (ret2libc) commit: c875be9afde5a6eed037249854b8a8759517263c, build: 2021-01-26__18:17:13

Instead of the code points we should calculate grapheme clusters of the Unicode characters to understand how many actual characters are printed on the screen.

### Expected behavior

Calculate the length of the string correctly and draw the graph node border line correctly

### Actual behavior

![image](https://user-images.githubusercontent.com/203261/146886019-867ac65f-2501-43ad-b27f-7bc20a0023a7.png)

### Steps to reproduce the behavior
- `rizin /bin/ls`
- `aaa`
- `s main`
- `afn 🔥sfddsf🔥🔥🔥🔥🔥🔥🔥`
- `VV`

### Additional Logs, screenshots, source code,  configuration dump, ...

I also suggest to use the correct name as well, as mentioned in the below comments:
 - `rz_str_unicode_codepoints()`
 - `rz_str_unicode_graphemes()`

- https://github.com/ziglang/zig/issues/234#issuecomment-905129195
- https://unicode.org/reports/tr29/
- https://github.com/jecolon/ziglyph/blob/main/src/segmenter/Grapheme.zig
- https://git.suckless.org/libgrapheme/files.html (maybe we could use it as a subproject, actually)

**Comment by XVilka** [comment]
@imbillow as part of your debuginfo work, and loading Unicode information from binaries, especially https://github.com/rizinorg/rizin/issues/3196, it will be necessary also to make sure the loaded information can be displayed correctly.

**Comment by wargio** [comment]
already fixed.
