### ISSUE TITLE
Version Information for go binary 1.18

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#2128]
**Is your feature request related to a problem? Please describe.**
Go binary version 1.18 now contains full VCS details (like git commit hash etc.)

https://blog.carlmjohnson.net/post/2021/golang-118-minor-features/

![image](https://user-images.githubusercontent.com/1408600/146976746-8b714641-f088-4ceb-ba6f-eeeb6ee14c61.png)

**Describe the solution you'd like**
Append go version information to add Go version information details when go lang is detected

**Additional files**

Test binary stripped and non-stripped courtesy of @stevemk14ebr [GoReSym_118.zip](https://github.com/rizinorg/rizin/files/7757178/GoReSym_118.zip)

**Comment by XVilka** [comment]
Also relevant: https://fedoraproject.org/wiki/Changes/Package_information_on_ELF_objects
