### ISSUE TITLE
Self-referential type crashes Rizin

### ISSUE THREAD

**Issue by VegaDeftwing** [rizinorg/rizin#2133]
**Environment information**
* Operating System: Arch Linux 5.15.10-zen1-1-zen
* Cutter version: 2.0.4
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub **(AppImage)**
  - [ ] Distribution repository
* File format: .so

**Describe the bug**

Upon loading this .so file, Cutter crashes and displays a window "Cutter received a signal it can't handle and will close. Would you like to create a crash dump for a bug report" 

**To Reproduce**

1. Open Cutter
2. Load the provided .so file
3. Click analyze
4. Crash

**Expected behavior**

Not crashing

**Additional context**

Provided .so file is from https://github.com/VegaDeftwing/PinkTromboneVCV 

zip contains the crash dump file as well as the .so: [CutterBug.zip](https://github.com/rizinorg/cutter/files/7750560/CutterBug.zip)

**Comment by ret2libc** [comment]
Steps to reproduce in Rizin:
```
$ ./build-dev/binrz/rizin/rizin /tmp/CutterBug/plugin.so 
 -- give | and > a try piping and redirection
[0x0000b770]> t const_reference
Segmentation fault (core dumped)
$ ./build-dev/binrz/rizin/rizin -v
rizin 0.4.0-git @ linux-x86-64
commit: c4f9df4b02944d3401c1ae11855bdbf66f9b08b1, build: 2021-12-23__09:52:42
```

**Comment by ret2libc** [comment]
BTW @XVilka 
```C
$ cat test.c 
#include <stdio.h>

struct const_reference;
typedef struct const_reference const_reference;

struct const_reference {
        int a;
};

int main(int argc, char **argv) {
        const_reference a = {3};
        printf("ref = %d\n", a.a);
        return 0;
}
```
Compiling this generates the problem as well.
