### ISSUE TITLE
Deleting arch hint does not work

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#2185]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | x86_64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 4487d7e1ac8ec0346f0f0b6f14dfdc7d5e424b34, build: 2022-01-08__15:06:38

### Expected behavior
```
[0x00000000]> wx 31ed4989d1
[0x00000000]> pd 1
            0x00000000      xor   ebp, ebp
[0x00000000]> aha ppc
[0x00000000]> pd 1
            0x00000000      lbz   r10, -0x12cf(r9)
[0x00000000]> aha 0
[0x00000000]> pd 1
            0x00000000      xor   ebp, ebp
[0x00000000]> ah-*
[0x00000000]> pd 1
            0x00000000      xor   ebp, ebp
```

### Actual behavior
```
[0x00000000]> wx 31ed4989d1
[0x00000000]> pd 1
            0x00000000      xor   ebp, ebp
[0x00000000]> aha ppc
[0x00000000]> pd 1
            0x00000000      lbz   r10, -0x12cf(r9)
[0x00000000]> aha 0
[0x00000000]> pd 1
            0x00000000      lbz   r10, -0x12cf(r9)
[0x00000000]> ah-*
[0x00000000]> pd 1
            0x00000000      lbz   r10, -0x12cf(r9)
```

**Comment by p371jah** [comment]
Weird. `aha-` doesn't work too. It deletes hint from the list but output of `pd 1` doesn't change.

**Comment by ret2libc** [comment]
I think it doesn't work in r2 either so it's probably a very old bug

**Comment by p371jah** [comment]
`ahb`/`ahb-`  uses almost the same code as `aha`/`aha-` so `ahb-` doesn't work too. Well it also removes a hint from the list but it doesn't affect disassembly output.
