### ISSUE TITLE
Allow to search for symbols/imports/exports with `rz-find`.

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2195]
Currently we have only magic, string, binary data search.
It would be useful to be able to search for function calls in the set of binaries.

For example, it could look like this:
- `rz-find -I printf /usr/bin/`  would search for `printf()` in executable file imports, and skip every non-executable file
- `rz-find -S blaargh /usr/bin/` would search for the symbol `blaargh()` in the binary (can be import, export or just internal one), we could remove old `-S` option to search for wide strings and substitute it with `-u` (for Unicode).

**Comment by thestr4ng3r** [comment]
I would also add the option to search for files that export a given symbol name

**Comment by DhruvaG2000** [comment]
Seems like this issue is being partially solved in PR https://github.com/rizinorg/rizin/pull/2256 but isn't linked here.

**Comment by PeiweiHu** [comment]
Now https://github.com/rizinorg/rizin/pull/2256 supports both `-I `and `-S`.

**Comment by PeiweiHu** [comment]
I forgot to add `closes ##` in pr. This issue was solved in https://github.com/rizinorg/rizin/pull/2256 and can be closed.
