### ISSUE TITLE
Setting `scr.pager=less` on Windows causes rizin to hang

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/rizin#2217]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10.0.19044.0 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.4 @ windows-x86-64 commit: 2373c53880e017be86afed5454bca5b5017b920e, build: Fri 01/14/2022__18:38:44.79

### Expected behavior
Setting `e scr.pager=less` or `e scr.pager='less -R'` should work.

### Actual behavior
It causes rizin to hang on the next command that tries to use the pager.

### Steps to reproduce the behavior
1. Install `less` on Windows via `scoop` or this binary (Which is what scoop installs): https://github.com/jftuga/less-Windows/releases/download/less-v590/less.exe (Adding it to a folder on the `PATH`)
2. Start rizin on any binary.
3. Set `e scr.pager=less` or `e scr.pager='less -R'`.
4. Run any command that will use the pager, e.g. `pd`.
5. rizin hangs.

### Additional Logs, screenshots, source code,  configuration dump, ...

![rizin-bug](https://user-images.githubusercontent.com/24731903/149745999-f8a99e61-a9a6-43f5-aaaf-69cac6c71e37.gif)

**Comment by ret2libc** [comment]
Could not reproduce on linux. Maybe something windows specific. Will need to check.

**Comment by segevfiner** [comment]
Very likely to be Windows specific. Hence the "Windows" on the title, and why I also listed my terminal setup.

**Comment by segevfiner** [comment]
It hangs here: https://github.com/rizinorg/rizin/blob/66d6bb94388045cc87e6d7e2b5e1ce78e1061c0b/librz/util/w32-sys.c#L77

This is because, just like in Linux (And other Unix-likes), OS pipes have a fixed size buffer and once it is full, writing to them blocks. On Windows it is common to just write to `stdin` after starting the process, as the process reading `stdin` will block waiting for it anyhow.

**Comment by segevfiner** [comment]
I think one correct way to fix this is to move the `WriteFile` to a background thread that will be joined once we finish reading the output from the process and the process ends. Not sure what threading API should be used inside rizin. Although this is Windows specific code anyhow. Otherwise we can try overlapped I/O but that seems a bit like overkill.

**Comment by ret2libc** [comment]
@GustavoLCR input on this?
