### ISSUE TITLE
Support yara in rz-sign

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#2227]
**Is your feature request related to a problem? Please describe.**
Support yara in rz-sign, at this stage it is more a nice to have, I wouldn't prioritize that but in the long run I think it would be very useful to have it in core.

**Describe the solution you'd like**
Ability to dump a signature as yara or import a rule as yara

**Comment by XVilka** [comment]
@wargio wasn't this already done?

**Comment by Maijin** [comment]
Yep it's done
