### ISSUE TITLE
Update Tree-Sitter to 0.20.x series

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2239]
- [ ] In rzshell parser
- [ ] In C types parser

https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.6

**Comment by thestr4ng3r** [comment]
This patch can also be removed after updating: https://github.com/rizinorg/rizin/commit/a9785645273cd5f142c02ddb6c4082f87c4f2d82
