### ISSUE TITLE
Jumping by mouse click in visual panels mode doesn't add to seek history

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/rizin#2269]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ windows-x86-64 commit: f2e421a896e8502724b36d427b9913ca900516c6, build: 29/01/2022__11:48:41.71

### Expected behavior
Clicking with the mouse on a symbol in visual panels mode to jump to it will add the previous location to the seek history so I can hit `u` to go back.

### Actual behavior
It does not add it to the seek history.

### Steps to reproduce the behavior
1. Open any binary.
2. Open visual panels mode `v`.
3. Click on any symbol with the mouse.
4. Try to go back by pressing `u`.

**Comment by segevfiner** [comment]
Seems like this even sometimes bugs out and clicking the mouse just jumps to somewhere that seems pretty random...

**Comment by XVilka** [comment]
There were some conversions from `rz_core_cmd*("s ...")` calls in the `librz/core/tui/panels.c` file to use the C API directly. It's probably just some function was used `rz_core_seek()` instead the one that saves history.
