### ISSUE TITLE
Rizin errors/crashes when parsing a specific PDB generated by MSVC2019

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/rizin#2270]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ windows-x86-64 commit: f2e421a896e8502724b36d427b9913ca900516c6, build: 29/01/2022__11:48:41.71

### Expected behavior
Running `idp` on the given binary and symbols file successfully loads the debug symbols.

### Actual behavior
Rizin errors/crashes with the error:
```
ERROR: parse_type_fieldlist: Unsupported leaf type 0x1404
ERROR: Parse TPI type error. idx in stream: 0x1f65
```

### Steps to reproduce the behavior
<details><summary><code>main.cpp</code></summary>

```cpp
#include <iostream>
#include <stdexcept>

#ifdef _MSC_VER
#include <Windows.h>
#endif

#ifdef _MSC_VER
#define NOINLINE __declspec(noinline)
#else
#define NOINLINE __attribute__((noinline))
#endif

static NOINLINE void trycatch_cpp() {
    std::string message("Test");

    try {
        throw std::runtime_error(message);
    } catch (const std::runtime_error& e) {
        std::cout  << __func__ << ": Caught: " << e.what() << std::endl;
    }
}

#ifdef _MSC_VER
static NOINLINE void trycatch_seh_access_violation() {
    int* x = nullptr;
    __try {
        std::cout << *x << std::endl;
    } __except (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) {
        std::cout << __func__ << ": Caught EXCEPTION_ACCESS_VIOLATION" << std::endl;
    }
}

static NOINLINE void trycatch_seh_access_violation_finally() {
    int* x = nullptr;
    __try {
        __try {
            std::cout << *x << std::endl;
        } __except (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) {
            std::cout << __func__ << ": Caught EXCEPTION_ACCESS_VIOLATION" << std::endl;
        }
    } __finally {
        std::cout << __func__ << ": Finally" << std::endl;
    }
}

static NOINLINE void trycatch_outputdebugstring() {
    constexpr const char* MESSAGE = "Hello, World!\n";

    ULONG_PTR args[2];
	args[0] = std::strlen(MESSAGE) + 1;
	args[1] = reinterpret_cast<ULONG_PTR>(MESSAGE);

	__try {
		RaiseException(DBG_PRINTEXCEPTION_C, 0, _countof(args), args);
	} __except (GetExceptionCode() == DBG_PRINTEXCEPTION_C ? EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH) {
		std::cout << __func__ << ": Caught" << std::endl;
	}
}
#endif

int main() {
    trycatch_cpp();

#ifdef _MSC_VER
    trycatch_seh_access_violation();
    trycatch_seh_access_violation_finally();
    trycatch_outputdebugstring();
#endif
}
```
</details>

<details><summary><code>CMakeLists.txt</code></summary>

```cmake
cmake_minimum_required(VERSION 3.22)
project(exceptions-test)
add_executable(exceptions-test main.cpp)
```
</details>

Binary (Debug, MSVC 2019 16.11.9): [exceptions-test.zip](https://github.com/rizinorg/rizin/files/7963732/exceptions-test.zip)

P.S. This is a small piece of code I written to see how rizin handles analyzing exception handlers, might be useful as a test binary for anyone who will try to improve rizin in this area.

### Additional Logs, screenshots, source code,  configuration dump, ...

![screenshot](https://user-images.githubusercontent.com/24731903/151662238-ebd3efeb-be11-4a35-a397-2f4522655466.png)

**Comment by ret2libc** [comment]
Thanks a lot for all these reports, we really appreciate them!

I noticed one thing:
```
rizin 0.2.0-git @ linux-x86-64, package: 0.2.0.1 (ret2libc) commit: c875be9, build: 2021-01-26__18:17:13
```

Where did you take this rizin? Could you make sure to use the latest stable version available or dev?

**Comment by segevfiner** [comment]
I did. That's just a copy pasta error. I'll edit this to the correct version.
