### ISSUE TITLE
Relocations are sometimes not patched correctly in the dissassembly

### ISSUE THREAD

**Issue by komugi64** [rizinorg/rizin#2277]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo Linux 64-bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64
commit: 85c00053e08dce8b526717e12d15691a4d448be8, build: 2022-01-29__23:00:38

### Behavior
Some relocations are not patched in the disassembly, when they should be

![2022-02-02-171511_763x215_scrot](https://user-images.githubusercontent.com/28266927/152201171-0683031f-7e81-4ca9-b0b9-e9f117996b89.png)

Disassembly at address `0x08000066` should be `push 0x800021c`

Here is the associated file :
[bof.ko.zip](https://github.com/rizinorg/rizin/files/7988625/bof.ko.zip)

### Expected behavior
Sometimes (I guess most of the time), they are patched correctly

![2022-02-02-174622_680x181_scrot](https://user-images.githubusercontent.com/28266927/152202845-eea5c8dc-9b6f-4b26-b358-842da8f047f6.png)

Maybe it's because it's 64-bit. Anyway here's the associated file :
[tostring.ko.zip](https://github.com/rizinorg/rizin/files/7988641/tostring.ko.zip)

**Comment by komugi64** [comment]
I also have a file with really weird string relocations (a kernel module from SecurityCTF 2019) :
[chall.ko.zip](https://github.com/rizinorg/rizin/files/7989388/chall.ko.zip)

- objdump and readelf don't find the values for the relocations
- rizin and r2 display different values that seem to come from nowhere
- but the printk's work correctly when the module is loaded

#### Respective outputs of rizin and objdump (with addresses synchronized with rizin)
![2022-02-02-202808_1366x768_scrot](https://user-images.githubusercontent.com/28266927/152223808-0cd28195-d120-4770-8215-5604eb3af4a3.png)

For example at address `0x080000a9` the argument for`printk` should be at address `0x08000438` not `0x8001568`

**Comment by thestr4ng3r** [comment]
Patching works now, but the reloc info in e.g. `ir` still shows `0x800020b` without the added value from the bytes below (e.g. 0x11). This should probably be fixed after #2277

**Comment by XVilka** [comment]
@thestr4ng3r the link you put is wrong I suppose?

**Comment by thestr4ng3r** [comment]
I can only guess now, but I probably meant #1699

**Comment by ret2libc** [comment]
Closing because it is fixed:

```
[0x08000058]> pdf @ sym.bof_open 
┌ sym.bof_open ();
│           0x08000066      push  str.6_Bof:_open                      ; 0x800021c ; "<6>Bof: open()\n"; RELOC 32 .rodata.str1.1 @ 0x0800020b
│           0x0800006b      call  reloc.target.printk                  ; RELOC 32 printk
│           0x08000070      xor   eax, eax
│           0x08000072      pop   edx
└           0x08000073      ret
[0x08000058]> pd 1 @ str.6_Bof:_open 
            ; DATA XREF from sym.bof_open @ 0x8000066
            ;-- str.6_Bof:_open:
            0x0800021c     .string "<6>Bof: open()\n" ; len=16
[0x08000058]> 

```
