### ISSUE TITLE
Install plugins on Windows

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/rizin#2280]
**Is your feature request related to a problem? Please describe.**
I want to be able to install plugins on Windows. The current `rz-pm` is a shell script tailored for Linux/macOS, and the plugins still use the radare2 old ACR build system, as such there is no convenient way to build plugins on Windows.

**Describe the solution you'd like**
Being able to install plugins on Windows. Need a different implementation of `rz-pm` and converting to a plugin build system that will work on Windows.

**Describe alternatives you've considered**
Don't use Rizin on Windows, but on Linux via Docker or WSL. But that won't work that well with cutter.

**Additional context**
P.S. Isn't this like... inverted? https://github.com/rizinorg/rizin/blob/00107ea05d2d769834272b253b38d792ce4001f4/binrz/rz-pm/rz-pm#L93-L97

I haven't tried but I think radare2 has rewrite of the pm script in c, I'm not sure if it works on Windows.

**Comment by ret2libc** [comment]
There was already a starting point of rz-pm in golang and we have plans to continue it, time permitting, however it is still there... Yes, rz-pm bash script is no good for Windows. Hopefully by mid year or so we can have rz-pm basic functionalities working in golang and all major OS. I'm not sure it makes sense to keep this task opened though, as we have already https://github.com/rizinorg/rz-pm/

**Comment by segevfiner** [comment]
Up to you. Can just move it there or close it altogether. I just wanted to point out the divergence in terms of radare2's rz-pm where they choose to abandon the Go implementation and implement something in C.

P.S. If you're feeling adventurous, it might be possible, as an interim solution, to get `rz-pm` working with msys2 using mingw gcc (Assuming the ABI is compatible) or some msvc wrapper script that translates the compiler flags. But that's always very dicey as you can imagine.

**Comment by XVilka** [comment]
Closing in favor of https://github.com/rizinorg/rz-pm/issues/6 and https://github.com/rizinorg/rz-pm/issues/12
