### ISSUE TITLE
pdf: Incorrect disassembly after `..`

### ISSUE THREAD

**Issue by kazarmy** [rizinorg/rizin#2288]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86-64 20.04
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: d533276df87fec9042381aad537995a280d71768, build: 2022-02-06__17:43:31

### Actual behavior

![expected-infinite-loop](https://user-images.githubusercontent.com/12002672/152676826-828be2c4-a178-458d-aa67-f1ed29ed8e18.PNG)

(r2 [8587412](https://github.com/radareorg/radare2/commit/8587412f077e66319025fd774c9a36670f1255f6) gets this right for some reason)

### Expected behavior

![xor-eax-eax](https://user-images.githubusercontent.com/12002672/152677002-ad184c7a-12c2-4fb0-85fe-f1edb71904e7.PNG)

### Steps to reproduce the behavior

[infinite-loop.bf.zip](https://github.com/rizinorg/rizin/files/8009957/infinite-loop.bf.zip)

**Comment by ret2libc** [comment]
This does not seem about disassembly, but it seems a bug somewhere in `pdf`, because actually the function is analyzed and disassembled correctly.

If you look at the graph indeed:
![image](https://user-images.githubusercontent.com/562321/152761672-3eea594d-8a55-4fbc-85f0-cb1156a32dc5.png)

Also, using `pdr`:
```
[0x00001040]> pdr
  ; DATA XREF from entry0 @ 0x1081
  ;-- section..text:
  ;-- .text:
┌ int main (int argc, char **argv, char **envp);
│ 0x00001040      endbr64                                              ; [14] -r-x section size 389 named .text
│ 0x00001044      add   byte [obj.array], 1                            ; [0x4040:1]=0
│ 0x0000104b      je    0x1050
| ----------- true: 0x00001050  false: 0x0000104d
│ 0x0000104d      jmp   0x104d
| ----------- true: 0x0000104d
│ 0x00001050      xor   eax, eax
└ 0x00001052      ret
```

That said, there is definitely a bug in `pdf`.

**Comment by kazarmy** [comment]
I agree with you that there is a bug in the `pdf` output.
