### ISSUE TITLE
API for the graph access

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2298]
Currently some of the graph features are implemented only in commands or in `RzGraph` and `RzAGraph` structures. But those APIs and structures aren't complete or good enough to perform a comparison, for example, of CFGs between two different functions or files, e.g. for `rz-diff` purpose but from the API.

**Comment by ret2libc** [comment]
RzGraph is quite generic and should remain so IMO.

What are exactly the API you are missing?

Differences in graphs is a very specific thing that needs to be done by the user of the API, not the API itself imo. Are two graphs the same based on the structure of the nodes? On the content of the nodes? On something else?

RzGraph deals only with the data structure, but it has no idea what's inside each node in the graph. I believe any real application that needs to use graphs would need to perform at least some operations on the content.

**Comment by XVilka** [comment]
Differences in graphs are required for the `rz-diff` and Cutter diff plugins.

**Comment by ret2libc** [comment]
Ok, implement them there. What's the problem with that? What kind of API do you need? If there is no real and concrete proposal, let's close this.

**Comment by XVilka** [comment]
Duplicate of https://github.com/rizinorg/rizin/issues/992
