### ISSUE TITLE
[FLIRT] - zfs not completing

### ISSUE THREAD

**Issue by re-fox** [rizinorg/rizin#2300]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 35
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  | `rizin 0.4.0-git @ linux-x86-64 commit: 52825a7a027c47e4da5335330c9755d77ab64ca8, build: 2022-02-10__16:08:20`

### Expected behavior
Analysis will complete

### Actual behavior
When running `zfs` against a sample binary and using a specific FLIRT set, rizin analysis does not complete.  I've let this run for a number of hours with no result. 

Neither the FLIRT signature or the binary are overly large, and the the binary does not contain many functions.  Other FLIRT signatures will run against this binary with no issue.  

### Steps to reproduce the behavior
 - Load the following binary in rizin  (password: infected)
[rizin_flirt_sample.zip](https://github.com/rizinorg/rizin/files/8044417/rizin_flirt_sample.zip)

 - Download the FLIRT dataset
```
wget "https://github.com/mandiant/capa/blob/master/sigs/3_flare_common_libs.sig?raw=true" --output-document=3_flare_common_libs.sig
```
- Load binary and run `zfs`
```
$ rizin -A rizin_flirt_sample
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for classes
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Applied 0 FLIRT signatures via sigdb
 -- Use hasher to calculate hashes of portion blocks of a file
[0x0040b227]> zfs ./3_flare_common_libs.sig
```
- Analysis never returns

### Additional Logs, screenshots, source code,  configuration dump, ...
I did run with some additional logging, but could not track down the source of the issue 
```
[0x0040b227]> zfs ./3_flare_common_libs.sig 
DEBUG: s-expr (statements (arged_stmt command: (cmd_identifier) args: (args (arg (arg_identifier)))))
DEBUG: statements: 'zfs ./3_flare_common_libs.sig '
DEBUG: commands with 1 childs
DEBUG: arged_stmt: 'zfs ./3_flare_common_libs.sig'
DEBUG: arged_stmt command: 'zfs'
DEBUG: Shrinking input to 'zfs ./3_flare_common_libs.sig'
DEBUG: old input = 'zfs ./3_flare_common_libs.sig'
DEBUG: new input = 'zfs ./3_flare_common_libs.sig'
DEBUG: parsed_arg 1: './3_flare_common_libs.sig'
DEBUG: processed parsed_arg 1: './3_flare_common_libs.sig'
DEBUG: FLIRT: Found flirt.RAND_event
DEBUG: FLIRT: Found flirt.CRYPTO_THREAD_get_current_id
DEBUG: FLIRT: Found flirt.CRYPTO_THREAD_get_current_id_1
DEBUG: FLIRT: Found flirt.CRYPTO_THREAD_get_current_id_2
DEBUG: FLIRT: Found flirt.CRYPTO_THREAD_get_current_id_3
DEBUG: FLIRT: Found flirt.Insert_nohint_U__pair___CBV__basic_string_DU__char_traits_D_std__V__allocator_D_2__std__U__pair_PAVBufferedTransformation_CryptoPP__V__basic_string_DU__char_traits_D_std__V__allocator_D_2__std___2__std__U_Nil_2_____Tree_V___Tmap_traits_V__basic_string_DU__char_traits_D_std__V__allocator_D_2__std__U__pair_PAVBufferedTransformation_CryptoPP__V__basic_string_DU__char_traits_D_std__V__allocator_D_2__std___2_U__less_V__basic_string_DU__char_traits_D_std__V__allocator_D_2__std___2_V__alDEBUG: FLIRT: Found flirt.resize___vector_UECPPoint_CryptoPP__V__allocator_UECPPoint_CryptoPP___std___std__QAEXI_Z
DEBUG: FLIRT: Found flirt.0HuffmanDecoder_CryptoPP__QAE_PBII_Z
DEBUG: FLIRT: Found flirt.HDU__char_traits_D_std__V__allocator_D_1__std__YA_AV__basic_string_DU__char_traits_D_std__V__allocator_D_2__0_PBDABV10__Z
DEBUG: FLIRT: Found flirt.CRYPTO_THREAD_get_current_id_4
... <analysis paused> ....
```

**Comment by ret2libc** [comment]
cc @wargio

**Comment by wargio** [comment]
Thank you for the bug report :)
