### ISSUE TITLE
Enable FreeBSD support for ARM, MIPS, PowerPC, SPARC

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#233]
Taken from https://www.freshports.org/lang/rizin
```
NOT_FOR_ARCHS=          armv6 armv7
--
17 | NOT_FOR_ARCHS_REASON=   does not build: Unsupported BSD architecture
```
It would be nice if FreeBSD developers explain what exact problems were with those architectures.

**Comment by XVilka** [comment]
@arrowd do you know why `armv6` and `armv7` are still disabled? Could we close this issue?

**Comment by arrowd** [comment]
I dont have an armv[67] machine to try the build, so yes, I'd rather close this.
