### ISSUE TITLE
afls command family not working and aren't tested

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#238]
### Work environment

n/a

### Actual behavior

| afls   same as aflsa
| aflsa  sort by address (same as afls)
| aflss  sort by size
| aflsn  sort by name
| aflsb  sort by number of basic blocks

Aren't working and aren't tested

### Expected behavior

| afls   same as aflsa
| aflsa  sort by address (same as afls)
| aflss  sort by size
| aflsn  sort by name
| aflsb  sort by number of basic blocks

Are working and tested or killed

**Comment by XVilka** [comment]
In theory it should be subsumed/merged into `aflt` since the Table API is more suitable for sorting by the column.

**Comment by Maijin** [comment]
Agree

**Comment by fangxlmr** [comment]
@ReJimp  This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by salutdamour** [comment]
I have found the targeted function rz_list_sort. I feel awkward to ask a simple question. Before I test and repair the afls command, shall I have to build the project? I have also installed the rizin by a easy way in my PC.

**Comment by XVilka** [comment]
@ReJimp of course, see these documents for building and contributing:
- [BUILDING.md](https://github.com/rizinorg/rizin/blob/dev/BUILDING.md)
- [CONTRIBUTING.md](https://github.com/rizinorg/rizin/blob/dev/CONTRIBUTING.md)
- [DEVELOPERS.md](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md)

**Comment by salutdamour** [comment]
@XVilka  Oh my god! I found I forgot to use git-clang-format 11 to format my code. It made PR run failed. What should I do to solve the problem.

**Comment by ret2libc** [comment]
@pelijah did you remove the `afls` commands?

**Comment by p371jah** [comment]
Yep, `afls` commands were removed since we have `aflt`.
