### ISSUE TITLE
Check old uses of `@@`/`@@@`

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#240]
In cfg.newshell we merged `@@`/`@@@` and changed the meaning of some of those, however there are other parts in the code that execute commands with the old syntax, so we should fix those. Even better, we should use APIs instead of executing `rz_core_cmd`, because using strings makes refactoring hard.

**Comment by XVilka** [comment]
If there are missed use cases it also means these commands/features are not covered by the tests. While it might be out of the scope of the issue, at least anyone who will work on this please make a list of those places to add tests later.

**Comment by ret2libc** [comment]
Yes they were reported by @Maijin and if it makes sense to keep those commands i will add tests. However considering they are not tested at all, if they are things that don't work very well we may even delete some.
