### ISSUE TITLE
Binary mask output/input for `rz-ax`.

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2458]
It's common in various datasheets to have particular bits set, e.g. `[0] - RST, [5-7] - MSK, [15-31] - DATA`.

With long numbers, e.g. 64bit numbers, counting manually these bits is painful, and calling external commands, e.g. Python is suboptimal.

The idea is to allow a new bit mode for `rz-ax` that will print something like this:
```
$ rz-ax =2 0xb3
10110011b
$ rz-ax -B 0xb3
[0-1]: 1
[4-5]: 1
[7]: 1
```
Or something similar

**Comment by ret2libc** [comment]
I'm not sure I understand how it works

**Comment by DhruvaG2000** [comment]
@XVilka currently ``rz-ax -B`` does  ``str -> bin`` conversion.

We will have to come up with a different parameter, but this feature sounds like a great idea! Especially coming from an embedded background I know the pain of manually counting set bits and their positions.

I suggest we use ``rz-ax -p`` (p for position perhaps? not the most intuitive but this is letter is not used currently) to basically achieve this. Let me know your thoughts and I will get started with this.

**Comment by XVilka** [comment]
@DhruvaG2000 yes, sounds good.
