### ISSUE TITLE
Debugging in rizin and strange warnings about ptrace_getregset

### ISSUE THREAD

**Issue by fr0ster** [rizinorg/rizin#2470]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 11/Intel/x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Intel/x64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 0c4308d07e0d89d84f221d796b74003268fdc4a6, build: 2022-03-29__11:51:46

### Expected behavior
```
[0x00001145]> ood
File dbg:///home/alex/prj/C++/a.out reopened in read-write mode
[0x7fbc4768c090]> dcu main
Continue until 0x55d2c04bf145 using 1 bpsize
hit breakpoint at: 0x55d2c04bf145
```
### Actual behavior
```
[0x00001145]> ood
Process with PID 362503 started...
= attach 362503 362503
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
Try: 'R!pid'
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
File dbg:///home/alex/prj/C++/a.out  reopened in read-write mode
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
[0x7f50acaf1090]> dcu main
Continue until 0x55ec10c28145
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
hit breakpoint at: 0x55ec10c28145
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
```

### Additional Logs, screenshots, source code,  configuration dump, ...

[test.zip](https://github.com/rizinorg/rizin/files/8381481/test.zip)

**Comment by ret2libc** [comment]
I cannot reproduce on Fedora 35, x86_64.
```
$ ./build/binrz/rizin/rizin -d ./a.out 
Process with PID 310403 started...
= attach 310403 310403
bin.baddr 0x55a7feeee000
Using 0x55a7feeee000
asm.bits 64
 -- Toggle between disasm and graph with the space key
[0x7f4851cae6a0]> ood
child received signal 9
Process with PID 310413 started...
= attach 310413 310413
Try: 'R!pid'
File dbg:///home/rschiron/projects/rizinorg/rizin/a.out  reopened in read-write mode
[0x7f82af7ae6a0]> dcu main
Continue until 0x55ba5f526145
hit breakpoint at: 0x55ba5f526145
[0x55ba5f526145]> ?V
0.4.0-git @ linux-x86-64
commit: be48ddcd9f0c2023d0e64750426c0476a13d8589, build: 2022-03-31__14:33:25
```

**Comment by fr0ster** [comment]
Hi

I written about other version of rizin
```
$ rizin -v
rizin 0.4.0-git @ linux-x86-64
commit: 0c4308d07e0d89d84f221d796b74003268fdc4a6, build: 2022-03-29__11:51:46
```
I try update source and check again

**Comment by fr0ster** [comment]
Anyway I got same mistakes
```
$ sudo rizin -d ls
[sudo] пароль для alex: 
Process with PID 335451 started...
= attach 335451 335451
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
bin.baddr 0x5624cea64000
Using 0x5624cea64000
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
asm.bits 64
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
PTRACE_GETREGSET: No such device
 -- Change the graph block definition with graph.callblocks, graph.jmpblocks, graph.flagblocks
[0x7f86f3b14090]> q
Do you want to quit? (Y/n) 
Do you want to kill the process? (Y/n)
```

**Comment by ret2libc** [comment]
Could it be some debian-specific thing? Are you in a container? Is kernel.yama.ptrace_scope set to 0?

**Comment by fr0ster** [comment]
> Could it be some debian-specific thing? Are you in a container? Is kernel.yama.ptrace_scope set to 0?

I set kernel.yama.ptrace_scope into 0 but it doesn't give any effect
Maybe it really debian-specific things.
I remember I had problem with radare2 2 years ago
https://github.com/radareorg/radare2/issues/17919

**Comment by ret2libc** [comment]
> > Could it be some debian-specific thing? Are you in a container? Is kernel.yama.ptrace_scope set to 0?
> 
> I set kernel.yama.ptrace_scope into 0 but it doesn't give any effect Maybe it really debian-specific things. I remember I had problem with radare2 2 years ago [radareorg/radare2#17919](https://github.com/radareorg/radare2/issues/17919)

Thank you for the reference, it helped! Could you please test https://github.com/rizinorg/rizin/pull/2501 and see if the errors make sense now?

**Comment by fr0ster** [comment]
Thanks

I pulled branch ignore-x86-xstate-enodev-error, build new rizin and check on rizin -d /bin/ls,
It works, thanks
I found one problem only:
If I open binary for debug and run execution by dc command I get message "PTRACE_CONT: No such process" after doo/ood comand. If I din't give dc command then doo/ood doesn't give message about PTRACE
```
$ rizin -d a.out
Process with PID 804673 started...
= attach 804673 804673
bin.baddr 0x564e54d1b000
Using 0x564e54d1b000
asm.bits 64
 -- Setup dbg.fpregs to true to visualize the fpu registers in the debugger view.
[0x7f12d5517090]> ood
child received signal 9
Process with PID 804674 started...
= attach 804674 804674
Try: 'R!pid'
File dbg:///home/alex/prj/C++/a.out  reopened in read-write mode
[0x7f196b864090]> dc
InVoltage: 128.700000
(804674) Process exited with status=0x0
[0x7f196b737699]> ood
PTRACE_CONT: No such process
child received signal 9
Process with PID 804676 started...
= attach 804676 804676
Try: 'R!pid'
File dbg:///home/alex/prj/C++/a.out  reopened in read-write mode
[0x7fd7c36f0090]> 
```

**Comment by ret2libc** [comment]
do you mean `PTRACE_CONT: No such process`?

**Comment by fr0ster** [comment]
> do you mean `PTRACE_CONT: No such process`?

If I open binary for debug and run execution by dc command I get message "PTRACE_CONT: No such process" after doo/ood comand. If I din't give dc command then doo/ood doesn't give message about PTRACE
```
$ rizin -d a.out
Process with PID 804673 started...
= attach 804673 804673
bin.baddr 0x564e54d1b000
Using 0x564e54d1b000
asm.bits 64
 -- Setup dbg.fpregs to true to visualize the fpu registers in the debugger view.
[0x7f12d5517090]> ood
child received signal 9
Process with PID 804674 started...
= attach 804674 804674
Try: 'R!pid'
File dbg:///home/alex/prj/C++/a.out  reopened in read-write mode
[0x7f196b864090]> dc
InVoltage: 128.700000
(804674) Process exited with status=0x0
[0x7f196b737699]> ood
PTRACE_CONT: No such process
child received signal 9
Process with PID 804676 started...
= attach 804676 804676
Try: 'R!pid'
File dbg:///home/alex/prj/C++/a.out  reopened in read-write mode
[0x7fd7c36f0090]> 
```

**Comment by ret2libc** [comment]
Yes I can reproduce that, but that's a separate problem and it doesn't seem to cause any harm at the moment. I'm going to investigate though, thanks!

**Comment by ret2libc** [comment]
By the way, could you test the branch again? I had to add a small fix because it was wrong.

**Comment by fr0ster** [comment]
Thanks, I checked last commit, debug works
Can I close issue?
