### ISSUE TITLE
C parser fails to load ELF file format

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#2474]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 35
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: be48ddcd9f0c2023d0e64750426c0476a13d8589, build: 2022-03-31__14:33:25

### Expected behavior
```
$ ./build/binrz/rizin/rizin -nn ./test/bins/elf/ls
 -- Control the signal handlers of the child process with the 'dk' command
[0x00000000]> pfo elf64
```
Also, `pf.elf_header` and others should run well.

### Actual behavior
```
$ ./build/binrz/rizin/rizin -nn ./test/bins/elf/ls
 -- Control the signal handlers of the child process with the 'dk' command
[0x00000000]> pfo elf64
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
Error forming RzType and RzBaseType pair out of enum
```

### Steps to reproduce the behavior
```
$ ./build/binrz/rizin/rizin -nn ./test/bins/elf/ls
 -- Control the signal handlers of the child process with the 'dk' command
[0x00000000]> pfo elf64
```

### Additional Logs, screenshots, source code,  configuration dump, ...

[err.txt](https://github.com/rizinorg/rizin/files/8390497/err.txt)
Does not seem to work on `0.3.4 @ linux-x86-64, package: 0.3.4-1.fc35 (Fedora)` either.

**Comment by ret2libc** [comment]
`pf.elf_header` seems to work. even though there are the errors.

**Comment by chinggg** [comment]
`rizin 0.3.1 @ linux-x86-64` also has the error but `radare2 5.6.6` doesn't. This seems to be related to the enum type parser. See https://github.com/rizinorg/rizin/blob/dev/librz/type/parser/types_parser.c#L950-L951 for the error

https://github.com/rizinorg/rizin/blob/dev/librz/type/parser/types_storage.c#L526-L530 Does the errors just mean the enum types are already defined

**Comment by XVilka** [comment]
It's not a bug. It tries to redefine the type `elf_type`, for example, that is already presented during the loading of the binary:
```
$ rizin -nn test/bins/elf/ls
[0x000000]> te
....
elf_type
...
[0x000000]> pfo elf64
Error forming RzType and RzBaseType pair out of enum: elf_type
```
I am not sure what is the best course of action then. The rest of the enums that don't overlap loaded just fine.
