### ISSUE TITLE
Append descriptor to the method name in command `icmj`

### ISSUE THREAD

**Issue by haeter525** [rizinorg/rizin#2479]
**Is your feature request related to a problem? Please describe.**

Hi there!
When searching for alternative solutions for #2475, I found a possible command called `icmj`, which lists method information from the perspective of object-oriented languages.

However, after testing, the output JSON structure seems not to include the method descriptor, which could be an issue when users need to distinguish the overloaded methods.

```json
  {
    "name": "<init>", // <--- Overloaded method 1
    "class": "Landroid/support/v4/widget/SimpleCursorAdapter;",
    "flags": [
      "public",
      "constructor"
    ],
    "addr": 376100
  },
  {
    "name": "<init>", // <--- Overloaded method 2
    "class": "Landroid/support/v4/widget/SimpleCursorAdapter;",
    "flags": [
      "public",
      "constructor"
    ],
    "addr": 376144
  },
```
> It's hard to tell which one is the method `Landroid/support/v4/widget/SimpleCursorAdapter; <init>(Landroid/content/Context;ILandroid/database/Cursor;[Ljava/lang/String;[I)V`.

**Describe the solution you'd like.**

Append the descriptor to the value of the key `name`. That used to be what Rizin did in the older version. In my opinion, it fixes this issue perfectly without any drawbacks.

**Describe alternatives you've considered.**

Introduce a new key for the descriptor. I think this solution should work if Rizin changed the content of the key `name` for reasons.

Please feel free to contact me for any clarification. Hope to hear the feedback soon. :D

**Comment by ret2libc** [comment]
@wargio thoughts on this?

**Comment by ret2libc** [comment]
```
[0x000001b4]> icm
address    index class  flags name                       
---------------------------------------------------------
0x0000019c 0     Ltest; pC    <init>()V
0x000001b4 1     Ltest; sp    main([Ljava/lang/String;)V
0x0000021c 2     Ltest; sp    result(II)I
[0x000001b4]> icmj~{}
[
  {
    "name": "<init>",
    "class": "Ltest;",
    "flags": [
      "public",
      "constructor"
    ],
    "addr": 412
  },
  {
    "name": "main",
    "class": "Ltest;",
    "flags": [
      "static",
      "public"
    ],
    "addr": 436
  },
  {
    "name": "result",
    "class": "Ltest;",
    "flags": [
      "static",
      "public"
    ],
    "addr": 540
  }
]
```

Just to understand.. Do you want the `name` value shown in the table above rather than the name shown in the json?

**Comment by wargio** [comment]
yeah it makes sense. i will check it out today.

**Comment by haeter525** [comment]
> Just to understand.. Do you want the name value shown in the table above rather than the name shown in the json?

Yes! I would like the `name` value shown in the table above to be printed in the JSON.

Thank you, @ret2libc and @wargio, for the quick reply!
