### ISSUE TITLE
Off_t undefined when writing plugin in Windows

### ISSUE THREAD

**Issue by TheNewJavaman** [rizinorg/rizin#2544]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 Pro amd64 21H2
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ windows-x86-64 commit: 08bf76d7b3a04d3d2e8fc7e5d1da377eeeaf6898, build: Thu 04/14/2022__ 9:39:31.20

### Expected behavior

No issues with type definitions

### Actual behavior

I am writing a C plugin for Rizin using Clion and Cmake in Windows. MSVC v143 (from Visual Studio 17/2022 Preview 2). When compiling, it looks like a header is not being included properly, even though I'm only including `rz_core.h`. I compiled rizin from dev and am using the `.cmake` configuration in my `CMakeLists`:

```
cmake_minimum_required(VERSION 3.22.3)
project(rizin_plugins)
set(CMAKE_C_STANDARD 11)
list(APPEND CMAKE_MODULE_PATH "$ENV{RIZIN_HOME}/lib/cmake/Rizin")
find_package(Rizin COMPONENTS Core)
include_directories(${rz_core_INCLUDE_DIRS})
add_library(function_matcher SHARED function_matcher.c)
target_link_directories(function_matcher PUBLIC ${rz_core_LIBRARY_DIRS})
target_link_libraries(function_matcher ${rz_core_LIBRARIES})
```

If I do this before including `rz_core.h`, everything works just fine:

```c
typedef long off_t; // TODO: Find proper header
```

Error:
```
C:\Users\gpiza\OneDrive\Code\rizin\rizin-install\include\librz\sdb\types.h(118): error C2081: 'off_t': name in formal parameter list illegal
```

**Comment by TheNewJavaman** [comment]
Also, I switched to C++ for unrelated reasons (vectors + maps made things easier for the plugin), and the problem has persisted.

**Comment by ret2libc** [comment]
Hi! Could you share part of your code at least? I'm not really interested in the body of your functions, just the basic stuff to try and reproduce. Thanks!

**Comment by ret2libc** [comment]
In the meantime, I think this is a better way to deal with our cmake package:

```
find_package(Rizin COMPONENTS Core)
add_library(function_matcher SHARED function_matcher.c)
target_link_libraries(function_matcher Rizin::Core)
```

To find the Rizin component (and the others), I think you should do
```
list(APPEND CMAKE_PREFIX_PATH "$ENV{RIZIN_HOME}/lib/cmake")
```

**Comment by XVilka** [comment]
We also could add/improve a small CMake-based test for plugins with our CI, like we have one for Meson:
- https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L559
- https://github.com/rizinorg/rizin/tree/dev/.github/cmake_test
- https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L833

cc @thestr4ng3r @GustavoLCR

**Comment by ret2libc** [comment]
I don't see a real difference for what concerns this bug with regards to the existing cmake_test and a plugin. Actually, we already test CMake config files on Windows, so until we get more info from @TheNewJavaman I am not sure what to do about this issue.

**Comment by ret2libc** [comment]
Ping @TheNewJavaman
