### ISSUE TITLE
VS Code as editor throws error on Windows

### ISSUE THREAD

**Issue by TheNewJavaman** [rizinorg/rizin#2551]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 Pro 21H2/x64
| File format of the file you reverse (mandatory)      | exe
| Architecture/bits of the file (mandatory)            | x64
| `rizin -v` full output, **not truncated** (mandatory)  | `rizin 0.4.0-git @ windows-x86-64 commit: 08bf76d7b3a04d3d2e8fc7e5d1da377eeeaf6898, build: Thu 04/14/2022__ 9:39:31.20`

### Expected behavior

1. Set VS Code as default editor with `e cfg.editor=code`
2. Edit search in key with `ee search.in`

### Actual behavior

- VS Code opens, but shows an error in a popup: `Unable to open 'rzC31E.tmp': File not found.`

### Steps to reproduce the behavior

In rizin:
```
e cfg.editor=code
ee search.in
```

### Additional Logs, screenshots, source code,  configuration dump, ...
 
![Screenshot (106)](https://user-images.githubusercontent.com/16387264/163886160-d3970459-5304-4a06-a873-4bc524fe19d0.png)

**Comment by TheNewJavaman** [comment]
Works find for notepad, though

**Comment by DMaroo** [comment]
I am unable to reproduce the error. Try using `e cfg.editor="code --wait"` once. Does it still give an error?

**Comment by TheNewJavaman** [comment]
@DMaroo That worked, please feel free to close the issue unless you think this should be added to the docs

**Comment by DMaroo** [comment]
I think this would be more relevant to VSCode docs than Rizin docs. However, any contributions to the doc are helpful.
