### ISSUE TITLE
Set default meson buildtype to debugoptimized?

### ISSUE THREAD

**Issue by kazarmy** [rizinorg/rizin#256]
Initial benchmark results with adc5fb8a08e88732939e4fb7643b90af195c797e on Ubuntu 20.04 (WSL). Binary is from #218. Benchmark command line is:

```
hyperfine --warmup 3 --export-markdown results.md 'rizin -A -q 5bae961fec67565fb88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00' 'rizin-debugoptimized -A -q 5bae961fec67565f
b88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00' 'rizin-release -A -q 5bae961fec67565fb88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00'
```

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `rizin -A -q 5bae961fec67565fb88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00` | 62.338 ± 2.795 | 57.851 | 68.552 | 1.50 ± 0.09 |
| `rizin-debugoptimized -A -q 5bae961fec67565fb88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00` | 41.475 ± 1.565 | 39.877 | 44.691 | 1.00 |
| `rizin-release -A -q 5bae961fec67565fb88c8bcd3841b7090566d8fc12ccb70436b5269456e55c00` | 41.706 ± 2.522 | 39.368 | 46.647 | 1.01 ± 0.07 |

It appears that for this particular use case, `rizin-debugoptimized` gives about a 1.5x speedup over the stock `rizin` build, while there's no significant difference between `rizin-debugoptimized` and `rizin-release`.  So I think that we should default to `--buildtype debugoptimized` otherwise users are going to leave performance on the table.

Also, perhaps a more important reason is that optimization can enable more warnings, e.g. https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/Warning-Options.html#index-Wmaybe-uninitialized.

(Btw, `hyperfine` doesn't randomize command execution sequence and benchmark system was a bit noisy so treat the above results with probably a grain of salt, though I do think the dominance of `rizin-debugoptimized` over `rizin` isn't in question both theoretically and practically.)

**Comment by kazarmy** [comment]
Added commit hash to https://github.com/rizinorg/rizin/issues/256#issue-774414467.

**Comment by kazarmy** [comment]
https://github.com/rizinorg/rizin/issues/256#issue-774414467
33% speedup -> 1.5x speedup

**Comment by Maijin** [comment]
I remember that optimization like -OS, -O2 and -O3 were generating a huge amount of failure in the tests, did you check if that those any effect on the testsuite?

**Comment by kazarmy** [comment]
Not yet. I do recall that my local Windows release builds were having problems with tests but I thought that was just the local AV acting up. I don't actually recall problems with Linux release builds but I'll probably have a look during/after the holidays.

**Comment by karliss** [comment]
Debugoptimzed in meson is better describe as release with debug symbols (-O2 -g instead of -Og) so performance should be the same which matches results above.

**Comment by kazarmy** [comment]
[Release in meson](https://mesonbuild.com/Builtin-options.html#core-options) is actually `-O3` but there have been reports stating that `-O3` does not produce faster code (e.g. https://stackoverflow.com/questions/11546075/is-optimisation-level-o3-dangerous-in-g hmm undefined behavior). For this particular case, I suspect that analysis spends a lot of time in recursive code which probably isn't amenable to `-O3` optimization.

Btw, Debian requests that packages [be compiled with`-O2 -g`](https://www.debian.org/doc/debian-policy/ch-files.html#binaries).

**Comment by ghost** [comment]
@kazarmy ~should this PR be closed?~

I didn't check the second PR, sorry
