### ISSUE TITLE
Microsoft Windows 10 Pro for Workstations (Version 10.0.19044 Build 19044) missing KD profile.

### ISSUE THREAD

**Issue by PAI5REECHO** [rizinorg/rizin#2560]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| Host OS/arch/bits (mandatory)                             | Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220417.1ffba9f
| Guest OS being kernel debugged | Microsoft Windows 10 Pro for Workstations (Version `10.0.19044 Build 19044`)
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | amd64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0-git @ linux-x86-64 commit: 3cbde10260fbf8a7a380217c97acd264ac5f3102, build: 1980-01-01__00:00:00

### Expected behavior
The rizin client should attach to the remote kd target VM through the serial device and drop into an interactive debugger session

### Actual behavior
The guest VM is frozen once rizin first connects, but no debugger session is initialized

### Steps to reproduce
1. I amended my Qemu virtual machine configuration by adding the needed serial port device for rizin to connect to:
```xml
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <!-- ... -->
  <qemu:commandline>
    <qemu:arg value="-chardev"/>
    <qemu:arg value="socket,id=serial0,path=/tmp/kd.pipe,nowait,server"/>
    <qemu:arg value="-serial"/>
    <qemu:arg value="chardev:serial0"/>
    <qemu:arg value="-object"/>
    <!-- ... -->
  </qemu:commandline>
</domain>
```
2. Then I enabled kernel debugging over serial in the guest, restarted, and attached rizin:
```console
./build/binrz/rizin/rizin -a x86 -b 64 -D winkd winkd:///tmp/kd.pipe
Opened pipe /tmp/kd.pipe with fd 0x3
ERROR: Could not find a suitable profile for the target OS
ERROR: Could not find a suitable profile for the target OS
[0x00000000]>
Do you want to quit? (Y/n) y
Detaching...
```

**Comment by XVilka** [comment]
It's a missing profile for your system, see [`subprojects/rzwinkd/profiles.h`](https://github.com/rizinorg/rizin/blob/dev/subprojects/rzwinkd/profiles.h).

If you enable debug output, it should print the values that you have on your machine, see [`winkd_read_ver()`](https://github.com/rizinorg/rizin/blob/dev/subprojects/rzwinkd/winkd.c#L817) function.

**Comment by PAI5REECHO** [comment]
I recently changed back to running Windows 11 Pro for Workstation since I was having this problem. I'm not able to dump the winkd version information anymore, sorry.
