### ISSUE TITLE
Installer detected in VirusTotal (Cynet) as malicious

### ISSUE THREAD

**Issue by KhazAkar** [rizinorg/rizin#2568]
Hi,
Regarding to this VirusTotal report, installer is detected as malicious by Cynet. Is this False Positive? I just want a confirmation, since there's ongoing approval process, and they told me to contact you about that.
https://www.virustotal.com/gui/file/00f69a6bfab66a8387a3ecdf0e1587ea262359d3c0497393c45bdb6d62ba2776

**Comment by wargio** [comment]
Yes it is indeed a false positive.
