### ISSUE TITLE
WinKD (WinDbg backend) `dcu` (debug continue until) to address broken

### ISSUE THREAD

**Issue by PAI5REECHO** [rizinorg/rizin#2627]
The `dcu` (**d**ebugger **c**ontinue **u**ntil) command no longer functions after the recent changes to the winkd debugger backend. It was working previously so this seems like a behavior regression with the recent changes. I'm using a Linux host and Windows 11 Pro for Workstation guest.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | NixOS Unstable x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0 @ linux-x86-64 commit: f2a1e5e09087550e70122c3a2bedd4e2a02f77f1, build: 1980-01-01__00:00:00

### Expected behavior
Should resume execution immediately when running `dcu` command unless program counter reaches given address

### Actual behavior
```
[0xfffff80544a1f1a0]> dr PC=PC+1
[0xfffff80544a1f1a0]> pd 3
            ;-- DbgBreakPointWithStatus:
            ;-- RtlpBreakWithStatusInstruction:
            0xfffff80544a1f1a0      int3
            ;-- rip:
            0xfffff80544a1f1a1      ret
            ;-- DbgBreakPointWithStatusEnd:
            0xfffff80544a1f1a2      int3
[0xfffff80544a1f1a0]> dcu <some address>
Continue until <some address>
```
Then it just hangs indefinitely

**Comment by XVilka** [comment]
Should be fixed now. Please comment here if it still isn't, and we will reopen.
