### ISSUE TITLE
Project ignores custom binary base address

### ISSUE THREAD

**Issue by elicn** [rizinorg/rizin#2676]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10
| File format of the file you reverse (mandatory)      | PE32+
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.4 @ windows-x86-64 commit: 2373c53880e017be86afed5454bca5b5017b920e, build: Fri 01/14/2022__18:38:44.79

### Expected behavior
Reloading a saved project containing a manually rebased binary is expected to load the binary again to the manually configured base address.

### Actual behavior
When loading a saved project file, rizin ignores the base address that was configured in the project db (`bin.baddr`) and uses the one set within the binary. After loading, all flags and function names that were created in the previous session still refer to the configured base address, but they show FF's as if they refer to invalid memory.

For example, a binary has a base address of 0x10000 but we manually rebase it to 0 and then create some functions and flags. Saving the project and reloading it would result in the binary being loaded to 0x10000 while all flags and names are correctly based on 0. Since the flags and names no longer match the currently used addresses, they seem to point to "invalid content" and show FF's.

Working around it by specifying `-B 0` together with `-p path\to\prj.rzdb` doesn't help and results in loading the binary to its default base address despite of the overriding command line option and the saved base address in the project file. Nevertheless, loading the binary with `-B 0` but _without_ `-p` seems to work OK (... but we lose the work we saved)

### Steps to reproduce the behavior
Unfortunately I cannot share the executable that I work on, but that was observed with an EFI / PE binary, so I believe it could be reproduced with any other PE:
1. Load a binary and rebase it to a different address than its default (e.g. 0)
2. Name a few functions and create a few flags after the file has been rebased
3. Save and close the project
4. Load the project and observe whether the binary was loaded to the manually configured base address (0), and whether the created flags and functions still refer to valid locations or not

### Additional Logs, screenshots, source code,  configuration dump, ...
N/A

**Comment by ret2libc** [comment]
Related to https://github.com/rizinorg/cutter/issues/2541 , https://github.com/rizinorg/rizin/issues/713 and https://github.com/rizinorg/rizin/issues/714

**Comment by elicn** [comment]
Indeed, it looks like a duplication of rizinorg/cutter#2541
Feel free to close / keep opened based on the org policy.
