### ISSUE TITLE
ELF arch handling

### ISSUE THREAD

**Issue by bdemick** [rizinorg/rizin#2680]
**Is your feature request related to a problem? Please describe.**
The ELF plugin [defaults to returning x86](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L1405) when `e_machine` is `EM_NONE` or not present in the [arch_translation_table](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L242). This has the undesired effect of falsely reporting that an ELF's arch is x86 in many cases. For instance, `EM_BPF` is not currently handled in elf_info.c's [machine_name_translation_table](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L69). `rz-bin` shows the machine type as unknown with the raw `e_machine` value, which is fine, but the architecture as x86, which is definitely incorrect. I have also seen firmware that uses ELF as a container but does not specify `e_machine`, which of course gets reported as x86 by default.

**Describe the solution you'd like**
`EM_NONE` should be represented in the `arch_translation_table`, and the `EM_80386` and `EM_X86_64` types should be added and explicitly mapped to `x86`. [rz_bin_elf_get_arch](https://github.com/rizinorg/rizin/blob/dev/librz/bin/format/elf/elf_info.c#L1396) should appropriately return "No machine" when `e_machine` is `EM_NONE`, and "Unknown or unsupported machine" when the `e_machine` value does not map to a currently-supported architecture.

**Describe alternatives you've considered**
Based on my initial review of the code, I'm not seeing any great alternatives and the solution appears fairly obvious. Happy to hear alternatives or justification for why x86 needs to be the default.

**Additional context**
I haven't fully investigated if fixing this requires changes outside of the ELF plugin to handle new `arch` types (e.g., "none" or "unknown"). I'm happy to get a PR going, but want to make sure I understand the full scope of any impacts this has on the larger project before undertaking it.

**Comment by ret2libc** [comment]
Hi, thanks for the issue! I think what you said is 100% right. If you want to create a PR for the fix, we'd be happy to review it and merge it. I think there was no real reason for having x86 as default case.

**Comment by bdemick** [comment]
Right on. Will get a PR submitted very soon, and thanks for the quick response!
