### ISSUE TITLE
RIP register not tracked on 32bit binary on Windows x64

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#2699]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 32
| `rizin -v` full output, **not truncated** (mandatory)  | 0.4.0 @ windows-x86-64 commit: 6498ee6760d37f6abb11784aa550aecd2e03100b, build: Wed 06/08/2022__15:43:46.93

### Expected behavior
`rip` flag is at the right address and it moves whenever you step in visual mode.

### Actual behavior
![image](https://user-images.githubusercontent.com/562321/173939970-aac273f5-cfc0-457b-b715-73756392a6f7.png)
RIP = 0x7ffd07544d4c, but no `rip` flag at that address.

### Steps to reproduce the behavior
Run `rizin -d <binary>`, go in visual mode. There is no `rip` register flag at the current offset and if you press `s`(for stepping one instruction) you can see the value of the register being updated but the rip flag does not move in the visual disassembly.

### Additional context
The file is 32bit. There is no rip/eip register in `fs registers ; fl`.

**Comment by ret2libc** [comment]
Debugging a 64bit file seems to show the right registers and the tracking of rip works well.

**Comment by XVilka** [comment]
@GustavoLCR could you please take a look, if you have time?
