### ISSUE TITLE
Switch from a mono repository to a multi repository

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#273]
**Is your feature request related to a problem? Please describe.**
Coverage is complicated to assess on a mono repository.

**Describe the solution you'd like**
Divide the Rizin code base into several repositories.

For example:
* rz_utils
* c parser (header file)
* esil
* ...

It will allow for better coverage and  CI management.
No unit test on rz_utils is necessary, during the testing phase on the Rizin repo.

(I want 100% coverage on rz_utils, **with** Asan or Valgrind running)

The issue management will be simplified.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by XVilka** [comment]
In practice it makes painful to keep such repositories synchronized and makes the release process more complex.

**Comment by ret2libc** [comment]
It is true that probably release process will be more complicated, but having different repositories (e.g. librz_bin, librz_util, librz_io, librz_asm, etc.) would force us to consider such modules as separated entities, with their own tests and API; it would facilitate reuse from other projects (e.g. maybe others would find it useful to use librz_bin, if there would be a good API); it would simplify versioning, as it's easier to track semantic versioning of a single logical unit; it would force devs to split changes in logical units.

I do realize there would be additional burden in having several repositories though, as for example a change that extends across several modules would require a PR in each of those and testing would be harder in such a case. Also, as @XVilka said, keeping those repos synchronized would be a bit harder (though with submodules or subprojects it would be just a matter of updating the commit id).

**Comment by XVilka** [comment]
I am closing this issue until there will be the more pressing need on deciding this. Currently it's not a priority and will introduce additional burden. We might reopen it in the future.
