### ISSUE TITLE
Analysis got the wrong Jump value

### ISSUE THREAD

**Issue by dmknght** [rizinorg/rizin#2742]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Parrot OS 5.0.1 amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | `ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ebaa4a14a2d41acd447bd396189a8c9a769e83ea, stripped`
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.4.0 release

### Expected behavior

rizin should point the jump to `ret` instructor

### Actual behavior
Rizin got the jump wrong. The function shows the instructions after `ret` which doesn't belong to it.

### Steps to reproduce the behavior
1. Analysis the file `rizin -A /usr/lib/x86_64-linux-gnu/libisc-export.so.1105`
2. Show disasm of the function `pdf @ sym.isc_file_basename`
3. See the error 
![image](https://user-images.githubusercontent.com/29118926/175797252-6b3bc2df-a056-4ec2-a0d1-f8fac02a325f.png)

### Compressed file
[libisc-export.so.1105.0.2.zip](https://github.com/rizinorg/rizin/files/8985884/libisc-export.so.1105.0.2.zip)

### Additional info
- Actual source code
![image](https://user-images.githubusercontent.com/29118926/175797295-9826ba2f-fbe6-4886-9968-e8e181b3097f.png)

**Comment by ret2libc** [comment]
Why do you say that the instructions after the `ret` should not be in the function? There is a `je 0x46e58` so it is correct that the basic block at 0x46e58 is part of the function.

What is not right is that function fcn.00013000 is a no-return function, so the instructions at 0x00046e72 should not be there. However this issue is already tracked at https://github.com/rizinorg/rizin/issues/2725 so I would close this issue. Please re-open if I misunderstood the problem.

**Comment by dmknght** [comment]
> Why do you say that the instructions after the `ret` should not be in the function? There is a `je 0x46e58` so it is correct that the basic block at 0x46e58 is part of the function.
> 
> What is not right is that function fcn.00013000 is a no-return function, so the instructions at 0x00046e72 should not be there. However this issue is already tracked at #2725 so I would close this issue. Please re-open if I misunderstood the problem.

Hello! I think i misunderstood the actual problem of this issue. I checked my note again and the issue is when decompiled code (with ghidra plugin) showed the instructions of the next function until it reached the `ret` instruction of next function.
![image](https://user-images.githubusercontent.com/29118926/175826248-c4e1e6f9-beef-4295-a3db-0be6d27c4066.png)

After check the binary again and read the #2725, i believe this is the same issue. Thank you for the info :D
