### ISSUE TITLE
Failing unit tests on System Z (S390) platform

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#279]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 S390
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -.
| rizin -v full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/4848de9cde57a226ad6d6b194b28e46205d2a0f5

### Actual behavior

https://travis-ci.com/github/rizinorg/rizin/jobs/490888540#L2828:
```
76/76 pdb                  FAIL            4.04s   killed by signal 9 SIGKILL
>>> MALLOC_PERTURB_=180 /home/travis/build/rizinorg/rizin/build/test/unit/test_pdb
Summary of Failures:
76/76 pdb                  FAIL            4.04s   killed by signal 9 SIGKILL
Ok:                 75  
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /home/travis/build/rizinorg/rizin/build/meson-logs/testlog.txt
FAILED: meson-test 
```

**Comment by Basstorm** [comment]
This issue is because of the different endianness of the architecture. Currently, the code of the PDB parser is not endianness friendly and we should rewrite the code completely to make it more readable and portable.
