### ISSUE TITLE
rz-bin -z -N 1 on ELF fails to find strings of length < 4

### ISSUE THREAD

**Issue by gblomqvist** [rizinorg/rizin#2859]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Kali x86 64
| File format of the file you reverse      | ELF
| Architecture/bits of the file             | x86/64
| `rizin -v` full output, **not truncated**  | rizin 0.5.0 @ linux-x86-64 commit: f1b2e7bd758f24dfab2577d615d3b86b4c31a60b

### Expected behavior
If the minimum string length specified to `rz-bin` using `-N` is `x`, then strings of length at least `x` should be found.
### Actual behavior
No strings of length less than 4 are found, seemingly regardless of the argument provided to `-N`. An example of strings which are commonly of length less than 4 are `scanf()` conversion specifications (e.g. "%d").

### Steps to reproduce the behavior
The source code of `some_elf` in [binary.zip](https://github.com/rizinorg/rizin/files/9229265/binary.zip):
```c
int main() { char *a = "1", *b = "22", *c = "333", *d = "4444"; }
```

Run `rz-bin -z -N 1 some_elf` and you'll see that only the string "4444" is discovered as compared to all four of them.

### Identified cause
The call to find strings in the binary in this case is made from `rz_bin_object_set_items()` in [librz/bin/bobj.c on line 503](https://github.com/rizinorg/rizin/blob/f1b2e7bd758f24dfab2577d615d3b86b4c31a60b/librz/bin/bobj.c#L503). The string function called is in [librz/bin/p/bin_elf.inc on line 1965](https://github.com/rizinorg/rizin/blob/f1b2e7bd758f24dfab2577d615d3b86b4c31a60b/librz/bin/p/bin_elf.inc#L1965). This function simply wraps a call to `rz_bin_file_strings(bf, 4, false)`. The `4` is a hard coded minimal string length. I believe the issue affects all file formats which has a plugin. [The `strings` function pointer in the RzBinPlugin struct currently only takes a `RzBinFile *` argument](https://github.com/rizinorg/rizin/blob/f1b2e7bd758f24dfab2577d615d3b86b4c31a60b/librz/include/rz_bin.h#L531). Shouldn't it perhaps also take a minimum string length argument, so that the call from `rz_bin_object_set_items()` can pass along the correct minimum string length?

**Comment by XVilka** [comment]
Good catch

**Comment by ret2libc** [comment]
Dropping here some thoughts on what could be done (though @wargio might know better):

- change rz_bin_file_strings from `RZ_API RZ_OWN RzList /*<RzBinString *>*/ *rz_bin_file_strings(RZ_NONNULL RzBinFile *bf, size_t min_length, bool raw_strings)` to `RZ_API RZ_OWN RzList /*<RzBinString *>*/ *rz_bin_file_strings(RZ_NONNULL RzBinFile *bf, RzBinFileStringOpt *opt)` where `RzBinFileStringOpt` contains not only minlength but also maxlength, raw_string and potentially other future filters (e.g. ASCII only, utf-8 only, etc.)
- `RzBinPlugin`s already have a `minstrlen` field... They could contain a full `RzBinFileStringOpt default_string_options` field with the defaults values being set there. For example, bin_dmp64 uses minstrlen=4 and rawstr=false, psxexe uses minstrlen=20 and rawstr=true, etc. 
- `RzBin` already have `minstrlen`, `maxstrlen` and `rawstr` and they can probably be replaced as well with `RzBinFileStringOpt`. These values are set when the user changes bin.maxstr, bin.minstr, etc. (e.g. https://github.com/rizinorg/rizin/blob/f1b2e7bd758f24dfab2577d615d3b86b4c31a60b/librz/core/cconfig.c#L2509)
- `RzBinFile`s already have `minstrlen` and `maxstrlen`. They can probably be removed.
- callers of `rz_bin_file_strings` will select whether the `RzBinFileStringOpt` to pass as argument will be come from `bin->string_opt`(from the user) or from `bf->o->plugin->default_string_opt`(set by the plugin of the binfile). 

WDYT?

**Comment by wargio** [comment]
there is actually a check to force the length to a certain length, usually 4 is minimum, because when you select 1, then is easier to just hexdump

**Comment by ret2libc** [comment]
Still, it should be possible for users to select a <4 number, like `strings` does.

**Comment by XVilka** [comment]
@ret2libc yes, your suggestions make sense, especially since these binary-specific options can also include the preference for endianness and encoding.

**Comment by wargio** [comment]
This was fixed.

```
$ rz-bin -z -N 1 /tmp/test2.txt
[Strings]
nth paddr      vaddr      len size section type  string                  
-------------------------------------------------------------------------
0   0x00000000 0x00000000 3   4            ascii das
1   0x00000004 0x00000004 1   2            ascii d
2   0x00000006 0x00000006 1   2            ascii a
3   0x00000008 0x00000008 2   3            ascii sd
4   0x0000000b 0x0000000b 3   4            ascii das
5   0x0000000f 0x0000000f 7   8            ascii dsasads
6   0x0000001a 0x0000001a 6   7            ascii sadasd
7   0x00000023 0x00000023 10  11           ascii sdadsadsaf
8   0x0000002e 0x0000002e 1   2            ascii a
9   0x00000030 0x00000030 2   3            ascii sf
10  0x00000033 0x00000033 2   3            ascii fa
11  0x00000037 0x00000037 3   4            ascii fsa
12  0x0000003b 0x0000003b 13  14           ascii fsasfojoijfds
13  0x00000052 0x00000052 6   7            ascii 324324
14  0x00000059 0x00000059 5   6            ascii 32443
15  0x0000005f 0x0000005f 1   2            ascii 2
16  0x00000070 0x00000070 9   10           ascii 432423432
17  0x00000080 0x00000080 9   10           ascii 432423423
18  0x0000008d 0x0000008d 7   8            ascii 4234234
19  0x00000099 0x00000099 9   10           ascii 423423423
20  0x000000a7 0x000000a7 23  24           ascii fuifiojsdoijfdsojsfdoij

$ rz-bin -z -N 2 /tmp/test2.txt
[Strings]
nth paddr      vaddr      len size section type  string                  
-------------------------------------------------------------------------
0   0x00000000 0x00000000 3   4            ascii das
1   0x00000008 0x00000008 2   3            ascii sd
2   0x0000000b 0x0000000b 3   4            ascii das
3   0x0000000f 0x0000000f 7   8            ascii dsasads
4   0x0000001a 0x0000001a 6   7            ascii sadasd
5   0x00000023 0x00000023 10  11           ascii sdadsadsaf
6   0x00000030 0x00000030 2   3            ascii sf
7   0x00000033 0x00000033 2   3            ascii fa
8   0x00000037 0x00000037 3   4            ascii fsa
9   0x0000003b 0x0000003b 13  14           ascii fsasfojoijfds
10  0x00000052 0x00000052 6   7            ascii 324324
11  0x00000059 0x00000059 5   6            ascii 32443
12  0x00000070 0x00000070 9   10           ascii 432423432
13  0x00000080 0x00000080 9   10           ascii 432423423
14  0x0000008d 0x0000008d 7   8            ascii 4234234
15  0x00000099 0x00000099 9   10           ascii 423423423
16  0x000000a7 0x000000a7 23  24           ascii fuifiojsdoijfdsojsfdoij

$ hexdump -C /tmp/test2.txt
00000000  64 61 73 00 64 00 61 00  73 64 00 64 61 73 00 64  |das.d.a.sd.das.d|
00000010  73 61 73 61 64 73 00 00  00 00 73 61 64 61 73 64  |sasads....sadasd|
00000020  00 00 00 73 64 61 64 73  61 64 73 61 66 00 61 00  |...sdadsadsaf.a.|
00000030  73 66 00 66 61 00 00 66  73 61 00 66 73 61 73 66  |sf.fa..fsa.fsasf|
00000040  6f 6a 6f 69 6a 66 64 73  00 00 00 00 00 00 00 00  |ojoijfds........|
00000050  00 00 33 32 34 33 32 34  00 33 32 34 34 33 00 32  |..324324.32443.2|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  34 33 32 34 32 33 34 33  32 00 00 00 00 00 00 00  |432423432.......|
00000080  34 33 32 34 32 33 34 32  33 00 00 00 00 34 32 33  |432423423....423|
00000090  34 32 33 34 00 00 00 00  00 34 32 33 34 32 33 34  |4234.....4234234|
000000a0  32 33 00 00 00 00 00 66  75 69 66 69 6f 6a 73 64  |23.....fuifiojsd|
000000b0  6f 69 6a 66 64 73 6f 6a  73 66 64 6f 69 6a 00     |oijfdsojsfdoij.|
000000bf
```

**Comment by wargio** [comment]
I was wrong, on the elf format, it is not fixed.
