### ISSUE TITLE
Dictionary spelling of `signature` vs `zignature`.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/rizin#291]
### Expected behavior
Dictionary spelling of `signature`.
I guess **`z` as a command has a nice mnemonic correspondence with the phonetics of `signatures`**.
But personally, **having it spelled this way everywhere feels quite irritating**.

Is there a special reason, or **does** the word `zignatures` **refer** to something very **specific** about this data structure **?**
Please let me know :)

### Actual behavior
`zignature`

### Steps to reproduce the behavior 
1. open `rizin`
2.  `z?`

**Comment by karliss** [comment]
Yes, zignatures refer to the specific formats and matching algorithms used by rizin and r2. Other tools use different formats and algorithms. For example IDA calls theirs FLIRT. Rizin has some support for FLIRT signatures. Having different names helps distinguishing what kind signature of files are you talking about.

**Comment by Semnodime** [comment]
Thank you for clarification 😃

**Comment by ITAYC0HEN** [comment]
Thank you for asking :)
Come and Join jour communities on [Mattermost](im.rizin.re), Telegram or IRC if you have more questions 😊
