### ISSUE TITLE
Add a way to force disable parser generation during build?

### ISSUE THREAD

**Issue by vext01** [rizinorg/rizin#2926]
Currently the rizin build system checks for the python yaml module at configure time and if it finds it, regenerates the rizin command parser during the build.

I have an (admittedly niche) scenario (OpenBSD packaging with [dpb](http://man.openbsd.org/dpb)), where the yaml module may be present at configure time, but not at build time.

This is what we think caused the build failure:
```
/usr/local/bin/python3.9 ../rizin-v0.4.0/librz/core/cmd_descs/cmd_descs_generate.py --output-dir librz/core/cmd_descs --src-output-dir /usr/obj/ports/rizin-0.4.0/rizin-v0.4.0/librz/core/cmd_descs ../rizin-v0.4.0/librz/core/cmd_descs/cmd_analysis.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_block.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_cmp.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_debug.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_descs.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_egg.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_eval.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_flag.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_heap_glibc.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_history.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_info.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_interpret.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_meta.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_open.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_plugins.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_print.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_project.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_quit.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_remote.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_resize.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_seek.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_shell.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_system.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_tasks.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_type.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_write.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_yank.yaml ../rizin-v0.4.0/librz/core/cmd_descs/cmd_zign.yaml
Traceback (most recent call last):
  File "/usr/obj/ports/rizin-0.4.0/build-amd64/../rizin-v0.4.0/librz/core/cmd_descs/cmd_descs_generate.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
ninja: build stopped: subcommand failed.
```

For now we can work around this by registering the yaml module as a build dependency of rizin, but it would be nice if either:

 - the build system knew that regenerating the parser isn't necessary (timestamps?), or
 - there was a way to force off regeneration.

Thanks

**Comment by ret2libc** [comment]
Hi, we could add an option to use the embedded parser without regenerating it, but i admit it feels strange to have some dep as configure time but not at build time... Usually packages like Deb and rpm can specify build dependencies or regular dependencies but i think none of these can have configure dependencies. Why does that happen for openbsd?

**Comment by wargio** [comment]
as discussed per chat this should be just a meson option to completely disable the line https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/meson.build#L34 like we do for sys libs

**Comment by thestr4ng3r** [comment]
> the build system knew that regenerating the parser isn't necessary (timestamps?), or

This is actually less trivial than it sounds, since regeneration happens into the build directory (as building should never touch anything in the sources), but the pregenerated files are in the source. So likely not worth the extra logic.

> there was a way to force off regeneration.

This is absolutely feasible, as @wargio noted. I would imagine having a tristate option to set to auto/on/off. Packaging scripts can force it to `off` always since the shipped files in the tarball are known to be up to date.

**Comment by thestr4ng3r** [comment]
> Usually packages like Deb and rpm can specify build dependencies or regular dependencies but i think none of these can have configure dependencies. Why does that happen for openbsd?

If the hypothesis of the race condition is correct, pyyaml would have been just available by chance during configure time and was uninstalled shortly after. Since the rizin package did not specify pyyaml as a dependency at all, it was correctly never installed/kept for it. But our build script still found it and thus assumed it to be available.

**Comment by sthen** [comment]
Hi - I updated the OpenBSD port to add the build dependency. We don't want builds to function differently depending on what other packages are installed at build time anyway and it's no problem to depend on pyyaml. I don't think you need to make any changes to cope, it's a pretty common thing for build systems to use tools that they have detected as being available, the porter just needs to list them (or disable them) so the build works as expected.

**Comment by thestr4ng3r** [comment]
I think it will still be nice to have the option to disable the regeneration entirely, even just to have fewer dependencies.
