### ISSUE TITLE
Heap out-of-bounds read (segv) in dex.c

### ISSUE THREAD

**Issue by m4drat** [rizinorg/rizin#2954]
Hi! We've been fuzzing your project and found the following error in `librz/bin/format/dex/dex.c`

### Work environment

OS: Ubuntu 20.04
File format: -
rizin version: https://github.com/rizinorg/rizin/commit/4b385978a1a33252c4f829d3db59fb3056afadb9

### Bug description

Heap out-of-bounds read (segv) in `librz/bin/format/dex/dex.c`

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/rizin: `sudo docker build -t oss-sydr-fuzz-rizin .`

2. Run docker container: `sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-rizin /bin/bash`

3. Execute rizin with crashing input (we sent all crashing inputs to you by email):
 `/rizin-fuzzing/libfuzzer-asan/bin/rizin -qq crash-sydr_sydr-id_001842_sydr_id_004804_time_0_execs_0_orig_afl_s01-id_004493_sync_afl_main-worker_src_004120_+cov_1039_out_of_bounds_5`

4. You will see the following output:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2472491==ERROR: AddressSanitizer: SEGV on unknown address 0x60400015bdcc (pc 0x000000ba27a3 bp 0x0c060004baac sp 0x7ffc9f5c2810 T0)
==2472491==The signal is caused by a READ memory access.
    #0 0xba27a3 in dex_resolve_proto_id /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/dex/dex.c
    #1 0xba3a37 in rz_bin_dex_imports /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/dex/dex.c:1493:18
    #2 0xae7b56 in rz_bin_object_set_items /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:449:16
    #3 0xae706b in rz_bin_object_new /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bobj.c:319:2
    #4 0xad7d31 in rz_bin_file_new_from_buffer /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bfile.c:150:19
    #5 0xadf3c7 in rz_bin_open_buf /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:272:8
    #6 0xadec27 in rz_bin_open_io /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/bin.c:330:18
    #7 0x1003353 in core_file_do_load_for_io_plugin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:727:23
    #8 0x1003353 in rz_core_bin_load /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/core/cfile.c:974:4
    #9 0x5b9af8 in rz_main_rizin /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/main/rizin.c:1119:14
    #10 0x7ff594b70082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x41da3d in _start (/home/madrat/Desktop/rizin-report/rz-installation-asan/bin/rizin+0x41da3d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/madrat/Desktop/rizin-report/rizin/build-asan/../librz/bin/format/dex/dex.c in dex_resolve_proto_id
==2472491==ABORTING
```

**Comment by wargio** [comment]
attach the bin here so we can reproduce this.

**Comment by m4drat** [comment]
Crashing input: [crash-sydr_sydr-id_001842_sydr_id_004804_time_0_execs_0_orig_afl_s01-id_004493_sync_afl_main-worker_src_004120_+cov_1039_out_of_bounds_5.zip](https://github.com/rizinorg/rizin/files/9394097/crash-sydr_sydr-id_001842_sydr_id_004804_time_0_execs_0_orig_afl_s01-id_004493_sync_afl_main-worker_src_004120_%2Bcov_1039_out_of_bounds_5.zip)
