### ISSUE TITLE
Do not insert mouse codes as characters in `~...` mode

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2987]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS ARMv8
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/c89b12a04608809b498a44ba7da4cdb468d04a44

### Expected behavior

Ignore any mouse events in the `~...` mode

### Actual behavior

It inserts the escape characters as an input string instead.

### Steps to reproduce the behavior
- Open iTerm2
- `rizin /bin/ls`
- `izz~....`
- then click using mouse or touchpad
- instead of the ignoring the click in this mode, it inserts the sequence as string

Before the click:
<img width="647" alt="Screen Shot 2022-08-29 at 11 49 28" src="https://user-images.githubusercontent.com/203261/187119422-4a752665-ebf7-4901-bd90-3ec78269836f.png">

After the click:
<img width="363" alt="Screen Shot 2022-08-29 at 11 49 54" src="https://user-images.githubusercontent.com/203261/187119446-2f407e1e-742b-4150-aed0-bbe58b19089b.png">

**Comment by whol-hoopa** [comment]
I want to give this a try but I cannot find the function where it handles mouse inputs. Any ideas?

**Comment by ret2libc** [comment]
It doesn't happen to me on 366a7840f3ef80230159109b39c2f4fbf185d55e actually.

**Comment by XVilka** [comment]
@ret2libc does it happen for you on latest `dev`? Because it still does for me.

@whol-hoopa see code in:
- `librz/cons/grep.c`
- `librz/cons/hud.c`

**Comment by whol-hoopa** [comment]
I looked into it and followed it.

The "~..." stack
![image](https://user-images.githubusercontent.com/47489579/216800937-96540aef-3dde-4439-97b3-deca6cf9944c.png)

After 
ReadConsoleInputW
KERNELBASE!GetConsoleInput
KERNELBASE!ConsoleCallServerGeneric

There is the normal input that doesn't accept and mouse clicks.

The normal input stack 
![image](https://user-images.githubusercontent.com/47489579/216801109-da0b1d31-cae8-469a-9c39-490284be0617.png)

Both of these stacks are using the same function "rz_cons_0_5!rz_line_readline+0x9"

What's different from it calling from "rz_cons_hud" vs "rz_core_fgets"

**Comment by ret2libc** [comment]
@XVilka I confirm it does not happen to me.
