### ISSUE TITLE
Build `stable` rz-ghidra for `stable` rizin Docker

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#2995]
Currently it tries to take `dev` branch of rz-ghidra every time

See also https://github.com/rizinorg/rz-ghidra/issues/299

**Comment by ret2libc** [comment]
Yes the branches for the docker file should be changed as part of the release process on the stable branch. Not much to do though , i don't think an issue is necessary.

**Comment by XVilka** [comment]
@ret2libc I thought it was done automatically

**Comment by ret2libc** [comment]
It is not. How would you switch to stable only on stable branch?
