### ISSUE TITLE
Heap commands do not work well when using glibc 2.35

### ISSUE THREAD

**Issue by WingsZeng** [rizinorg/rizin#3053]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 @ linux-x86-64 commit: 69d7c7225a0734bce2b2a16d7ec8f2efa362de1d

### Actual behavior

most heap commands do not work well, such as:

'dmh':
```
[0x7ffa217f4992]> dmh
Arena @ 0x7ffa219004c0
Chunk(status=free,      addr=0x0, size=0xfffffffffffffff8, flags=NON_MAIN_ARENA,IS_MMAPPED,PREV_INUSE)[top][brk_start: 0x55cade4ce000, brk_end: 0x55cade4ef000]
[0x7ffa217f4992]> 
```

'dmha':
```
[0x7ffa217f4992]> dmha
Main arena  (addr=0x7ffa219004c0, lastRemainder=0x0, top=0x0, next=0x0, free)
Thread arena(addr=0x0, lastRemainder=0xffffffffffffffff, top=0xffffffffffffffff, next=0xffffffffffffffff)
Thread arena(addr=0xffffffffffffffff, lastRemainder=0x55f339523c45, top=0x50, next=0x7fcbcc06e210)
[0x7ffa217f4992]> 
```

**Comment by XVilka** [comment]
@WingsZeng could you please retry with the latest `dev`? I believe, it should be fixed.

**Comment by WingsZeng** [comment]
> @WingsZeng could you please retry with the latest `dev`? I believe, it should be fixed.

yes, it has been fixed. Thank you!
