### ISSUE TITLE
Support MachO chained fixups (binaries compiled with XCode >= 13)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3091]
> All programs and dylibs built with a deployment target of macOS 12 or iOS 15 or later now use the chained fixups format. This uses different load commands and LINKEDIT data, and won’t run or load on older OS versions. (49851380)

https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes

**Comment by thestr4ng3r** [comment]
Chained fixups overall are supported, but the `DYLD_CHAINED_PTR_64` type is not yet.
