### ISSUE TITLE
Support loading Unicode and emoji variable, constants, and function names from DWARF, PDB debug information.

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3196]
C23 standard adopted Unicode names officially: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2836.pdf

Upcoming GCC 13 release will support them: https://gcc.gnu.org/gcc-13/changes.html
LLVM/Clang 15 should already support them.

We already support this in some cases but not all, AFAIK, nor it's really tested.

We should compile test files with variables, contants, and function names in these and test loading from both DWARF and PDB files.

See also https://github.com/tree-sitter/tree-sitter-c/pull/127

Test file with C code with math profile Unicode symbols: [3196.zip](https://github.com/rizinorg/rizin/files/12023518/3196.zip)

**Comment by XVilka** [comment]
LLVM 16.0.0 was released supporting math profile: https://www.unicode.org/L2/L2022/22230-math-profile.pdf

**Comment by b1llow** [comment]
DWARF already loads unicode characters correctly.

<img width="562" alt="image" src="https://github.com/rizinorg/rizin/assets/24983369/75adcd9b-bba3-4c02-b435-54eacbe64716">

<img width="560" alt="image" src="https://github.com/rizinorg/rizin/assets/24983369/fda4334d-88b6-4946-92ef-3dc1a13ad845">

**Comment by XVilka** [comment]
@imbillow cool, please add a test then and we can close this one.

**Comment by XVilka** [comment]
@imbillow could you please add a test for this one? So we can close it.

**Comment by XVilka** [comment]
@imbillow on some Linux runners the order of the test is slightly different:
```
[XX] 635 ms   db/cmd/dwarf "DWARF with unicode"
RZ_NOPLUGINS=1 /home/travis/build/rizinorg/rizin/install/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -qc 'id~DW_AT_name
avgl
' bins/dwarf/demo_utf8
-- stdout
--- expected
+++ actual

@@ -16,11 +16,11 @@
 	DW_AT_name [DW_FORM_string]	: gv2
 	DW_AT_name [DW_FORM_strp]	: (.debug_str+0xa): main
 global int 👊 @ 0x2003c /tmp/lima/demo_utf8.c:85
+global int 🚀 @ 0x20040 /tmp/lima/demo_utf8.c:115
+global int 😀 @ 0x20044 /tmp/lima/demo_utf8.c:145
+global int 💀 @ 0x20038 /tmp/lima/demo_utf8.c:55
+global const int À @ 0x738 /tmp/lima/demo_utf8.c:1711
+global const int À @ 0x734 /tmp/lima/demo_utf8.c:1611
+global const int gv1 @ 0x73c /tmp/lima/demo_utf8.c:1811
 global int 🕐 @ 0x20034 /tmp/lima/demo_utf8.c:25
-global int 💀 @ 0x20038 /tmp/lima/demo_utf8.c:55
-global const int À @ 0x734 /tmp/lima/demo_utf8.c:1611
-global const int À @ 0x738 /tmp/lima/demo_utf8.c:1711
-global int 😀 @ 0x20044 /tmp/lima/demo_utf8.c:145
-global int 🚀 @ 0x20040 /tmp/lima/demo_utf8.c:115
-global const int gv1 @ 0x73c /tmp/lima/demo_utf8.c:1811
 global const int gv2 @ 0x740 /tmp/lima/demo_utf8.c:1911
```

**Comment by b1llow** [comment]
@XVilka

I feel like I could remove avgl from this test, or change the code so that the avgl output is sorted by address, or does rizin have a magic trick like the ~ command to make the output sorted a certain way?

**Comment by XVilka** [comment]
> @XVilka
> 
> I feel like I could remove avgl from this test, or change the code so that the avgl output is sorted by address, or does rizin have a magic trick like the ~ command to make the output sorted a certain way?

Yep, that would work, see `~?`, e.g. `~$[column]`

**Comment by XVilka** [comment]
@imbillow I thought about it, and I think sorting global variables in `avgl` output by the address out of the box is the best solution.
