### ISSUE TITLE
Rizin's grep should be case-insensitive by default

### ISSUE THREAD

**Issue by kazarmy** [rizinorg/rizin#3240]
**Is your feature request related to a problem? Please describe.**

Currently

```
[0x00000000]> el~RZIL
[0x00000000]>
```

```
[0x00000000]> el~rzil
rzil.step.events.read: enables/disables printing aezse read event
rzil.step.events.write: enables/disables printing aezse write event
[0x00000000]>
```

```
[0x00000000]> el~RzIL
          asm.cmt.il: Show RzIL expressions as comments
[0x00000000]>
```

This seems like a sad state of affairs.

**Describe the solution you'd like**

Rizin's grep (`~`) should be case-insensitive by default so that `el~rzil` gives me:

```
[0x00000000]> el~rzil
          asm.cmt.il: Show RzIL expressions as comments
rzil.step.events.read: enables/disables printing aezse read event
rzil.step.events.write: enables/disables printing aezse write event
[0x00000000]>
```

**Describe alternatives you've considered**

A new config var, say `search.case_sensitive` as suggested by #594, could be implemented and set to true by default.

I'm aware that `el~+rzil` will get me what I want but it's not obvious that I need to add the `+`, since I don't know what the output should be when I do `el~rzil`. 

**Additional context**

VSCode, Emacs and Google Search (https://www.google.com) all have case-insensitive search by default.

More generally, it's easier to realize that a search should be narrowed (because it's obvious from the search results), than to realize that it should be widened (is the searched item truly not found or is it because the search is not wide enough?).

**Comment by ret2libc** [comment]
I agree! 👍

**Comment by wargio** [comment]
agreed
