### ISSUE TITLE
Support of the basic ARMv8 NEON instructions with RZIL 

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3282]
After [Float and FBasic RZIL support](https://github.com/rizinorg/rizin/pull/3184) is merged, implement uplifting of the basic NEON instructions for ARMv8, to allow testing.

See attached test files:
```c
#include <stdio.h>

int main(int argc, char **argv) {
	float a, b;
	a = 5.4;
	b = 0.000008;
	double c = a - b + a * b;
	printf("a = %f b = %f c = %e\n", a, b, c);
	return 0;
}
```
Emulated with RZIL it should produce these values:
```
a = 5.400000 b = 0.000008 c = 5.400035e+00
```

[float_ex1.zip](https://github.com/rizinorg/rizin/files/10379333/float_ex1.zip)

**Comment by Heersin** [comment]
Got it, will work on it from this weekend.

**Comment by XVilka** [comment]
@Heersin hi, have you had any luck with those?

**Comment by Heersin** [comment]
> @Heersin hi, have you had any luck with those?

Hi @XVilka Anton, I have lifted vmov and vldr/vstr, logical and compare instructions
working on vldn/vstn now.

Should I send a WIP pr for early review ?

**Comment by XVilka** [comment]
> Should I send a WIP pr for early review ?

Yes, please do. It will help also @brightprogrammer and @imbillow since both MIPS and Tricore have FPU instructions.

**Comment by XVilka** [comment]
Only missing things now are instruction-level tests, just like for other RzIL instructions.
