### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [rizinorg/rizin#3293]
Would you like to add more error handling for return values from functions like the following?
* [fputs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream") ⇒ [lang_c_run](https://github.com/rizinorg/rizin/blob/2987e035da827903329ec6433410899b985e2434/librz/lang/p/c.c#L102)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [mpc_input_new_string](https://github.com/rizinorg/rizin/blob/f3a4200c4e704866d68f084f42524170a525776a/subprojects/mpc/mpc.c#L103)
* [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [rz_th_lock_new](https://github.com/rizinorg/rizin/blob/a988941bf2ac14fe926d2fdc6bee661a62ef8ade/librz/util/thread_lock.c#L8)

**Comment by XVilka** [comment]
@elfring MPC is a third-party code, and you need to open an issue in https://github.com/orangeduck/mpc. Two others are ours.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by thestr4ng3r** [comment]
reporter is a bot

**Comment by elfring** [comment]
I am not a “bot”.

:thought_balloon: It seems to be more convenient for some contributors to think in such a direction.

-----

:thinking: It is just safer to [handle also “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?
