### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [rizinorg/rizin#3294]
I would like to point out that identifiers like “[`__read`](https://github.com/rizinorg/rizin/blob/cad4e0ae0f967f325bfb2da25d18f1d3ddff2966/librz/io/p/io_fd.c#L37 "Update candidate")” and “[`__write`](https://github.com/rizinorg/rizin/blob/45796515509a056e991b41d9626a511624ab9b3f/librz/io/p/io_srec.c#L48 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by XVilka** [comment]
@elfring good point. Could you please send a PR fixing those names? `srec_write()`, `srec_read()`, and other `__<function>`s?

**Comment by thestr4ng3r** [comment]
reporter is a bot

**Comment by elfring** [comment]
I am not a “bot”.

:thought_balloon: It seems to be more convenient for some contributors to think in such a direction.

-----

:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
