### ISSUE TITLE
Command 'iAj' causes crash and command 'iA' incorrect for arm arch

### ISSUE THREAD

**Issue by altaic** [rizinorg/rizin#3363]
**Environment information**
* Operating System: macOS 12.4
* Cutter version: 2.0.5
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: arm binary (GD32F307 microcontroller)

**Describe the bug**

After loading an arm binary (setting analysis disabled, the architecture='arm', bits=16, endianness='little', kernel='none') and opening the console, entering the command `iAj` causes cutter to crash. Furthermore, `iA` outputs:

```
offset     size   arch      machine 
------------------------------------
0x00000000 164836 (null)_64  
```

I imagine the arch should be 'arm_64' or some such, not '(null)_64'.

**Comment by ret2libc** [comment]
@altaic are you able to download/test https://github.com/rizinorg/cutter/suites/6895909402/artifacts/267486351 ?

**Comment by XVilka** [comment]
I cannot reproduce on either `dev` or `stable` (using the ELF files)

**Comment by thestr4ng3r** [comment]
Can be reproduced with a raw binary blob, rather than e.g. an elf

**Comment by altaic** [comment]
@thestr4ng3r Yes, I was using a raw binary (as I noted for a GD32F307 microcontroller).

**Comment by XVilka** [comment]
```
rizin =
 -- Use 'e asm.offset=true' to show offsets in 16bit segment addressing mode.
[0x00000000]> iA
offset     size arch      machine
----------------------------------
0x00000000 512  (null)_64
[0x00000000]> iAj
WARNING: pj_ks: assertion 'j && k && v' failed (line 171)
zsh: segmentation fault  rizin =
```
