### ISSUE TITLE
Language should be inferred before demangling the symbols

### ISSUE THREAD

**Issue by DMaroo** [rizinorg/rizin#3404]
Currently, the demangling happens in the

```c
RzList /*<RzBinSymbol *>*/ *symbols(RzBinFile *bf)
```

function, which has to be implemented for every executable format by its plugin. The interface can be found at

https://github.com/rizinorg/rizin/blob/f4e15d232a407a72ff8d393f22ff06daf4205c6c/librz/include/rz_bin.h#L531

It is invoked in `rz_bin_object_set_items` as following

https://github.com/rizinorg/rizin/blob/f4e15d232a407a72ff8d393f22ff06daf4205c6c/librz/bin/bobj.c#L455

The invocation of `symbols` happens before the invocation of `rz_bin_language_detect`

https://github.com/rizinorg/rizin/blob/f4e15d232a407a72ff8d393f22ff06daf4205c6c/librz/bin/bobj.c#L527

This implies that `symbols` tries to guess the language for every single symbol instead of using the language detected in `rz_bin_language_detect`. This language is then used to resolve the demangler and demangle the symbol. As expected, the guesses can be incorrect and hence many symbols don't even get demangled by the correct demangler (the one associated with the executable's language).

The solution to this is not just to put the `rz_bin_language_detect` before the `symbols` function is called. This is because `rz_bin_language_detect` uses the symbols in the binfile (`binfile->o->symbols`) to deduce the language of the executable. And the symbols list is empty until the `symbols` function gets executed, which populates the list.

One way would be to populate the symbols list, but not demangle it yet. Then detect the language. Once we know the language, we can now demangle the symbols, without guessing the language for every symbol. This would require us to implement two functions (on which populates, other which demangles) for all the executable plugins (not so good).

I would like to hear about any neater and less disruptive solutions.

**Comment by XVilka** [comment]
> One way would be to populate the symbols list, but not demangle it yet. Then detect the language. Once we know the language, we can now demangle the symbols, without guessing the language for every symbol. This would require us to implement two functions (on which populates, other which demangles) for all the executable plugins (not so good).

This looks like a good way forward. @wargio what do you think?

**Comment by wargio** [comment]
i partially agree on that.
What it depends on also is that the bin itself could also infer a language prior to detect it.

**Comment by DMaroo** [comment]
> What it depends on also is that the bin itself could also infer a language prior to detect it.

If the language is detected at any point in `rz_bin_language_detect`, it just returns there, not running the rest of the code.

I think, for now, going forward with a separate symbol population function and a separate demangler function seems to be a good idea. The `RzBinPlugin` interface is already cluttered enough and one extra function pointer won't hurt.

**Comment by wargio** [comment]
i fully agree on this.

**Comment by XVilka** [comment]
It's necessary for the Rust demangling to properly work in Rizin: https://github.com/rizinorg/rz-libdemangle/issues/30

**Comment by Akhilesh9148** [comment]
I want to work on this issues please assign me this issue

**Comment by wargio** [comment]
done

**Comment by wargio** [comment]
I'm taking over this.
