### ISSUE TITLE
db/archos/linux-x64/dbg_fds dbg.fds.count test intermittent failure

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3409]
It often fails from time to time, and often disappears after the restart, but the failure value is always the same - 6, while expected is 3.

We should investigate the possible reason and make it more reliable

```
[XX] db/archos/linux-x64/dbg_fds dbg.fds.count
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -d -Qc 'ddl~?
' bins/elf/analysis/elf-nx
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-3
+6

-- stderr
Process with PID 19760 started...
glibc.fc_offset = 0x00148
```

**Comment by iiiuwioajdks** [comment]
Hi, I'm new to rizin and I want to know exactly how to reproduce this error so that I can try to solve it @XVilka

**Comment by Priyanshuraturi28** [comment]
have you solved it ?

**Comment by XVilka** [comment]
@Busteinjieber no, go ahead if you want
