### ISSUE TITLE
Convert `RzBitmap` to `RzBitvector`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3429]
Since most of the things between two are duplicated, we have two choices:
- Simply substitute all `RzBitmap` uses with `RzBitvector` and remove it completely
- Make `RzBitmap` a thin wrapper/macroses around `RzBitvector` to preserve the abstraction but remove code duplication.

**Comment by syd-faiz** [comment]
I noticed there is an open issue regarding [insert issue description here]. I would like to contribute to this project and I am interested in working on this issue. Could you please assign this issue to me? I am excited to collaborate with you and contribute to the development of this project.

Thank you for your time and consideration.

Best regards,

**Comment by ghost** [comment]
I noticed there is an open issue regarding #3429. I would like to contribute to this project and I am interested in working on this issue. Could you please assign this issue to me? I am excited to collaborate with you and contribute to the development of this project.

Thank you for your time and consideration.

**Comment by XVilka** [comment]
@syd-faiz we cannot assign non-members of the project due to GitHub restrictions, but sure, go ahead. See the following files:
- `librz/util/bitvector.c`
- `librz/util/bitmap.c`
- `librz/include/rz_util/rz_bitvector.h`
- `librz/include/rz_util/rz_bitmap.h`

**Comment by iiiuwioajdks** [comment]
Hello, I am a newcomer who wants to participate in this gsoc. I contributed a pr in the community. Can you please review it for me, thank you for your time: https://github.com/rizinorg/rizin/pull/3433

**Comment by XVilka** [comment]
Fixed by https://github.com/rizinorg/rizin/commit/0e1bbd28f8e62e63bea081a00d72cb8b6a3155e0
