### ISSUE TITLE
Improve `cmd_math` help and details and update The Rizin Book with new `cmd_math` commands

### ISSUE THREAD

**Issue by brightprogrammer** [rizinorg/rizin#3440]
PR #3421 ported `cmd_help` commands to RzShell and changed the `?` symbol used for math operations to `%` to remove ambiguity between real help commands like `a?` or `d?` and math commands like `?a` or `?h` etc...
- The PR has some issues with it's command's help messages and more detailing needs to be done.
- The PR also didn't update The Official Rizin Book with new command's information. 

This issue is to address these changes and problems.

**Comment by XVilka** [comment]
Closed by https://github.com/rizinorg/rizin/commit/9ab709bc34843f04ffde3b63322c809596123e77
