### ISSUE TITLE
rz-gg: sflib incorrect argument constraints on linux i386

### ISSUE THREAD

**Issue by giladreti** [rizinorg/rizin#3476]
*note: this issue cannot be reproduced before #3475 is merged as rz-gg just doesn't work without it.*

it seems like shellforge had a regression in i386 binary generation when calling syscalls.
the problem was introduced in rizin in PR #2428 which updated the autogenerated sflib. as can be seen, the argument constaints of the syscall wrappers changed from `r` (general purpose register) to `g` (which allows memory locations too). this can cause problems as the syscall functions save `ebx` on the stack which moves `esp` without the compiler knowledege which can make it reference stack saved arguments wrongly.
i opened a PR to shellforge4 at https://github.com/whatsbcn/shellforge4/pull/7. when it is fixed, i think it should suffice to regenerate sflib and update rizin's sflib.

### Expected behavior
when compiling
```c
int log(char *s, int l) {
  write(2, s, l);
}

int main() {
  log("hello", sizeof("hello"));
  log(" ", sizeof(" "));
  log("world!", sizeof("world!"));
  exit(0);
}
```
via `rz-gg -b 32 -a x86 -F -O test.c` and running `./test` `hello world!` should be printed

### Actual behavior

`hello` is printed.

**Comment by ret2libc** [comment]
Nice, thanks!

**Comment by giladreti** [comment]
I am not sure if shellforge4 is still maintained as the last issue closed was 3 years ago (and the last commit 5 years ago) and it's seems like the owner haven't had any GitHub activity in the past year. 
Is forking it under rizinorg an option?

**Comment by XVilka** [comment]
No objections on keeping a fork under rizinorg in this case. If someone picks up the project later, we can always switch/synchronize.

**Comment by ret2libc** [comment]
Ok with it 👍

**Comment by wargio** [comment]
same

**Comment by XVilka** [comment]
@giladreti done: https://github.com/rizinorg/shellforge4

**Comment by giladreti** [comment]
thanks!
i opened a PR https://github.com/rizinorg/shellforge4/pull/1
