### ISSUE TITLE
Auto-add prefixes to symbol names

### ISSUE THREAD

**Issue by kazarmy** [rizinorg/rizin#3493]
**Is your feature request related to a problem? Please describe.**

Consider the following command sequence:

![auto-add-prefix-1](https://user-images.githubusercontent.com/12002672/235348666-d605e499-84e9-426f-91bd-832ec5f364c9.PNG)

Now I want to seek to `func_X`:

![auto-add-prefix-2](https://user-images.githubusercontent.com/12002672/235348730-4c500852-8446-45f0-9f11-26edbac277d4.PNG)

Ok...

![auto-add-prefix-3](https://user-images.githubusercontent.com/12002672/235348858-50c97856-bdce-41a2-a692-421c1ba6d802.PNG)

Eh?! (The actual flag name is:)

![auto-add-prefix-4](https://user-images.githubusercontent.com/12002672/235348882-fc90eca5-bbb2-4a08-a12a-453a6fd4b5e1.PNG)

This feels like a somewhat sad state of affairs.

**Describe the solution you'd like**

If _symbolName_ (defined by `is`) is an unknown address, the following prefixes should be tried, in order:

1. `sym.`
2. `loc.`
3. `obj.`
4. ~~`reloc.`~~

**Describe alternatives you've considered**

Adding flags that directly correspond to the symbol names in `is` would clutter up the flag list even more.

**Comment by ret2libc** [comment]
Definitely, I like it.

**Comment by kazarmy** [comment]
I'm skipping `reloc.` because the corresponding symbols don't appear in `is`.

**Comment by kazarmy** [comment]
Closing due to proposal in https://github.com/rizinorg/rizin/pull/3494#issuecomment-1531570578.
