### ISSUE TITLE
ARMv7 MSR instruction cannot be disassembled

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3505]
`rz-asm -d -a arm -b 16 83f31188` should return `msr basepri, r3`, currently it's `invalid`

Likely should be resolved with capstone auto-sync and update

**Comment by Rot127** [comment]
@XVilka Did you really meant `arm` there?

Because Capstone does this:

**ARM**

```
./cstool -d arm 83f31188
 0  83 f3 11 88  ldmdahi	r1, {r0, r1, r7, r8, r9, r12, sp, lr, pc}
```

**Thumb + mclass**

```
./cstool -d cortexm 83f31188
 0  83 f3 11 88  msr	basepri, r3
```

And `llvm-objdump` does the same:

**ARM**

```
./bin/llvm-objdump --print-imm-hex -d --disassemble-symbols=_start --triple=arm arm.bin 

arm.bin:	file format elf32-littlearm

Disassembly of section .text:

00008150 <_start>:
    8150: 8811f383     	ldmdahi	r1, {r0, r1, r7, r8, r9, r12, sp, lr, pc}
```

**Thumbv7m**
```
./bin/llvm-objdump -d --disassemble-symbols=_start --triple=thumbv7m arm-thumb.bin 

arm-thumb.bin:	file format elf32-littlearm

Disassembly of section .text:

000003fc <_start>:
     3fc: f383 8811    	msr	basepri, r3

```

**Comment by XVilka** [comment]
@Rot127 not sure I understand your question. Yes, it's ARMv7, Cortex-M profile, Thumb.

**Comment by Rot127** [comment]
The cortex processor needs to be set (note the `-c cortex`), otherwise it defaults to `cpu = v8`:

```
./build/binrz/rz-asm/rz-asm -d -a arm -c cortex -b 16 83f31188
msr basepri, r3
```

vs.

```
./build/binrz/rz-asm/rz-asm -d -a arm -b 16 83f31188
invalid
```

This also works for me with the current `dev` branch (so Capstone v4).

**Comment by XVilka** [comment]
@Rot127 it's interesting, that originally I met this problem in the ELF file - FreeRTOS image for Cortex-M. Thus, I suppose the problem is that RzBin/ELF didn't set the right CPU model.

**Comment by Rot127** [comment]
Mh, weird. Do you have a link to the binary?

**Comment by XVilka** [comment]
@Rot127 I cannot share it. I will try to make an artificial example.

**Comment by Rot127** [comment]
closed with https://github.com/rizinorg/rizin/pull/3674
