### ISSUE TITLE
`cmd~word?` should return an error (right syntax is `cmd~?word`)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#352]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            |  x86/32
| rizin -v full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/4e38b5aba863ed4d7d0f815bd8b48f5394ae9d53

### Expected behavior

Some kind of error should be shown if 

### Actual behavior

It tries to count something and shows the wrong result instead.

### Steps to reproduce the behavior 
```
$ rizin test/pe/flare_notepad.ex
[0x01013a00]> e analysis.bb.maxsize=2048
[0x01013a00]> aaa
[0x01013a00]> pdf~ret
╰           0x01013f1b      ret
[0x01013a00]> pdf~ret?
3
[0x01013a00]> pdf~?ret
1
```

**Comment by ret2libc** [comment]
I cannot reproduce:
```
$ ./build-dev/binrz/rizin/rizin ./test/bins/pe/flare_notepad.ex 
 -- Emulate the base address of a file with e file.baddr.
[0x01013a00]> e analysis.bb.maxsize=2048
[0x01013a00]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x01013a00]> pdf~ret
└           0x01013f1b      ret
[0x01013a00]> pdf~ret?
1
[0x01013a00]> pdf~?ret
1
^D
$ ./build-dev/binrz/rizin/rizin -v
rizin 0.1.0-git 26592 @ linux-x86-64 git.4.4.0-1350-g4e38b5aba
commit: 4e38b5aba863ed4d7d0f815bd8b48f5394ae9d53 build: 2021-01-13__09:39:23
```

**Comment by XVilka** [comment]
Oh, looks like it happens only because of https://github.com/rizinorg/rizin/pull/351/files#diff-e5fc91db395b03c4d8f7cd9482f62f84a4797fd2d9859973b0960d442a171ba3
A bug in `rz_str_ncpy()` I guess?
