### ISSUE TITLE
deb package for ubuntu doesn't work

### ISSUE THREAD

**Issue by dgutson** [rizinorg/rizin#3525]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Ubuntu x86 22.04.2 LTS
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| `rizin -v` full output, **not truncated** (mandatory)  | N/A

### Expected behavior

`sudo dpkg -i rizin_0.5.1-2_amd64.deb` just works

### Actual behavior

```
Unpacking rizin (0.5.1-2) ...
dpkg: dependency problems prevent configuration of rizin:
 rizin depends on librizin-common (>= 0.5.1-2); however:
  Package librizin-common is not installed.

dpkg: error processing package rizin (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 rizin
```

I obtained it from https://software.opensuse.org/download/package?package=rizin&project=home%3ARizinOrg which is the link that ends up after clicking the INSTALL button in the official page.

**Comment by XVilka** [comment]
Also we need to push 0.5.2 release to the OBS.

**Comment by ret2libc** [comment]
You should not download the single packages but follow the instructions from our rizin.re site, which explains how to add an apt repository to your system. After that, you can just do apt install rizin and it will download and install all necessary packages.

**Comment by dgutson** [comment]
@ret2libc thanks, that worked, but please keep in mind that the other method is listed also in the official page, and it is broken:
![image](https://github.com/rizinorg/rizin/assets/9671770/c169c024-6c0a-4f2c-b74b-b190f8975b8b)

So thanks again for you help (it it worked), this ticket is about either removing the other option or fixing it.

**Comment by ret2libc** [comment]
> @ret2libc thanks, that worked, but please keep in mind that the other method is listed also in the official page, and it is broken

Good point! I never tried that myself and I thought it allowed you to download all packages. I see two options:
1) easier, faster: just update the doc/webpage to explicitly as to use the repository
2) create a single rizin package instead of splitting it into multiple ones, trying to follow "best practices".

Probably 1) is better.

I'm not aware of a way to remove the "Grab binary packages directly" option.

**Comment by dgutson** [comment]
I don't know the answer, everything I know is the many hours googling how to get (and the appropriate version) librizin-common, and I'd like to avoid such a waist to other people. The only distro that worked out-of-the-box was Kali Linux, but making it work in python-slim image is a PITA.

**Comment by ret2libc** [comment]
Sure, we would like to avoid people's waisting time too :) We'll find a solution to this, thanks for reporting the problem.

**Comment by ret2libc** [comment]
This can be closed, the website has been updated.
