### ISSUE TITLE
Add Kali Linux to the distros

### ISSUE THREAD

**Issue by dgutson** [rizinorg/rizin#3546]
Kali Linux has rizin available in their package repositories, you may want to add it to the list of distros.

**Comment by XVilka** [comment]
It's outdated one, so probably better not to advertise:
<img width="999" alt="Screenshot 2023-06-02 at 11 22 13" src="https://github.com/rizinorg/rizin/assets/203261/06dcc94d-2b02-45e4-8fba-477c8b862f2a">

**Comment by dgutson** [comment]
Interesting, how did you get that report?
 I will file them an issue to update to latest version.

**Comment by XVilka** [comment]
@dgutson see these:
- https://repology.org/project/rizin/versions
- https://repology.org/project/cutter-re/versions

**Comment by dgutson** [comment]
Thanks.

Reported here: https://bugs.kali.org/view.php?id=8341

**Comment by XVilka** [comment]
Kali updated Rizin and Cutter btw.

**Comment by XVilka** [comment]
@dgutson could you please ping them again for 0.6.1 release?

**Comment by dgutson** [comment]
@XVilka i think you guys have to develop some sort of official broadcast to the distros, from maintainers to maintainers. I can (though I stopped using Kali), but a simple user shouldn't be the communication channel.

Thanks anyway for pinging me. Feel free to close this issue.

**Comment by XVilka** [comment]
Good point. Thank you!
