### ISSUE TITLE
Support for MD2 hashing function

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3582]
Despite being outdated for a long time, it's still possible to see it used in some old binaries and firmwares. OpenSSL can't be used for it since it is deprecated and will be removed relatively soon. It has to be implemented independently.

See `phl` command and these files:
- `librz/hash/p/*`
- `librz/hash/algorithms/*`

**Comment by rockrid3r** [comment]
Hi. I am gonna do it. Already started.
