### ISSUE TITLE
API and command (or output in `-v`) for channel (`dev` or `stable`, or `release`)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3608]
- [ ] Provide API, similar to `rz_version_*()` to return the channel: `dev`, `stable`, `release`, or something else
- [ ] Add it in the output of `-v` 

It's necessary for https://github.com/rizinorg/rz-pm/issues/26

**Comment by ret2libc** [comment]
I'm not sure it's fully necessary.

`rizin -v` already has a `commit` displayed if rizin was compiled from git.
We could show it in `rizin -H` as well and use it to determine if dev or not.

**Comment by XVilka** [comment]
What if Rizin was compiled from git but `stable` branch? Or some feature branch like capstone-ng? I think update channels are useful abstraction.

**Comment by ret2libc** [comment]
Does it matter? I was thinking that if rizin is dev, then rz-pm should use `main` rz-pm-db branch, otherwise it should stick to the released version. Plugins compiled for 0.5.0 should be compatible with all 0.5.0 versions of rizin and so on.

**Comment by XVilka** [comment]
@ret2libc difference between `dev` and `stable` is huge, it will allow us to provide different updates for plugins too - not only for Rizin, but also for e.g. `rz-ghidra` if there is a fix necessary for the `0.5.x` series.

**Comment by ret2libc** [comment]
Yes ofc dev vs stable is huge. What I'm saying is that I'm not sure we want to distinguish between stable and e.g. 0.5.x . If there is a fix in rz-ghidra for 0.5.x series it should work without any change at all to all rizin 0.5.x versions.

So it should be enough to know that the version of rizin is 0.5.x.

**Comment by XVilka** [comment]
Feel free to close if you think it's unnecessary. It might be more helpful for displaying Cutter version too though
