### ISSUE TITLE
Create global variables from debug information (DWARF, PDB, etc)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3625]
Now that we removed typelinks and added types propagation from the global variables (see `aat` and `avg` commands), they also should be created when the information is available in DWARF, PDB, and any other debug info information format.
- [x] DWARF
- [x] PDB

**Comment by gogo2464** [comment]
I got a lot of bugs using pdb:


:> e pdb.autoload=true
:> dc
(24368) loading library at 0x00007FFF73E10000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF70680000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF73EA0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF67FE0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF741C0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF470F0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF716D0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF72C30000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF71590000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF71B10000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF72210000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF71C20000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF73900000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF71BE0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF709A0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF67FA0000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF72240000 (C) C
ERROR: Couldn't open bin for file 'C'
(24368) loading library at 0x00007FFF71B00000 (C) C
ERROR: Couldn't open bin for file 'C'
(


is iyt my bad or is it fixed please?

**Comment by b1llow** [comment]
> I got a lot of bugs using pdb:
> 
> :> e pdb.autoload=true :> dc (24368) loading library at 0x00007FFF73E10000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF70680000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF73EA0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF67FE0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF741C0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF470F0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF716D0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF72C30000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF71590000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF71B10000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF72210000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF71C20000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF73900000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF71BE0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF709A0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF67FA0000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF72240000 (C) C ERROR: Couldn't open bin for file 'C' (24368) loading library at 0x00007FFF71B00000 (C) C ERROR: Couldn't open bin for file 'C' (
> 
> is iyt my bad or is it fixed please?

Can you share this file so I can debug it easier?

**Comment by gogo2464** [comment]
My file is too big to upload it in github issue.

You can download it here: https://www.roblox.com/home

the file is then in "C:\Users\YOURUSERNAME\AppData\Local\Roblox\Versions\version-88cfc23f4e7d4e4b\RobloxPlayerBeta.exe".

**Comment by gogo2464** [comment]
@imbillow is it ok for you?

**Comment by b1llow** [comment]
`https://msdl.microsoft.com/download/symbols/RobloxPlayerBeta.pdb/1BA0718E8FE3E8DACED75863D664982D1/RobloxPlayerBeta.pdb`

rizin tried to download this file, but it's not on Microsoft's pdb server, maybe it's private? Then I realized that my rizin is clearly different from yours. @gogo2464 

```
RZ_CURL=1 rizin -e pdb.autoload=true ../RobloxPlayerBeta.exe 
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
 -- Enhance your graphs by increasing the size of the block and graph.depth eval variable.
[0x1458cc004]> idpd
Falling back to uncompressed pdb
Attempting to download uncompressed pdb in /home/hoshinoaya/.local/share/rizin/pdb/RobloxPlayerBeta.pdb/1BA0718E8FE3E8DACED75863D664982D1/RobloxPlayerBeta.pdb
ERROR: Error while downloading pdb file
PDB "RobloxPlayerBeta.pdb" download failed
```

**Comment by gogo2464** [comment]
I have not installed rizing from source YET!

I am going to.

**Comment by gogo2464** [comment]
.\OUT\bin\rizin.exe -e "pdb.autoload=true" -e "scr.color=3" -c "ood" -d C:\Users\USERNAME\AppData\Local\Roblox\Versions\version-88cfc23f4e7d4e4b\RobloxPlayerBeta.exe
Spawned new process with pid 2948, tid = 26056
WARNING: rz_list_get_tail_data: assertion 'list' failed (line 532)
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
(2948) loading library at 0x00007FFF74AB0000 (C) C
ERROR: Couldn't open bin for file 'C'
WARNING: rz_list_iter_get_data: assertion 'iter' failed (line 56)

==> Process finished

Spawned new process with pid 27012, tid = 30612
WARNING: rz_list_iter_get_data: assertion 'iter' failed (line 56)
WARNING: File dbg://C:\\Users\\USERNAME\\AppData\\Local\\Roblox\\Versions\\version-88cfc23f4e7d4e4b\\RobloxPlayerBeta.exe reopened in read-write mode
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x334e800) exeeds bin.maxstrbuf (0xa00000), skipping it.
WARNING: bin_file_strings: search interval size (0x1174000) exeeds bin.maxstrbuf (0xa00000), skipping it.
 -- You can redefine descriptive commands in the hud file and using the 'V_' command.

**Comment by gogo2464** [comment]
and still


:> dc
(28176) loading library at 0x00007FFF74AB0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF73290000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF724A0000 (C) C
ERROR: Couldn't open bin for file 'C'
ERROR: Cannot create flag "teb.23784" at 0xd0b5e9f000 because there is already "PRIVATE__..d0b5e9f000" flag
(28176) loading library at 0x00007FFED0960000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF730F0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF729C0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF730C0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF728A0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF729F0000 (C) C
ERROR: Couldn't open bin for file 'C'
(28176) loading library at 0x00007FFF723A0000 (C) C
ERROR: Couldn't open bin for file 'C'

**Comment by gogo2464** [comment]
@imbillow The issue probably arrived because I tried with r2 before. The pdb could have been already download and could not be erased.

**Comment by b1llow** [comment]
> @imbillow The issue probably arrived because I tried with r2 before. The pdb could have been already download and could not be erased.

This executable does some anti-debugging and is basically not a problem with the pdb module.

**Comment by gogo2464** [comment]
ok thanks for the PR!

**Comment by gogo2464** [comment]
> > @imbillow The issue probably arrived because I tried with r2 before. The pdb could have been already download and could not be erased.
> 
> This executable does some anti-debugging and is basically not a problem with the pdb module.

then why did rizin talk about the file 'C'? thiçs file does not exists.

**Comment by b1llow** [comment]
The dllname is taken from here, but I don't know much about windows APIs. @gogo2464 

https://github.com/rizinorg/rizin/blob/8fba9b41896b9d7ff3c2c4e8ad6808316daf59dc/librz/debug/p/native/windows/windows_debug.c#L720-L755

**Comment by gogo2464** [comment]
--edited-- I was wrong

try GetModuleFileNameExA instead of GetModuleFileNameExW because A means ascii and W means wide ascii. it is a custom windows charset. char pointers in C are ascii.

oh my bad everything is wide here


--end of edited--

Are you sure the issue is in this function? I could get a look.

**Comment by gogo2464** [comment]
oh my bad everything is wide here

**Comment by wargio** [comment]
@imbillow i think the issue is that the file name is in unicode/utf-16 that is why the error says `loading library at 0x00007FFF73290000 (C) C`  instead of `C:\\` etc..

**Comment by wargio** [comment]
Probably this `lib->Path` needs to be converted into utf-8

https://github.com/rizinorg/rizin/pull/4099/files#diff-c6718dd464e425f83c835c1116e74df235320f401164191baecc36a038a749b5R327-R328

**Comment by wargio** [comment]
@gogo2464 try this patch https://github.com/rizinorg/rizin/pull/4108

**Comment by gogo2464** [comment]
sure let me try!

**Comment by gogo2464** [comment]
no does not work https://github.com/rizinorg/rizin/pull/4108#issuecomment-1891759493

the pdb are not ptinted
