### ISSUE TITLE
??? not working in newshell

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#363]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| rizin -v full output, **not truncated** (mandatory)  | rizin 0.1.0-git 25890 @ linux-x86-64 git.0.1.0-git commit: ca5a1fb6a8512514969eb5b7d0630ed72c0409d5 build: 2021-01-14__23:25:25     

### Expected behavior
`???` should print proper help.

### Actual behavior
```
[0x00000000]> ???
DEBUG: s-expr (commands (arged_command command: (cmd_identifier)))
DEBUG: commands: 'pg'
DEBUG: commands with 1 childs
DEBUG: arged_command: 'pg'
DEBUG: arged_command command: 'pg'
DEBUG: s-expr (commands (help_command command: (cmd_identifier)))
DEBUG: commands: '???'
DEBUG: commands with 1 childs
DEBUG: help_command: '???'
Error while executing command: ???
```

**Comment by XVilka** [comment]
I propose to rename it to `m` as in `math`.

**Comment by ret2libc** [comment]
The thing is that there is not just math there... 
Things like:
```
| ?! [cmd]                         run cmd if $? == 0
```

Or:
```
| ?a                               show ascii table
```
Or:
```
| ?im message                      show message centered in screen
```

I don't know, it seems more like 'utility' (`u`)?
