### ISSUE TITLE
/wi doesn't work

### ISSUE THREAD

**Issue by imyxh** [rizinorg/rizin#3633]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x86-64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.2 @ linux-x86-64

### Expected behavior

`/wi` searches for wide string ignoring case

### Actual behavior

ERROR: core: Missing ' ' after /i

### Steps to reproduce the behavior

load any file and `/wi foo`

Sorry for the low-quality report; just noticed this while hacking around on my phone. I can try to look into it more later.

**Comment by imyxh** [comment]
Whoa, I always forget how fast y'all move here. Thanks so much!

**Comment by ret2libc** [comment]
It was an easy one tbh ;)
