### ISSUE TITLE
ESIL shifts by register ID not by register value.

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#3643]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | ARM
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ linux-x86-64 commit: 5cebf82f6cab1d4e6374693065fbc7a17c423657

### Expected behavior

ESIL is able to shift values by register.

e.g. the result should be this:
```bash
# 14460100 = andeq r4, r1, r4, lsl r6
./rz-asm -a arm -b 32 -E 0x14460100
zf,?{,r6,r4,<<,r1,&,0xffffffff,&,r4,=,}
```

### Actual behavior

```bash
# 14460100 = andeq r4, r1, r4, lsl r6
./rz-asm -a arm -b 32 -E 0x14460100
zf,?{,72,r4,<<,r1,&,0xffffffff,&,r4,=,}
```

`72` instead of `r6`.

### Steps to reproduce the behavior

Run the commands above.

### Additional Logs, screenshots, source code,  configuration dump, ...

This is fixed with https://github.com/rizinorg/rizin/pull/3591/commits/27ff2758e7669c3fe869d22daa1e74598b9b1f03.

But since shifts via register are anything but uncommon this implies that quite a lot of ESIL emulations are incorrect.

**Comment by Rot127** [comment]
cc @radare I got lost in radare's file tree. But this bug might effect you guys as well.

**Comment by wargio** [comment]
@trufae

**Comment by Rot127** [comment]
@trufae Also take a look at this instruction:

```
./cstool -d arm fc6e0300
 0  fc 6e 03 00  strdeq	r6, r7, [r3], -r12
	ID: 442 (strd)
	op_count: 3
		operands[0].type: REG = r6
		operands[0].access: READ
		operands[1].type: REG = r7
		operands[1].access: READ
		operands[2].type: MEM
			operands[2].mem.base: REG = r3
			operands[2].mem.index: REG = r12
			operands[2].mem.scale: 0
		operands[2].access: WRITE
		Subtracted: True
	Code condition: 0
	Write-back: True
	Post index: true
	Registers read: r6 r7 r3 r12
	Registers modified: r3
	Groups: IsARM 
```

In Rizin it currently produces:
```
rz-asm -a arm -b 32 -E 0xfc6e0300
zf,?{,r6,r3,0xffffffff,&,=[8],r7,4,r3,+,0xffffffff,&,=[8],ip,r3,+=,}
```

but it should be
```
zf,?{,r6,r3,0xffffffff,&,=[4],r7,4,r3,+,0xffffffff,&,=[4],ip,r3,-=,}
```

Difference:
- Should load 4 bytes instead of 8 (because it writes to a 4byte register).
- The writeback should subtract the `ip` register, not add it.

Fix: https://github.com/rizinorg/rizin/pull/3591/commits/a9e1eafaced0701559c3bed295a219df529667d1

**Comment by trufae** [comment]
Thanks for the headsup! fixed in r2 now

**Comment by Rot127** [comment]
Fixed with https://github.com/rizinorg/rizin/pull/3645
