### ISSUE TITLE
Some default panels broken

### ISSUE THREAD

**Issue by imyxh** [rizinorg/rizin#3647]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 6.4.1-arch2-1 x86_64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ linux-x86-64 (not printed: commit 83e40b0c0cc76fc344dd778ec89c5eb43a2eaa8a)

### Expected behavior

The default panels in visual panels mode should work.

### Actual behavior

"Stack" and any other panels using `px` commands are broken for some reason. The default command for "Stack" is `pxq 256@r:SP` which runs fine on its own but not in the panel. Changing the command (using the `"` key) to `pxq 256@r:SP` again makes the window say `pxq 256@r:SP (xc 256@r:SP)` which seems to work fine but also prints the results of `xc`, not `pxq`. Changing the command to `xc 256@r:SP` works as intended.

The "Registers" command is out of date and should be ``%== true `e cfg.debug`; %! dr; %% ar``. Changing it to this works fine.

### Steps to reproduce the behavior

Open anything with `-d` and check `V!`

### Additional Logs, screenshots, source code,  configuration dump, ...

![image](https://github.com/rizinorg/rizin/assets/12703838/5d5913f9-7b15-45e0-8adb-5a2daea2f6ea)

**Comment by imyxh** [comment]
I can submit a PR for the quick fix at https://github.com/imyxh/rizin/commit/755535fb95a43d062e2ddebb6a95bc8a2e4ba382 if you wish but it makes more sense to figure out what's going on with `px` first

**Comment by wargio** [comment]
could you test my fix?

**Comment by imyxh** [comment]
> could you test my fix?

Works fine for me! It's blank when not in debug mode whereas the old code did `ar` but I don't think it matters much. It's probably nicer to have the command shorter like this.

That being said, although changing the default panels fixes the issue at a glance (already did this in https://github.com/imyxh/rizin/commit/755535fb95a43d062e2ddebb6a95bc8a2e4ba382) I'm still worried about why `px` doesn't work and if that's pointing to some deeper problem.

**Comment by wargio** [comment]
the reason why it doesn't work using px is because the default output is `xc` not `px`.
All the panels should be ported to use the C code and many things should be removed from there.

**Comment by XVilka** [comment]
> the reason why it doesn't work using px is because the default output is `xc` not `px`. All the panels should be ported to use the C code and many things should be removed from there.

Right, a bunch of code can be shared between "classic" visual mode and panels: https://github.com/rizinorg/rizin/issues/384
