### ISSUE TITLE
Show original Unicode flag name in `pxa` and `pd` outputs when `e asm.flags.real` is set

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3677]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS ARM64
| File format of the file you reverse (mandatory)      | *
| Architecture/bits of the file (mandatory)            | *
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/f1006f97c24b9cd21fcc7d3faaaea8b6e0305857

### Expected behavior

Show the original flag name in `pxa` and `pd` outputs when `e asm.flags.real=true` is set

### Actual behavior

```
[0x00000672]> e asm.flags.real=true
[0x00000672]> sd +4
[0x00000676]> f "(🎈️)"
[0x00000676]> pd 4
│           ;-- _________:
│           0x00000676      06af           add   r7, var_40h
│           0x00000678      7860           str   r0, [r7, 4]           ; argc
│           0x0000067a      3960           str   r1, [r7]              ; argv
│           0x0000067c      4d4a           ldr   r2, [data.000007b4]   ; [0x7b4:4]=0x10926 ; "&\t\x01"
[0x00000676]> pxa 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
             /_________
0x00000676  06af 7860 3960 4d4a 7a44 4d4b d358 1b68  ..x`9`MJzDMK.X.h ; argc ; argv
[0x00000676]> fl.
0x00000676 1 _________
[0x00000676]> fl.j
[{"name":"_________","size":1,"offset":1654}]
```

Also, I am not sure `fl.j` doesn't show the real name of the flag

**Comment by ghost** [comment]
Kindly can you assign me this issue

**Comment by XVilka** [comment]
@ru-cpu go ahead

**Comment by PeiweiHu** [comment]
`f "(🎈️)"` is setting flag name, which doesn't accept Unicode by current design (librz/flag/flag.c:550). `real_name` can be set by `fN`.

```
[0x100003a74]> f flag_name
[0x100003a74]> pd 1
            ;-- flag_name:
            0x100003a74      stp   x24, x23, [sp, 0x20]
[0x100003a74]> fN flag_name "(🎈️)"
[0x100003a74]> pd 1
            ;-- (🎈️):
            0x100003a74      stp   x24, x23, [sp, 0x20]
[0x100003a74]> e asm.flags.real
false
[0x100003a74]> fl.
0x100003a74 1 flag_name
[0x100003a74]> fl.j
[{"name":"flag_name","realname":"(🎈\ufe0f)","size":1,"offset":4294982260}]
[0x100003a74]> e asm.flags.real=true
[0x100003a74]> fl.
0x100003a74 1 (🎈️)
[0x100003a74]>
```
