### ISSUE TITLE
Refactor all base type accesses to use the RzAnalysisBaseType API

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#368]
The `RzAnalysisBaseType` API designed in last year's gsoc is the only way that the base types should be accessed:
https://github.com/rizinorg/rizin/blob/486ed69698edfa0c2bd2446b4151026a1e7a129b/librz/include/rz_analysis.h#L2124-L2130

Currently there may be some accesses that still access the sdb directly and there are some other functions here:
https://github.com/rizinorg/rizin/blob/486ed69698edfa0c2bd2446b4151026a1e7a129b/librz/include/rz_util/rz_ctypes.h#L21-L34
All such cases shall be refactored to use only the new api above to completely abstract them away from sdb.

As explained in the end of the description in #369, it might be helpful to do this partially in parallel with it.

**Comment by XVilka** [comment]
I think this one can be closed, since all `sdb_types` accesses are already isolated in `RzTypes` and now are part of the https://github.com/rizinorg/rizin/issues/371 and https://github.com/rizinorg/rizin/issues/275
