### ISSUE TITLE
Switch case on ARM64 not identified

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#3689]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 13.4.1 M1 Max
| File format of the file you reverse (mandatory)      | Mach0
| Architecture/bits of the file (mandatory)            | arm/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ darwin-arm-64 commit: 9c1b88903e4f0e3df2ed8145e619f1e4c208baff

### Expected behavior
From r2:
![image](https://github.com/rizinorg/rizin/assets/562321/42c2e345-ac30-44ce-9e7e-b1fa409af05f)

### Actual behavior
![image](https://github.com/rizinorg/rizin/assets/562321/466737e6-2ef9-4cf8-8984-7eec83ffa964)

### Steps to reproduce the behavior
```
$ rizin -NNA /bin/ls
> VVp
```

### Additional Logs, screenshots, source code,  configuration dump, ...
- [/bin/ls](https://github.com/rizinorg/rizin/files/12143988/ls.zip)

**Comment by XVilka** [comment]
@ret2libc try updating Rizin - commit you mentioned didn't update Capstone to the latest yet.

**Comment by ret2libc** [comment]
Same with rizin 0.6.0 @ darwin-arm-64
commit: ba84a920ad1ac5fdbf73f1729054f946284a362d

**Comment by XVilka** [comment]
Then it boils down on importing some commits for `librz/analysis/jmptbl.c`

**Comment by ret2libc** [comment]
This was fixed!
