### ISSUE TITLE
Bundle all types functionality in a new module RzTypes

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#369]
Currently, types code is somewhat scattered throughout the codebase.

For base types, the database of base types is here in RzAnalyis:
https://github.com/rizinorg/rizin/blob/486ed69698edfa0c2bd2446b4151026a1e7a129b/librz/include/rz_analysis.h#L645
Along with the new `RzAnalysisBaseType` API.

Then there is also some stuff in util which operates on a given sdb:
https://github.com/rizinorg/rizin/blob/486ed69698edfa0c2bd2446b4151026a1e7a129b/librz/include/rz_util/rz_ctypes.h#L21-L34

And the parsing of C headers is in RzParse:
https://github.com/rizinorg/rizin/blob/a3a339b11b1e241ee95201d7b666ff291c8e2100/librz/include/rz_parse.h#L73-L77

For C Types, there is the structure and parser in RzParse:
https://github.com/rizinorg/rizin/blob/a3a339b11b1e241ee95201d7b666ff291c8e2100/librz/include/rz_parse.h#L79-L115

All of these things shall be merged in a single module called `RzTypes`. I think we could have something like an `RzTypes` struct that contains the base types database and also any context needed for the parsers.
Because moving and renaming all of this will first cause compiler errors at all usages of it and especially the naked `SDB *sdb_types` in `RzAnalysis`, this might be a good chance to do partially in parallel with #368 or at least identify the places to change.

**Comment by ret2libc** [comment]
What would you expect `RzTypes` to depend on? `RzAnalysis`? `RzAsm`?

**Comment by thestr4ng3r** [comment]
Ideally:
`RzAnalysis` > `RzTypes` > `RzUtil`
