### ISSUE TITLE
`afv` command changes

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3702]
- Move `afv` to `afvl`
- Add TABLE mode to `afvlt`
- Add SHORT mode to `afvl`
- Add LONG mode for `afvll`

Print more details when available - e.g. from loclists or CFA in LONG and TABLE modes

**Comment by b1llow** [comment]
@XVilka  What information should be displayed in TABLE, SHORT and LONG mode?

**Comment by XVilka** [comment]
@imbillow SHORT is the same as the current one. LONG and TABLE should provide the same information (as much as possible probably - list of all locations, e.g, etc) just in a different format.
