### ISSUE TITLE
Regex is slow

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#3730]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ linux-x86-64 commit: 7febd38e9d00a8b97b32f974d87aa7a9af37dd39

### Expected behavior

`rz_regex_exec()` should be roughly as fast as `regexec` (from `<regex.h>`).  

### Actual behavior

`rz_regex_exec` performance

![perf](https://github.com/rizinorg/rizin/assets/45763064/11cb9399-85f6-4212-82f8-7aca46faf6bb)

`regexec` performance is at least 20-40 times faster.

![perf2](https://github.com/rizinorg/rizin/assets/45763064/4a6e0784-57ca-4977-80d7-d83555acd3a1)

### Steps to reproduce the behavior

Performance is measured like this:

```
// Checkout commit which supports TriCore tokens
git checkout 7febd38e9d00a8b97b32f974d87aa7a9af37dd39
// Build rizin normally
valgrind --tool=callgrind rizin -Qc "pd 50" test/bins/tricore/Blinky_LED_1_KIT_TC367_TFT.elf
// Build rizin with https://github.com/Rot127/rizin/tree/regex-perf
valgrind --tool=callgrind rizin -Qc "pd 50" test/bins/tricore/Blinky_LED_1_KIT_TC367_TFT.elf
// Compare performance of regexec/rz_regex_exec in rz_asm_tokenize_asm_regex()
kcachegrind callgrind.out.*
```

### Additional Logs, screenshots, source code,  configuration dump, ...

cc @GustavoLCR

**Comment by XVilka** [comment]
I believe the best possible solution is just using libpcre2 dependency - it has JIT, is well maintained and tested, and is presented in almost any system already. For those systems where it isn't, e.g. Windows, we can just bundle it.

**Comment by ret2libc** [comment]
Where are regex used? Are they used in any important/long loop?

**Comment by Rot127** [comment]
Not at many places. Only for asm string tokenization and at two-three places for parsing of asm strings (for var analysis).

But if we tokenize more asm strings in the future, this becomes a problem. @XVilka could feel the difference of regex parsed asm strings vs. non-regex parsed asm strings in TriCore.
