### ISSUE TITLE
Update `man` pages for Rizin tools

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3731]
For every tool/binary Rizin provides `man` page should be updated to be in sync with the actual options and features.
Also, for some tools there are no man pages at all, e.g. `rz-test`.
- [x] rizin
- [x] rz-diff
- [ ] rz-asm
- [ ] rz-ax
- [ ] rz-bin
- [ ] rz-find
- [ ] rz-gg
- [ ] rz-hash
- [ ] rz-run
- [x] rz-sign
- [ ] rz-test

**Comment by byteninjaa0** [comment]
could you provide more information

**Comment by XVilka** [comment]
@sohail1734 see 
- `binrs/man/` for the man pages sources
- compare them with the output of `<tool> -h`

**Comment by byteninjaa0** [comment]
i have updated two man pages rizin.1 and rz-diff.1 , how should i make a pr

**Comment by XVilka** [comment]
@byteninjaa0 if you plan to update man pages, the best time is now, as the release will be soon (this month or so),

**Comment by byteninjaa0** [comment]
okay
