### ISSUE TITLE
`px` command to print in Rizin `wx` commands

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3732]
It should return a chain of `wx` commands for a given size. `px*` is probably a good name for such command.
It's very useful for creating tests. Currently the command is located in `pc*` but it's probably could be aliased to `px*` too.

Also like `px` it should accept length argument

**Comment by byteninjaa0** [comment]
i am working on this .

**Comment by ret2libc** [comment]
@XVilka what's the purpose of this feature? Could you provide a full example?

**Comment by byteninjaa0** [comment]
the purpose of this feature is that when we want to write a particular data into memory we use px its like "hey i want to write this data into memory" then rizin generates the 'wx' command , so this feature (px*) would allow the user to create chain of wx command 
for example -
[0x0040000]>px* 4 6 0x2000
here the 6 is the no. of wx command that would be generated starting with the given memory address 
so output will be
wx 0x2000 0x0
wx 0x2004 0x1
wx 0x2008 0x2
wx 0x200c 0x3
wx 0x2010 0x4
wx 0x2014 0x5

On a personal note, I'm still in the learning phase of my journey with the Rizin project. The prospect of contributing to a dynamic and impactful project like this is truly exciting for me. While I'm honing my skills, I'm enthusiastic about the opportunity to learn from experienced contributors and make a meaningful contribution to the project.

**Comment by XVilka** [comment]
@sohail1734 @ret2libc 
1) There already exists `pc*` command but it doesn't accept length
2) It prints `wx XXXXX; sd 0x234`(write bytes then seek), I personally think `wx XXXXX @ 0x10` format makes better sense
3) `px*` should be just an alias to `pc*` after these changes

This kind of command is very useful for creating tests, e.g. I used contrived `pc*` command to generate the testcase for https://github.com/rizinorg/rizin/issues/3733

**Comment by byteninjaa0** [comment]
yes that would be more clear but for that we will have to adjust the code that generates the chain of wx commands

**Comment by XVilka** [comment]
> yes that would be more clear but for that we will have to adjust the code that generates the chain of wx commands

yes.

**Comment by byteninjaa0** [comment]
in cmd_print.yaml file there is no such name like pc* ,where it is located?

**Comment by XVilka** [comment]
@sohail1734 line 151

**Comment by byteninjaa0** [comment]
got it

**Comment by XVilka** [comment]
If you change `pc*`, it probably makes sense extending all of `pc` subcommands with length. Using `@!<size>` syntax for a block size looks clunky and counterintuitive.

**Comment by haruInDisguise** [comment]
Hey there!
I've been working on this feature in a way, that allows implementing n-size array printing for multiple language targets. 
As of right now, this only implements the 'px*' command (i.e. variable length array printing in "rizin style"). The command must be supplied with an argument and is therefore not an alias to 'pc*', but that would be easy to adjust.
I know that this idea goes beyond what this Issue proposed and probably deserves its own Issue.
What do you think of this general concept? I've found myself wanting to print, say, an n-byte C array quite a few times.
[My commit](https://github.com/haruInDisguise/rizin/tree/command-px_star)

**Comment by byteninjaa0** [comment]
where is the handler of pc command i have read the rz_shell.md its written that we can use the script sys/rzshell_which.py to find the handler of the command but where is that script located

**Comment by wargio** [comment]
Just try to find `"pc"` within `libr/core/cmd_descs/cmd_descs.h`

**Comment by ret2libc** [comment]
> @sohail1734 @ret2libc
> 
> 1. There already exists `pc*` command but it doesn't accept length
> 2. It prints `wx XXXXX; sd 0x234`(write bytes then seek), I personally think `wx XXXXX @ 0x10` format makes better sense
> 3. `px*` should be just an alias to `pc*` after these changes
> 
> This kind of command is very useful for creating tests, e.g. I used contrived `pc*` command to generate the testcase for #3733

What about `wx $(p8 100)`?

**Comment by byteninjaa0** [comment]
can you explain how this would work

**Comment by haruInDisguise** [comment]
The ```$()``` construct executes a command 'in place' (see "command substitution" in zsh/bash). Due to the nature of the shell, this result is passed as an argument to the ```wx``` command.
In your example: ```p8 100``` prints 100 bytes of data from the current offset/binary. The ```wx``` command then writes our 100 bytes, starting at the current offset.
The expansion could look like this:
```wx $(p8 100)``` => ```wx 99aabbccddee...```

**Comment by byteninjaa0** [comment]
is there something else to do in this issue?

**Comment by byteninjaa0** [comment]
anything*

**Comment by XVilka** [comment]
Closing after some consideration as `pc*` would suffice
