### ISSUE TITLE
rizin does not load plugins automatically

### ISSUE THREAD

**Issue by FalcoGer** [rizinorg/rizin#3766]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu Mate 22.04
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| `rizin -v` full output, **not truncated** (mandatory)  | `rizin 0.6.0 @ linux-x86-64 commit: 24257e3a7f2fb6494052aab1f631330098ef35dc`

### Expected behavior

rizin loads all plugins from from either `$HOME/.local/share/rizin/plugins` or `/usr/local/share/rizin/plugins`

### Actual behavior

rizin loads no plugins whatsoever.
Loading plugins manually with `rizin -l /home/paul/.local/share/rizin/plugins/analysis_ghidra.so -l /home/paul/.local/share/rizin/plugins/asm_ghidra.so -l /home/paul/.local/share/rizin/plugins/core_ghidra.so -l /home/paul/.local/share/rizin/plugins/libcore_pdd.so` works

### Steps to reproduce the behavior
1. Compile some plugin, such as jsdec. Use `~/.local/` as prefix.
2. Install
3. run rizin and list core plugins (`Lc`)
4. note that they're absent
5. make a symlink `~/.local/share/rizin/plugins` to point to `~/.local/lib/x86_64-linux-gnu/rizin/plugins/`
6. run rizin and list core plugins
7. note that they are absent
8. make a symlink `/usr/local/share/rizin/plugins` to point to `~/.local/lib/x86_64-linux-gnu/rizin/plugins/`
9. run rizin and list core plugins
10. note that they are still absent
11. look at [documentation on plugins](https://book.rizin.re/plugins/intro.html) and find no information on where rizin loads plugins from (optional)

**Comment by FalcoGer** [comment]
Well I found out that when I build and install rizin bundled with cutter, then no plugins are loaded. But when I build rizin on it's own then it works fine. What's more is when I build rizin on it's own and then build cutter without rizin bundled, then cutter segfaults. However when I build cutter with rizin bundled, then cutter only segfaults when I try to load the ghidra plugin. What a mess.

**Comment by XVilka** [comment]
What your `rizin -H` shows?

**Comment by FalcoGer** [comment]
```text
rizin -H
RZ_VERSION=0.6.0
RZ_PREFIX=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix
RZ_EXTRA_PREFIX=
RZ_MAGICPATH=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix/share/rizin/magic
RZ_INCDIR=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix/include/librz
RZ_LIBDIR=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix/lib
RZ_SIGDB=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix/share/rizin/sigdb
RZ_EXTRA_SIGDB=
RZ_LIBEXT=so
RZ_RCONFIGHOME=/home/username/.config/rizin
RZ_RDATAHOME=/home/username/.local/share/rizin
RZ_RCACHEHOME=/home/username/.cache/rizin
RZ_LIBR_PLUGINS=/home/username/repositories/hacking/cutter_disassembler/cutter/build/Rizin-prefix/lib/rizin/plugins
RZ_EXTRA_PLUGINS=
RZ_USER_PLUGINS=/home/username/.local/lib/rizin/plugins
RZ_IS_PORTABLE=0
```

well that would've been nice to know.

` -H ([var])   display variable` isn't exactly the best help text to find out how to diagnose the issue.

**Comment by FalcoGer** [comment]
and with ghidra loaded in rizin it also doesn't crash cutter anymore when using the ghidra cutter plugin.

**Comment by ret2libc** [comment]
Was this solved @FalcoGer ?

**Comment by FalcoGer** [comment]
yes. thank you. Maybe add more info to the `-H` flag in the help output? `Displays variables` really didn't do it for me to debug this issue.

**Comment by ret2libc** [comment]
Yeah the help messages might not be the best :) Do you have suggestions? @FalcoGer
