### ISSUE TITLE
Mechanism to limit the values assigned to config evaluable vars.

### ISSUE THREAD

**Issue by PeiweiHu** [rizinorg/rizin#3771]
**Is your feature request related to a problem? Please describe.**

Is there a mechanism to limit the value assigned to the config variables?  For example, the values of asm.var.summary are limited to 0, 1, and 2. And the assignment of other values will be forbidden. This sounds reasonable. But currently I can assign any values to asm.var.summary like the number 100 by `e asm.var.summary=100`. The unlimited assignment may lead to unexpected behaviors.

**Describe the solution you'd like**

Involve new mechanism to limit the assignments to config variables by the command `e`.

**Comment by thestr4ng3r** [comment]
This is already possible by implementing the validation in the callback, e.g.
```
florian-macbook:~ florian$ rz
[0x00000000]> e asm.arch
arm
[0x00000000]> e asm.arch=asdf
ERROR: core: asm.arch: cannot find (asdf)
[0x00000000]> e asm.arch
arm
[0x00000000]>
```

**Comment by PeiweiHu** [comment]
Thank you so much. I will check it.
