### ISSUE TITLE
`rizin` using wrong instruction offsets despite `rz-asm` correctly disassembling multiple instructions

### ISSUE THREAD

**Issue by Baseng0815** [rizinorg/rizin#3772]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux/x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Renesas RL78/32
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ linux-x86-64, commit: 6aca5866b9  (origin/arch-rl78; rz_strbuf_new and rz_strbuf_appendf for rl78)

### Expected behavior

Disassembling multiple instructions using `rizin` behaves the same as feeding the bytes manually to `rz-asm`.

### Actual behavior

Correct behavior by `rz-asm` for [rizin-testbins/rl78/caesar_nostrip](https://github.com/rizinorg/rizin-testbins/blob/master/rl78/caesar_nostrip) at offset 0x06b3 (0x16b3 in file):

```
❯ ./rz-asm/rz-asm -a rl78 -d "2026 340000 b814"
subw sp, #0x26
movw de, #0x0
movw [sp+0x14], ax
```

Wrong behavior by `rizin`:

```
:> px 7 @ 0x6b3
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x000006b3  2026 3400 00b8 14                         &4....
:> pd 3 @ 0x6b3
            ;-- _main:
┌ int dbg.main(int argc, char **argv);
│           0x000006b3      subw  sp, #0x26                            ; caesar.c:43 { ; int main(int argc, char **argv);
│           0x000006b7      nop
│           0x000006bb      movw  [sp+0x0], ax
:>
```

[caesar_nostrip.zip](https://github.com/rizinorg/rizin/files/12375257/caesar_nostrip.zip)

**Comment by ret2libc** [comment]
Where can we test the rl78 arch? Which branch?

**Comment by XVilka** [comment]
> Where can we test the rl78 arch? Which branch?

https://github.com/rizinorg/rizin/pull/3649, though it's incomplete and misses analysis plugin. So we have to wait, I suppose.

**Comment by Rot127** [comment]
@Baseng0815 Might be a problem with `movw de, #0x0` depends on `subw sp, #0x26`. If this is the case you need to implement some kind of buffer to save the last disassembled instruction.
Otherwise, please debug your plugin first to see, if it is not aother problem in your plugin.
