### ISSUE TITLE
Switch from `RzList` to `RzPVector` in `RzBinPlugin`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3775]
Currently it uses a lot of `RzList` which is slower to traverse and takes more memory. The idea is to substitute them for `RzPVector` instead.
These are members that could be switched:
- [x] `RzList /*<RzBinImport *>*/ *(*imports)(RzBinFile *bf);`
- [x] `RzList /*<RzBinSymbol *>*/ *(*symbols)(RzBinFile *bf);`
- [x] `RzList /*<RzBinString *>*/ *(*strings)(RzBinFile *bf);`
- [x] `RzList /*<RzBinVirtualFile *>*/ *(*virtual_files)(RzBinFile *bf);`
- [x] `RzList /*<RzBinMap *>*/ *(*maps)(RzBinFile *bf);`
- [ ] `RzList /*<RzBinAddr *>*/ *(*entries)(RzBinFile *bf);`
- [x] `RzList /*<RzBinSection *>*/ *(*sections)(RzBinFile *bf);`
- [x] `RzList /*<RzBinField *>*/ *(*fields)(RzBinFile *bf);`
- [x] `RzList /*<char *>*/ *(*libs)(RzBinFile *bf);`
- [x] `RzList /*<RzBinReloc *>*/ *(*relocs)(RzBinFile *bf);`
- [x] `RzList /*<RzBinTrycatch *>*/ *(*trycatch)(RzBinFile *bf);`
- [x] `RzList /*<RzBinClass *>*/ *(*classes)(RzBinFile *bf);`
- [x] `RzList /*<RzBinMem *>*/ *(*mem)(RzBinFile *bf);`
- [x] `RzList /*<RzBinReloc *>*/ *(*patch_relocs)(RzBinFile *bf);`
- [x] `RzList /*<RzBinFileHash *>*/ *(*hashes)(RzBinFile *bf);`
- [x] `RzList /*<RzBinResource *>*/ *(*resources)(RzBinFile *bf);`

**Comment by XVilka** [comment]
@PeiweiHu hi, do you plan to continue working on this?

**Comment by PeiweiHu** [comment]
> @PeiweiHu hi, do you plan to continue working on this?

I just came across this message since the last month was too busy. I will continue working on this and also other stuffs these days.
