### ISSUE TITLE
Pointer read with `*` command not working

### ISSUE THREAD

**Issue by laomaiweng** [rizinorg/rizin#3780]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Android/Termux arm 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | arm 64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ linux-arm-64 commit: 03dd2d222aa217346d81dcc8e6fcaf966bc2eb30

### Expected behavior

The pointer `*` command behaves as documented (at least for reads, I didn't attempt writes):

```
*entry0             # read the value contained at the
                      entrypoint
```

### Actual behavior

```
[0x00001d90]> *entry0
ERROR: Command '?v' does not exist.
```

Since `rz_pointer_handler` just execs a `?v` command for reads, I also tried directly using `%v` (since IIUC `%` replaces radare2's `?` in rizin):

```
[0x00001d90]> %v entry0
0x1d90
[0x00001d90]> %v *entry0
0x0
[0x00001d90]> pxw 4 @ entry0
0x00001d90  0xd503249f
```

For this binary I expected `*entry0` to return `0xd503249f` (or a 64-bits value, whatever).

### Steps to reproduce the behavior

Any binary exhibits the (presumably) faulty behavior. For the above snippets I used the `rizin` binary itself. No other action was taken in rizin prior to running the above commands.

### Additional Logs, screenshots, source code,  configuration dump, ...

No rizinrc was in use for the above snippets.

**Comment by XVilka** [comment]
Good catch. It also should use the API instead of calling the command.

**Comment by laomaiweng** [comment]
Hmm I misread the code in `rz_pointer_handler`, it does `?v [%s]`, so I should have tried `%v [entry0]`, which indeed works.

This means the only issue here is that `rz_pointer_handler` should use the API, as you pointed out. Would it be ok to just `sprintf` the expr to dereference as `[%s]` and pass that to `r2_num_math` ? It's still playing with strings which may not be the cleanest way to implement this. :-/

**Comment by XVilka** [comment]
@laomaiweng `rz_num_math()` automatically resolves strings like flag names, etc. So just passing it should be sufficient.
