### ISSUE TITLE
Colors support in help output of `rz-*` and `rizin` tools

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3799]
Rizin supports different color modes and themes in the shell and output inside corresponding tools, including help on shell commands.

We should do the same in `rizin -h`, `rz-diff -h`, etc output. See how it's done for internal shell in `librz/core/cmd/cmd_api.c`, e.g. `fill_usage_strbuf()`, `do_print_child_help()`, etc.

Reusing some of the code, and providing one function to be called for those, just with different input for printing colored/themed output for `-h` options is preferred.

<img width="704" alt="Screenshot 2023-08-28 at 13 39 33" src="https://github.com/rizinorg/rizin/assets/203261/58d547c2-1c47-4df6-9626-1664a27a6439">

**Comment by wargio** [comment]
we should also refactor the argopt because is very bugged.

**Comment by byteninjaa0** [comment]
i would like to work on this but i dont know where to start

**Comment by XVilka** [comment]
@sohail1734 see the files that are in `librz/main/*.c` - the help messages are here. Just look how it's done in the internal shell and try to replicate the same logic in those.
You could even try to extract the common part, if necessary, to share between internal shell and those help messages.

**Comment by byteninjaa0** [comment]
"While working on issue #3890, I've encountered various functionalities of functions in cmd_api.c. Now, the picture is becoming clearer. To complete this task, I just need some time because my exams are near.

**Comment by AbhiTheModder** [comment]
@XVilka Like this:?
![image](https://github.com/rizinorg/rizin/assets/85984486/c7e72953-7ab1-4572-9d4b-822dc6868981)

**Comment by XVilka** [comment]
Not exactly. See example inside the Rizin shell (`?` command) separate options with color, etc

**Comment by AbhiTheModder** [comment]
> Not exactly. See example inside the Rizin shell (`?` command) separate options with color, etc

Ok got it: options in white, helps in green and extra cmds in yellow

![image](https://github.com/rizinorg/rizin/assets/85984486/00c0a157-12ee-4ee9-9303-7a2572c35a9d)

Am I correct ?

**Comment by XVilka** [comment]
Something like that, but I would reverse and keep descriptions white but commands themselves green, to be more inline with the Unix shell coloring.

**Comment by AbhiTheModder** [comment]
> Something like that, but I would reverse and keep descriptions white but commands themselves green, to be more inline with the Unix shell coloring.

@XVilka You mean like this:?
![image](https://github.com/rizinorg/rizin/assets/85984486/5e5f7ab9-52a1-475c-8812-4acd4c2afeec)

**Comment by wargio** [comment]
i would say almost there. i would also have different colors for the values in the examples.

**Comment by byteninjaa0** [comment]
i was thinking to do it by rzcons similar to what it is done in the core commands the problem i faced is for every subcommand there is a seperate instance in the pointer cd of rzcmddesc and lines are printed one by one followed by the comment which too is handled by a seperate function (fill_wrapped_comment) in cmd_api.c but this is not the case here . i was trying to format the help message into name , args , summary and print it as it is printed in the core commands but i am still finding a way how to do it.

**Comment by AbhiTheModder** [comment]
@byteninjaa0 Great, will be waiting for those updates till then I'm happy using my little brain ideas for myself 😂

**Comment by byteninjaa0** [comment]
![image](https://github.com/rizinorg/rizin/assets/62786136/80546e90-65fa-4720-9532-44f55bd9a59f)
how does it look ?

**Comment by wargio** [comment]
looks very good

**Comment by byteninjaa0** [comment]
![image](https://github.com/rizinorg/rizin/assets/62786136/bb4f11bd-c2ed-44d3-a91c-e49b6bc75a2b)
for rz-diff -h

**Comment by byteninjaa0** [comment]
![image](https://github.com/rizinorg/rizin/assets/62786136/0c67ad32-78c0-435e-bde1-3163bc58d12d)
rz-asm

**Comment by AbhiTheModder** [comment]
Awesome 👍🏻

**Comment by XVilka** [comment]
Closed by https://github.com/rizinorg/rizin/commit/5c28709cb247790eebd2a86867a067c789173796
