### ISSUE TITLE
env should require a space for the argument

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#3802]
as per below ... surprisingly it does work

![env-help](https://github.com/rizinorg/rizin/assets/12002672/c653336d-b094-4fce-8ed8-1436a92c0e04)

_Originally posted by @kazarmy in https://github.com/rizinorg/rizin/pull/3800#discussion_r1307103553_

**Comment by XVilka** [comment]
Also the help message should be fixed - `Same as %SHELL` should be removed/

**Comment by XVilka** [comment]
Fixed by https://github.com/rizinorg/rizin/commit/77f860cbc6dffe43c7128678f6c8ab4cf17015a3

**Comment by kazarmy** [comment]
77f860cbc6dffe43c7128678f6c8ab4cf17015a3 fixes just the help, not the grammar
