### ISSUE TITLE
dbt: Missing `main` stack frame

### ISSUE THREAD

**Issue by kazarmy** [rizinorg/rizin#3806]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86-64 22.04
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ linux-x86-64 commit: 6d202f16985670d4943e8e8faba0b0a4829e7e4f

### Actual behavior

![missing-main](https://github.com/rizinorg/rizin/assets/12002672/5a22b3fd-449a-4ed4-a9bb-561bd2546933)

### Expected behavior

Something along the lines of

```
[0x0040052f]> dbt
... loc.func_0
... main loc.func_6+6
... fs+181840
... fs+182016
... entry0+41
```

`dbt` output does seem a bit off.

**Comment by byteninjaa0** [comment]
do we have to edit cmd_debug.c file

**Comment by kazarmy** [comment]
I don't think so afaik
