### ISSUE TITLE
Rename some of the environment variables

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3808]
- [ ] `{ "RZ_RCONFIGHOME", confighome },` -> `RZ_CONFIGHOME`
- [ ] `{ "RZ_RDATAHOME", datahome },` -> `RZ_DATAHOME`
- [ ] `{ "RZ_RCACHEHOME", cachehome },` -> `RZ_CACHEHOME`
- [ ] `{ "RZ_LIBR_PLUGINS", plugins },` -> `RZ_LIB_PLUGINS`

Should fix sources and fortune messages

**Comment by byteninjaa0** [comment]
I've edited these three files-
/doc/fortunes.tips
./librz/include/rz_lib.h
./librz/main/rizin.c
are there any more?
