### ISSUE TITLE
Asking for quit confirmation twice when debugging remotely

### ISSUE THREAD

**Issue by 8dcc** [rizinorg/rizin#3818]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArcoLinux, kernel 6.4.12
| File format of the file you reverse (mandatory)      | Remote qemu debugging (`gdb://localhost:1234`)
| Architecture/bits of the file (mandatory)            | 32 bits
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.1 @ linux-x86-64, commit: d9af48b56e47afadd1a77e74c12099efd5e8e19e

### Expected behavior

When debugging remotely with `scr.confirmquit` enabled, ask to confirm exit and then ask if the user wants to kill the process (or vice versa).

### Actual behavior

After executing `q`, it asks the user if he wants to quit twice:
```
[0x0000f15b]> q
Do you want to quit? (Y/n) y
Do you want to kill the process? (Y/n) y
Do you want to quit? (Y/n) y
```

### Steps to reproduce the behavior
After running `rizin -d dbg://localhost:1234`:

>**Edit:** Asciinema removed the video, just see output in [actual behavior](#actual-behavior).

I was debugging a 32 bit kernel in qemu (`qemu -s`).

**Comment by vanshjangir** [comment]
Can I take this issue?

**Comment by ret2libc** [comment]
Sure @vanshjangir , go ahead!

**Comment by vanshjangir** [comment]
I have made a draft pull request, please review it and request changes if required.
