### ISSUE TITLE
Panel Empty

### ISSUE THREAD

**Issue by CHr15W3** [rizinorg/rizin#3829]
Hi,
I am experiencing some issues with rizin. 
I am on fedora 37, using this (self compiled) rizin version:
```
rizin 0.7.0 @ linux-x86-64
commit: a5780a3855c5673274856baa7b6bcf3be1777892
```
I was playing around with using command line tools instead of ghidra. When trying some toy examples (megabeets example, 32-bit ELF binary) I wanted to try a decompiler (rz-ghidra). When calling `pdg` from the normal cli, the current function gets decompiled successfully, however when using the visual panel mode, and changing the command of one panel to `pdg` this does not work. It also, however, does not work with commands such as `pdf` 

### Expected behavior
Panel should display output of the command

### Actual behavior
Panel is completely empty, like with commands which do not have any output

### Steps to reproduce the behavior
Open a binary, navigate to main function (`s main`), open visual panel mode (`v`), change mode of panel to `pdf` or `pdg`

**Comment by ret2libc** [comment]
Confirmed.

**Comment by ret2libc** [comment]
Could you check what you get when you execute `pdf`/`pdg` when not in visual panel mode?

**Comment by CHr15W3** [comment]
works normally, i.e. prints the disassemly or the decompilation of the function I'm currently in.
