### ISSUE TITLE
ZStd's headers and libraires

### ISSUE THREAD

**Issue by b1llow** [rizinorg/rizin#3830]
libzstd installs its own headers and libraries, but we've already statically linked so this should be redundant behavior.

<img width="189" alt="image" src="https://github.com/rizinorg/rizin/assets/24983369/0b73a7a7-d306-4bd6-8e07-84d94b2d0100">
<img width="189" alt="image" src="https://github.com/rizinorg/rizin/assets/24983369/36a3c590-bcfe-4e56-815e-c8cdd052d314">

**Comment by ret2libc** [comment]
We should remove the `install_headers` in lib/meson.build and also the pkgconfig.generate
