### ISSUE TITLE
Add SM4 {de,en}cryption support

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3851]
Rizin supports SM3 hashing algorithm but not SM4 encryption algorithm yet. 

[ShāngMì 4 (SM4, 商密4)](https://en.wikipedia.org/wiki/SM4_(cipher)) (formerly SMS4) is a block cipher used in the Chinese National Standard for Wireless LAN WAPI (WLAN Authentication and Privacy Infrastructure) and also used with Transport Layer Security.

It's also supported by OpenSSL:
- https://www.openssl.org/docs/man3.0/man7/EVP_CIPHER-SM4.html
- https://www.openssl.org/docs/man3.0/man3/EVP_sm4_cbc.html

**Comment by 0xSh4dy** [comment]
Hey! I'd love to work on this issue, can I? @XVilka
