### ISSUE TITLE
Configure repositories to deliver Rizin to linux distro users

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#387]
**Is your feature request related to a problem? Please describe.**
For now we don't build .deb packages and users are either expected to build the tool themselves or wait for distro maintainers to package and maintain Rizin. Hopefully distros will show interest soon in packaging Rizin.

**Describe the solution you'd like**
A lot of users run Ubuntu (either in container or VM or natively). PPA are a nice way to build and distribute packages to Ubuntu users, as it provides a repository they can add to their system and then install/update Rizin as they would with any other package.

**Describe alternatives you've considered**
Create the .deb file ourselves, like it was done in radare2, is probably error prone and it is not said it would work on all releases.

There is also OBS (from Suse) that seems to be able to create repositories for multiple distros.

**Additional context**
https://help.launchpad.net/Packaging/PPA

**Comment by ret2libc** [comment]
Examples for OBS:
https://build.opensuse.org/package/show/home:fhoech/DisplayCAL
https://build.opensuse.org/package/show/openSUSE:Tools/build

**Comment by XVilka** [comment]
A good example on how it's done is the LLVM project: https://apt.llvm.org

**Comment by ret2libc** [comment]
I'm more inclined for OBS at the moment. It builds on multiple archs/distros for us and it provides the repositories needed for each distro, without us having to configure/maintain anything on our servers.

**Comment by ret2libc** [comment]
More info about OBS:
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.best-practices.scm_integration.html
https://openbuildservice.org/2013/11/22/source-update-via_token/
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.authorization.token.html#id-1.5.10.16.4

**Comment by ret2libc** [comment]
FYI: this needs to be done *after* the release (or at least a pre-release) is done, because I need a nice and good URL for the src tarball to try things a bit.

**Comment by ret2libc** [comment]
As some distros are already shipping rizin I'm going to postone this for 1.0.0. We'll see if it's going to be necessary.

**Comment by ret2libc** [comment]
Done. https://github.com/rizinorg/rizin/blob/dev/INSTALL.md#linux
