### ISSUE TITLE
Show `crc64`, `blake3` and `sm3` hashes too in `iT` output

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3871]
Currently these are presented:
```
[0x1000033e0]> iT
md5 6208fa5974c3df6fa3d6fa1664fdd0b5
sha1 0d7b7619143c0215ee54b4200277ec0689fcea05
sha256 fd78205727d973ae022be414cb38a39b3e3e252f8026045775203983d2217c96
crc32 42048b29
entropy 2.548695
```
As 64bits and BLAKE got more popular these days, showing them would be nice too.

@wargio do you think it's a reasonable request or it will negatively affect the performance?

**Comment by wargio** [comment]
i think would be smart to have an eval, like `e bin.hashes.default=md5,sha1,sha256,crc32,entropy,blake,sm3` etc..

**Comment by XVilka** [comment]
Good idea

**Comment by byteninjaa0** [comment]
how you guys explain and guide me how to do it

**Comment by wargio** [comment]
You will likely need to create a new eval in `core/cconfig.c` and then configure the RzHash to use this new value instead of hardcoding it. then we will need a similar PR for cutter.

**Comment by s1gse9v** [comment]
Hey there, I have created a PR that implements this. Would be grateful for any feedback
