### ISSUE TITLE
Move Hashtable and Set primitives from SDB to RzUtil 

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3894]
Currently they are located in these files:
- `librz/util/sdb/src/ht_*.{c,h}`
- `librz/util/sdb/src/set.{c,h}`

They should be moved upward, to `librz/util/` and properly documented with Doxygen.

**Comment by vanshjangir** [comment]
Hey, I would like to help fix this issue. Is there somebody working on it, or should I take it?

**Comment by ret2libc** [comment]
You can take it @vanshjangir !

**Comment by vanshjangir** [comment]
Hey, I have made the necessary changes. Just need help on how should I document them.

**Comment by ret2libc** [comment]
Start by pushing the changes in a PR so we can have a first look.
