### ISSUE TITLE
Bug in swapping bits of signed integers in case of missing compiler builtin.

### ISSUE THREAD

**Issue by createyourpersonalaccount** [rizinorg/rizin#3899]
I am looking at the code for `rz_swap_st16` in the case where the compiler builtin is missing. Does this code make sense for a 16-bit integer? It is equal to the 32-bit code, and I think it is wrong.

Compare signed 16-bit version

https://github.com/rizinorg/rizin/blob/5211cdcfb06cc0740d568d54a2a160453a36869e/librz/include/rz_endian.h#L669-L676

to signed 32-bit version

https://github.com/rizinorg/rizin/blob/5211cdcfb06cc0740d568d54a2a160453a36869e/librz/include/rz_endian.h#L687-L694

Not only I think the signed 16-bit version is wrong, but I think all signed versions are wrong if the compiler builtin is missing. The behavior depends on the signed integer representation, so it cannot be defined via operators operating on values like `&, |, ^`, etc, it needs to be interpreted as a `ut8` array.

I would like to fix this bug but I do not know what the meaning of `rz_swap_st16` is. Can it be clarified? Just reverse order of bytes in representation?

**Comment by ret2libc** [comment]
```c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

static inline uint32_t rz_swap_st32(uint32_t val) {
 	val = ((val << 8) & 0xFF00FF00) | ((val >> 8) & 0xFF00FF);
 	return (val << 16) | ((val >> 16) & 0xFFFF);
 }

 static inline uint16_t rz_swap_st16(uint16_t val) {
 	val = ((val << 8) & 0xFF00FF00) | ((val >> 8) & 0xFF00FF);
 	return (val << 16) | (val >> 16);
 }

int main(int argc, char **argv) {
	uint32_t x = 0xdeadbeef;
	uint32_t y = __builtin_bswap32(x);
	uint32_t z = rz_swap_st32(x);
	printf("32bit %x -> %x (%x)\n", x, y, z);
	uint16_t x2 = 0xdead;
	uint16_t y2 = __builtin_bswap16(x2);
	uint16_t z2 = rz_swap_st16(x2);
	printf("16bit %x -> %x (%x)\n", x2, y2, z2);
	return 0;
}
```

Result:
```
32bit deadbeef -> efbeadde (efbeadde)
16bit dead -> adde (0)
```

so yes, the 16bit version is wrong.

**Comment by createyourpersonalaccount** [comment]
@ret2libc Thank you for confirming it! I decided to remove these unused functions in https://github.com/rizinorg/rizin/pull/3900.
