### ISSUE TITLE
function name display should take priority over data flags

### ISSUE THREAD

**Issue by ctlayon** [rizinorg/rizin#3907]
For Windows, often times `aaa` assigns data flags to functions that are passed to threads via `createthread` i.e. "data.<OFFSET>". To be able to rename the thread to something more useful like `MainThread` I have to do the following actions:

- `f- data.<OFFSET>`
- `afn MainThread @ <OFFSET>`

If I try to run afn before running `f- data.<OFFSET>` on a function offset that has a data flag, the data flag persists. Until I explicitly remove it with `f- data.<OFFSET>` I think, by default, anytime you run `afn` on a section that is recognized as a function the new function name should take priority.

**Comment by ctlayon** [comment]
I think https://github.com/rizinorg/rizin/pull/3911 fixes this function over data flag priority issue!

**Comment by ret2libc** [comment]
@ctlayon would you say we can close this then?

**Comment by ctlayon** [comment]
Yeah! (closing with this comment)
