### ISSUE TITLE
Memleaks in DWARF module

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#3917]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | 
| Architecture/bits of the file (mandatory)            | 
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ linux-x86-64 commit: 4d2575ff98064bc2e99672005ac1effc8eb5881a

### Expected behavior

No memleaks in DWARF module

### Actual behavior

```
...
==140606== LEAK SUMMARY:
==140606==    definitely lost: 316,893 bytes in 3,835 blocks
==140606==    indirectly lost: 428,721 bytes in 10,285 blocks
==140606==      possibly lost: 1,123 bytes in 30 blocks
==140606==    still reachable: 6,885,363 bytes in 98,414 blocks
==140606==         suppressed: 0 bytes in 0 blocks
```

### Steps to reproduce the behavior

Run the `db/analysis/vars Function va_args arguments from DWARF` test with `valgrind --leak-check=full`:

```
valgrind --leak-check=full ./build/binrz/rizin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aaa
(sig; afv; afs; pd 1; echo "")
s dbg.printf
.(sig)
s dbg.prout
.(sig)
s dbg._fpadd_parts
.(sig)
s dbg.strnlen_s
.(sig)
s dbg._Wctomb
.(sig)
s dbg._Mbtowc
.(sig)
s dbg.feraiseexcept
.(sig)
s dbg._Atrealloc
.(sig)
' test/bins/elf/float_ex1/float_ex1_hightec
```

### Additional Logs, screenshots, source code,  configuration dump, ...

[memleak.log](https://github.com/rizinorg/rizin/files/12886438/memleak.log)

**Comment by b1llow** [comment]
I'll try to fix it tonight.
