### ISSUE TITLE
`afvl` command improvements

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3943]
- In `afvl` short output print `@ COMPOSITE` or `@ LOCLIST` for corresponding arguments (in the SHORT mode, also in the `pdf`/`pdr` outputs)
* Make intervals like `[(0x8010fb1c, 0x8010fb3f): a4,	(0x8010fb42, 0x8010fb48): a13,	(0x8010fb48, 0x8010fb5e): a4,	(0x8010fb5e, 0x8010fb64): a13,	(0x8010fb64, 0x8010fb6d): a4]` shorter by using the length instead of the end address.

**Comment by b1llow** [comment]
- Do you mean that in SHORT mode only print `@ COMPOSITE` or @ `LOCLIST` and omit the details?
- And in LONG and TABLE mode `[(0x8010fb1c, 0x8010fb3f): a4,	(0x8010fb42, 0x8010fb48): a13,	(0x8010fb48, 0x8010fb5e): a4,	(0x8010fb5e, 0x8010fb64): a13,	(0x8010fb64, 0x8010fb6d): a4]`
  =>  `[(0x8010fb1c, 23): a4,	(0x8010fb42, 6): a13,	(0x8010fb48, 16): a4,	(0x8010fb5e, 6): a13,	(0x8010fb64, 9): a4]`, right?

**Comment by b1llow** [comment]
@XVilka

**Comment by XVilka** [comment]
@imbillow precisely
