### ISSUE TITLE
Add function `rz_bin_object_get_symbol_at()`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3968]
Similarly to functions like:
- `rz_bin_object_get_string_at()`
- `rz_bin_object_get_map_at()`

**Comment by AniketNS** [comment]
Hey @XVilka, I'd like to work on this issue. Can you please assign this issue to me?

**Comment by XVilka** [comment]
@AniketNS go for it, send a PR

**Comment by AniketNS** [comment]
Hello @XVilka, Can you please elaborate on the issue?

**Comment by byteninjaa0** [comment]
Hello @AniketNS you can begin with finding the functions rz_bin_object_get_string_at() and
rz_bin_object_get_map_at() where they are located and how they work and what they do.

**Comment by HN026** [comment]
https://github.com/rizinorg/rizin/pull/3972

@XVilka Can you check this out?
