### ISSUE TITLE
Implement basefind feature

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#413]
Basefind aims at find the base address of a raw binary by using ASCII strings and their intersections.

There are various implementations of this:
- https://github.com/sgayou/rbasefind (in Rust)
- https://github.com/mncoppola/ws30/blob/master/basefind.py (Python)
- https://github.com/mncoppola/ws30/blob/master/basefind.cpp (C++)
- https://gist.github.com/rpw/2c4064712638bce602755a938991e5e9 (Python)

Since Rizin is often used for reversing raw binaries (e.g. firmware) it's commonly used feature in this scenario. It could be a part of the Rizin itself, moreover, reusing the strings detection logic, see https://github.com/rizinorg/rizin/issues/38

**Comment by fangxlmr** [comment]
@cascades-sjtu This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by cascades-sjtu** [comment]
Roger that. Do I have to write it in C?

**Comment by cascades-sjtu** [comment]
Roger that.
