### ISSUE TITLE
DWARF: Support V850 32bit register profile

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4160]
Opening `rizin-testbins`'s `v850/hello-v850` prints the error:
```
ERROR: No DWARF register mapping function defined for v850 32 bits
```

**Comment by b1llow** [comment]
I can't find documentation that describes this. But it feels like a good guess that it's in the same order as the V850 GR?

**Comment by XVilka** [comment]
@imbillow likely. I recommend checking the source of the v850 toolchain, though.
