### ISSUE TITLE
Scrolling in panel mode attempts to executes symbol names as command.

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#4216]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | all(?)
| `rizin -v` full output, **not truncated** (mandatory)  |rizin 0.7.0 @ linux-x86-64 commit: c5e787d8674f02de9f2f5632f442c92e19c7e639

### Expected behavior

- Entering panel mode `v`
- Scroll by holding `J` or `K`
- Everything is fine

### Actual behavior

Symbol names are executed as command during scrolling. Warning are thrown like:

```
ERROR: Command 'entry0' does not exist.
ERROR: Displaying the help of command 'e'.

ERROR: Usage: e[?]   # List/get/set config evaluable vars
| e <key>[=<val|?>] [<key>[=<val|?>] ...]] # Get/Set value of config variable <key>
| el[j*qlJ] [<key>]      # List config variables with their descriptions
| e-                     # Reset config variables
| e! <key>               # Invert the boolean value of config variable <key>
| ec[?]                  # Set color for given key (prompt, offset, ...)
| ee <key>               # Open editor to change the value of config variable <key>
| er <key>               # Set config variable <key> as read-only
| es [<key>]             # List all config variable spaces or sub-keys/sub-spaces if a <key> is provided
| et <key>               # Show type of given config variable <key>
```

### Steps to reproduce the behavior

```
RZ_NOPLUGINS=1 rizin -c "e scr.color=0 ; aa ; v" test/bins/elf/analysis/elf-sparc-execstack  2> log
# Scroll down by holding "J"
```

quit and check error log

```
less log
```

### Additional Logs, screenshots, source code,  configuration dump, ...

None

**Comment by Rot127** [comment]
Holding down `j`, `k`, `J` or `K` seems to be the problem.

**Comment by XVilka** [comment]
I think it's also related to https://github.com/rizinorg/rizin/issues/3831

Might be caused by one of these: https://github.com/rizinorg/rizin/issues?q=is%3Aissue+is%3Aopen+rz_core_cmd
