### ISSUE TITLE
Fix RzIL operations/handlers for 80-bit floats

### ISSUE THREAD

**Issue by DMaroo** [rizinorg/rizin#4252]
80-bit floats are handled incorrectly by Rizin. Partial fixes (like #4251) help in fixing some of the IL operations. But many other IL operations are still broken.

Example:

```
x = 1.l (0x3fff8000000000000000)
y = -0.384677154767621320985l (0xbffdc4f4676e7d934000)

ret = rz_float_div(x, y, RZ_FLOAT_RMODE_RNE)

ret != -2.59958250082224806804l (0xc000d907403a7256641c)
```

`x`, `y`, and `div` are 80-bit floats here (`RZ_FLOAT_IEEE754_BIN_80`). Here `ret != x / y`. Also, the rounding mode does not matter, the result is incorrect regardless.

This issue is a blocker for tracetesting and running floating-point emulateme tests (rizinorg/rizin-testbins#147) for x86 floating-point RzIL (#3865).

**Comment by DMaroo** [comment]
Tagging @Heersin since they may be interested.

**Comment by Heersin** [comment]
Marked

**Comment by XVilka** [comment]
@Heersin do not forget about this one too, please
