### ISSUE TITLE
Buggy project parsing

### ISSUE THREAD

**Issue by elicn** [rizinorg/rizin#4296]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 11 64 bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.0 @ windows-x86-64 commit: d3bac05e5619b28a0e02eb1e7790315dc8311422

### Expected behavior
Saving a project and load it properly on another time.

### Actual behavior
Tried to disassemble a PE file with a given PDB file and a specific base address (`-B`). Saving project on rizin CLI and reloading it (either on CLI or Cutter) fails.

### Steps to reproduce the behavior
I am sorry but the file is not shareable neither an Asciinema, however I've added a redacted transcript of the commands and output. Hope it helps..

#### Repro Steps:
These are the commands I used. All of them seemed to work fine with the expected results (most of the output was left out for brevity).

```
rizin.exe -B 0x7ff04000 "C:\Path to\myfile.exe"
 -- If you want to open the file in read-write mode, invoke rizin with '-w'
[0x7ff04288]> idp "C:\Path to\myfile.pdb"
[0x7ff04288]> aaa
[0x7ff04288]> afl
[0x7ff04288]> pdf @ pdb.myfile.somefunc
[0x7ff04288]> Ps "C:\Path to\myfile.rzdb"
[0x7ff04288]>  (Ctrl+D)
Do you want to save the 'C:\Path to\myfile.rzdb' project? (Y/n) y
```
Then:
```
rizin.exe -p "C:\Path to\myfile.rzdb"
ERROR: Global variable gSomeGlobalVar at 0x7ff19f60 already exists!
ERROR: core: Failed to load project: invalid content encountered
  functions parsing failed
 -- You can redefine descriptive commands in the hud file and using the 'V_' command.
[0x00016288]>
```
Though the initial seek address does not take the correct base address into account, commands like `afl` seem to produce results that make sense. However, attempts to `pdf` a function or `px` an address that used to belong to a function shown on `afl` result in either "invalid" instructions or ff's.

The project cannot be opened by Cutter as well:
![image](https://github.com/rizinorg/rizin/assets/10291650/af5697e8-ffd7-4778-9814-573cd4aa8f1d)

Some additional notes:
 1. Repeating these steps (i.e. loading the binary with its PDB) on Cutter produces the same results: a corrupted project file regardless of specifying a binary load address
 2. Attempts to browse through the binary on Cutter (e.g. pressing 'x' to open xrefs or right clicking an address) result in a total crash: Cutter just disappears without any error messages. Not sure this is related though..
 3. All the problems described in this issue appear on the latest version of rizin (0.7.0) but not on the previous version (Cutter 0.6.2 @ windows-x86-64 commit: 18b1243435df428b58bcefc4ec37aef558aab96e)

**Comment by XVilka** [comment]
I guess it's related to recent changes in parsing global variables from PDB; not sure how, though. cc @imbillow

**Comment by b1llow** [comment]
@elicn I used a random pe file that seems to be fixed in this PR, can you try it?

**Comment by elicn** [comment]
Where can I find the built binary? (I am using Windows)

**Comment by p371jah** [comment]
> Where can I find the built binary? (I am using Windows)

AppVeyor artifacts https://ci.appveyor.com/project/rizinorg/rizin/builds/49277611

**Comment by elicn** [comment]
Thank you fellow black cat.

The corrupted project issue seems to be solved now: I can save and restore the project just fine. However, when restoring the project, rizin falls back to the default base address rather than the one used to load the original binary. That is, if I load the binary with `-B 0x7ff00000`, save the project and then restore it, all data will be located at default offsets (low addresses) instead of the one I originally used. `afl` info will show the expected addresses, but when I `pdf` a function I get all "invalid" instructions and if I `px` an address it shows all FF's.

**Comment by XVilka** [comment]
@elicn that base address issue, was it happening before too? e.g. on 0.6.3? Or is it new to the 0.7.0 as well?

**Comment by elicn** [comment]
Tested it on rizin 0.6.2 @ windows-x86-64 commit: 18b1243435df428b58bcefc4ec37aef558aab96e.
It has the same base address issue.

Steps:
 1. Load a binary with `-B` specifying an address
 2. `idp` to load the PDB file (not sure this is actually relevant)
 3. `Ps` to save the project
 4. Exit rizin and load the project with `-p`
 5. `afl` output shows correct adresses (maybe because of the PDB info?)
 6. `pdf`-ing a function results in all "invalid" instructions
 7. `px`-ing the same address shows all FF's

**Comment by XVilka** [comment]
@elicn ok, that's a separate issue; I extracted it. Lets close this one
