### ISSUE TITLE
[Miscellaneous] Auto publish releases to Winget

### ISSUE THREAD

**Issue by Dragon1573** [rizinorg/rizin#4344]
## Is this feature request related to a problem?

NO. This feature is not for `rizin` executables.

Currently, this application is submitted to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) as `Rizin.Rizin` by contributors or volunteers. The manifest is manually updated at the moment, so some of the users complaining about the outdated manifests.

The moderators of [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) recommend authors or publishers automate their submit process, so a newer manifests can immediately noticed and submitted to the repository once the package is released.

## Targets we want to achieve

Configure a GitHub Workflow, automatically invoked when new release of this repository was published. The Workflow can create manifests of the new release and submit to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs).

## Alternatives

Nope. I would prefer the above sulution.

## Additional context

- See https://github.com/microsoft/winget-pkgs/issues/142824#issuecomment-1984772380
- There are [example configurations](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml) by Microsoft PowerToys

**Comment by Dragon1573** [comment]
Seems nobody is interested in this suggestion. This issue will be closed as "Not planned".

**Comment by XVilka** [comment]
We are interested, but we don't have time for this as our limited efforts go into other things with bigger priorities. We will happily review the PR.
