### ISSUE TITLE
Add mention of `str.search.*` variables in the help of `iz` and `izz`.

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4399]
Just like `w??` has more details, I think the same approach could be used for `iz` commands, explaining how `str.search.*` affect the output.

See:
- `librz/core/cmd_descs/cmd_info.yaml`
- `librz/core/cmd_descs/cmd_write.yaml`

**Comment by w0rm29** [comment]
i can take it

**Comment by w0rm29** [comment]
do i need to add `src.seacrh.*` to the iz description?
