### ISSUE TITLE
Release `.tar.gz` and `.zip` lack version prefix `v` in folder name.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/rizin#4430]
Release `.tar.gz` and `.zip` lack version prefix `v` in folder name.

### Expected behavior
Released `.tar.gz`, `.zip`, and `.tar.xz` be indentical in decompressed content and files be named `rizin-vX.X.X`.

### Actual behavior
- `.tar.gz` and `.zip` has compressed file and root folder named `rizin-X.X.X` instead of `rizin-vX.X.X`.
- `.tar.xz` is as expected only.

### Steps to reproduce the behavior
Download and decompress the `.tar.gz`, `.zip` and `.tar.xz` files listed under [releases](https://github.com/rizinorg/rizin/releases).

**Comment by wargio** [comment]
Do you refer to the source code generated by GitHub ? if yes, then we cannot control that.

**Comment by Semnodime** [comment]
Yes, I was referring to the two assets at the bottom of the Release page, named Source Code.

**Comment by Semnodime** [comment]
Since the names actually do include the version number, I wonder how the name is generated.

Simply omitting the first character of the release tag would seem quite arbitrary, especially if it only happened for tags starting with 'v'.

**Comment by wargio** [comment]
i have actually no idea. this sounds like more a bug in GH release process. unfortunately we do not control them

**Comment by ret2libc** [comment]
Yeah if it's about the GH-generated source code it doesn't really matter. They should not be used anyway by people because we provide the `-src` tarballs which include *for real* all necessary code to build Rizin.

**Comment by ret2libc** [comment]
I'm going to close, but if there's something we can do to fix it, happy to re-open! Thanks
