### ISSUE TITLE
Show file/address space percentage in the right screen corner in the visual mode

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4477]
[Neo]Vim shows the percentage of the file, where you are located in the bottom right corner. Rizin could show it too, in visual modes. Both top right and bottom right corner locations are fine:

<img width="1431" alt="Screenshot 2024-05-06 at 9 12 18 PM" src="https://github.com/rizinorg/rizin/assets/203261/5cc86987-e5bc-4c4a-b23f-a3c8d38af27d">

<img width="1149" alt="Screenshot 2024-05-06 at 9 13 03 PM" src="https://github.com/rizinorg/rizin/assets/203261/d3d9b283-69e2-4e75-8934-e55bb8cf4f30">

<img width="1039" alt="Screenshot 2024-05-06 at 9 12 40 PM" src="https://github.com/rizinorg/rizin/assets/203261/6ddb7281-c03e-44e2-bca7-32aa18a6f829">

See how it's done in NeoVim:

<img width="1512" alt="Screenshot 2024-05-06 at 9 15 51 PM" src="https://github.com/rizinorg/rizin/assets/203261/3a4b3f82-05ae-4835-b3ca-1cd56c3cab83">

**Comment by PeiweiHu** [comment]
I am on it.

**Comment by p371jah** [comment]
Exactly how much is 1% in 64 bit address space?

**Comment by XVilka** [comment]
@pelijah, we don't need to show *all* of the address space. Just mapped regions.
