### ISSUE TITLE
Pic18 call instructions not detected

### ISSUE THREAD

**Issue by karliss** [rizinorg/rizin#4520]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Arch x86_64
| File format of the file you reverse (mandatory)      | .hex
| Architecture/bits of the file (mandatory)            | PIC18
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.7.3 @ linux-x86-64

### Expected behavior

Call instructions produce an xref to target instruction.  Call instructions are used to for detecting function starts

### Actual behavior

No xrefs for call instructions. Only one function found in the file.

### Steps to reproduce the behavior
-  https://github.com/rizinorg/rizin-testbins/blob/master/pic18c/FreeRTOS-pic18c.hex

### Additional Logs, screenshots, source code,  configuration dump, ...
![image](https://github.com/rizinorg/rizin/assets/7101031/2b652aa6-6671-4599-b7a4-2fa91e94da68)

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by karliss** [comment]
Need to retest with rizin dev.
![image](https://github.com/rizinorg/rizin/assets/7101031/5892705c-34b8-4ead-974c-1e56e1d4ab84)

**Comment by XVilka** [comment]
Looks like we don't have function-level analysis tests for PIC, just see `test/db/analysis/pic` - we should extend the testing as well, not only the RzIL.

**Comment by karliss** [comment]
Retested with rizin 0.8.0 @ linux-x86-64  7b91fb69c2e805645de3e89da28532932908f699 . Same thing. If I understand things correctly, doesn't seem like pic18_analysis sets anything for call instruction beside the instruction type.  

The  steps I did:
* `rizin -a pic ihex://rizin-test-bins/pic18c/FReeRTOS-pic18c.hex`
* `e asm.cpu` -> verify that asm.cpu is set to pic18 seems to be the default value without me setting it manualy
* `aaa` probably not needed, but just in case
* `axf @ 0x12e`  one of the first call instructions in file
