### ISSUE TITLE
"afl." caused segmentation fault at middle of function

### ISSUE THREAD

**Issue by davendu** [rizinorg/rizin#455]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.10 docker image (`ubuntu:20.10`)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | amd64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git 25593 @ linux-x86-64 git.0.2.0-git commit: 3821e0362096bae23a3d75178b82ac65d47fc967 build: 2021-01-25__13:15:23

### Expected behavior

Print a list of current function, like: `0x0000c540  111 33208 -> 2469 fcn.0000c540`

### Actual behavior

`Segmentation Fault (core dumped)`

### Steps to reproduce the behavior
- `docker run -it --rm ubuntu:20.10` and compile latest RIzin in Docker
- Run `rizin /bin/ls` in docker
- Run `aaa` in rizin's shell
- Choose any random function in the output of `afl`, for example, `0xc540`
- Run `afl.`. The output should be `0x0000c540  111 33208 -> 2469 fcn.0000c540`
- Seek to `s 0xc541` and run `afl.`, Rizin would crash.

### Additional Logs, screenshots, source code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/58910463/105711620-c495ad80-5f53-11eb-9141-3565bd62628d.png)

**Comment by ret2libc** [comment]
Hi @davendu . I have created https://github.com/rizinorg/rizin/pull/456 with a fix for this issue. If you want to try it, your feedback is welcome. The solution is of course to not segfault, but I also chose to make `afl.` behave similar to `afi.`: even if you are in the middle of a function, the current function you are in will be considered anyway.

**Comment by davendu** [comment]
Hi @ret2libc. Great, I’ll check it tomorrow.

Actually I’m not sure how it should behavior. I just type commands randomly for learning how to use Rizin. So I think fix the crash is enough for me. I’m not sure if anyone else have other ideas about this command.

BTW I think I can write a test for this function. Is it necessary? If so, should I push to refs/fix-655 directly or open another PR?

发自我的iPhone

在 2021年1月25日，22:24，Riccardo Schirone <notifications@github.com> 写道：

﻿

Hi @davendu<https://github.com/davendu> . I have created #456<https://github.com/rizinorg/rizin/pull/456> with a fix for this issue. If you want to try it, your feedback is welcome. The solution is of course to not segfault, but I also chose to make afl. behave similar to afi.: even if you are in the middle of a function, the current function you are in will be considered anyway.

**Comment by ret2libc** [comment]
> BTW I think I can write a test for this function. Is it necessary? If so, should I push to refs/fix-655 directly or open another PR?

Opening a new PR is fine. I don't think you can push to that PR.
Have a look at https://github.com/rizinorg/rizin/blob/dev/test/README.md and how other tests are written to write the test for it. Tests are always welcome :)
