### ISSUE TITLE
Serialize RzIL

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4553]
Currently we serialize RzAnalysis but do not store RzIL. We might want to consider also serializing it as well.

**Comment by wargio** [comment]
i don't think it is useful. also if we serialize it we need to de-serialize it.

**Comment by thestr4ng3r** [comment]
Depends on what kind of info there is that would be worth serializing and restoring. Most of the state of emulation is stored in RzReg and memory instead.

**Comment by Rot127** [comment]
Can't think of a specific use case, either. As @thestr4ng3r already said, since the operation depends on input, we would need to save this input state as well. Which sounds like a lot of work, if we don't have any good reason to do so.
