### ISSUE TITLE
Incorrect handling of OpenBSD specific code

### ISSUE THREAD

**Issue by cjeker** [rizinorg/rizin#4576]
The OpenBSD handling in bsd_debug.c is incorrect. The inspected flags have nothing to do with the execution state of the process. In OpenBSD -current the PS_STOPPED field was removed and so this code no longer compiles.

https://github.com/rizinorg/rizin/blob/2b4aa5351eb1f6721a629bd20a8d659d5c09d99e/librz/debug/p/native/bsd/bsd_debug.c#L223-L231

That code should do the same as the FreeBSD and NetBSD code and inspect p_stat. This will return the scheduler state (SSLEEP, SSTOP, SRUN, SONPROC and SDEAD) of the main thread.

I do not use rizin but was notified about the build failure on OpenBSD-current. This is why I open this issue.

See also https://github.com/radareorg/radare2/issues/23158 for the same issue in radare2.

**Comment by Rot127** [comment]
@thestr4ng3r Do you have a working OpenBSD machine? I tried to set up a VM quickly, but it takes forever to get it to a state to compile Rizin.

**Comment by cjeker** [comment]
I created a PR #4579 with the change that was committed to the OpenBSD ports repository to fix this issue.

**Comment by cjeker** [comment]
I guess this can be closed now. Right?
