### ISSUE TITLE
`aar` ignores `analysis.jmp.cref` value

### ISSUE THREAD

**Issue by p371jah** [rizinorg/rizin#469]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | 6814610

Option `analysis.jmp.cref` is set to false by default but `aar` ignores its value and anyway creates xrefs for conditional jumps.

See `librz/core/cmd_analysis.c` for how `aar` command is implemented.

**Comment by fangxlmr** [comment]
@ss-buyi This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka
