### ISSUE TITLE
Mini-map/graph view - Shift-TAB doesn't go to the previous node

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#551]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 commit: 96ea7e512691f5fa7a2094b9d78d0f96e16114b2, build: 2021-02-09__14:08:36

### Expected behavior
Pressing Shift-TAB in mini-map/graph view (`VV` + `pp`) goes back to the previous node.

### Actual behavior
Pressing Shift-TAB in mini-map/graph view does nothing.

### Steps to reproduce the behavior
- `rz /bin/rizin`
- `s main`
- `af`
- `VV`
- `pp`
- Press `TAB`
- Press `Shift-TAB`
- 💔 

This bug also happens in the pre-built 0.1.0 release.

This bug is not present in radare2 (git and latest release).

**Comment by ret2libc** [comment]
It was removed by mistake in a commit. I'm going to fix it.

**Comment by ret2libc** [comment]
Fixed with https://github.com/rizinorg/rizin/pull/553
