### ISSUE TITLE
Background server blocks Rizin

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#554]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 commit: 3e64a2e16a4a4d4bc7879299152e67c99084a685, build: 2021-02-09__17:04:35

### Expected behavior
Starting a background rap server (`=&:`) starts the server in the background, allowing to perform other Rizin commands and exit.

### Actual behavior
Starting a background rap server blocks Rizin (though the server works), making it impossible to kill the server or exit Rizin. Performing `Ctrl+z` and killing the background process is the only way to exit.

### Steps to reproduce the behavior
- `rz -q -c '=&: 8080 ; echo hi' --`
- Mmm, `hi` wasn't printed?
- Presses `Ctrl+c`
- 💔 

This issue is also present in radare2, but I am pretty sure this used to work...

**Comment by ret2libc** [comment]
Trying to reproduce, I get this:
```
$ rizin -q -c '=&: 8080 ; echo hi' --
Failed to set cpu affinity
Background rap server started.
hi
rap: listening at port 8080 ssl off
RAP Server started (rap.loop=true)
^Caccept: Invalid argument
```
and ^C worked.

Could you do `ldd $(which rizin)` please?

**Comment by caribpa** [comment]
Ha, interesting.

Did your server exit after pressing Ctrl+C?

`ldd $(which rizin)`:
```
	linux-vdso.so.1 (0x00007ffebfff0000)
	librz_util.so.0.2.0-git => /usr/bin/../lib/librz_util.so.0.2.0-git (0x00007fe545dd8000)
	librz_main.so.0.2.0-git => /usr/bin/../lib/librz_main.so.0.2.0-git (0x00007fe545d9e000)
	libpthread.so.0 => /usr/bin/../lib/libpthread.so.0 (0x00007fe545d7d000)
	libc.so.6 => /usr/bin/../lib/libc.so.6 (0x00007fe545bb0000)
	libdl.so.2 => /usr/bin/../lib/libdl.so.2 (0x00007fe545ba9000)
	libm.so.6 => /usr/bin/../lib/libm.so.6 (0x00007fe545a64000)
	libz.so.1 => /usr/bin/../lib/libz.so.1 (0x00007fe545a48000)
	libcrypto.so.1.1 => /usr/bin/../lib/libcrypto.so.1.1 (0x00007fe54576a000)
	librz_socket.so.0.2.0-git => /usr/bin/../lib/librz_socket.so.0.2.0-git (0x00007fe545759000)
	librz_flag.so.0.2.0-git => /usr/bin/../lib/librz_flag.so.0.2.0-git (0x00007fe54574d000)
	librz_cons.so.0.2.0-git => /usr/bin/../lib/librz_cons.so.0.2.0-git (0x00007fe545717000)
	librz_hash.so.0.2.0-git => /usr/bin/../lib/librz_hash.so.0.2.0-git (0x00007fe54570e000)
	librz_crypto.so.0.2.0-git => /usr/bin/../lib/librz_crypto.so.0.2.0-git (0x00007fe5456e9000)
	librz_io.so.0.2.0-git => /usr/bin/../lib/librz_io.so.0.2.0-git (0x00007fe5456a9000)
	librz_reg.so.0.2.0-git => /usr/bin/../lib/librz_reg.so.0.2.0-git (0x00007fe54569c000)
	librz_bp.so.0.2.0-git => /usr/bin/../lib/librz_bp.so.0.2.0-git (0x00007fe545695000)
	librz_syscall.so.0.2.0-git => /usr/bin/../lib/librz_syscall.so.0.2.0-git (0x00007fe54568e000)
	librz_parse.so.0.2.0-git => /usr/bin/../lib/librz_parse.so.0.2.0-git (0x00007fe545629000)
	librz_asm.so.0.2.0-git => /usr/bin/../lib/librz_asm.so.0.2.0-git (0x00007fe545207000)
	librz_egg.so.0.2.0-git => /usr/bin/../lib/librz_egg.so.0.2.0-git (0x00007fe5451f4000)
	librz_search.so.0.2.0-git => /usr/bin/../lib/librz_search.so.0.2.0-git (0x00007fe5451ec000)
	librz_analysis.so.0.2.0-git => /usr/bin/../lib/librz_analysis.so.0.2.0-git (0x00007fe544f64000)
	librz_debug.so.0.2.0-git => /usr/bin/../lib/librz_debug.so.0.2.0-git (0x00007fe544f17000)
	librz_config.so.0.2.0-git => /usr/bin/../lib/librz_config.so.0.2.0-git (0x00007fe544f0e000)
	librz_bin.so.0.2.0-git => /usr/bin/../lib/librz_bin.so.0.2.0-git (0x00007fe544dad000)
	librz_core.so.0.2.0-git => /usr/bin/../lib/librz_core.so.0.2.0-git (0x00007fe544b41000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe545eb9000)
	libssl.so.1.1 => /usr/bin/../lib/libssl.so.1.1 (0x00007fe544ab0000)
	libxxhash.so.0 => /usr/bin/../lib/libxxhash.so.0 (0x00007fe544aa4000)
	libzip.so.5 => /usr/bin/../lib/libzip.so.5 (0x00007fe544a85000)
	libcapstone.so.4 => /usr/bin/../lib/libcapstone.so.4 (0x00007fe54441b000)
	librz_magic.so.0.2.0-git => /usr/bin/../lib/librz_magic.so.0.2.0-git (0x00007fe544416000)
	liblz4.so.1 => /usr/bin/../lib/liblz4.so.1 (0x00007fe5443f3000)
	librz_lang.so.0.2.0-git => /usr/bin/../lib/librz_lang.so.0.2.0-git (0x00007fe5443e3000)
	libtree-sitter.so.0 => /usr/bin/../lib/libtree-sitter.so.0 (0x00007fe5443b6000)
	libuv.so.1 => /usr/bin/../lib/libuv.so.1 (0x00007fe544383000)
	libbz2.so.1.0 => /usr/bin/../lib/libbz2.so.1.0 (0x00007fe544370000)
	liblzma.so.5 => /usr/bin/../lib/liblzma.so.5 (0x00007fe544348000)
	libgnutls.so.30 => /usr/bin/../lib/libgnutls.so.30 (0x00007fe544145000)
	libnettle.so.8 => /usr/bin/../lib/libnettle.so.8 (0x00007fe5440fd000)
	libmagic.so.1 => /usr/bin/../lib/libmagic.so.1 (0x00007fe5440d1000)
	libp11-kit.so.0 => /usr/bin/../lib/libp11-kit.so.0 (0x00007fe543f9c000)
	libidn2.so.0 => /usr/bin/../lib/libidn2.so.0 (0x00007fe543f7b000)
	libunistring.so.2 => /usr/bin/../lib/libunistring.so.2 (0x00007fe543df9000)
	libtasn1.so.6 => /usr/bin/../lib/libtasn1.so.6 (0x00007fe543de3000)
	libhogweed.so.6 => /usr/bin/../lib/libhogweed.so.6 (0x00007fe543d9a000)
	libgmp.so.10 => /usr/bin/../lib/libgmp.so.10 (0x00007fe543cf8000)
	libffi.so.7 => /usr/bin/../lib/libffi.so.7 (0x00007fe543cec000)
```

I installed Rizin from the following [AUR package](https://aur.archlinux.org/packages/rizin-git/).

**Comment by caribpa** [comment]
Both `/lib` and `/lib64` are symlinks to `/usr/lib`.

**Comment by ret2libc** [comment]
> Did your server exit after pressing Ctrl+C?

Yes it did!

**Comment by caribpa** [comment]
Wow.

What happens when you start the background server in the interactive command line:
```
rz --
=&: 8080
```

Can you still perform other commands after starting the server?

**Comment by ret2libc** [comment]
```
$ ./builddir/binrz/rizin/rizin --
 -- Most of commands accept '?' as a suffix. Use it to understand how they work :)
[0x00000000]> =&: 8080
Failed to set cpu affinity
Background rap server started.
[0x00000000]> rap: listening at port 8080 ssl off
RAP Server started (rap.loop=true)
[0x00000000]> 
[0x00000000]> pd 10
            0x00000000      invalid
            0x00000001      invalid
            0x00000002      invalid
            0x00000003      invalid
            0x00000004      invalid
            0x00000005      invalid

```

Interesting. I will try with archlinux container.

**Comment by ret2libc** [comment]
However, after I do ^D to exit rizin, I cannot kill the rizin process anymore and i have to do `pkill rizin`.

**Comment by caribpa** [comment]
Certainly something is going on as I just tried with the static release after even uninstalling Rizin-git and the same issue is there.

I tried in different terminals (`xterm` and `urxvt`), as well as different shells and nope, the background server blocks Rizin.

**Comment by caribpa** [comment]
Can you try the [static build](https://github.com/rizinorg/rizin/releases/download/v0.1.0/rizin-v0.1.0-static-x86_64.tar.xz)?

**Comment by ret2libc** [comment]
> Can you try the [static build](https://github.com/rizinorg/rizin/releases/download/v0.1.0/rizin-v0.1.0-static-x86_64.tar.xz)?

Reproduced with static build, yeah!

**Comment by caribpa** [comment]
> Reproduced with static build, yeah!

Wooo! I'm not crazy 🎉

**Comment by ret2libc** [comment]
> > Reproduced with static build, yeah!
> 
> Wooo! I'm not crazy tada

Eheh, never thought that ;) I think it is a race condition. I tried to build the rizin-git AUR pkg on archlinux container and with all the dependency libs I was able to reproduce, however it is enough to re-compile without, for example, capstone sys dependency and it does not reproduce anymore.

**Comment by ret2libc** [comment]
Still a bug
