### ISSUE TITLE
-= flag - Use-case scenario?

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#566]
**Is your feature request related to a problem? Please describe.**
The use-case for the `-=` flag is unclear/unnecessary.

Unless I am missing something, there's no circumstance where using `-=` (command line shortcut for `!=!`, according to the help `-h`, though it behaves like `=!=`) is useful:
- Server `cd /bin`, `rz rap://:8080`
- Client: `rz -c '=+ rap://localhost:8080/rizin' -= --` ❎ Doesn't start a remote cmd with the server, same with TCP/UDP

On the other hand, shouldn't `-=` imply `--` to avoid the weird `-= --` sequence as Rizin still asks for a file when using `-=`?

**Describe the solution you'd like**
Either an explanation for the use-case of `-=` or removal of the flag.

**Describe alternatives you've considered**
💔 

**Additional context**
This behavior is the same in radare2.

**Comment by XVilka** [comment]
I would vote for removing it.

**Comment by ret2libc** [comment]
Yeah I guess it is just easier/better to have the user do `rizin -c '=+ rap://localhost:8080/meson.build;=!=' --` instead of the flag.

**Comment by caribpa** [comment]
> Yeah I guess it is just easier/better to have the user do rizin -c '=+ rap://localhost:8080/meson.build;=!=' -- instead of the flag.

Note that `-=` do nothing in every case as it tries to start a remote cmd mode without actually connecting to the remote server (it simply changes the prompt to `[=!0x00000000]>`, but it is not interacting with the remote server).

In order for the remote connection to be established after connecting with `=+`, a descriptor needs to be passed to `=!=` (though this currently doesn't work in Rizin: #552):
- `rz -c '=+ rap://localhost:8080/rizin ; =!= 0' --` ✅ Correctly starts a remote cmd with the server
- `rz -c '=+ rap://localhost:8080/rizin' -= --` ❎ Connects and just changes the prompt to `[=!0x00000000]>`
