### ISSUE TITLE
Java bytecode disassembly/analysis/binary parsing code refactoring

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#569]
The existing code of the JVM bytecode disassembly, analysis, and binary parsing is truly terrible and not very well integrated with the rest of Rizin code. I propose to:
- [x] Remove the dsojson.c and use RzUtil functions
- [x] Write tests for different JVM bytecode versions in our testsuite
- [x] Refactor the code to reduce duplication, maybe move it out of the `shlr/` directory
- [ ] Compare the results with other Java reversing tools
- [ ] Provide better integration of the same features with the DEX analysis
- [x] Various bugfixes and improvements along the way

**Comment by ret2libc** [comment]
What about moving it out of rizin repository into extras until someone show proper interest in making this really better?

**Comment by wargio** [comment]
Remove DsoJson here: https://github.com/rizinorg/rizin/pull/585

**Comment by XVilka** [comment]
@wargio @ret2libc lets close this issue since majority of it had been done already. The only left part is assembly, right?
And maybe better integration with DEX
