### ISSUE TITLE
Ctrl+S - Forward-search

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#571]
**Is your feature request related to a problem? Please describe.**
When using `Ctrl+R` to use the backward-search you may accidentally skip the history result you wanted and you are forced to cancel the search and start from the beginning.

**Describe the solution you'd like**
Pressing `Ctrl+S` performs forward-search (like emacs/readline), allowing selecting the history result you just skipped.

**Describe alternatives you've considered**
💔 

**Additional context**
As an emacs user, this issue annoys me every time 🙂

By the way, there's something mapped in `Ctrl+S` that seems to cancel the search and move the cursor one character back when pressed out of the search-mode, what is it supposed to do?

**Comment by XVilka** [comment]
The fix would likely be needed here: [`librz/cons/dietline.c`](https://github.com/rizinorg/rizin/blob/dev/librz/cons/dietline.c)
