### ISSUE TITLE
Ctrl-_/Ctrl-/ and Meta-_/Meta-/ - Undo and Redo

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#572]
**Is your feature request related to a problem? Please describe.**
Sometimes you accidentally delete part of the command you are writing, to aid the clumsy user it would be nice to have an undo and redo keyboard shortcuts.

**Describe the solution you'd like**
Following the emacs/readline shortcuts:
- `Ctrl-_` or `Ctrl-/` for undoing
- `Meta-_` or `Meta-/` for redoing

Pressing multiple times undo/redo further.

**Describe alternatives you've considered**
💔 

**Additional context**
Truth is that readline doesn't seem to have a redo, and vanilla emacs has a "strange" redo: `Ctrl-_` or `Ctrl-/` for undoing, `Ctrl-g` for reversing the undo-action (not yet redid anything and only works right after an undo), now, after `Ctrl-g`, `Ctrl-_` or `Ctrl-/` perform redo until another `Ctrl-g` is pressed to reverse the meaning of `Ctrl-_` or `Ctrl-/`.

Some of the modern popular emacs packages/frameworks have `Ctrl-_` or `Ctrl-/` mapped as undo and `Meta-_` or `Meta-/` as redo to avoid the madness.

**Comment by ret2libc** [comment]
Are you suggesting we keep an history of every key pressed by the user so that we are able to restore his command line in case he deletes something? It might look a bit excessive at a first thought... 

Is this sort of feature implemented in bash/zsh?

**Comment by caribpa** [comment]
Both bash and zsh have this feature.

One you press `Enter`, the undo history is flushed.

**Comment by ret2libc** [comment]
> Both bash and zsh have this feature.
> 
> One you press `Enter`, the undo history is flushed.

You never finish to learn..... Wow, I wasn't aware of this feature even though I've used bash for so long!! Thanks ;)

**Comment by XVilka** [comment]
The fix would likely be needed here: [`librz/cons/dietline.c`](https://github.com/rizinorg/rizin/blob/dev/librz/cons/dietline.c)

**Comment by kui8shi** [comment]
Hello, I would like to do this as a microtask required for the application of GSoC2023. it may be late but is it still ok?
Now I looked the codebases of rizin and bash and have made functions which are triggered when ctrl-/ or ctrl-_ are pressed, and when meta-/ or meta-_ are pressed, respectively.

**Comment by ret2libc** [comment]
@ez2take go ahead and submit a PR when ready :) feel free to join us on Mattermost to ask questions.
