### ISSUE TITLE
Ctrl-T and Meta-T - Transpose characters and words

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#582]
**Is your feature request related to a problem? Please describe.**
`Ctrl-T` and `Meta-T` are used in bash, zsh, and emacs to transpose characters and words. Example:
```sh
# Note that the cursor is represented with [ ]
$ zsh
# Writes the following and moves the cursor to the first o
> echo "hell[o] world"  # Enter is not pressed
# Presses Ctrl-t, now the command prompt looks like this:
> echo "helo[l] world"
```
Other example:
```sh
> echo "helol [w]orld" # Enter is not pressed
# Presses Meta-t, now the command prompt looks like this:
> echo "world helol["]
```

**Describe the solution you'd like**
In Rizin, `Ctrl-T` could be really useful to aid with typos (especially those regarding binary/hex representation):
```sh
$ rz /bin/rizin
> izq ~Usage
# 0x2150 53 52 Usage: rizin -c '!*rzp x' # run commands via rzpipe\n
> ps @ 0x1250
# \xff\xffH\x83\xf8\xff\x0f\x84\xd4
# Lazy Human: What?
# *Ctrl-p and places the cursor over the 2*
> ps @ 0x1[2]50
# *Presses Ctrl-t*
> ps @ 0x2150  # *Presses Enter*
# Usage: rizin -c '!*rzp x' # run commands via rzpipe
```
Not so sure about `Meta-T`, maybe in compound commands for moving the `;` around words.

**Describe alternatives you've considered**
💔 

**Additional context**
🤷

**Comment by ret2libc** [comment]
very niche feature, I think. I don't see this being done any time soon. Closing for now.
