### ISSUE TITLE
u/U - undo/redo seek - Documented but not working

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#595]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64, package: 0.2.0.r25701.639fe1170-git (AUR) commit: 639fe1170b33ec361f204c0a914fcd7a71c240c9, build: 2021-02-11__15:55:00

### Expected behavior
Pressing `u` performs undo seek (as stated in the general family help: `?*???`), pressing `U` performs redo seek.

### Actual behavior
Pressing `u` or pressing `U` return: `Command does not exist.`

### Steps to reproduce the behavior
- `rz --`
- `s++`
- `u`
- 💔 
- `U`
- 💔 

### Additional Logs, screenshots, source code,  configuration dump, ...
There's even a startup tip telling about these commands which happen to even be accidentally documented in this (unrelated) issue: #407

Moreover, `u` and `U` work in visual/panels mode.

In radare2, `u` performs `uname`, but undo is placed under `us`, whereas redo (`U`) doesn't work.

**Comment by ret2libc** [comment]
No, `u` and `U` are not commands. There's a problem in `?*???` it shouldn't actually print anything because it is not a valid command.

**Comment by ret2libc** [comment]
Use `sHu` / `sHr` for seek undo/redo.

**Comment by ret2libc** [comment]
As we are in the process of moving commands to newshell, there's some compatiblity layer still in place and `?*???` happens to be redirected to the `?` old command. We'll fix that.

**Comment by caribpa** [comment]
Two questions:
- Are there any plans for using `u` and `U` for something?
- Same question for `su` and `sU`

It is a bit weird to type `sHu` or `sHr` considering there's nothing in `sh` (and the other keys mentioned before), unless there's a plan for launching an interactive system shell with the `sh` command (not really necessary as `!sh` does it).

**Comment by ret2libc** [comment]
> Two questions:
> 
>     * Are there any plans for using `u` and `U` for something?

Not right now, but we don't exclude maybe some global `undo`/`redo` functionalities.

> 
>     * Same question for `su` and `sU`

Not really.

> 
> It is a bit weird to type `sHu` or `sHr` considering there's nothing in `sh` (and the other keys mentioned before), unless there's a plan for launching an interactive system shell with the `sh` command (not really necessary as `!sh` does it).

I have to agree it feels a bit weird... The reason to not use `sh` is to avoid confusion with the shell `sh` indeed. And the reason why `sHu`/`sHr` instead of other commands under `s` is because `sH` is "seek history", so the undo/redo functions are actually related to the seek history and I thought it made sense to group all of them under the same name. What do you think?

**Comment by caribpa** [comment]
I have no problem for not having `u`/`U` or `su`/`sU` related to seek. Especially if eventually there will be some global undo/redo under `u`/`U`. Though, if this will really be the case, aliasing `sHu` => `su` and `sHr` => `sU` will make consistent the usage of all the undo/redo key-maps in Rizin (again, because Visual/Panels mode use `u`/`U`).

What annoys me a little is that `sH` is not `sh`. Honestly, saying that `sH` was chosen instead of `sh` to avoid confusion with the shell (without planing to add nothing under `sh`) doesn't seem a compelling reason considering there are already some key combinations that offer a different functionality than the POSIX shell ones (`dd`, `ar`, `fc`, `fg`, `id`, to name a few), also there's `pdf` and `doc` that don't produce/open PDFs or documents 😃

**Comment by ret2libc** [comment]
> there are already some key combinations that offer a different functionality than the POSIX shell ones (dd, ar, fc, fg, id, to name a few), also there's pdf and doc that don't produce/open PDFs or documents smiley 

lol :D good points actually. cc @XVilka @ITAYC0HEN @Maijin  ? thoughts about undo/redo command names?

**Comment by Maijin** [comment]
I think that, till undo and redo are only used for seek I think keeping it under `s` would make more sense than having it under `u/U`.
Once undo/redo are able to do more (analysis, writing, hints etc.) then we should revisit this.
