### ISSUE TITLE
Command 'exit' does not exist

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#607]
**Is your feature request related to a problem? Please describe.**
The `exit` command can be used in radare2 to exit. Unfortunately this command is not recognized in Rizin. Users unfamiliar with the `vi` editor family (or shells, as `Ctrl-D` also exits) may have a hard time exiting Rizin.

**Describe the solution you'd like**
Re-add the `exit` command so a newbie can exit Rizin without stress.

**Describe alternatives you've considered**
💔 

**Additional context**
The static 0.1.0 release also doesn't have `exit`.

**Comment by officialcjunior** [comment]
If `exit` is going to be equal to `q` command, it's just a line long, so we can make `exit` a new command without thinking much.
Where should it be added? `cmd_quit.yaml` as well?

**Comment by ret2libc** [comment]
> If `exit` is going to be equal to `q` command, it's just a line long, so we can make `exit` a new command without thinking much.

Yes, it is just that.

> Where should it be added? `cmd_quit.yaml` as well?

No, I believe it makes more sense to have it directly in the root tree, in `cmd_descs.yaml`.

**Comment by officialcjunior** [comment]
Sure. And the actual function handler should go at... `cmd_quit.c` ?

**Comment by ret2libc** [comment]
> Sure. And the actual function handler should go at... `cmd_quit.c` ?

That's fine, yes. Or just in `cmd.c`, as you prefer.
