### ISSUE TITLE
Add conditional check specific to a file extension.

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#609]
**Is your feature request related to a problem? Please describe.**
The CI is really slow.

**Describe the solution you'd like**
Add conditional check (path check).

**Describe alternatives you've considered**
...

**Additional context**
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by ret2libc** [comment]
Last time we tried there were some problems related to the fact that some jobs are *required*, thus if they are not run because skip by a path-check, the PR will never be green.

**Comment by ghost** [comment]
> Last time we tried there were some problems related to the fact that some jobs are _required_, thus if they are not run because skip by a path-check, the PR will never be green.

I will open a PR to test.
