### ISSUE TITLE
Filtering ?* is broken

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#611]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64, package: 0.2.0.r25723.954ea58ee-git (AUR) commit: 954ea58ee25064fb68d04d06b88ae1599da5154c, build: 2021-02-12__17:02:24

### Expected behavior
Filtering the output of `?*`, either with the built-in grep `~` or with a pipe `|`, returns filtered results.

### Actual behavior
Filtering the output of `?*` returns weird/wrong/no results.

### Steps to reproduce the behavior
- `rz --`
- `?* ~ascii`
- 💔 - no results
- `?* | grep ascii`
- 💔 - no results
- `?* ~register`
- 💔 - one result, same with system's grep through pipe

### Additional Logs, screenshots, source code,  configuration dump, ...
Note that redirecting the output to a file works: `?* > /tmp/test`

This issue is also present in the 0.1.0 static build, but not present in radare2.

**Comment by ret2libc** [comment]
> Note that redirecting the output to a file works: ?* > /tmp/test

Does it mean that in /tmp/test you find `ascii`?

Anyway, this is an issue but nothing we can do in the short run. The only solution is to move to newshell as many commands as possible. The reason is that `?*` now works with the data registered within newshell and all the old "type" of commands are not registered anywhere.  This issue will be automatically fixed as we move forward with newshell transition.

**Comment by caribpa** [comment]
> Does it mean that in /tmp/test you find `ascii`?

No 🙂, /tmp/test lists all possible Rizin commands. I could use system's grep to filter that file, though weirdly there's nothing with ascii (?).
This is weird, why it doesn't contain the help from `???` nor, for example `afb=` (the help message of these commands contain the word "ascii").

**Comment by ret2libc** [comment]
Because they need to be converted to newshell, sorry. See doc/newshell for some rough doc about it

**Comment by caribpa** [comment]
I get it now 👼 

Thanks for clarifying 👍
