### ISSUE TITLE
Add ** (exponentiation/power) to ? math operations

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#613]
**Is your feature request related to a problem? Please describe.**
The built-in math/logical calculation/conversion command `? <expression>` is quite handy. Unfortunately, in several occasions when calculating an offset, the fun is interrupted due to the missing exponentiation/power capabilities of `?`.

**Describe the solution you'd like**
Because `^` performs XOR, `**` can be used as symbol for exponentiation/power as it is what it's used in built-in bash and zsh math capabilities for this same purpose (zsh also accepts negative exponents):
```sh
$ rz --
> ?vi 3**6
# 729
> ? 2**-1 ~fvalue[1]
# 0.5
```

**Describe alternatives you've considered**
Currently bitwise left shift could be used with 2, but no shortcuts (other than multiplying the number, or parentheses operations, with itself multiple times) exist for the other numbers/parentheses operations 💔 

**Additional context**
🤷

**Comment by majodu** [comment]
If possible could I take this issue?

**Comment by ret2libc** [comment]
> If possible could I take this issue?

Sure! You can work on whatever you prefer ;)

**Comment by ret2libc** [comment]
This issue is still clearly described, so I'm removing the stale flag in case some newcomers want to give it a shot since it should be quite easy to implement. Low prio however.

**Comment by DhruvaG2000** [comment]
> Because ^ performs XOR, ** can be used as symbol for exponentiation/power

The challenge in using ``**`` as the new operator would be that the way operations are implemented currently is using a char input to a switch statement. If there's an easy work around for this please do let me know.

**Comment by wargio** [comment]
you can switch to `*` and then check if the next char is another `*`

**Comment by ret2libc** [comment]
> > Because ^ performs XOR, ** can be used as symbol for exponentiation/power
> 
> The challenge in using `**` as the new operator would be that the way operations are implemented currently is using a char input to a switch statement. If there's an easy work around for this please do let me know.

See for example how `RNCROR` `RNCSHR` and `RNCGT` are handled.

**Comment by DhruvaG2000** [comment]
> See for example how RNCROR RNCSHR and RNCGT are handled.

Thanks @ret2libc this pointer helped alot. now `**` works 😄
