### ISSUE TITLE
Rizin server - Add --server/-S flags - Remove opening a rap server

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#614]
**Is your feature request related to a problem? Please describe.**
As discussed in #593, the ability to start a rap server using `rap://:<port>` as a `<file>` parameter, and with `o` from the interactive Rizin's command line, is inconsistent with the overall `o` usage and the ability to start other servers.

In summary:
- `o` and `<file>` will no longer be able to start a rap server.
- To allow starting Rizin in server mode, the command line flags `--server` and `-S` will be added.

**Describe the solution you'd like**
```sh
$ rz --server rap://:8080 ✅
$ rz -S rap://:8080 ✅ 
$ rz rap://:8080 ❎ 
$ rz --server tcp://:8080 ✅ 
$ rz -S gdb://:8080 ✅ 
$ rz -q -c '=: 8080' -- ✅ 
$ rz -q -c 'o rap://:8080' -- ❎ 
```

**Describe alternatives you've considered**
💔 

**Additional context**
🤷

**Comment by caribpa** [comment]
After `--server`/`-S` are added, maybe the `-C` flag is a bit redundant/really-specific:

>  -C           file is host:port (alias for -c+=http://%s/cmd/)

Thoughts?

**Comment by ret2libc** [comment]
> After `--server`/`-S` are added, maybe the `-C` flag is a bit redundant/really-specific:
> 
> > -C           file is host:port (alias for -c+=http://%s/cmd/)
> 
> Thoughts?

I agree.

**Comment by caribpa** [comment]
Then, I think the `-C` flag could be converted into the abbreviation of `--client`/`--connect` which could be a shortcut for `-c '=+ <proto>/<addr>:<port>/[<file>|<pid>] ; =!= 0'` (or simulating the current rap client mode), making the following behavior consistent:
```sh
# Start Rizin in rap server mode
$ rz -S rap://:8080

# Start Rizin in remote rap client mode
$ rz -C rap://localhost:8080//bin/rizin

# Start Rizin in tcp server mode
$ rz --server tcp://:8080 /bin/rizin

# Start Rizin in remote tcp client mode
$ rz --client tcp://localhost:8080
```
