### ISSUE TITLE
-- (double dash) should be treated as "end of flags" | Allow launching Rizin without a <file>

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#615]
**Is your feature request related to a problem? Please describe.**
After discussing in #593, and concluding with #614, it occurred to me that there's no reason for forcing the user to specify something as `<file>` parameter when launching Rizin.

Moreover, currently the "open without file/plugin" behavior is achieved by passing `--` as `<file>` parameter to Rizin.
According to the [POSIX Utility Syntax - Guideline 10](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02):
> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

Meaning: `rz -- -test`, `rz -d -- -test`, etc shall treat `-test` as `<file>` instead of just parsing `--` and ignoring `-test`.

Try it with any non-built-in POSIX utility:
```sh
$ touch -- -test
$ ls -- -test
# -test
$ echo hi | tee -- -test
# hi
$ cat -- -test
# hi
```

**Describe the solution you'd like**
- `--` is used to signal "end of flags" to be consistent with the standard command line utilities syntax.
- The user shouldn't be forced to pass a `<file>` to Rizin

```sh
$ rz
# Starts Rizin like if the current -- (and not -, a.k.a malloc://512) was passed

$ rz --
# Starts Rizin exactly in the same way as described above

$ rz -test
# Starts Rizin in the same way as described above and attempts to parse the '-t' flag with 'est' as value

$ rz -- -test
# Starts Rizin and opens the -test file

$ rz -d -- -test
# Starts Rizin with the -test file in debug mode
```

**Describe alternatives you've considered**
💔 
Honestly, one could always use `./` or full/relative path to work around this:
```sh
$ rz ./-test
# Starts Rizin and opens the -test file
```

But there's still no reason for not allowing launching Rizin without `<file>`.

**Additional context**
This limitation is also present in radare2.

**Comment by ret2libc** [comment]
It seems actually reasonable and that it makes sense!

**Comment by XVilka** [comment]
The files to change are:
- `librz/main/rizin.c`
- rest of `librz/main/*.c` if we want to have the same behaviour for all Rizin tools.
