### ISSUE TITLE
Swap - (single dash) and = (equal sign) meaning

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#616]
**Is your feature request related to a problem? Please describe.**
This issue follows the same trend as #615 to standardize the special command line flags recognized when launching Rizin.

According to the [POSIX Utility Syntax - Guideline 13](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02):
> For utilities that use operands to represent files to be opened for either reading or writing, the '-' operand should be used to mean only standard input (or standard output when it is clear from context that an output file is being specified) or a file named -.

Meaning: `rz -`, `rz -d -`, etc, shall treat `-` as an indicator to start Rizin and process the data coming from stdin, instead of loading the `malloc://512` plugin.

Try it with any utility that reads a file:
```sh
$ echo hi | cat - > test
$ sed 's/./\U&/g' - < test
# HI
```
It shall be noted that using `--` (double dash) before `-` doesn't change the meaning of `-` as stdin (see #615):
```sh
$ echo hi | cat -- - > test
$ sed 's/./\U&/g' -- - < test
# HI
```

Surprisingly, Rizin is able to read (more or less) from the standard input, but uses the `=` special flag.

**Describe the solution you'd like**
Swap the `=` and the `-` special command line flags recognized by Rizin as `<file>` parameter:
- `-` should read from stdin, following the standard for command line utilities
- `=` should load the `malloc://512` plugin

```sh
$ rz - < /bin/rizin
# Starts Rizin and reads /bin/rizin from stdin

$ rz =
# Starts Rizin and loads the malloc://512 plugin
```

It shall be noted that currently reading from stdin doesn't truly work and mangles the terminal, see #617 (a `reset` solves it).

**Describe alternatives you've considered**
💔 

**Additional context**
This behavior is also present in radare2.

**Comment by caribpa** [comment]
Due to the fact that `=` is used in Rizin's interactive command line to refer to the client/server family, maybe it is a good idea to either:
- Remove the `=` special flag from Rizin's startup flags to avoid possible confusion with the client/server `=` meaning in interactive mode
- Move the `=` special startup flag to `--plugin m`/`-Pm` (new) regular flags
- Move the `=` interactive client/server family command to `R` (new) interactive family command (short for "Remote")

**Comment by ret2libc** [comment]
This also seems to be reasonable to me.

**Comment by XVilka** [comment]
I think it would be a good fit for 0.2.0 to break things early and don't change the behavior later.

**Comment by wargio** [comment]
i like it

**Comment by fangxlmr** [comment]
@seanachao This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by seanachao** [comment]
There are some test question, I will continue to resolve it .
