### ISSUE TITLE
Remove broken tail command or alias to cat <file> ~:-5..

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#623]
**Is your feature request related to a problem? Please describe.**
In #53, commands `head` and `less` (among others) were removed in favor of the `cat <file> ~:..10` and `cat <file> ~..` (respectively) filter commands.

However, the command `tail` is still present and its output seems broken (the first line outputted is incomplete) compared to `cat <file> ~:-5..`:
```sh
$ rz --
> tail test
# .                                                                                       ❎ 
# * Nam a sapien.
# * Nullam rutrum.
# * Praesent augue.
# * Integer placerat tristique nisl.

> cat test ~:-5..
# * Com sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ✅ 
# * Nam a sapien.
# * Nullam rutrum.
# * Praesent augue.
# * Integer placerat tristique nisl.
```

**Describe the solution you'd like**
In spirit of #53, I'd propose to remove `tail`.

Alternatively, remove current `tail` implementation and just alias `tail <n> <file>` to `cat <file> ~:-<n>..`, though aliases for `head` and `less` (`cat <file> ~:..<n>` and `cat <file> ~..` correspondingly) shall be also provided for consistency's sake. 

**Describe alternatives you've considered**
💔 

**Additional context**
The broken `tail` output issue also happens in radare2.

**Comment by ret2libc** [comment]
I think we can kill it, we probably missed it @XVilka

**Comment by officialcjunior** [comment]
I will look into this. Should the stuff needed for consistency's sake be done right now, as well?

**Comment by ret2libc** [comment]
I think it's enough to kill tail for now
