### ISSUE TITLE
Check if build_mig_index and related scripts still work

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#645]
This is mainly an exploration task. It seems like `build_mig_index.py` is used to create the `mig_index.h` file. To generate that, you need a `traps.json`, which is generated by `machtraps.py`.

We should check if `machtraps`/`build_mig_index` still work and actually add them to the meson files, so that they are automatically called if something needs to be updated.

Also, `machtraps` seems to be the only user of `aefa`, which in turns uses `arA`. This last command seems to have several limitations, so I was considering removing both `arA` and `aefa` altogether, but before doing so we should find an alternative for the mentioned python scripts.

**Comment by XVilka** [comment]
Fixed by https://github.com/rizinorg/rizin/commit/5f5c0d66dfdc01db1af782bb024c2873fdd27a1a
