### ISSUE TITLE
Add the possibility to disable dwarf source line information

### ISSUE THREAD

**Issue by xarkes** [rizinorg/rizin#653]
**Is your feature request related to a problem? Please describe.**

Currently if one wants to hide the information of source line, one has to do `e asm.dwarf=false` which might remove other useful dwarf information as well.
We discussed it in a PR for Cutter here https://github.com/rizinorg/cutter/pull/2600 and I'll detail the solution we thought would be the best. 

**Describe the solution you'd like**
- Rename `asm.pdb.lines` to `asm.debug.lines`
- When dwarf information is available:
  * If `asm.dwarf=true` and `asm.debug.lines=false` hide dwarf source line information
  * If `asm.dwarf=false` hide dwarf source line information anyways

Feel free to edit this issue in order to add more details.

**Comment by ret2libc** [comment]
I think what you suggest make sense and it should be fairly easy to do, however in practice at the moment I am not sure which additional information get included with asm.dwarf=true. Do you have an example where this is an actual problem? Apart from that anyway, the feature sounds good to me and makes sense.

**Comment by XVilka** [comment]
@thestr4ng3r maybe you could include this in our DWARF refactoring PR too?

**Comment by thestr4ng3r** [comment]
Yes, this can be done. But line information is conceptually independent of dwarf as dwarf is just one possible source of information for it.
