### ISSUE TITLE
Fix `:>` command

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#666]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64
commit: 1c25a4ace35e4ea2cd695ed6a9f34c1872598a10, build: 2021-02-19__11:49:27

### Expected behavior

No error

### Actual behavior

```
[0x00006b60]> :>qwe
Command ':' does not exist.
[0x00006b60]> q
```
But it creates the file `qwe` in the current directory.

**Comment by ret2libc** [comment]
Well.. Actually, now that I think about it, I'd close this issue because it behaves the same as bash.

```
$ gvcxjkbvckbljc>hello
bash: gvcxjkbvckbljc: command not found...
$ ls hello 
hello
```
