### ISSUE TITLE
Add a helper script for quick finding of command handlers

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#691]
Like `git grep "<cmdname>"` previously, but walking the yaml.
I'm not yet exactly sure what the best way will be to find the function in the C code once the name is known. But in the worst case a `git grep cmd_xyz_handler` should be useful enough already.

**Comment by ret2libc** [comment]
Something like `git grep -nWG "^[^[:blank:]].*rz_tasks_break_handler(" *.c` could work.
