### ISSUE TITLE
Sort out the `ah*` commands

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#698]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  | https://github.com/rizinorg/rizin/commit/d4638fe6dcd1fb98d3be6661cd001b84a5c42c50

Currently we have two duplicate commands, two of them marked as "deprecated". We need to figure out if something is missing in non-deprecated one, implement it, and remove the rest.
Note, that they serve somewhat different purpose and might not be deprecated at all.

### Expected behavior

Only one command should stay

### Actual behavior

```
| ahd foo a0,33      replace opcode string
| aho call           change opcode type (see aho?) (deprecated, moved to "ahd")
| aht [?] <type>     Mark immediate as a type offset (deprecated, moved to "aho")
```

After the change also tests should be updated and added if necessary.

**Comment by DMaroo** [comment]
Did #2130 fix it or not?

**Comment by ret2libc** [comment]
> Did #2130 fix it or not?

I don't think it does. @pelijah do you know whether the commands listed in this issue really do different things or if some of them should be removed?

**Comment by p371jah** [comment]
They all work but `aho` is not covered by tests.

**Comment by ret2libc** [comment]
Ok, thanks pelijah. Let's close this then.
