### ISSUE TITLE
Diff between local run and CI run (rz-test)

### ISSUE THREAD

**Issue by ghost** [rizinorg/rizin#702]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux x86_64
| File format of the file you reverse (mandatory)      | ...
| Architecture/bits of the file (mandatory)            | ...
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 <br> commit: cca2b8cd0937b1d5b47366534470a6d9b52d4ab4, build: 2021-02-24__09:45:57

### Expected behavior
The result of the rz-test should be the same on the local machine and the CI.

### Actual behavior
Some test are failing:
* `dk 9` tests
* time related print
* `RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -d -Qc px0 bins/elf/analysis/elf-nx`

### Steps to reproduce the behavior
```
git checkout dev
cd test
make
rz-test
```

### Additional Logs, screenshots, source code,  configuration dump, ...
[log.txt](https://github.com/rizinorg/rizin/files/6034827/log.txt)

**Comment by XVilka** [comment]
See also https://github.com/rizinorg/rizin/issues/398 - some test results also depend on the compiler.
