### ISSUE TITLE
Serialize Breakpoints to Projects

### ISSUE THREAD

**Issue by q8ing** [rizinorg/rizin#707]
**Environment information**
* Operating System: Windows 10 Pro (20H2) 19042.804
* Cutter version: 1.12.0
* Obtained from:
  - [] Built from source
  - [x ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: .exe

**Describe the bug**
Breakpoints are not saved.

I placed some breakpoints and saved my project, I loaded my project again, but I didn't find my saved breakpoints.

**To Reproduce**

1. Set a break point.
2. Save your project.
3. Close the program.
4. Load your saved project again.
5. Open breakpoint tab.

**Expected behavior**

Breakpoints must be loaded when I load my project again.

**Screenshots**

![1](https://user-images.githubusercontent.com/52950756/108917257-8538aa80-7640-11eb-943b-f40c956c4792.png)
![2](https://user-images.githubusercontent.com/52950756/108917260-8669d780-7640-11eb-8842-3fda60d08cc0.png)
![3](https://user-images.githubusercontent.com/52950756/108917266-879b0480-7640-11eb-8fc6-363c4eafffa5.png)
![4](https://user-images.githubusercontent.com/52950756/108917272-88cc3180-7640-11eb-9737-b13bd637ea5a.png)
![5](https://user-images.githubusercontent.com/52950756/108917282-89fd5e80-7640-11eb-9de1-21739275a2db.png)

**Additional context**

I don't know If this is a bug or this feature not available yet.

**Comment by thestr4ng3r** [comment]
Debug itself in general is not serialized on purpose because it is runtime-dependent. But information that stays present beyond debug sessions like breakpoints should be serialized and currently isn't.

**Comment by q8ing** [comment]
Thank you very much @ITAYC0HEN and @thestr4ng3r for clearing these facts to me :)

**Comment by DMaroo** [comment]
@thestr4ng3r In case you haven't already started with this, can I take this up? I would like to fix this.

**Comment by thestr4ng3r** [comment]
Sure, sounds like a good addition!
