### ISSUE TITLE
Linux x64 - Cross-arch static compilation to x86 requires static_runtime=true

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#735]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Linux x64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | n/a

### Expected behavior
Cross-arch compiling Rizin statically from x64 to x86 works when following the [BUILDING](https://github.com/rizinorg/rizin/blob/dev/BUILDING.md) guide (and forcing 32 bit build).

### Actual behavior
Cross-arch static compilation doesn't work without adding the `-Dstatic_runtime=true` meson flag.

### Steps to reproduce the behavior
```sh
$ git clone https://github.com/rizinorg/rizin
$ cd rizin
$ CFLAGS="-static -m32" LDFLAGS="-static -m32" meson --prefix="${PWD}/build/install" --default-library=static --buildtype=release build
$ ninja -C build
# 💔 - error: /usr/bin/ld: attempted static link of dynamic object `/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib32/libutil.so'
```

### Additional Logs, screenshots, source code,  configuration dump, ...
The full error is:
```
[...]
[1376/1550] Linking target binrz/rz-test/rz-test
FAILED: binrz/rz-test/rz-test 
cc  -o binrz/rz-test/rz-test binrz/rz-test/rz-test.p/rz-test.c.o binrz/rz-test/rz-test.p/load.c.o binrz/rz-test/rz-test.p/run.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -static -m32 -static -m32 -Wl,--start-group librz/util/librz_util.a librzspp.a subprojects/sdb/src/libsdb.a subprojects/zlib-1.2.11/libz.a -ldl -lm -pthread /usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib32/libutil.so -Wl,--end-group
/usr/bin/ld: librz/util/librz_util.a(lib.c.o): in function `rz_lib_dl_open':
lib.c:(.text+0xa0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/gcc/x86_64-linux-gnu/10/../../../../lib32/libutil.so'
collect2: error: ld returned 1 exit status
[...]
```

**Important**: This error does **not** happen (meaning that the cross compilation is successful) when passing `-Dstatic_runtime=true` to meson:

```sh
$ git clone https://github.com/rizinorg/rizin
$ cd rizin
$ CFLAGS="-static -m32" LDFLAGS="-static -m32" meson --prefix="${PWD}/build/install" --default-library=static -Dstatic_runtime=true --buildtype=release build
$ ninja -C build
# ❤️ - Though with many warnings in the linking process saying:
# /usr/bin/ld: librz/util/librz_util.a(lib.c.o): in function `rz_lib_dl_open':
# lib.c:(.text+0xa0): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Currently the `--default-library=static` meson flag doesn't seem to imply `-Dstatic_runtime=true` according to [this](https://github.com/rizinorg/rizin/blob/dev/meson.build#L20) (and the following) lines, but I don't know if this is wanted behavior.

Note that I purposely used Kali Linux as it is a popular distro in the InfoSec world, install `gcc-multilib` for being able to cross-compile.

**Comment by ret2libc** [comment]
It is expected.

Wanting to compile the internal rizin libraries as static does not mean that you want to also want get the dependencies in a static way.

What we could do is to automatically set `CFLAGS=-static` and `LDFLAGS=-static` whenever you set `-Dstatic_runtime=true`, so in case you want to compile rizin statically, you just set `-Dstatic_runtime=true`.

**Comment by caribpa** [comment]
Why isn't this an issue in Windows?

**Comment by ret2libc** [comment]
> Why isn't this an issue in Windows?

I will check.. Maybe `util` lib does not exist on Windows?

**Comment by ret2libc** [comment]
I believe this, as a building problem and maybe requiring doc adjustment, should be fixed for 0.2.0 @caribpa @XVilka

In particular because it was working before, AFAIR.

**Comment by caribpa** [comment]
I've just tried to cross-compile with `CFLAGS="-m32" LDFLAGS="-m32" meson --prefix="${PWD}/build/install" -Dstatic_runtime=true --buildtype=release build` and (as expected) it errors with:
```
meson.build:22:2: ERROR: Problem encountered: Cannot use `static_runtime` when libraries are dynamically built. Set `--default-library=static` if you want to build statically.
```

Instead of returning an error (and forcing the user to comply), shouldn't it be better to warn the user, automatically set `--default-library=static`, and proceed with the setup?

**Comment by ret2libc** [comment]
> Instead of returning an error (and forcing the user to comply), shouldn't it be better to warn the user, automatically set --default-library=static, and proceed with the setup?

In theory... it would. It is not possible though :D
