### ISSUE TITLE
Remove io_rbuf

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#751]
There's a plugin io_rbuf that does not seem to work at all. It's not tested either. I propose to kill it.

**Comment by ret2libc** [comment]
@thestr4ng3r RIght now there is this `io_rbuf` plugin, that however does not reallly work. In theory, your new RzIOPlugin that is used to read special virtual files, should just wrap all the RzBuffer methods, right? So in theory you might need a io plugin similar to this that can just wrap an existing rzbuffer. WDYT?

**Comment by thestr4ng3r** [comment]
It needs a bit more, in particular opening from a given uri like `bin://3/somefile` and for this, finding the right buffer in the core. But the reading, writing, etc. will be similar, yes.

**Comment by ret2libc** [comment]
Then we can probably just kill this plugin and create a new one...
