### ISSUE TITLE
User friendly way for searching in a defined memory map

### ISSUE THREAD

**Issue by caribpa** [rizinorg/rizin#766]
**Is your feature request related to a problem? Please describe.**
In a constant quest for finding the next level of laziness (and extending the life of my keyboard), I am saddened with the fact that there's no easy and clean way for searching in a defined memory region.

To accomplish this, one has to resort to the undignified `e search.from/to=` (and altering `search.in`) after annotating the library boundaries from `dmm`, or using the hackish `@{` instead of enjoying the pleasure of having this functionality integrated in the search (`/`) (or maybe easier in `@`) command.

**Describe the solution you'd like**
```
$ rizin -d /bin/rizin
> /a jmp rsp @m:rizin
# Searches for the assembled opcode in the 'rizin' debug memory map

# Equivalent of having done:
> /a jmp rsp @{$(dmm ~rizin[0]) $(dmm ~rizin[1])}

# As an extra, specific permissions may be specified after the `m` and before the `:`
> /a jmp rsp @mrx:rizin
# Searches for the assembled opcode in the 'rizin' debug rx memory map

# Equivalent to:
> e search.in=dbg.maps.rx
> /a jmp rsp @{$(dmm ~rizin[0]) $(dmm ~rizin[1])}
```

**Describe alternatives you've considered**
💔 

**Additional context**
🤷

**Comment by caribpa** [comment]
Forgot to say, but the `stack` and the `heap` are also in the group of "defined memory maps", so:
```sh
> /a jmp rsp @m:stack

# Is equivalent to
> e search.in=dbg.stack
> /a jmp rsp
```

**Comment by caribpa** [comment]
By the way @ret2libc, do you know why `/a jmp rsp @{$(dmm ~rizin[0,1])}` is not working (and separate shell expansions are required, like showed in the OP)?

**Comment by ret2libc** [comment]
> By the way @ret2libc, do you know why `/a jmp rsp @{$(dmm ~rizin[0,1])}` is not working (and separate shell expansions are required, like showed in the OP)?

It seems a bug in the grammar. I'll have a look.

**Comment by ret2libc** [comment]
`/a push r15 @($(dm~map.usr_bin_ls.r_x[0,1]))` works now, btw. 

Also, what once was `@{ ... }` is now `@(....)`.


I think for this to be considered to be implemented we should be a bit more precise on exactly what we want. In particular, `@m:rizin` what shall it mean, exactly? There may be 10 maps related to the rizin binary while debugging, which one? ALl of them? How to specify just one? Have we considered the use of `@e:search.in=XX` specifier?

@caribpa it would be awesome to have you back btw ;)
