### ISSUE TITLE
`/a jmp rsp @{$(dmm ~rizin[0,1])}` is not working

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#773]
By the way @ret2libc, do you know why `/a jmp rsp @{$(dmm ~rizin[0,1])}` is not working (and separate shell expansions are required, like showed in the OP)?

_Originally posted by @caribpa in https://github.com/rizinorg/rizin/issues/766#issuecomment-791398622_

---

In grammar.js there is:
```
prec.right(1, seq($._simple_command, "@{", alias($.arg_brace, $.arg), alias($.arg_brace, $.arg), "}")),
```
thus the grammar expects two arguments between `@{...}`. However `${....)` is considered as a single argument (at least before the command expansion is performed) so the above command fails to be parsed.

A solution is probably to accept a variable number of arguments between `@{...}` and check  if there are exactly 2 in the `tmp_fromto_command` handler, which is executed after the parser has substituted the `$(..)` with the output.

**Comment by caribpa** [comment]
> A solution is probably to accept a variable number of arguments between `@{...}` and check if there are exactly 2 in the `tmp_fromto_command` handler, which is executed after the parser has substituted the `$(..)` with the output.

This solves the problem in `@{`, but doesn't seem like a generalized solution 😔 

Honestly, I don't know how the popular shells expand the shell-substitution, but if I have to guess, they recursively expand the `$()` (and backticks) from the innermost to the outermost, like a LIFO, before parsing the command (at least this is the behavior I expect).

This said, I am not sure which other Rizin commands can take advantage of a shell-expansion returning more than one value for being parsed as different parameters. It may be worth investigating for a future refactor (or to conclude that doing it is not worth it) 📚

**Comment by ret2libc** [comment]
> > A solution is probably to accept a variable number of arguments between `@{...}` and check if there are exactly 2 in the `tmp_fromto_command` handler, which is executed after the parser has substituted the `$(..)` with the output.
> 
> This solves the problem in `@{`, but doesn't seem like a generalized solution 😔

I will of course try to solve it in other places as I see fit.

> 
> Honestly, I don't know how the popular shells expand the shell-substitution, but if I have to guess, they recursively expand the `$()` (and backticks) from the innermost to the outermost, like a LIFO, before parsing the command (at least this is the behavior I expect).

You have to parse things before anyway, because otherwise you may end up replacing things like
```
?e 'Hello $(?e World)'
```
but in this case the command should not be substituted, because of the single quotes.

**Comment by caribpa** [comment]
> You have to parse things before anyway, because otherwise you may end up replacing things like
> 
> ```
> ?e 'Hello $(?e World)'
> ```
> 
> but in this case the command should not be substituted, because of the single quotes.

Excellent point. No idea how the shells do it, maybe they first detect the quoting before the LIFO shell expansion, followed by the command parsing? Sounds really complex... 🤔

**Comment by ret2libc** [comment]
BTW, just to be clear, by design we don't allow a command substitution to create new "tokens", though you can create new "arguments" (except in this case and maybe others i will check better).

**Comment by caribpa** [comment]
That's perfectly fine as it is better not to overcomplicate the code just for 2 commands that may support this hackery

**Comment by ret2libc** [comment]
There are probably few other commands that require fixing. In general, all statements that accept more than one argument (but not "as many as possible"). For example, `@@@=` wants exactly 2*n number of arguments, but you may want to "create" those arguments with a command substitution. Another example is `@@s:`, which wants 3 arguments.

The solution I will implement is to make those statements accept `$.args` (which means that any number of arguments will be accepted by the parser). Then, each handler in `cmd.c` will ensure that the right number of arguments was passed to the handler (after command substitution is done).

As a side note, I will also go back from `@{...}` to `@(...)`. The change was done mainly for old parser (see https://github.com/rizinorg/rizin/commit/c3dee9332c19f874ac2cc9294a9ffe17575d8141) but it required special handling in the new parser.... We don't need to stay compliant with oldshell anymore, so let's just remove special handlings to simplify the grammar.

**Comment by caribpa** [comment]
> The solution I will implement is to make those statements accept `$.args` (which means that any number of arguments will be accepted by the parser). Then, each handler in `cmd.c` will ensure that the right number of arguments was passed to the handler (after command substitution is done).

This is indeed the smartest choice, good call 👍 👍

**Comment by caribpa** [comment]
> For example, `@@@=` wants exactly 2*n number of arguments, but you may want to "create" those arguments with a command substitution. Another example is `@@s:`, which wants 3 arguments.

On a side note, are `@@@=` and `@@@c:` necessary? can't the parser just tell if, for example, `@@=` will act like current `@@=`, or `@@@=` depending on the type of arguments it receives (like `pd` with the optional `arm <bits>` arguments)?

**Comment by ret2libc** [comment]
> On a side note, are `@@@=` and `@@@c:` necessary? can't the parser just tell if, for example, `@@=` will act like current `@@=`, or `@@@=` depending on the type of arguments it receives (like `pd` with the optional `arm <bits>` arguments)?

I think it is necessary, yes. I don't see how you can distinguish in `pd @@=10 20 30 40` whether you want to execute `pd` on `10`, `20`, `30`, and `40` or if you want to execute `pd` on `10` with blocksize `20`, and `30` with blocksize `40`. Hope it's clear.

**Comment by caribpa** [comment]
Shouldn't `@@=` use addresses (according to the help)?

**Comment by ret2libc** [comment]
> Shouldn't `@@=` use addresses (according to the help)?

It does. `10`, `20`, `30, `40` are addresses. What i mean is that if you use your proposed solution (that was to use `@@=` for both current `@@=` and `@@@=`) there is no way to distinguish what is an address and what is a block size.

**Comment by caribpa** [comment]
I've just checked that the following works:
```sh
[0x00000000]> pd 1 @@=10 20 30
            0x0000000a      invalid
            0x00000014      invalid
            0x0000001e      invalid
```
But what's exactly its use case (of allowing these int to hex conversion)?

I've always used `@@=` with "addresses" (in appearance), especially something relative like: `pd 1 @@=$$ $$+10 $$+20`, or `pd 32 @@=esp ebp`.

What I'm suggesting (implementation wise) is, if `@@=` is force to recognize addresses only (something preceded by 0x, or magically converted to that, like registers), numbers following an address can be interpreted as the blocksize for the address just read, this parsing can allow skipping blocksizes for some addresses: `@@=$$ 16 ebp esp 32`

Honestly, I'm bringing this up because I always forget the `@@@` family, and get confused when `@@@?` outputs no help.

**Comment by ret2libc** [comment]
> I've just checked that the following works:
> 
> ```shell
> [0x00000000]> pd 1 @@=10 20 30
>             0x0000000a      invalid
>             0x00000014      invalid
>             0x0000001e      invalid
> ```
> 
> But what's exactly its use case (of allowing these int to hex conversion)?
> 
> I've always used `@@=` with "addresses" (in appearance), especially something relative like: `pd 1 @@=$$ $$+10 $$+20`, or `pd 32 @@=esp ebp`.
> 
> What I'm suggesting (implementation wise) is, if `@@=` is force to recognize addresses only (something preceded by 0x, or magically converted to that, like registers), numbers following an address can be interpreted as the blocksize for the address just read, this parsing can allow skipping blocksizes for some addresses: `@@=$$ 16 ebp esp 32`
> 
> Honestly, I'm bringing this up because I always forget the `@@@` family, and get confused when `@@@?` outputs no help.

`@@@?` does not exist anymore. I've merged most of radare2 `@@`/`@@@` into just `@@?`.

I think your concept of "addresses" is broken, sorry :D Every number or anything that can be converted to a number is an address. 10, 0xa, 012, 0b1010 all refer to the same address "0xa" (which is just a number). Also `flag1 + flag2` is an address. It already works how you suggest it, because "or magically converted to that, like registers" is exactly what happens, with the thing that not only registers can be converted to numbers.

**Comment by caribpa** [comment]
> I think your concept of "addresses" is broken, sorry :D Every number or anything that can be converted to a number is an address. 10, 0xa, 012, 0b1010 all refer to the same address "0xa" (which is just a number). Also `flag1 + flag2` is an address. It already works how you suggest it, because "or magically converted to that, like registers" is exactly what happens, with the thing that not only registers can be converted to numbers.

The battle was hard and you fought better. I yield 🙇
