### ISSUE TITLE
Convert `i` commands to newshell

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#786]

**Comment by ret2libc** [comment]
I'm going to wait for @thestr4ng3r refactoring on RzBin before doing this. Let's see how it goes, but if it takes too much we can probably move this out of 0.2.0 and I'll focus on another set of commands.

**Comment by XVilka** [comment]
It is also important for the https://github.com/rizinorg/cutter/pull/2637 - a better `i`-like API is required.

**Comment by thestr4ng3r** [comment]
Can be started now imo. There might be more changes from me in those commands, but I wouldn't expect anything large.
