### ISSUE TITLE
4-byte strings (`wchar*`) recognized inconsistently

### ISSUE THREAD

**Issue by lukasjuhrich** [rizinorg/rizin#802]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            | x86-64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.1.0 0 @ linux-x86-64 git.0.1.0 <br>commit: unknown build: 2021-03-09__03:14:04

### Expected behavior
Correctly creating / reporting a 4-byte string when manually creating with `Cs <length *4> @address`.
In particular, having the same behavior for short (<3 chars) as well as long strings (approx. >5 chars?)

### Actual behavior
The long string is correctly created by the automatic analysis on file load (without passing explicit flags).
The short string is not recognized.
Adding the short string by using the same command that has been reported for the long string creates it and retains the length, but only reports the first letter as content.

### Steps to reproduce the behavior
Binary not shareable unfortunately. Session excerpt:
```
[0x01157c6c]> psW
ns
[0x01157c6c]> C*~<0x01157cd8
Cs 220 @ 0x01157cd8 # Invalid value for command line parameter 'resolution'.
[0x01157c6c]> C*~<0x01157c6c
[0x01157c6c]> Cs 12 @0x01157c6c # ns.
[0x01157c6c]> C*~<0x01157c6c
Cs 12 @ 0x01157c6c # n
[0x01157c6c]> psW @0x01157cd8
Invalid value for command line parameter 'resolution'.
[0x01157c6c]> px @0x01157cd8
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x01157cd8  4900 0000 6e00 0000 7600 0000 6100 0000  I...n...v...a...
0x01157ce8  6c00 0000 6900 0000 6400 0000 2000 0000  l...i...d... ...
0x01157cf8  7600 0000 6100 0000 6c00 0000 7500 0000  v...a...l...u...
0x01157d08  6500 0000 2000 0000 6600 0000 6f00 0000  e... ...f...o...
0x01157d18  7200 0000 2000 0000 6300 0000 6f00 0000  r... ...c...o...
0x01157d28  6d00 0000 6d00 0000 6100 0000 6e00 0000  m...m...a...n...
0x01157d38  6400 0000 2000 0000 6c00 0000 6900 0000  d... ...l...i...
0x01157d48  6e00 0000 6500 0000 2000 0000 7000 0000  n...e... ...p...
0x01157d58  6100 0000 7200 0000 6100 0000 6d00 0000  a...r...a...m...
0x01157d68  6500 0000 7400 0000 6500 0000 7200 0000  e...t...e...r...
0x01157d78  2000 0000 2700 0000 7200 0000 6500 0000   ...'...r...e...
0x01157d88  7300 0000 6f00 0000 6c00 0000 7500 0000  s...o...l...u...
0x01157d98  7400 0000 6900 0000 6f00 0000 6e00 0000  t...i...o...n...
0x01157da8  2700 0000 2e00 0000 0000 0000 7500 0000  '...........u...
0x01157db8  7400 0000 7700 0000 0000 0000 7400 0000  t...w.......t...
0x01157dc8  7200 0000 7500 0000 6500 0000 0000 0000  r...u...e.......
[0x01157c6c]> px @0x01157c6c
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x01157c6c  6e00 0000 7300 0000 0000 0000 6e00 0000  n...s.......n...
0x01157c7c  7600 0000 0000 0000 7200 0000 0000 0000  v.......r.......
0x01157c8c  0000 0000 4400 0000 6500 0000 7300 0000  ....D...e...s...
0x01157c9c  6b00 0000 7400 0000 6f00 0000 7000 0000  k...t...o...p...
0x01157cac  0000 0000 4700 0000 6100 0000 6d00 0000  ....G...a...m...
0x01157cbc  6500 0000 0000 0000 4100 0000 7500 0000  e.......A...u...
0x01157ccc  7400 0000 6f00 0000 0000 0000 4900 0000  t...o.......I...
0x01157cdc  6e00 0000 7600 0000 6100 0000 6c00 0000  n...v...a...l...
0x01157cec  6900 0000 6400 0000 2000 0000 7600 0000  i...d... ...v...
0x01157cfc  6100 0000 6c00 0000 7500 0000 6500 0000  a...l...u...e...
0x01157d0c  2000 0000 6600 0000 6f00 0000 7200 0000   ...f...o...r...
0x01157d1c  2000 0000 6300 0000 6f00 0000 6d00 0000   ...c...o...m...
0x01157d2c  6d00 0000 6100 0000 6e00 0000 6400 0000  m...a...n...d...
0x01157d3c  2000 0000 6c00 0000 6900 0000 6e00 0000   ...l...i...n...
0x01157d4c  6500 0000 2000 0000 7000 0000 6100 0000  e... ...p...a...
0x01157d5c  7200 0000 6100 0000 6d00 0000 6500 0000  r...a...m...e...
[0x01157c6c]> 
```

**Comment by ret2libc** [comment]
@XVilka I'm assigning this to you because it is about the `C` command and I guess it makes sense to fix this while you move the commands to newshell. I believe the API has no real problem and indeed strings like these are recognized when loading the binary (see `rz_core_bin_apply_strings`), but you cannot use any `C` subcommands to define it. `rz_core_bin_apply_strings` uses the `rz_meta_set` API, so it's likely just about calling the right functions in `C` handlers.

**Comment by XVilka** [comment]
I think it should be fixed, @lukasjuhrich please retest on the latest `dev`.

**Comment by ret2libc** [comment]
I'm closing this according to https://github.com/rizinorg/rizin/issues/802#issuecomment-944191849 . @lukasjuhrich feel free to re-open it or create a new issue if you still have this problem. Thanks for the report!
