### ISSUE TITLE
rz-asm crashed when parsing python bytecode

### ISSUE THREAD

**Issue by Heersin** [rizinorg/rizin#803]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux
| File format of the file you reverse (mandatory)      | pyc
| Architecture/bits of the file (mandatory)            | pyc
| `rizin -v` full output, **not truncated** (mandatory)  | rz_asm 0.2.0-git @ linux-x86-64 commit: 27408a26cbc75f9bde3e0bcd8e537bc3a5c9cb36, build: 2021-03-08__20:34:55

### Expected behavior
Parse `0x0000006a` to an opcode with arguments

### Actual behavior
crashed with the following output:
```
 WARNING: rz_list_get_n: assertion 'list' failed (line 447)
 WARNING: rz_list_get_n: assertion 'list' failed (line 447)
 [1]    32414 segmentation fault (core dumped)  ./rz-asm -a pyc -d 0x0000006a
```

### Steps to reproduce the behavior
`rz-asm -a pyc -d  0x0000006a`

### Additional Info

- Everything works fine when using rizin `pd`.

- In `librz/asm/p/asm_pyc.c : line 22` Var `shared` is fetched from `bin->cur->o->obj`. It is used to get `cobjs` and `interned_table` (required by `rz_pyc_disasm`), but there is no NULL pointer check for it.
```
	RzBinPlugin *plugin = bin && bin->cur && bin->cur->o ? bin->cur->o->plugin : NULL;

	if (plugin) {
		if (!strcmp(plugin->name, "pyc")) {
			shared = bin->cur->o->bin_obj;
		}
	}
	RzList *cobjs = rz_list_get_n(shared, 0);
	RzList *interned_table = rz_list_get_n(shared, 1);
```

**Comment by Yuuoniy** [comment]
I don't think the code you paste has problems, function `rz_list_get_n`  `rz_pyc_disasm`  would deal with NULL pointer.
actually, I debug it with gdb, the  segmentation fault is due to `get_opcode_by_version:148 in opcode.c ` after adding a `rz_return_val_if_fail` for `version`，`disassemble:31 in asm_pyc.c ` would then cause an cause segmentation fault due to `opcodes_cache` NULL pointer.
Patching the two places could solves the segmentation fault. but it couldn't parse 0x0000006a  either. What's the expected output for this parse?

**Comment by Heersin** [comment]
> I don't think the code you paste has problems, function `rz_list_get_n` `rz_pyc_disasm` would deal with NULL pointer.
> actually, I debug it with gdb, the segmentation fault is due to `get_opcode_by_version:148 in opcode.c ` after adding a `rz_return_val_if_fail` for `version`，`disassemble.c:32 in opcode.c ` would then cause an cause segmentation fault due to `opcodes_cache` NULL pointer.
> Patching the two places could solves the segmentation fault. but it couldn't parse 0x0000006a either. What's the expected output for this parse?

You are right, I didn't continue to debug it after catching the NULL pointer. 
The `0x0000006a` is a randomly generated data for testing the pyc plugin. So the expected output is an opcode or an error message.
