### ISSUE TITLE
FLIRT implementation and testing signatures

### ISSUE THREAD

**Issue by williballenthin** [rizinorg/rizin#817]
I've recently implemented FLIRT [elsewhere](https://github.com/williballenthin/lancelot/tree/master/flirt/src) (and [here](https://github.com/williballenthin/viv-utils/blob/master/viv_utils/flirt.py)), and would be happy to share information and test cases from our Apache 2.0 work.

To get started, here is a .sig file (and corresponding .pat file) that contains around 108k FLIRT signatures generated with pcf/sigmake from IDA 7.4 against VC2015/2017/2019 x32/x64 C runtimes and common open source libraries. They are not derived from Hex-Rays signatures and are licensed Apache 2.0 with copyright to FireEye. They should exercise most FLIRT code paths for the latest signature format, including functions larger than u16::MAX.

If rizin wants to rely more on FLIRT, particularly with open source signatures, then do please reach out! We're collecting and preparing a comprehensive signature set for PE analysis and would be happy to have this used elsewhere.
[1.sig.gz](https://github.com/rizinorg/rizin/files/6133304/1.sig.gz)

[1.pat.gz](https://github.com/rizinorg/rizin/files/6133303/1.pat.gz)

**Comment by XVilka** [comment]
@williballenthin this is glorious! We will take a look and test our implementation more thoroughly. Of course, we would be happy to have it integrated in the Rizin/Cutter/RzGhidra.

**Comment by ITAYC0HEN** [comment]
This is fantastic @williballenthin! :)
Are the Apache2-licensed signatures overlap with some of IDA's? (if so, that's great).
Would you mind sharing some stats about the performance we should expect to see when applying these signatures to certain binaries?

**Comment by williballenthin** [comment]
> Are the Apache2-licensed signatures overlap with some of IDA's?

They should, since I suspect both we and Hex-Rays are extracting signatures from things like the MSVC universal runtimes, ATL/MFC frameworks, etc. But to reiterate, we're not taking nor translating any signatures provided by Hex-Rays.

**Comment by williballenthin** [comment]
> Would you mind sharing some stats about the performance we should expect to see when applying these signatures to certain binaries?

The above signature files (1.sig and 1.pat) should only be used for testing right now - they do contain many signatures but they're not as comprehensive as they could be nor are they documented like they should be (e.g. exactly which input .lib files did we use, which versions of MSVC do they cover, etc). Soon we'll have something more appropriate for distribution and I'll be happy to update this thread with links.

@mr-tz and I are triaging the performance of the signature files this week. When we have some claims that we can back up with data, then we'll be happy to share!

**Comment by ITAYC0HEN** [comment]
Thanks for all your assistance! I can't express how meaningful it is for us. Coming from IDA, I just waited for the day Rizin will detect library functions as part of its initial analysis phase.

I tested the sig file against some random binaries using `rizin` and it worked very nicely.

```
# Before FLIRT with full analysis
[0x004450e6]> afl~fcn.?
808

# Run flirt sigs. Finished instantly
[0x004450e6]> zfs flirts-sigs/1.sig

# 500+ functions detected <3
[0x004450e6]> afl~flirt.?
537

# Leaving us with these
[0x004450e6]> afl~fcn.?
231
```

I tried to compare the results with IDA but I couldn't apply `1.sig` to the binary. I loaded the signature file but when trying to apply it, it was stuck on either "Planned" or "Current" :/
I guess that you already compared `1.sig` with the results of the built-in ones. We also want to compare how IDA handles `1.sig` compare to us.

**Comment by XVilka** [comment]
Now Rizin fixed parsing of all signatures, including those. We should work on better integration in the analysis loop, etc.

**Comment by wargio** [comment]
@williballenthin Hey, i want to improve the FLIRT support on rizin and also generate signatures, do you have signatures that i can use for testing? like bin -> pat -> flirt that i can test so i can write some code to test the generation?

**Comment by williballenthin** [comment]
our scripts and data for building signatures are here: https://github.com/mandiant/siglib/, for example, here: https://github.com/mandiant/siglib/tree/master/data/VS2019

this contains references to where we got the bin, the intermediate pat files, and also the sig files. you'll have to bring your own `sigmake.exe` though :-/

**Comment by williballenthin** [comment]
there's also [idb2pat](https://github.com/mandiant/flare-ida/blob/master/python/flare/idb2pat.py) that you can use to understand how to generate pat files from mapped modules (such as within IDA).

**Comment by wargio** [comment]
nice! thank you! i will start giving a look to the files :)
