### ISSUE TITLE
Non-deterministic test failure in db/cmd/write

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#828]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OpenBSD 6.8, x86_64
| `rizin -v` full output, **not truncated** (mandatory)  | `rizin 0.2.0-git @ openbsd-x86-64 commit: 6b3c58ebfaeb71a72737a2e60acd952f51ea96ed, build: 2021-03-13__17:32:18`

Happened once after 377 runs of rz-test:
```
[XX] db/cmd/write wen 3 writable bin
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'mkdir .tmp
cp bins/mach0/mac-ls2 .tmp/ls-wen
o .tmp/ls-wen
r
wen 3
r
oo+
r
wen 3
r
rm .tmp/ls-wen
' --
-- stdout
@@ -1,4 +1,4 @@
 38704
 38704
 38704
-38707
+38704


-- stderr
rz_io_extend failed
rz_io_extend failed
```

**Comment by ret2libc** [comment]
@thestr4ng3r @XVilka is this still happening? I haven't really followed the openbsd CI...

**Comment by XVilka** [comment]
Haven't seen it happening for quite a while. Was accidentally fixed probably. Closing.

**Comment by XVilka** [comment]
The only errors we now see on OpenBSD are timeouts.
