### ISSUE TITLE
Show current flag in the command prompt, near the address

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/rizin#866]
**Is your feature request related to a problem? Please describe.**
For example, I set `db sym.imp.free` and `db sym.imp.malloc` (i have no idea where they are in memory). Then I do `dc` to continue debugging and I hit a breakpoint. I see this:
```
[0x55b934e5ad80]> dc
hit breakpoint at: 0x55b934e5aae0
[0x55b934e5aae0]> 
```
I have no idea what I hit.

**Describe the solution you'd like**
It would be great to see something like this:
```
[0x55b934e5ad80:main]> dc
hit breakpoint at: 0x55b934e5aae0
[0x55b934e5aae0:sym.imp.malloc]> 
```

**Describe alternatives you've considered**
```
[0x55b934e5ad80:main]> dc
hit breakpoint at: 0x55b934e5aae0
[0x55b934e5aae0:malloc]> 
```

**Comment by XVilka** [comment]
Good idea but should be optional.
