### ISSUE TITLE
Missing arguments or redundant arguments for main function

### ISSUE THREAD

**Issue by Heersin** [rizinorg/rizin#882]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PPC, PPC32, arm, Mips, Mips64
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 commit: 15451293882a5803fd0d764c5b363a0fdb880d8a, build: 2021-03-21__10:24:57

### Expected behavior

In the disassembly output of main function, It should be like this :
`main (int32_t argc, int32_t argv) ` or with one more environment pointer argument.

### Actual behavior

Arm-linux-android-echo : 
```
┌ main ();
```

Arm-linux-gnu-echo:
```
/ main ();
```

Mips:
```
/ main (int32_t arg_10h, int32_t arg_18h, int32_t arg_1ch, int32_t arg_20h, int32_t         arg_24h, int32_t arg_28h, int32_t arg_2ch, int32_t arg_30h, int32_t arg_34h, int32_t        arg_38h, int32_t arg_3ch, int32_t arg_50h, int32_t arg_54h);
```

Mips-64
```
/ main (int64_t arg_0h, int64_t arg_4h, int64_t arg_8h, int64_t arg_ch, int64_t arg_10h,    int64_t arg_18h, int64_t arg_20h, int64_t arg_28h, int64_t arg_30h, int64_t arg_38h,        int64_t arg_40h, int64_t arg_48h);
```
PowerPC:
```
/ dbg.main (signed int arg_20h);
```

PowerPC32
```
/ main (signed int arg_50h);
```

x86-gnu-linux
```
/ main (int32_t arg_4h);
```

x86-64-gnu-linux
```
/ main ();
```

### Steps to reproduce the behavior

- Download binary from this [link](https://github.com/Heersin/rizin-testbins/tree/rz_test_expand/abi_bins/elf/platforms) , I chose the echo program as the test binary
- Open them in rizin then analysis them by `aaa` command
- seek to main (most of them can use `s main`)
- `pdf~main` or `pdf` to view the disassembly output

### Additional Logs, screenshots, source code,  configuration dump, ...

- IDA can recognize the main's signature correctly
- BinaryAnalysisPlatform can recognize the main signature

### related tests
[main_signature](https://github.com/rizinorg/rizin/blob/dev/test/db/abi/platforms/main_signatures)

**Comment by XVilka** [comment]
Please add a link to these tests in the testsuite

**Comment by ret2libc** [comment]
Re-checked this and this is the currently failing ones:
- `./build-dev/binrz/rizin/rizin -A -qc "s main;pdf~main:0" test/bins/abi_bins/elf/platforms/powerpc-linux-gnu-symexec-guess`
- `./build-dev/binrz/rizin/rizin -A -qc "s main;pdf~main:0" test/bins/abi_bins/elf/platforms/x86_64-macho-echo`

So it is already a quite good improvement!
