### ISSUE TITLE
Map_dwarf_reg_to_x86_reg warnings when processing a modified binary

### ISSUE THREAD

**Issue by Heersin** [rizinorg/rizin#883]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.2.0-git @ linux-x86-64 commit: 15451293882a5803fd0d764c5b363a0fdb880d8a, build: 2021-03-21__10:24:57

### Expected behavior
No warning when processing a ELF binary 

### Actual behavior

When open a ELF binary (about 1.4 M), rizin reported several warnings : 
```
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
```

### Steps to reproduce the behavior
- Download binary from [this link](https://github.com/junxzm1990/x86-sok/blob/master/testsuite/linux/utils/findutils/gcc_m32_O2/find)
- `rizin ./find` to open it

### Additional Logs
```
./rizin ~/blackhole/rz-test-exp/x86-sok/testsuite/linux/utils/findutils/gcc_m32_O2/find
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: (../librz/analysis/dwarf_process.c:858):map_dwarf_reg_to_x86_reg: code should not be reached
WARNING: No calling convention defined for this file, analysis may be inaccurate.
[0x0804a9bb]> 
```

### Additional Infos
This binary is built by a modified toolchain (see this [repo](https://github.com/junxzm1990/x86-sok))

**Comment by ret2libc** [comment]
@thestr4ng3r i've given this task to you just because you very recently worked on dwarf. If you don't have time/will, just un-assign it ;) FYI.

**Comment by HoundThe** [comment]
I had a look and some DWARF mapping to registers from https://01.org/sites/default/files/file_attach/intel386-psabi-1.0.pdf are missing, from a quick debug its FPU registers (numbers 11-18) and number 8 which is RA.

**Comment by ret2libc** [comment]
@thestr4ng3r how much work would this be? Do you have any idea? Is it a complicated or easy thing?

@HoundThe do you have time/will to help with this?
