### ISSUE TITLE
Merge LUA53 (in extras) with LUA54 (in core)

### ISSUE THREAD

**Issue by Maijin** [rizinorg/rizin#886]
**Is your feature request related to a problem? Please describe.**
There are two plugins for Lua, one in extras supporting LUA53 and one in core supporting LUA54.

Extras URL - https://github.com/rizinorg/rizin-extras/tree/master/lua53

**Describe the solution you'd like**

* Merge LUA53 (in extras) with LUA54 (in core)
* Remove LUA53 from extras

CC @Heersin

**Comment by Heersin** [comment]
Ok, I will work on it these days :D

**Comment by XVilka** [comment]
Was fixed in https://github.com/rizinorg/rizin/commit/3bbff71ee1300a54d32db6ee4178c61228404741
