### ISSUE TITLE
RZ_GITTIP is "unknown" when built from Cutter with Release 0.1.1

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#920]
Happens in the CI builds of https://github.com/rizinorg/cutter/commit/e28b2a15b0588dc65d5e1172078be1ae88eab6db, which use rizin release 0.1.1 (dfe0ff1)
![Bildschirmfoto 2021-03-28 um 12 21 34](https://user-images.githubusercontent.com/1460997/112749064-290ad280-8fc0-11eb-9b2d-dc7fff991c80.png)
![Bildschirmfoto 2021-03-28 um 12 20 14](https://user-images.githubusercontent.com/1460997/112749033-f7920700-8fbf-11eb-9cc6-45b1f18c4e0c.png)

Instead of "unknown", there should be the git hash. This might already be fixed on dev since there have been quite a few changes, but it should be checked in any case.

**Comment by ret2libc** [comment]
If you use a release tarball there is no GITTIP because it is computed only when git is present.

**Comment by thestr4ng3r** [comment]
It's using git from the submodule. It could as well be an issue in Cutter, but I didn't check in detail yet.

**Comment by XVilka** [comment]
@thestr4ng3r is this still a problem?

**Comment by thestr4ng3r** [comment]
yes, currently it shows up as "".

**Comment by ret2libc** [comment]
I'm preparing package for Fedora for rizin 0.2.0 and I did not see problems with GITTIP. It just showed the first line when doing `rizin -v`. Maybe it has to do with submodules?

**Comment by ret2libc** [comment]
@thestr4ng3r please check again. I think this problem is fixed, so I'm going to close.
