### ISSUE TITLE
Port `test/unit/legacy_unit` tests to the current unit test framework

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#923]
There is a bunch of tests in `test/unit/legacy_unit`.
Some of them are irrelevant now, some could be ported to the newer miniunit format that we use currently.

**Comment by maitid** [comment]
how do I resolve this problem could you please help.

**Comment by ret2libc** [comment]
@dipumaiti Make sure to read https://github.com/rizinorg/rizin/tree/dev/test#unit-tests , https://github.com/rizinorg/rizin/tree/dev/test#unit-tests-1 and try to run them. Understand how minunit is used and look through some existing unit tests in https://github.com/rizinorg/rizin/tree/dev/test/unit .

Then look at https://github.com/rizinorg/rizin/tree/dev/test/unit/legacy_unit and try to come up with new unit tests that use minunit to tests those behaviour tracked in legacy_unit.

**Comment by maitid** [comment]
hello ret2libc! I am very beginner and really don't have any idea to how to run and where  to run any code if you could explain me how could I crack this problem it would be great help!! please.

**Comment by ret2libc** [comment]
> hello ret2libc! I am very beginner and really don't have any idea to how to run and where to run any code if you could explain me how could I crack this problem it would be great help!! please.

Then look at https://github.com/rizinorg/rizin/blob/dev/README.md , try to build Rizin and play a bit with it, maybe by looking at https://book.rizin.re/ as well. Then go through the materials I've linked above.

To understand a bit the various API I'd start by quickly reading the include files that you can find in `librz/include/`.

**Comment by ret2libc** [comment]
This probably does not warrant any specific milestone for now as it's just testing... This seems a good task for someone who wants to start getting familiar with the codebase though.

**Comment by DMaroo** [comment]
I think this issue is still relevant and should not be closed. The legacy tests should be ported to the new miniunit test format. It will be much better, and uniform that way.
