### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#942]
Because until the dust settles there are some changes in the release process, we should track them and put into the documentation for developers/maintainers.

**Comment by XVilka** [comment]
1. As `stable` branch might get some cherry-picks or special commits to fix particular bugs or things specific for the stable branch, it can get de-sync with `dev` branch. When you want to release a new version that just tracks current `dev` branch, you can pull the changes from `dev` into `stable` with the branch name `release-X.Y.Z` where `X.Y.Z` is the released version. See these commands:
```
git checkout stable
git merge -s ours dev
git checkout --detach dev
git reset --soft stable
git checkout stable
git commit --amend -C HEAD
```
This is usually done for major releases (X increases) or, occasionally, for minor releases (Y increases). Patch releases (Z increases) are usually done through cherry-picks.

2. If the CI is fine, we should put a tag `vX.Y.Z` from the `stable` branch that will trigger the comprehensive testing of Rizin on various platforms and preparing the tarballs/packages.

3. If this CI pipeline succeeds the "draft" release will be created.

**Comment by XVilka** [comment]
Now, that project migrations are implemented by @thestr4ng3r in `librz/core/project_migrate.c` the important part of the release process would be testing how old projects are loaded and if some serialized information is missing or changed the format.

**Comment by thestr4ng3r** [comment]
No, project testing should be irrelevant to the release process. This kind of stuff must be done on a per-commit level (at least when the projects are considered "stable") so there will be 0 breakage no matter which dev commit you use. Also all this testing should be automatic.

**Comment by XVilka** [comment]
Cutter did an amazing job on this, we could use the template:
- https://github.com/rizinorg/cutter/issues/2680
- https://github.com/neovim/neovim/issues/11023 - is also good to check

**Comment by XVilka** [comment]
We also should put a corresponding tag to the used `rizinorg/rizin-testbins` commit.

**Comment by XVilka** [comment]
Was largely done, cc @ret2libc

**Comment by ret2libc** [comment]
The idea of having a issue with a checklist is good though.

**Comment by ret2libc** [comment]
This is done, we also integrated the issue template.
