### ISSUE TITLE
Undefined symbols: "_environ"

### ISSUE THREAD

**Issue by ryandesign** [rizinorg/rizin#952]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac OS X 10.6.8 i386 32
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | n/a

### Expected behavior

Successful build from source

### Actual behavior

Build failure:

```
Undefined symbols for architecture i386:
  "_environ", referenced from:
      _rz_subprocess_start in subprocess.c.o
     (maybe you meant: _rz_sys_get_environ, _rz_sys_set_environ )
ld: symbol(s) not found for architecture i386
```

We know that old versions of Mac OS X don't have `_environ` and you appear to already have code in librz/util/sys.c to deal with that:

```c
RZ_API char **rz_sys_get_environ(void) {
#if __APPLE__ && !HAVE_ENVIRON
	env = *_NSGetEnviron();
#else
	env = environ;
#endif
	// return environ if available??
	if (!env) {
		env = rz_lib_dl_sym(NULL, "environ");
	}
	return env;
}
```

But something isn't working.

### Additional Logs, screenshots, source code,  configuration dump, ...

Build log: [log.txt.zip](https://github.com/rizinorg/rizin/files/6246872/log.txt.zip)

**Comment by XVilka** [comment]
I think it might be because we don't check for `_environ` in `meson.build` while we should. cc @ret2libc @karliss

**Comment by XVilka** [comment]
@ryandesign please test again with the latest version from `dev` branch.
