### ISSUE TITLE
Remove legacy signatures ("zignatures") support

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#973]
Current format of signatures serialization uses SDB and separates values with commas (`,`) which is often problematic. Moreover, this storage format is inefficient.

We need to reimplement the storing and loading, consider some denser format as well.

See the current implementation in:
- `librz/core/cmd_zign.c`
- `librz/analysis/sign.c`

**Comment by ret2libc** [comment]
@XVilka @wargio does this have anything to do with what done by @wargio ? I'm not sure this is a good issue as it stands right now.

**Comment by XVilka** [comment]
It will be fixed by removing legacy signatures at 0.5.0. Until then I think it's better to keep this open.

**Comment by ret2libc** [comment]
@XVilka Do you refer to zignature.c file? The file you mentioned in the description does not exist anymore.

**Comment by wargio** [comment]
they still do exists, they have just been moved, but is ok, because i'm going to handle this issue.
