### ISSUE TITLE
Build error: ‘RZ_CRYPTO_STATIC_PLUGINS’ undeclared here

### ISSUE THREAD

**Issue by lenerd** [rizinorg/rizin#996]
# Build error: ‘RZ_CRYPTO_STATIC_PLUGINS’ undeclared here

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux, x86 64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | n/a
| `rizin -v` full output, **not truncated** (mandatory)  | n/a

The issue occurred while building the latest release v0.2.0 as well as the current dev branch at 63fbfd1cafa331c2024f05f2fd3936143b82dde1.

### Expected behavior

The build runs through.

### Actual behavior

Build fails with the following error (used `ninja -v`):

```
[116/1497] cc -Ilibrz/crypto/librz_crypto.so.0.3.0-git.p -I. -I.. -I../librz/include -Isubprojects/sdb -I../subprojects/sdb -Isubprojects/sdb/src -I../subprojects/sdb/src -I../shlr/spp -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g --std=gnu99 -fvisibility=hidden -D_GNU_SOURCE -Werror=sizeof-pointer-memaccess -fPIC -DRZ_PLUGIN_INCORE=1 -MD -MQ librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o -MF librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o.d -o librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o -c ../librz/crypto/crypto.c
FAILED: librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o 
cc -Ilibrz/crypto/librz_crypto.so.0.3.0-git.p -I. -I.. -I../librz/include -Isubprojects/sdb -I../subprojects/sdb -Isubprojects/sdb/src -I../subprojects/sdb/src -I../shlr/spp -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g --std=gnu99 -fvisibility=hidden -D_GNU_SOURCE -Werror=sizeof-pointer-memaccess -fPIC -DRZ_PLUGIN_INCORE=1 -MD -MQ librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o -MF librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o.d -o librz/crypto/librz_crypto.so.0.3.0-git.p/crypto.c.o -c ../librz/crypto/crypto.c
../librz/crypto/crypto.c:62:2: error: ‘RZ_CRYPTO_STATIC_PLUGINS’ undeclared here (not in a function)
   62 |  RZ_CRYPTO_STATIC_PLUGINS
      |  ^~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

I am not sure what goes wrong here.
- `build/config.h` is correctly generated and defines `RZ_CRYPTO_STATIC_PLUGINS`
- Stopping the compilation after preprocessing `-E` results in a file where the only reference to a `config.h` is the following:
    ```
    # 1 "../subprojects/sdb/src/config.h" 1`
    ```
    So maybe the includes happen in the wrong order.

### Steps to reproduce the behavior
```
$ git clone git@github.com:rizinorg/rizin.git
$ cd rizin
$ meson --buildtype=debug build
$ ninja -C build
```

Please let me know if I can provide you any other information.

**Comment by ret2libc** [comment]
Hi,

I was not able to reproduce this issue.

Could you give us more information like:
- meson version
- ninja version
- content of `build/meson-logs/meson-log.txt`
- gcc version
- content of `build/config.h`

Thanks!

**Comment by lenerd** [comment]
Hi,
here are the versions:
```
$ meson --version                         
0.57.2
$ ninja --version
1.10.2
$ gcc --version
gcc (GCC) 10.2.0
[...]
```
and the requested files:
- [config.h.txt](https://github.com/rizinorg/rizin/files/6296532/config.h.txt)
- [meson-log.txt](https://github.com/rizinorg/rizin/files/6296533/meson-log.txt)

I also added a copy of the `crypto.c` after preprocessing `-E`:
- [crypto_preprocessed.c.txt](https://github.com/rizinorg/rizin/files/6296550/crypto_preprocessed.c.txt)

**Comment by lenerd** [comment]
I solved the problem: There was some non-existent directory in my `CPATH` and `C_INCLUDE_PATH` environment variables. For some reason this shuffled the order of the include paths specified via `-I` such that a wrong `config.h` was included.

I am happy having fixed the problem, but I do not understand this behavior ...

Anyway, thanks for your time!
