### ISSUE TITLE
Load Layout in Visual Panels doesn't request a path for the file

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#999]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | -
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| `rizin -v` full output, **not truncated** (mandatory)  https://github.com/rizinorg/rizin/commit/63fbfd1cafa331c2024f05f2fd3936143b82dde1

### Expected behavior

1. `rizin /bin/ls`
2. `aaa`
3. `V!`
4. Go to the `File`->`Save Layout` menu and save into some file
5. Close Rizin
6. Open Rizin again
7. `V!`
8. Go to the `File` - `Load Layout` menu and it should ask for the file path to load

### Actual behavior

It doesn't ask for anything nor shows any menu when choose `Load Layout`.

**Comment by officialcjunior** [comment]
> It doesn't ask for anything nor shows any menu when choose Load Layout.

Hey, what did you mean by it's not showing any menu?
Currently it stores all the files at `~/.local/share/rizin/.rzpanels` on my machine. Isn't that a good thing?

Are you referring that it should ask the user from where to load the saved panels from when picking 'Saved'?
![image](https://user-images.githubusercontent.com/29057155/117385895-8bca8480-af03-11eb-924c-580224e5977a.png)

**Comment by XVilka** [comment]
Yes

**Comment by XVilka** [comment]
Nevermind, after some thinking I came to the conclusion that it is fine AS IS already. Lets close this.
